### ISSUE TITLE
TimePicker 时间选择器 在火狐浏览器下 样式不对

### ISSUE THREAD

**Issue by toolgood** [Tencent/tdesign-vue#100]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
火狐浏览器 95.0.2 (64 位)
 

**Describe the bug**
TimePicker 时间选择器 在火狐浏览器下 样式不对

**Comment by chaishi** [comment]
@uyarn 跟进中

**Comment by uyarn** [comment]
getComputedStyle在Firefox下获取复合属性的问题 本周修复

**Comment by uyarn** [comment]
Duplicate of https://github.com/Tencent/tdesign-vue/issues/107
