### ISSUE TITLE
[SelectInput] multiple无法使用clearable属性

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue#1005]
### tdesign-vue 版本

0.42.1

### 重现链接

https://codesandbox.io/s/grdlcm?file=/src/demo.vue

### 重现步骤

打开demo即可复现

### 期望结果

multiple正常开启clearable属性

### 实际结果

multiple无法开启clearable属性

### 框架版本

any

### 浏览器版本

any

### 系统版本

any

### Node版本

any

**Comment by uyarn** [comment]
这个issue由两个问题导致 

- [ ] 问题1 tag input事件透传失效问题

https://github.com/Tencent/tdesign-vue/pull/1007

问题2 select input clearable

**Comment by xiaosansiji** [comment]
已在 0.42.2 版本修复
