### ISSUE TITLE
[select] 箭头会突然地消失，mouseenter 和 mouseleave 的效果也很奇怪

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1009]
### tdesign-vue 版本

0.42.1

### 重现步骤

https://user-images.githubusercontent.com/11605702/173812452-29882d0e-2a25-478f-993d-7a9a60d3affe.mov

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue/pull/1007

**Comment by xiaosansiji** [comment]
已在 0.42.2 版本修复
