### ISSUE TITLE
form里面的select，如果是多选，保存再编辑的时候，select回显不出来，审查元素，删除<div class="t-input t-size-m t-select__input">竟然显示出来了，版本0.31.0是正常的

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#101]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

![录屏](https://user-images.githubusercontent.com/15682051/147398221-c68ca8ce-5263-4283-8042-bbd43300058f.gif)

select组件也没有添加readonly属性，而且很奇怪placeholder明明是“请输入员工英文名搜索”，为啥变成了“请输入”？

![image](https://user-images.githubusercontent.com/15682051/147398413-83fb1d26-0d0b-44f5-96d2-15cfaeb0cff6.png)

**Comment by geff1991** [comment]
![image](https://user-images.githubusercontent.com/6264677/147523620-ccdda86b-4538-4f53-bcb3-06ea8c025cef.png)
input placeholder是有点问题，为空时不需要展示默认值请输入的
