### ISSUE TITLE
[cascader] options异步加载较长时间时，v-model的值会被重置为空

### ISSUE THREAD

**Issue by joykk** [Tencent/tdesign-vue#1010]
### tdesign-vue 版本

^0.40.3

### 重现步骤

<template>
  <div>
    selectedValue:{{ selectedValue }}
    <h1>xxxxxxxxxx</h1>
    <t-cascader
      v-model="selectedValue"
      :options="options"
      :placeholder="placeholder"
      :filterable="filterable"
      size="medium"
      class="t-demo-cascader"
    />
  </div>
</template>
<script>
import { ListProductCascader } from '@/api/vue-api-client'

export default {
  props: {
    multiple: {
      required: false,
      default: function() {
        return false
      },
      type: Boolean
    },
    filterable: {
      default: function() {
        return true
      },
      type: Boolean
    },
    placeholder: {
      default: function() {
        return '请选择产品，如无子产品选择请选择“缺省”'
      },
      type: String
    },
    value: {
      required: true,
      default: function() {
        return ''
      },
      type: String
    }
  },
  data: function() {
    console.log(this.value)
    return {
      selectedValue: this.value,
      options: []
    }
  },
  created() {
    this.handleLoadOption()
    // this.load()
  },
  methods: {
    load() {
      return new Promise((resolve) => {
        setTimeout(() => {
          // 在这里设置超时之后可以100%自动选上
          this.selectedValue = this.value
          console.log(this.selectedValue)
        }, 10000)
      })
    },
    onChange(val) {
      this.$emit('input', val)
    },
    handleLoadOption() {
     // 耗时较长
      ListProductCascader().then(response => {
        if (response.code_str !== 'Ok') {
          this.$notify.error({ title: '错误', message: response.error_info })
          return
        }
        this.options = response.data
        console.log(this.selectedValue.length)
        if (this.selectedValue.length === 0) {
          this.selectedValue = this.value
        }
        console.log(this.selectedValue)
      }).catch(error => {
        console.log(error)
      })
    }
  }
}
</script>

<style scoped>

.t-demo-cascader-title {
  margin: 10px 0;
}
.t-demo-cascader + .t-demo-cascader {
  margin-top: 16px;
}
</style>

### 期望结果

插件可以自动选择上

### 实际结果

插件不会自动选择

### Node版本

v16.15.0
vue 2.6.14

**Comment by ldc4** [comment]
https://github.com/Tencent/tdesign-vue/blob/741bb9c96de58dec7a57d63e12242cf2d4030359/src/cascader/core/helper.ts#L27

这里在异步options场景下，回显有问题，是否在找不到option的情况下，也默认保留value值即可？
<img width="694" alt="image" src="https://user-images.githubusercontent.com/6810758/179684379-71e81999-d7d7-4fb7-9b74-d7c16a080b22.png">

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue/pull/1228 已修复
