### ISSUE TITLE
[table] 当设置了吸顶headerAffixedTop时， 列拖拽排序dragSort="col" 无法使用

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1014]
### tdesign-vue 版本

0.42.1

### 重现链接

https://stackblitz.com/edit/angular-fw8skg?file=src/demo.vue

### 重现步骤

当table中配置了headerAffixedTop和dragSort="col"时， 吸顶后无法进行列拖拽排序

### 期望结果

希望可以吸顶时也可以支持列拖拽排序功能

### 实际结果

吸顶和列拖拽排序无法同时使用

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1029

**Comment by xiaosansiji** [comment]
已在 0.42.2 版本修复
