### ISSUE TITLE
[table] 列拖拽排序dragSort="col"和列配置同时使用时，拖拽列错误

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1015]
### tdesign-vue 版本

0.42.1

### 重现链接

https://stackblitz.com/edit/angular-ieb45c?file=src/demo.vue

### 重现步骤

1.  当列配置全选时，列拖拽正常
2.  列配置中去掉“平台”， 然后交换“类型”和“序号”的位置，实现是交换的是“序号”和“平台”

https://user-images.githubusercontent.com/13745660/174034569-a8443b40-ad92-4e9a-9b6f-143b8ba52c62.mov

### 期望结果

支持列配置和拖动列同时使用

### 实际结果

列配置中去掉列后，拖拽交互的列正确

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
TODO

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1029

**Comment by xiaosansiji** [comment]
已在 0.42.2 版本修复
