### ISSUE TITLE
[table] 异步获取数据，吸顶功能失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1025]
### tdesign-vue 版本

0.42.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-wq2msb?file=/src/demo.vue

### 重现步骤

重现链接中点击获取数据

在 0.42.1版本中滚动发现吸顶功能失效
0.42.0版本该功能正常

### 期望结果

效果与0.42.0版本一致

### 实际结果

吸顶功能失效

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1023

**Comment by xiaosansiji** [comment]
已在 0.42.2 版本修复

**Comment by LoopZhou** [comment]
重现链接在0.42.2版本尝试，该问题依旧存在

**Comment by chaishi** [comment]
second resolved in https://github.com/Tencent/tdesign-vue/pull/1052

**Comment by uyarn** [comment]
fixed in 0.43.0
