### ISSUE TITLE
[InputNumber] enter事件无法触发

### ISSUE THREAD

**Issue by WULIbinbin** [Tencent/tdesign-vue#1033]
### tdesign-vue 版本

0.42.1

### 重现链接

https://codesandbox.io/s/proud-dew-mlcepb?file=/src/App.vue

### 重现步骤

点击键盘Enter

### 期望结果

enter、enter.native事件能正常触发

### 实际结果

enter、enter.native事件都无法触发

### 框架版本

vue(2.6.11)

**Comment by uyarn** [comment]
fixed in 0.43.0
