### ISSUE TITLE
[Cascader] 当级联菜单 第一级菜单 和  第二级菜单的 value重复的时候 无法选中靠前的内容

### ISSUE THREAD

**Issue by Object-you** [Tencent/tdesign-vue#1037]
### tdesign-vue 版本

所有

### 重现链接

已测试 在 CodeSandbox 也有同样的效果

### 重现步骤

例如 option为
```
[{
label:"name",
value:"name"
},
{
label:"obj",
value:"obj",
children:[{
label:"name",
value:"name"
}]
}
]
```
第一项 name 就无法选中

### 期望结果

我认为 第二级的value和第一级的 value 不应该有value值重复无法选中的问题 
最起码 valueType为 full时不该
毕竟已经有路径了 完全可以找到对应的唯一

**Comment by pengYYYYY** [comment]
value 值需要为唯一,底层依赖的tree要求数据源为唯一值

**Comment by Object-you** [comment]
@pengYYYYY
