### ISSUE TITLE
[select] 开启虚拟滚动时 采用自定义面板内容方式 点选卡顿

### ISSUE THREAD

**Issue by zhangningself** [Tencent/tdesign-vue#1039]
### tdesign-vue 版本

0.42.2

### 重现步骤

<template>
  <div class="tdesign-demo-select-base">
    
    <t-select
      v-model="value"
      :loading="loading"
      filterable
      placeholder="请选择"
      :scroll="{ type: 'virtual' }"
      :popup-props="{ overlayStyle: { height: '300px' } }"
    >
      <t-option v-for="item in options" :value="item.value" :label="item.label" :key="item.value">
        <span class="left">{{ item.value }}/{{ item.label }}</span>
        <span class="right font-12 pl-4" style="color: #8492a6">{{ item.label }}</span>
      </t-option>
    </t-select>
  </div>
</template>

<script lang="jsx">
export default {
  data() {
    return {
      loading: false,
      value: '',
      options: [],
    }
  },
  methods: {
    getDataList() {
      this.loading = true
      setTimeout(() => {
        this.loading = false
        const options = []
        for (let i = 0; i < 1500; i++) {
          options.push({ label: `选项${i + 1}`, value: String(i) })
        }
        this.options = options
      }, 2000)
    },
  },
  mounted() {
    this.getDataList()
  },
}
</script>

<style scoped>
.tdesign-demo-select-base {
  width: 450px;
  display: flex;
}

.tdesign-demo-select-base .t-select__wrap + .t-select__wrap {
  margin-left: 36px;
}
</style>

### 期望结果

虚拟滚动生效

### 实际结果

依旧卡顿

**Comment by uyarn** [comment]
没看懂你的问题 能不能在codesandbox上复现一下
https://codesandbox.io/s/h5ehl1?file=/src/demo.vue

**Comment by uyarn** [comment]
slot的方式暂时没支持虚拟滚动 现在是基于option的数据去做虚拟滚动的data计算 不过接下来会支持一下

**Comment by zhangningself** [comment]
> 不过接下来会支持一下

好的

**Comment by uyarn** [comment]
assign to @skytt

**Comment by uyarn** [comment]
已在0.45.2支持
