### ISSUE TITLE
[taginput] 中文输入过程中删除输入内容，会删除已添加tag,以及中文输入时点击回车键后内容有误

### ISSUE THREAD

**Issue by chiyu1996** [Tencent/tdesign-vue#1041]
### tdesign-vue 版本

0.42.2

### 重现步骤

输入几个tag后，输入中文，然后删除拼音字母时会把已添加的tag删除
![QQ20220623-111420-HD](https://user-images.githubusercontent.com/18342366/175199695-3599f6ac-f957-4294-89ef-0a982f107317.gif)
输入数字后，再输入拼音按回车，会删除之前的输入内容，只保留中文输入的拼音
![baf6b6425646ad398b3c85df74273835](https://user-images.githubusercontent.com/18342366/175199209-e6c9a2e7-8535-4822-9d9b-835294a5bbfe.gif)

**Comment by chiyu1996** [comment]
处理中

**Comment by uyarn** [comment]
published in 0.43.0
