### ISSUE TITLE
[ColorPicker] 颜色选择器样式异常

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1044]
### tdesign-vue 版本

0.42.2

### 重现步骤

![image](https://user-images.githubusercontent.com/25051361/174768424-68dd890b-1b81-43ce-ad49-12caeffbd681.png)
先选中此下拉框不关闭，然后点击关闭按钮或者其他地方关闭颜色选择器，此下拉框会显示在其他地方，如下图所示；
![image](https://user-images.githubusercontent.com/25051361/174768759-a15599f9-a004-4587-9b86-d6d7cbdc80a4.png)

**Comment by wenkm** [comment]
这个问题通过修改`tdesign-common`里的`popup`样式可以解决
https://github.com/Tencent/tdesign-common/pull/565

**Comment by a-l-o-n-g** [comment]
> 这个问题通过修改`tdesign-common`里的`popup`样式可以解决 [Tencent/tdesign-common#565](https://github.com/Tencent/tdesign-common/pull/565)

是我这边去修改样式?

**Comment by wenkm** [comment]
> 是我这边去修改样式?

已经提了PR，但是ESLINT检查失败了😂

**Comment by a-l-o-n-g** [comment]
> 



> > 是我这边去修改样式?
> 
> 已经提了PR，但是ESLINT检查失败了😂

**Comment by a-l-o-n-g** [comment]
> > 
> 
> > > 是我这边去修改样式?
> > 
> > 
> > 已经提了PR，但是ESLINT检查失败了😂

那没事，继续等

**Comment by a-l-o-n-g** [comment]
> > > 
> > 
> > 
> > > > 是我这边去修改样式?
> > > 
> > > 
> > > 已经提了PR，但是ESLINT检查失败了😂
> 
> 那没事，继续等

table组件合并单元格的是谁在看啊

**Comment by xiaosansiji** [comment]
已在 0.43.2 版本修复
