### ISSUE TITLE
[table]根据您提供的实例代码，操作后合并单元格还是有问题 #992 

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1045]
可参考#992的issue

https://user-images.githubusercontent.com/25051361/174739737-bd25b50d-4646-44c8-87d3-e934cb6beda3.mp4

_Originally posted by @a-l-o-n-g in https://github.com/Tencent/tdesign-vue/issues/992#issuecomment-1161317838_

**Comment by a-l-o-n-g** [comment]
没人看这个问题吗?

**Comment by a-l-o-n-g** [comment]
![image](https://user-images.githubusercontent.com/25051361/176123391-8b21e7fa-8bb7-4af6-9242-a07aad4c6a39.png)
刚刚操作您发的demo

**Comment by xiaosansiji** [comment]
哦 删除中间这一行的时候确实还有这个问题，我们再排查下
<img width="731" alt="image" src="https://user-images.githubusercontent.com/7600149/176124124-2a2ef551-d311-4ff9-99c7-913dda365019.png">

**Comment by xiaosansiji** [comment]
下次遇到问题没解决的情况，可以 reopen 原先的 issue，这样信息比较全一些

**Comment by a-l-o-n-g** [comment]
好的，因为我在标题和描述中都写了原来的issue编号，所以就没去重开了

**Comment by xiaosansiji** [comment]
操作复现：
![Kapture 2022-06-28 at 15 54 05](https://user-images.githubusercontent.com/7600149/176125343-61973313-ca8d-4e04-8339-99c2cee0bead.gif)

**Comment by a-l-o-n-g** [comment]
你这边用的是什么录屏软件？方便告知吗

**Comment by chaishi** [comment]
@a-l-o-n-g 如果是 MAC，直接 `ctrl + shift + 5`

**Comment by chaishi** [comment]
我继续看下这个问题

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1110

**Comment by xiaosansiji** [comment]
已在 0.43.2 版本修复
