### ISSUE TITLE
[menu] 包含次级菜单的menu组件before超出实际menu高度，会误触发

### ISSUE THREAD

**Issue by airkingZy** [Tencent/tdesign-vue#1049]
### tdesign-vue 版本

0.42.2

### 重现链接

https://tdesign.tencent.com/vue/components/menu#%E5%A4%9A%E5%B1%82%E6%94%B6%E7%BA%B3%E5%AF%BC%E8%88%AA

### 重现步骤

1.多层收纳导航，鼠标从下移动到menu框内，还没移动到menu框内时，二级菜单已经触发显示

### 期望结果

在鼠标移动到menu-item内时，才触发对应的二级菜单显示

### 实际结果

![企业微信截图_cff3b9c8-7967-48f5-97a4-e794405e0d1c](https://user-images.githubusercontent.com/24963857/174988121-a84b9b42-2cf3-4da2-b684-c7c67e8fdafc.png)
![企业微信截图_ba759b1a-686c-4ed1-bee6-15f745d455c8](https://user-images.githubusercontent.com/24963857/174988147-1d2b891b-3e80-4954-a177-6c8be0726efc.png)
![企业微信截图_f4463e30-2a56-4f27-8c07-1b4a9b518a2b](https://user-images.githubusercontent.com/24963857/174988198-8a5e9450-838b-4e35-930d-a4450fcdae10.png)

超出实际menu范围，是设计本意如此还是bug？作为页面的头部menu时候，下面有其他内容时候，很容易误触。

### 框架版本

2.x

**Comment by wenkm** [comment]
试着改了下，需要修改当前dom结构，改的地方比较多，还涉及到common的修改。我想下有没有更简单的方式，再提PR
