### ISSUE TITLE
[t-table] 表格筛选功能丢失

### ISSUE THREAD

**Issue by YikaJ** [Tencent/tdesign-vue#1050]
### tdesign-vue 版本

0.42.2

### 重现链接

https://tdesign.tencent.com/vue/components/table#%E5%8F%AF%E7%AD%9B%E9%80%89%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

直接看官网例子，表格筛选的图标丢失，无法进行表格筛选。

### 期望结果

恢复到 0.41.7 的样子，从这个版本之后，filter 没再出现过了

https://0_41_7-tdesign-vue.surge.sh/vue/components/table#%E5%8F%AF%E7%AD%9B%E9%80%89%E7%9A%84%E8%A1%A8%E6%A0%BC

<img width="884" alt="企业微信截图_fa0b0228-c187-4cad-a5df-b5f55549d44b" src="https://user-images.githubusercontent.com/8725110/175005387-f5e6ec83-a611-4df4-84c8-05b62d53740b.png">

### 实际结果

<img width="882" alt="企业微信截图_c0cd9458-8bdb-452e-8f47-235303172e32" src="https://user-images.githubusercontent.com/8725110/175005349-b24d3cb2-09cd-4c5e-83ab-b85728669a83.png">

### 补充说明

0.41.7 这个版本之后，filter 开始出问题了

**Comment by steven12138** [comment]
同问题，build之后筛选图标丢失
build之前无问题

**Comment by uyarn** [comment]
fixed in 0.43.0
