### ISSUE TITLE
日历组件当选择年，隐藏周末的时候，月份会被清空

### ISSUE THREAD

**Issue by YFAnt** [Tencent/tdesign-vue#106]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
https://tdesign.tencent.com/vue/components/calendar
Add browser version here
chrome 96.0.4664.110
**Describe the bug**
https://tdesign.tencent.com/vue/components/calendar 日历组件，当选择年，点击隐藏周末，月份的组件会被清空。

**Additional context**
官方事例

**Comment by xiaosansiji** [comment]
![image](https://user-images.githubusercontent.com/7600149/147440186-bf49e10a-20fb-4291-a485-806bfbdf9c3a.png)
实现有问题，切换到年的时候，其实不用再展示“隐藏周末”选项了

**Comment by PsTiu** [comment]
收到，正在处理

**Comment by YFAnt** [comment]
另外 滚动选择年份是你们特意这样设计的么，比如我滚动到2009年，只能先选择一次2011年，然后在打开在选择么，感觉这个功能不对劲啊

**Comment by YFAnt** [comment]
@PsTiu

**Comment by xiaosansiji** [comment]
> 另外 滚动选择年份是你们特意这样设计的么，比如我滚动到2009年，只能先选择一次2011年，然后在打开在选择么，感觉这个功能不对劲啊

其实... 是考虑日历大部分场景下都只看近几年的数据，select 选项直接从 1970 年开始选项太多了，滚动选择体验比较差，比较了下 AntD 等其他几个组件库也都是类似设计。你有强烈需求要看很久之前的日历信息么？如果需要的话可以讨论下要不要增加个 API 用来控制展示几年内的信息

**Comment by YFAnt** [comment]
没事 我只是提个意见， 这个你可以放一阵子，可以看下使用者的需求，要是真有人了提了，到时候再加也来的及。

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
