### ISSUE TITLE
[Select] 启用虚拟滚动时，初始选项展示不出来

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#1062]
### tdesign-vue 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-5swkx9?file=/src/demo.vue

### 重现步骤

select配置虚拟滚动

### 期望结果

点击选择时，options能正常显示

### 实际结果

![image](https://user-images.githubusercontent.com/5775725/175272804-b78c2d62-9ab8-4fea-be0b-a8f470a3ce30.png)

首次点击时，options显示为空

**Comment by uyarn** [comment]
我排查一下 只有一个数据应该也不会开启才对

**Comment by uyarn** [comment]
fixed in 0.43.0
