### ISSUE TITLE
[Cascader] value 设为空字符串的选择，解析后的 value 变成了 t1、t2?

### ISSUE THREAD

**Issue by leeui2020** [Tencent/tdesign-vue#1064]
### tdesign-vue 版本

0.41.3

### 实际结果

<img width="311" alt="1" src="https://user-images.githubusercontent.com/64050937/175286447-424839db-173f-463d-9d67-d3116488cbc1.png">

**Comment by pengYYYYY** [comment]
cascader依赖与tree组件，tree组件要求key为唯一，如果不存在，则会给一个唯一值
