### ISSUE TITLE
[Table] 当width列宽总和小于 table 元素时,  resizable拖动列到最大后不能再拖动

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1067]
### tdesign-vue 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-3txuc4?file=/src/demo.vue

### 重现步骤

https://user-images.githubusercontent.com/13745660/175451421-d5b12e30-4b2d-46ca-8044-adb232020cb7.mov

### 期望结果

列宽拖动后可以再拖动

### 实际结果

拖动到最大后，不能再拖动该列

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by LoopZhou** [comment]
在0.44.0版本中验证，该问题未解决。

**Comment by LoopZhou** [comment]
在width列宽总和小于 table 元素时的情况， 依旧有一些问题。
比如
1.  线往左侧拖动缩小，结果是列宽往右侧移动增加了。 
2. 另外就是拖动后可能导致不能二次拖动的问题。  

![image](https://user-images.githubusercontent.com/13745660/180164865-f9d202f6-9459-4465-af48-679b09ea545d.png)

配置的width宽度小于table， 比如示例都是100px,  界面上实际是343px。 当往左侧拖动一点距离到300px。

![image](https://user-images.githubusercontent.com/13745660/180165149-8d0f4830-d1c7-4771-8513-60eff45ddd33.png)

colgroup的width变成了300px,  实际展示的效果是线往右侧移动了。实际展示列宽变成了618px,  因为resize默认拖动范围代码中配置的是const DEFAULT_MIN_WIDTH = 80; const DEFAULT_MAX_WIDTH = 600;  导致该列不能再拖动。

这种情况下，拖动时是否应该按比例来计算列宽的缩放大小呢？

**Comment by ZTao-z** [comment]
认领 #1067

**Comment by ZTao-z** [comment]
定位到问题了：在列的宽度总和小于表的宽度，浏览器会自动撑开每一列，导致显示列宽度和设置的不一致。
具体可以参考这篇文章：https://x-front-team.github.io/2017/04/25/table-layout%E7%90%86%E8%A7%A3%E5%88%B0%E6%94%BE%E5%BC%83/

**Comment by uyarn** [comment]
fixed 0.45.1
