### ISSUE TITLE
头像机器人（无意冒犯，感觉就是这样）

### ISSUE THREAD

**Issue by whp98** [Tencent/tdesign-vue#1068]
### 重现链接
https://tdesign.tencent.com/

### 重现步骤
官网

### 期望结果
用自己喜欢的把，像素风也没多好看，搞得像是机器人，设计ui的人就喜欢用这种头像吗

### 实际结果
很多设计师和开发者用着风格一致的头像，不知道是不是腾讯规定的，反正看着像机器人，也不是那么好看

| Environment | Info |
|---|---|
| 相关版本 | 0.42.2 |
| 框架版本 / 基础库版本 | VUE |
| 系统、浏览器 | Win |
| Node版本 |  |

![image](https://user-images.githubusercontent.com/32877126/175456951-13249931-7f70-4445-b3ec-9c5b7be8bba4.png)

**Comment by xiaosansiji** [comment]
并不是腾讯规定。。
设计师之前给 TDesign 的一些核心贡献同学，根据个人真人照片定制出了一些这样 TDesign 风格的头像，算是一种感谢和小福利吧，也没有要求大家一定把头像换成这样 😅

**Comment by xiaosansiji** [comment]
头像风格算是一种个人感受吧，可能每个人的喜好会有些差异，GitHub 头像是大家根据自己意愿选择的。
仓库 issue 还是会更聚焦在方案讨论或者 bug 反馈上，这个 issue 稍后会被关闭。

**Comment by whp98** [comment]
好的是我不了解看来大家挺喜欢的
