### ISSUE TITLE
[Dialog] 文本溢出的情况下滚动经常失效

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1071]
### tdesign-vue 版本

0.42.2

### 重现步骤

视频开头演示的是可以正常滚动
https://user-images.githubusercontent.com/25051361/175500430-649fc83e-0766-4837-b39b-800f5ac26678.mp4

### 期望结果

能正常滚动

**Comment by uyarn** [comment]
已修复待发布

**Comment by xiaosansiji** [comment]
已在 0.43.2 版本修复
