### ISSUE TITLE
[table] 列宽拖动hover位置建议居中

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1078]
### tdesign-vue 版本

0.42.2

### 重现链接

https://codesandbox.io/s/mkl7n7?file=/src/demo.vue

### 重现步骤

<img width="621" alt="table拖动hover" src="https://user-images.githubusercontent.com/13745660/175849234-38b35840-6207-485a-939b-3c6a4b5a5fed.png">

### 期望结果

鼠标移动到竖线左右小范围内，变换鼠标光标

### 实际结果

当前为竖线左侧

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
67fa2707c55a1a8facab7a6880a42431ad0d2b23

此处受控和非受控逻辑变更引起的问题，回退这个版本的代码
