### ISSUE TITLE
`Dialog`组件的`body`样式问题（缺少左右`padding`造成）

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#108]
**Describe Framework**
- [x] tdesign-vue

**Describe Environment**
https://codesandbox.io/s/tdesign-vue-demo-forked-z36ce?file=/src/demo.vue

**Describe the bug**
在`Dialog`组件中使用`Input`组件，当`Input`组件处于`foucs`状态时，`input`的`box-shadow`左右两边无法正常显示

**Additional context**
建议为`Dialog`的`t-dialog__body`样式至少添加 `2px` 的左右`padding`

为什么至少是`2px`呢？

因为`input`的`box-shadow`的扩散半径是`2px`;

暂时不知其他带阴影组件的范围是不是`2px`

![image](https://user-images.githubusercontent.com/49895922/147441543-bf108fa6-c146-49d9-8991-40b0a4bd10c4.png)

**Comment by chaishi** [comment]
收到，可以联系 @uyarn 讨论
