### ISSUE TITLE
[input-number] 希望inputNumber可以支持大数的输入、新增、减少

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1080]
### 这个功能解决了什么问题

目前业务上功能需要输入整位数18位，小数点后保留两位的数字。
但是js number的精度不能支持到18位，输入后会有精度不准确的问题，会自动变化。

### 你建议的方案是什么

希望inputNumber可以支持大数据的输入、新增、减少。 当超过number精度时，不做Number强转而是以字符串的形式展示等。

**Comment by chaishi** [comment]
> 目前后端数据整数位允许到18位，小数位保留2位，但是按原生来16就不精确了

我本周处理下这个特性，支持一下大数据的输入和计算

**Comment by uyarn** [comment]
release 0.46.0
