### ISSUE TITLE
[Tree 树组件] 1.可以在箭头后面增加icon；2.箭头可以替换图标

### ISSUE THREAD

**Issue by Ellenhx** [Tencent/tdesign-vue#1084]
### 这个功能解决了什么问题

我们有些场景会需要在箭头前面加图标，用户指示类型
<img width="343" alt="image" src="https://user-images.githubusercontent.com/89068547/176164762-a165c7db-0399-4f17-a30a-24b2e856bfce.png">

### 你建议的方案是什么

1.可以在箭头后面增加icon；2.箭头可以替换图标

**Comment by xiaosansiji** [comment]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/7600149/176165535-6d298025-5baa-42ed-8bcc-00423e5f5cd7.png">
icon 和 label 位置都支持 slot 自定义，可以参考官网上这个自定义的例子：
https://tdesign.tencent.com/vue/components/tree?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87%E7%9A%84%E6%A0%91
<img width="596" alt="image" src="https://user-images.githubusercontent.com/7600149/176165719-719aa5c2-7d92-49e4-9bad-ae90a1b16f45.png">
