### ISSUE TITLE
[DatePicker ] 尺寸属性更新之后没有了

### ISSUE THREAD

**Issue by waviness** [Tencent/tdesign-vue#1087]
### tdesign-vue 版本

0.43.0

### 重现步骤

尺寸属性更新之后没有了，size设置不生效

**Comment by HQ-Lin** [comment]
尺寸属于误录的api，设计没有这个规划，之前也没有实现过

**Comment by waviness** [comment]
之前有的，我还用了，而且都属于选择框，其他的组件都有，理论上应该要有吧？
