### ISSUE TITLE
[select]多选下拉未显示placeholder，且控制台报错 Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by githubKingW** [Tencent/tdesign-vue#1089]
### tdesign-vue 版本

0.43.0

### 重现链接

https://codesandbox.io/s/pf5nf8?file=/src/demo.vue

**Comment by uyarn** [comment]
谢谢反馈 有个判断没有判空 确实是比较明显的问题 发布了0.43.1版本修复 麻烦升级一下：）
