### ISSUE TITLE
[date-picker] 重构后的新版本不再支持自定义后缀图标

### ISSUE THREAD

**Issue by Furrywind** [Tencent/tdesign-vue#1090]
### tdesign-vue 版本

0.43.0

### 重现链接

https://codesandbox.io/s/fck7b7?file=/src/demo.vue

### 框架版本

Vue(2.6.14)

### 补充说明

链接为官方例子，甚至连Vue-Next(0.17.2)的官方例子都没有实现

**Comment by HQ-Lin** [comment]
这周处理下

**Comment by xiaosansiji** [comment]
已在 0.43.2 版本修复
