### ISSUE TITLE
[transfer] 穿梭框进行穿梭时报错

### ISSUE THREAD

**Issue by ottff54321** [Tencent/tdesign-vue#1096]
### tdesign-vue 版本

0.42.2

### 重现链接

https://0_42_2-tdesign-vue.surge.sh/vue/components/transfer

### 重现步骤

1.官网点击基础穿梭框的穿梭箭头
2.[Vue warn]: Error in callback for watcher "totalCount": "TypeError: Cannot read properties of undefined (reading 'current')"

### 期望结果

无报错，数据正确获取

### 实际结果

[Vue warn]: Error in callback for watcher "totalCount": "TypeError: Cannot read properties of undefined (reading 'current')"

**Comment by xiaosansiji** [comment]
已在 0.43.3 中修复
