### ISSUE TITLE
[table] table的列配置功能失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1097]
### tdesign-vue 版本

0.43.1

### 重现步骤

目前0.43.1的官网即可复现

https://user-images.githubusercontent.com/13745660/176844160-115ed7b3-e8b7-415e-ad41-e223251c45e4.mov

### 期望结果

0.42.2版本正常

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
67fa2707c55a1a8facab7a6880a42431ad0d2b23

此处受控和非受控逻辑变更引起的问题，回退这个版本的代码
