### ISSUE TITLE
[Table] 自定义组件不显示

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1114]
### tdesign-vue 版本

0.43.1

### 重现步骤

<img width="935" alt="企业微信截图_015d51d1-d277-402b-91f7-248bc2c1e76e" src="https://user-images.githubusercontent.com/11605702/176985844-d14df62b-a3ec-4c53-a9fe-4d74476208af.png">

**Comment by xiaosansiji** [comment]
已在0.43.2 版本修复
