### ISSUE TITLE
[body样式] 0.42.2版本没有问题，0.43.2版本有问题

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1123]
### tdesign-vue 版本

0.43.2

### **0.42.2版本**
![image](https://user-images.githubusercontent.com/25051361/177145283-cd5283c2-542a-400c-90f1-510178d9f014.png)

### **0.43.2版本**
![image](https://user-images.githubusercontent.com/25051361/177145589-f51813cf-4cc5-4e55-a633-f6e05c01e505.png)

### 期望结果

为什么会影响到body样式？
希望不会影响，不然得去调整body样式

### 框架版本

2.6.11

### 浏览器版本

Chrome   101.0.4951.67（正式版本） （64 位）

**Comment by a-l-o-n-g** [comment]
tdesign-vue/es/style/index.css 这个是以前的全局样式吗？

**Comment by xiaosansiji** [comment]
是，全局样式和 reset 样式都需要引入
