### ISSUE TITLE
[Collapse] td-starter 创建的项目中 collapse不显示样式

### ISSUE THREAD

**Issue by hanzhichao** [Tencent/tdesign-vue#1136]
### tdesign-vue 版本

0.40.3

### 重现步骤

1. td-starter创建像
2. 新建页面并配置conponents.ts 菜单路由
3. 复制官网Collapse示例
4. 查看页面

### 期望结果

样式正常

### 实际结果

无样
![Uploading WX20220706-181054@2x.png…]()
式

### Node版本

8.12.1

**Comment by uyarn** [comment]
图裂开了 直接复制一个demo能复现吗
