### ISSUE TITLE
[table] 为什么没有双击单元格事件?

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1138]
### tdesign-vue 版本

0.43.2

### 重现步骤

看到之前有同学已经提过了，而且已经增加了cell-click事件，但怎么没有cell-dbclick单元格双击事件？或者是其他的事件能代替此事件？

**Comment by chaishi** [comment]
一个元素的事件比较多，不适合每一个事件都加上，需要一个更通用的方式去实现。

如，table.addEventListener(click, handler) ，给 table 加一个事件代理试试
