### ISSUE TITLE
[t-table] 组合了 dropdown/tooltip等基于Popup来实现的弹出式组件的业务场景会出现预期之外效果

### ISSUE THREAD

**Issue by logan-yunlong** [Tencent/tdesign-vue#1145]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-6unbwn?from-embed=&file=/src/demo.vue

### 重现步骤
https://codesandbox.io/s/tdesign-vue-demo-forked-6unbwn?from-embed=&file=/src/demo.vue
1. 悬停在在表格中，平台列字段，会显示按钮元素。
2. 悬停显示的按钮，无法顺利的选择伴随按钮展开的dropdown组件。

### 期望结果
从理论上来说，表格的事件监听移出到了dropdown元素中，移出后应当继续隐藏按钮中组件；
但是对于常用的表格和更多按钮的组合，期待有简单的方案来组合组件来实现功能~

### 实际结果
详见图片
<img width="1101" alt="wecom-temp-1cef053693ad642697dd9c8eb13f4006" src="https://user-images.githubusercontent.com/26224399/177967606-5a67f14e-f9b4-4d05-826a-3885c62e707e.png">
<img width="986" alt="wecom-temp-e3dabf5d31944b16c178ce8db35f7e04" src="https://user-images.githubusercontent.com/26224399/177967630-d2481fa1-69d4-4044-a0b2-f4c2d4aa7437.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.43.2 |
| 框架版本 / 基础库版本 | "tdesign-vue": "0.43.2",     "tdesign-icons-vue": "~0.0.8",     "vue": "~2.6.14" |
| 系统、浏览器 | macOS(12.4 (21F79)) chrome(版本 103.0.5060.114（正式版本） (x86_64)) |
| Node版本 |  |

**Comment by uyarn** [comment]
忘记看这个issue了.. 这周回复下

**Comment by logan-yunlong** [comment]
> 忘记看这个issue了.. 这周回复下

小事儿，排期处理即可

**Comment by uyarn** [comment]
这种实现方式好像没法解决 尝试用attach 如果挂在tr里 会挤压样式 https://codesandbox.io/s/tdesign-vue-demo-forked-7lj4oe?file=/src/demo.vue
如果挂在table里 通过mouseenter mouseleave又依旧会改变hoveridx

**Comment by logan-yunlong** [comment]
是的，这似乎是一个两难的抉择，我参考了elementUI的代码，写了一个小demo，发现依然会有这样组合的问题。（elementUI好的一点是组件的动画效果不会闪来闪去）

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICB7e2hvdmVySW5kZXh9fVxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgQGNlbGwtbW91c2UtZW50ZXI9XCJlbnRlclwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBhbGlnbi1pdGVtczogY2VudGVyXCI+XG4gICAgICAgICAgPGVsLWljb24+PHRpbWVyIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuIHN0eWxlPVwibWFyZ2luLWxlZnQ6IDEwcHhcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvc3Bhbj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1wb3BvdmVyIGVmZmVjdD1cImxpZ2h0XCIgdHJpZ2dlcj1cImhvdmVyXCIgcGxhY2VtZW50PVwidG9wXCIgd2lkdGg9XCJhdXRvXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PlxuICAgICAgICAgICAgPGRpdj5uYW1lOiB7eyBzY29wZS5yb3cubmFtZSB9fTwvZGl2PlxuICAgICAgICAgICAgPGRpdj5hZGRyZXNzOiB7eyBzY29wZS5yb3cuYWRkcmVzcyB9fTwvZGl2PlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgICA8ZWwtdGFnPnt7IHNjb3BlLnJvdy5uYW1lIH19PC9lbC10YWc+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1wb3BvdmVyPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiT3BlcmF0aW9uc1wiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlxuICAgICAgICAgICAgICDljaDkvY3nrKZcbiAgICAgICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgICAgIDxlbC1kcm9wZG93biB2LXNob3c9XCJzY29wZS5yb3cuZGF0ZSA9PT0gaG92ZXJJbmRleFwiPlxuICAgICAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlxuICAgICAgICAgICAgICDmm7TlpJpcbiAgICAgICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPC9lbC1kcm9wZG93bj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgaW1wb3J0IHtyZWZ9IGZyb20gXCJ2dWVcIjtcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG4gIGNvbnN0IGhvdmVySW5kZXggPSByZWYoLTEpO1xuICBjb25zdCBlbnRlciA9ICAocm93LCBjb2x1bW4sIGNlbGwsIGV2ZW50KT0+e1xuICAgIGhvdmVySW5kZXgudmFsdWUgPSByb3cuZGF0ZTtcbiAgfVxuY29uc3QgaGFuZGxlRWRpdCA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cbmNvbnN0IGhhbmRsZU9wZWFydG9yID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by logan-yunlong** [comment]
> 这种实现方式好像没法解决 尝试用attach 如果挂在tr里 会挤压样式 https://codesandbox.io/s/tdesign-vue-demo-forked-7lj4oe?file=/src/demo.vue 如果挂在table里 通过mouseenter mouseleave又依旧会改变hoveridx

嗯 之前也曾经尝试过，不过后来我们决定使用自主控制的思路，
既：
1. 自行维护一个hoverIndex的数据
2. hoverIndex的数据只有在mouse in row的时候才会更新，在mouse out row的时候，不更新，
3. 下拉框的显示隐藏控制根据 hoverIndex === rowIndex 时来决定展开
