### ISSUE TITLE
[table] 多级表头是不支持表尾?

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1149]
### tdesign-vue 版本

0.43.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-ptrk5j?file=/src/demo.vue

### 重现步骤

如图所示，只是在官方的多级表头demo中添加了两行代码`:foot-data="footData"` 与 `footData: [{}],`；其他代码全是demo中的未做修改；
但是表尾却只渲染了前几列td，后面的td不见了；
是否是我代码上缺失其他配置？如果不是，能否修复？毕竟在实际情况中多级表头也是存在合计行的
![image](https://user-images.githubusercontent.com/25051361/178089693-97c44a15-8676-4f5e-8230-c2a291a4c339.png)
![image](https://user-images.githubusercontent.com/25051361/178089703-c8ce79fb-0f90-437d-8df3-df44ffe49eb6.png)

![image](https://user-images.githubusercontent.com/25051361/178089676-f5c2755a-c022-46a5-97a0-ae91a2aa45fc.png)

### 浏览器版本

Chrome   版本 103.0.5060.114（正式版本） （64 位）

**Comment by a-l-o-n-g** [comment]
这个是bug吗

**Comment by chaishi** [comment]
这周空了，我来写一下

**Comment by a-l-o-n-g** [comment]
> 这周空了，我来写一下

好的，Thanks♪(･ω･)ﾉ  怎么我提的bug好像都是你这边帮忙看

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1217

**Comment by chaishi** [comment]
@a-l-o-n-g 因为 PMC 兜底处理问题（刚好 3 个框架的 Table 是我在维护）

**Comment by uyarn** [comment]
fixed in 0.45.1
