### ISSUE TITLE
windows10,1920*1080,150%缩放，chrome高版本（本机96），会出现boder线显示粗细明显差别

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#115]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**
<img width="780" alt="table-border" src="https://user-images.githubusercontent.com/20809990/147536366-b1144bef-dd5b-4689-b142-8c00d001579a.png">
样式问题，使用border-collapse: collapse;在浏览器进行缩放时不能按预期工作，边框的粗细会不一致
**Additional context**

**Comment by chaishi** [comment]
@xiecz123 我们可以如何做到 浏览器进行缩放时，粗细也一致呢？

**Comment by xiecz123** [comment]
> @xiecz123 我们可以如何做到 浏览器进行缩放时，粗细也一致呢？

首先你能复现出来吗？border-collapse: collapse这个属性在这种情况下原生就是有问题的。应该使用border-collapse: separate;border-spacing: 0;。然后再排查一下其他细节问题。然后可以参考一下其他组件库的实现。
