### ISSUE TITLE
[DatePicker] vue2+webpack 常规全局引用，报错（相关同学请检查 Vue 版本号是否为 Vue2.6.x，TD 暂不支持新版本 2.7.x）

### ISSUE THREAD

**Issue by gitwlp** [Tencent/tdesign-vue#1152]
### tdesign-vue 版本

 "tdesign-vue": "^0.43.2"   
 vue 2 项目 date-picker报错 

### 重现链接

https://0_43_2-tdesign-vue.surge.sh/vue/components/date-picker

### 重现步骤

![image](https://user-images.githubusercontent.com/79010739/178193498-4eb2b94e-278d-45c6-901a-598c97906e1f.png)

### 期望结果

不报错

### 实际结果

报错

### 框架版本

"tdesign-icons-vue": "^0.1.1",     "tdesign-vue": "^0.43.2",     "unplugin-auto-import": "^0.8.8",     "unplugin-vue-components": "^0.19.6",     "vue": "^2.6.14",     "vue-router": "^3.5.1",

### 浏览器版本

Chrome 已是最新版本
版本 103.0.5060.114（正式版本） （64 位）

### 系统版本

window10

### Node版本

v16.15.0

### 补充

**Comment by gitwlp** [comment]
DatePicker 组件根本没法用啊，水的一匹，领导还非得用这库，一堆shi山一样的组件。

**Comment by uyarn** [comment]
<img width="118" alt="image" src="https://user-images.githubusercontent.com/26377630/178243770-0217b20f-0cbd-4d0f-9376-70c695549962.png">
tdesign-vue与vue2.7暂时无法兼容  请将vue改成`~2.6.14` 删除lock文件 并重新安装一下

**Comment by uyarn** [comment]
> DatePicker 组件根本没法用啊，水的一匹，领导还非得用这库，一堆shi山一样的组件。

https://github.com/Tencent/tdesign-vue/blob/develop/README.md 
2.7版本发布之后 已经更新了README 出现没法使用的问题 先看清楚文档 再开始表达不满

**Comment by chaishi** [comment]
Vue2 刚刚发布 2.7，没有锁定版本的业务都会从 2.6 自动更新到不兼容版本 2.7。
要不顺带去给 Vue 提个 issue 喷一喷，问问为什么要突然来个不兼容更新版本

**Comment by HQ-Lin** [comment]
> DatePicker 组件根本没法用啊，水的一匹，领导还非得用这库，一堆shi山一样的组件。

有组件问题就说问题，哪怕不是组件的问题都已经耐心给你解答了，基本的debug排查都不会就来喷，你的代码很好的话来贡献代码看看

**Comment by chaishi** [comment]
> 有组件问题就说问题，哪怕不是组件的问题都已经耐心给你解答了，基本的debug排查都不会就来喷，你的代码很好的话来贡献代码看看

算了，咱们照顾下这位 小菜鸟吧，毕竟在学校呆了那么多年连基本的礼貌都没有学会，如何指望 TA 的技术有多厉害

**Comment by gitwlp** [comment]
各位大佬批评的是，是小弟学艺不精，疏忽了版本，昨天情绪过激在这给各位大佬和前辈说个sorry了，现在问题解决了，感谢。

**Comment by sodatea** [comment]
理论上不是 Vue 的 breaking change。应该是不知道为什么你的依赖管理器没有正确地处理 vue 的版本。

对库开发者：
根据报错查到的直接根源：Vue 2.7 的 `getCurrentInstance()` 返回的 internal instance 只有 `proxy` 属性，导致 `useVModel` 等依赖了 instance 上其他字段的函数运行时报错。

对用户：
理论上你不应该装到 2.7，因为 `@vue/composition-api` 的 `peerDependencies` 里写明了范围 `< 2.7` https://github.com/vuejs/composition-api/blob/7e7114251d5cad37957d1aa3caa14c971f08af28/package.json#L53-L55
出现这个问题应该是你的依赖管理工具出了 bug，解析到了错误的 `vue` 版本 。
或者除非你刚好是在 Vue 2.7.0 发布到 `@vue/composition-api` 1.7.0 发布之间的一小段时间里装的依赖……

---

为什么这不算破坏性变更？

- 对于只用 `vue` 的用户，2.7 之前没有 `getCurrentInstance` 方法，新加入这个方法不是破坏性变更；
- 对于用 `vue` +  `@vue/composition-api` 的库来说，只要版本解析正常，是不会引入 2.7 的，不会碰到此类问题；
