### ISSUE TITLE
[steps] 在steps点状模式下，如果展示为竖直展示，当steps的宽度固定，而某一项的内容过长会换行展示，则会出现dot icon被挤压的问题

### ISSUE THREAD

**Issue by JohnnyMarkBeee** [Tencent/tdesign-vue#1154]
### tdesign-vue 版本

0.43.3

### 重现链接

https://stackblitz.com/edit/angular-6zygvj?file=src%2Fdemo.vue

### 重现步骤

在steps点状模式下，如果展示为竖直展示，当steps的宽度固定，而某一项的内容过长会换行展示，则会出现dot icon被挤压的问题

### 期望结果

Dot icon不会被挤压

### 实际结果

Dot icon被右侧内容挤压变形

**Comment by xiaosansiji** [comment]
fixed in 0.44.0
