### ISSUE TITLE
可以添加固定在表尾的合计行吗？

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaishi** [comment]
有

**Comment by xiecz123** [comment]
> 有

用lastFullRow吗？那怎么固定在表尾呢？就是设置表格高度之后，不管表格内容是多还是少，合计行永远固定在列表底部，不随表格内容滚动。

**Comment by jiadongliuuuuu** [comment]
感谢反馈！我们拉研发对齐实现，再次感谢

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365
