### ISSUE TITLE
[Badge] 徽标是否应该默认 cursor: pointer;

### ISSUE THREAD

**Issue by ccccpj** [Tencent/tdesign-vue#1160]
### tdesign-vue 版本

0.43.3

### 重现链接

https://0_43_3-tdesign-vue.surge.sh/vue/components/badge

### 重现步骤

一般使用 徽标的组件都是可点击的，如果 徽标不是  cursor: pointer; 的话会有点奇怪

### 期望结果

 t-badge--circle { cursor: pointer; }

**Comment by xiaosansiji** [comment]
<img width="158" alt="企业微信截图_e9fa3862-40da-4d5f-82b1-1b4f2758c8f0" src="https://user-images.githubusercontent.com/7600149/178422457-8049f2da-d80d-4951-93b0-554c6428bf40.png">
一般徽标修饰的元素才需要被点击的，比如上图是在提醒用户点击这个按钮部分。
