### ISSUE TITLE
[table] 列隐藏配置

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1163]
### tdesign-vue 版本

0.43.2

### 重现步骤

1. 在API中我只找到`displayColumns`，但这个属性按我理解是只在列配置功能中有效，于是给`columnController`传个空对象，然后在`displayColumns`中传需要显示的字段（为什么不是传需要隐藏的字段），以上不知道我是否有理解错或者操作错，望指正；
2. 有没有其他配置项能直接配置隐藏列呢（有可能我没注意到）？譬如在列配置中`columns`直接配置隐藏列

**Comment by xiaosansiji** [comment]
`columns` 中不写那一列，不就不展示了么。。

**Comment by a-l-o-n-g** [comment]
到时候获取行数据不就缺失了这一列的数据？

**Comment by a-l-o-n-g** [comment]
> `columns` 中不写那一列，不就不展示了么。。

到时候获取行数据不就缺失了这一列的数据？

**Comment by chaishi** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/11605702/178477067-cbb5c143-3251-480e-ba0d-c5365c791a79.png">

**Comment by chaishi** [comment]
> 到时候获取行数据不就缺失了这一列的数据？

获取行数据，和列 有什么关系

**Comment by a-l-o-n-g** [comment]
只能通过配置列去实现吗？

**Comment by chaishi** [comment]
有点看不懂问题是啥
