### ISSUE TITLE
[Select] 使用 t-option 自定义选项时无法动态筛选

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#1175]
### tdesign-vue 版本

0.43.3

### 重现链接

https://stackblitz.com/edit/angular-3muzh7?file=src%2Fdemo.vue

### 重现步骤

- 前半段gif：右边select，是正常的（使用 prop options）
- 后半段gif：左边select，是不正常的（使用 t-option）：

![2022-07-14_21-45-17 (1)](https://user-images.githubusercontent.com/11243798/178997752-7c8f36f6-6ff2-401e-ab57-5603ad161de7.gif)

> （似乎使用 t-option 总是出现问题...

**Comment by skytt** [comment]
目前对 t-option 的机制会导致这个问题，会重新调整一下实现方式，可以先用 `options` 参数来传~

**Comment by uyarn** [comment]
fixed 0.45.2
