### ISSUE TITLE
[table] 多级表头的列拖拽问题，不生效

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1177]
### tdesign-vue 版本

0.43.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-noh2ns?file=/src/demo.vue

### 重现步骤

该示例为官方多级表头demo，表头数据是计算属性返回，很多情况是需要计算属性去计算表头或者是table数据
![image](https://user-images.githubusercontent.com/25051361/179130229-1095ce16-a4c0-49ac-a4f1-31a05757e18d.png)

**Comment by chaishi** [comment]
开发的时候，并没有支持 多级表头的列宽调整，以后是否支持，待定

**Comment by a-l-o-n-g** [comment]
> 开发的时候，并没有支持 多级表头的列宽调整，以后是否支持，待定

是指列拖拽吧？

**Comment by chaishi** [comment]
支持，开始处理

**Comment by chaishi** [comment]
这么多层，表头，哪个和哪个转换顺序呢？是什么样的需求场景需要调整多级表头的顺序，哪一集和哪一集

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/11605702/185776425-3e6ad5f7-58f0-461e-81d3-f3fc32187504.png">

**Comment by chaishi** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/11605702/185779212-7b0fe3a6-a19c-4d2b-a7ff-a5f05054e1ab.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/11605702/185779221-95f261cb-5e44-477c-9eec-e68e56c0f439.png">

https://github.com/Tencent/tdesign-vue/pull/1341
会完善多级表头的拖拽事件参数，而后业务侧根据这些参数自行调整表头的顺序

**Comment by xiaosansiji** [comment]
已在 0.46.2 版本修复

**Comment by a-l-o-n-g** [comment]
0.46.2 版本是需要自己根据这些参数进行列拖拽处理是吧?

**Comment by a-l-o-n-g** [comment]
@chaishi
