### ISSUE TITLE
[讨论] 阴影整体有点偏重效果

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1191]
### tdesign-vue 版本

1

### 重现步骤

<img width="381" alt="企业微信截图_d2dfd28d-ee74-4036-b18b-a5e5608b24d5" src="https://user-images.githubusercontent.com/11605702/179886727-c9e05c0f-a3b6-47a6-b0fa-37fc910d893e.png">

**Comment by uyarn** [comment]
阴影接下来也是可配置的
