### ISSUE TITLE
[Dialog] 支持全屏功能

### ISSUE THREAD

**Issue by zhangkuangwen** [Tencent/tdesign-vue#1204]
### 这个功能解决了什么问题

可以方便查看更多信息

### 你建议的方案是什么

新增一个全屏功能的api

**Comment by chaishi** [comment]
全屏 Dialog 的 UI 是什么样的

**Comment by zhangkuangwen** [comment]
类似于element ui的 fullscreen 这个api

**Comment by sinbadmaster** [comment]
这个issue要支持吗？我可以支持一下

**Comment by dianjie** [comment]
> 这个能力的使用场景可以介绍下不？有截图说明就更好了

[https://vvbin.cn/next/#/comp/modal](https://vvbin.cn/next/#/comp/modal)，像vben的这种全屏我感觉可以参考一下

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue/issues/1651
