### ISSUE TITLE
[date-picker] 时间组件clearable单独使用时不生效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1207]
### tdesign-vue 版本

0.44.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-se7kjf?file=/src/demo.vue

### 重现步骤

重现链接：
1. 示例1 中 单独配置clearable 不生效
2. 示例2中 默认有值的情况下， 随意输入值,   然后input失焦，没有做时间格式验证和转换,  显示了错误的信息

### 期望结果

1.  date-picker 可以单独配置clearable 清除数据
2.  希望在失去焦点时，可以展示目前显示的date值，不显示错误的信息

### 实际结果

![image](https://user-images.githubusercontent.com/13745660/180733555-319017fd-3b45-4906-9238-193789995701.png)

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by HQ-Lin** [comment]
1. Input 这里对删除的判断有点问题，readonly不应该跟clearable 冲突，应该只跟可否输入有关
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/24469546/180737457-edd05ac9-62f9-47ed-be1c-124830e8bc77.png">
2.失焦问题可能是另一个问题引起的，面板展开状态下再次点击输入框不应该收起，这个已经修复，看看下版本是不是这个问题也一起修复了

**Comment by uyarn** [comment]
fixed in 0.45.1
