### ISSUE TITLE
[TreeSelect] 选中的文本过长时，显示内容被下拉图标遮挡

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1210]
### tdesign-vue 版本

0.44.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-hp3etl?file=/src/demo.vue

### 重现步骤

当选中文本过长时，被下拉图标遮挡， 在0.43.0版本出现该情况，希望能和0.42.2版本展示

### 期望结果

0.42.2版本
![image](https://user-images.githubusercontent.com/13745660/180745367-7e2ca612-2142-4abb-be53-37f94d4580b7.png)

### 实际结果

![image](https://user-images.githubusercontent.com/13745660/180745636-5761bfdd-b0bb-43d2-ace5-f54b8197c033.png)

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by uyarn** [comment]
fixed in 0.45.1
