### ISSUE TITLE
[Cascader联级组件及其面板] 希望添加每列最顶部添加全选功能

### ISSUE THREAD

**Issue by JunSevenX** [Tencent/tdesign-vue#1220]
### 这个功能解决了什么问题

![626fe5f42bb462b25710d84495a4cc1](https://user-images.githubusercontent.com/72909879/181193520-f2721d38-382b-46e0-8ac2-7f3b8d17f12c.jpg)
![b40ec17667100cbc92752299380562f](https://user-images.githubusercontent.com/72909879/181193540-e6bb3a46-0817-4bce-8bd8-2064bb430747.jpg)
### 你建议的方案是什么

无

**Comment by chaishi** [comment]
合理需求，安排
