### ISSUE TITLE
[Select] 再次点击能够关闭选择框

### ISSUE THREAD

**Issue by DamanYang-cn** [Tencent/tdesign-vue#1222]
### 这个功能解决了什么问题

有的时候点开下拉框，想要通过再次点击选拉框来关闭下拉框，但是tdesign的下拉框不行，我看了别的比如ant和element都是可以的，希望尽快把这个做上去。

### 你建议的方案是什么

使t-select在展开选择内容时，再次点击下拉框可以收起。

**Comment by uyarn** [comment]
这个交互会改掉

**Comment by uyarn** [comment]
fixed in 0.45
