### ISSUE TITLE
[Button]ghost loading按钮文字消失

### ISSUE THREAD

**Issue by WZzhaoyi** [Tencent/tdesign-vue#1246]
### 重现链接
https://codesandbox.io/s/tdesign-vue-button-loading-dir7mh?file=/src/demo.vue

### 重现步骤
同时设置按钮ghost和loading

### 期望结果
loading时按钮文字显示

### 实际结果
loading时按钮文字隐去

| Environment | Info |
|---|---|
| 相关版本 | 0.45.1 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | MacOS、Chrome |
| Node版本 |  |

**Comment by uyarn** [comment]
@Wen1kang

**Comment by DevinXian** [comment]
issue 已认领

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
