### ISSUE TITLE
[Dialog] 未设置 confirmBtn 的类型为 null，导致使用函数式调用报错。

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#1249]
### tdesign-vue 版本

0.45.1

### 重现步骤

![image](https://user-images.githubusercontent.com/8199240/182797176-a0ed44ee-2360-4fc3-867a-720bd1313054.png)

### 期望结果

![企业微信截图_16596004728719](https://user-images.githubusercontent.com/8199240/182797252-f0fdb21a-7f42-44ef-899a-84fb8cacd4ed.png)

confirmBtn 类型声明应该有 null 类型。

### 框架版本

vue 2.6.11

**Comment by huoyuhao** [comment]
已领取

**Comment by uyarn** [comment]
0.46.1已发布
