### ISSUE TITLE
【Bug】合并单元格后内容丢失

### ISSUE THREAD

**Issue by huihuimoe** [Tencent/tdesign-vue#125]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
バージョン: 96.0.4664.110（Official Build） （x86_64）
Add browser version here

**Describe the bug**
tdesign-vue >=0.31 后合并单元格丢失内容

0.30 效果
![image](https://user-images.githubusercontent.com/1707683/147625422-086b59f2-2a9a-4986-af3e-b73e93112264.png)

0.31-0.32 丢失 cell
![image](https://user-images.githubusercontent.com/1707683/147625488-e93d146b-68fd-488a-af9d-f5d8b37ebf2a.png)

详看：
https://codesandbox.io/s/tdesign-vue-demo-forked-4j9d5?file=/src/demo.vue

**Comment by realyuyanan** [comment]
我看下。

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复

**Comment by huihuimoe** [comment]
thanks, 可以了

**Comment by huihuimoe** [comment]
@xiaosansiji 这边 0.33.1 又出现了一个丢失内容的 case，辛苦再看下哈

https://codesandbox.io/s/tdesign-vue-demo-forked-4j9d5?file=/src/demo.vue

![image](https://user-images.githubusercontent.com/1707683/149867832-fd1291bc-11ad-4ba7-ab27-0e6f1efecc40.png)

**Comment by realyuyanan** [comment]
> 

![image](https://user-images.githubusercontent.com/22365107/149870378-f54e026a-7d13-45a0-a86a-1984ceaa43e4.png)
目前正在处理的这个mr已经修复了，等下个版本修复哈。

**Comment by chaishi** [comment]
已修复，并发布至 `v0.33.2`
