### ISSUE TITLE
[t-button] 建议：loading 可选不 disabled

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue#1253]
### 这个功能解决了什么问题

Button 的 loading 功能不错。

### 你建议的方案是什么

建议：Button 的 loading 为 true 时，可选不 disabled。

因为有时，loading 也可以点击进行 `取消` 。

**Comment by chaishi** [comment]
你可以给 <button> 组件加一层 然后给 div 添加取消实践，示例： `<div onClick=“cancel"><button/></div>`

**Comment by vikyd** [comment]
> 你可以给 组件加一层 然后给 div 添加取消事件，示例： `<div onClick=“cancel"><button/></div>`

变相做到肯定可以。
原生提供，更方便。

**Comment by chaishi** [comment]
可以考虑扩展 `disabled` 属性，当其值为 `disabled=except-loading` 时，不禁用加载状态的图标

**Comment by uyarn** [comment]
@vikyd 这个已经改了 issue关闭了
