### ISSUE TITLE
[menu] expandType='normal'时，含有三级子菜单的时候页面会报错，并无法渲染子菜单

### ISSUE THREAD

**Issue by sinbadmaster** [Tencent/tdesign-vue#1257]
### tdesign-vue 版本

0.45.1

### 重现链接

https://stackblitz.com/edit/angular-ftiyuz?file=package.json,src%2Fdemo.vue

### 重现步骤

打开重现链接，打开开发者工具即可查看报错

### 期望结果

可以正常渲染出子菜单

### 实际结果

![image](https://user-images.githubusercontent.com/40019023/183384161-5463d1b5-1d3d-4098-adf8-faac306bcb3a.png)

### 框架版本

vue(2.6.14)

**Comment by justtoday111** [comment]
已认领
