### ISSUE TITLE
[TagInput] 无法解析Java Web后端返回List类型数据

### ISSUE THREAD

**Issue by DamanYang-cn** [Tencent/tdesign-vue#1260]
### 这个功能解决了什么问题

Java Web后端返回List类型数据是["1", "2"]，但该组件只支持解析['1', '2']格式，虽然可以通过替换解决问题，但还是希望能改进一下。

### 你建议的方案是什么

完善数据解析

**Comment by chaishi** [comment]
看不明白这个问题，"" 双引号 和 '' 单引号，不都是字符串么，为何一个可以，一个不可以，提供一下浮现问题的代码哈

**Comment by LeoEatle** [comment]
要传入的应该是数组而不是字符串吧
Java Web返回的是不是一个字符串？是否应该`JSON.parse`一下？
