### ISSUE TITLE
[t-upload] 使用上传组件处理1.6GB到2GB的文件浏览器崩溃

### ISSUE THREAD

**Issue by lw28vlk** [Tencent/tdesign-vue#1262]
### tdesign-vue 版本

0.45.1

### 重现步骤

使用任意单独的1.6G以上文件（2G以内）上传毕现，超过2G和1.6G以内都不会有问题。

### 浏览器版本

chrome最新

### 系统版本

mac和win都有

**Comment by EricHan0723** [comment]
大文件还是做分片吧
