### ISSUE TITLE
[colorpicker] 使用vue@2.5.2 带触发元素的颜色选择器渲染不出来

### ISSUE THREAD

**Issue by wangling6821** [Tencent/tdesign-vue#1266]
### tdesign-vue 版本

0.45.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-oufow4?file=/src/demo.vue:95-102

### 重现步骤

将vue版本切换为2.5.2

### 期望结果

可以使用带触发器的颜色选择器

### 实际结果

渲染后只有一个空的span标签
![image](https://user-images.githubusercontent.com/26473852/183834805-dfb8dada-f4cb-4fda-9c8d-ade02161eae1.png)

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-vkqg8h?file=/src/demo.vue
大概率和@vue/composition-api有关 使用了@vue/composition-api的组件都无法在2.5下正常渲染 
但是看@vue/composition-api的依赖又是 vue > 2.5 <2.7
测试下来其实得2.6.0才可以正常
