### ISSUE TITLE
[ConfigProvider] classPrefix仅对部分组件生效

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#1269]
### tdesign-vue 版本

0.45.2

### 实际结果

目前大量的组件，仍然使用config.ts中的prefix来生成class。而不是使用configProvider中的classPrefix。

**Comment by uyarn** [comment]
开发中 预计未来1-2个版本会全部替换完

**Comment by uyarn** [comment]
0.46.0已修复
