### ISSUE TITLE
Icon Button 圆形small时，变成椭圆形了

### ISSUE THREAD

**Issue by ifAandBisC** [Tencent/tdesign-vue#127]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by ifAandBisC** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-w6647?file=/src/demo.vue

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
