### ISSUE TITLE
[Table]表格嵌套情况下不能独立控制 stripe/border 属性

### ISSUE THREAD

**Issue by Foxhunters** [Tencent/tdesign-vue#1272]
tdesign-vue 版本
0.45.1

重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-h8vq4d?file=/src/demo.vue

重现步骤
<img width="1390" alt="企业微信截图_5c51843f-66ce-4c6b-bded-8438f147eace" src="https://user-images.githubusercontent.com/39594058/184076190-716ce451-538e-40e5-9561-21829db87426.png">

期望结果
No response

实际结果
No response

框架版本
No response

浏览器版本
No response

系统版本
No response

Node版本
No response

补充说明
No response

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/761

**Comment by uyarn** [comment]
published 0.46.2
