### ISSUE TITLE
[Collapse] 折叠面板几个问题

### ISSUE THREAD

**Issue by yuzunyue** [Tencent/tdesign-vue#1277]
### tdesign-vue 版本

0.45.2

### 重现链接

只在我这个程序里有此问题，CodeSandbox无法复现

### 重现步骤

问题一：Collapse无法显示
![image](https://user-images.githubusercontent.com/32872977/184282702-da859e1e-f833-400e-832a-2af974f2b8e5.png)
![image](https://user-images.githubusercontent.com/32872977/184282781-7c72b66a-e33c-453d-af72-c012002f18b7.png)
collapse为空
问题代码如下：
![image](https://user-images.githubusercontent.com/32872977/184282827-f4d20252-8885-4ab2-8538-a2af2e604386.png)
如果在panel外套一层div，就可以解决
![image](https://user-images.githubusercontent.com/32872977/184282939-e826090d-c73e-4796-93f5-b13454ab459a.png)
![image](https://user-images.githubusercontent.com/32872977/184283006-b2c58d1d-1990-4b5e-9b3e-2877107e40bd.png)

问题二：将header设置为slot时，expandOnRowClick不生效，不是slot时，生效，此问题也只在我的程序里有，可以参看前边代码

### 框架版本

Vue(2.5.2)

### 系统版本

Win10

### Node版本

14

**Comment by chaishi** [comment]
只有截图不行，需要可复现问题的示例代码。

https://stackblitz.com/edit/angular-p8392q?file=src%2Fdemo.vue,src%2Fmain.js
请在这个链接里面复现一下你说的问题
