### ISSUE TITLE
tree-select, select等filterable时，关闭弹出层需要在其他地方单击两下才行

### ISSUE THREAD

**Issue by geff1991** [Tencent/tdesign-vue#128]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**
![test1](https://user-images.githubusercontent.com/6264677/147638173-7bbbc54d-a4a9-4a5a-b7b5-0ba1a1d00b30.gif)

![test2](https://user-images.githubusercontent.com/6264677/147638150-af1682c3-6875-45a7-9e6a-4a28089944f9.gif)

**Additional context**

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
