### ISSUE TITLE
📌 [示例代码改造] 使用Space组件替换示例代码

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue#1281]
## 说明

1. 使用`Space`组件替换  example中组件的示例代码，减少手动写的用于纵向、横向对齐的样式代码，并尽可能保持样式不变，文档持续更新 可参考此PR - https://github.com/Tencent/tdesign-vue/pull/1309
2. 参与贡献请在此 `issue` 中评论领取的组件
3. 领取后请在两周内提交代码，过程中发现组件问题可以提 `issue` 或在 `PR` 中修复

### 基础
* [x] `Button` @YuhangLike  https://github.com/Tencent/tdesign-vue/pull/1334
* [x] `Icon` @Isabella327 https://github.com/Tencent/tdesign-vue/pull/1343
* [x] `Link` @zhangpaopao0609 https://github.com/Tencent/tdesign-vue/pull/1376
### 布局

* [x] `Divider` @Isabella327 https://github.com/Tencent/tdesign-vue/pull/1343
* [x] `Grid`
* [x] `Layout` @vegetalbirddd https://github.com/Tencent/tdesign-vue/pull/1517
* [x] `Space` 

###  导航

* [x] `Affix`
* [x] `Anchor` 
* [x] `Breadcrumb` @Isabella327 https://github.com/Tencent/tdesign-vue/pull/1343
* [x] `Dropdown`
* [x] `Pagination`
* [x] `Steps` @sechi747  https://github.com/Tencent/tdesign-vue/pull/1394
* [x] `Tabs` @yangchao987 https://github.com/Tencent/tdesign-vue/pull/1471
 

### 输入

* [x] `Cascader ` @pengYYYYY https://github.com/Tencent/tdesign-vue/pull/1457
* [x] `Checkbox` @Summer-Shen  https://github.com/Tencent/tdesign-vue/pull/1485
* [x] `ColorPicker` @Summer-Shen  https://github.com/Tencent/tdesign-vue/pull/1485
* [x] `DatePicker`  @Summer-Shen https://github.com/Tencent/tdesign-vue/pull/1485
* [x] `Form` @Summer-Shen https://github.com/Tencent/tdesign-vue/pull/1368
* [x] `Input`
* [x] `InputNumber` https://github.com/Tencent/tdesign-vue/pull/1284
* [x] `InputAdornment`
* [x] `Radio` @yangchao987 https://github.com/Tencent/tdesign-vue/pull/1375
* [x] `RangeInput`
* [x] `Select` https://github.com/Tencent/tdesign-vue/pull/1309
* [x] `SelectInput` 
* [x] `Slider`
* [x] `Switch` @Isabella327 https://github.com/Tencent/tdesign-vue/pull/1343
* [x] `TagInput` https://github.com/Tencent/tdesign-vue/pull/1531
* [x] `Textarea`
* [x] `Transfer` 
* [x] `TimePicker` https://github.com/Tencent/tdesign-vue/pull/1475
* [x] `TreeSelect`
* [x] `Upload`  (先别认领)

### 数据展示

* [x]  `Avatar`  @jiazengp https://github.com/Tencent/tdesign-vue/pull/1350
* [x]  `Badge` @sechi747 https://github.com/Tencent/tdesign-vue/pull/1381
* [x] `Calendar` 
* [x] `Card`  https://github.com/Tencent/tdesign-vue/pull/1531
* [x] `Collapse ` 
* [x] `Comment` 
* [x] `List` 
* [x] `Loading` @sechi747 https://github.com/Tencent/tdesign-vue/pull/1394
* [x] `Progress` @sechi747  https://github.com/Tencent/tdesign-vue/pull/1394
* [x] `Skeleton` 
* [x] `Swiper` 
* [x] `Table` 
* [x] `Tag` 
* [x] `Tooltip`
* [x] `Tree` @lmmlala https://github.com/Tencent/tdesign-vue/pull/1406

### 消息提醒

* [x] `Alert` @royal-cc https://github.com/Tencent/tdesign-vue/pull/1393
* [x] `Dialog` @mark1307779 https://github.com/Tencent/tdesign-vue/pull/1333
* [x] `Drawer`
* [x] `Message` @code-x2022 https://github.com/Tencent/tdesign-vue/pull/1455
* [x] `Notification` @sechi747  https://github.com/Tencent/tdesign-vue/pull/1394
* [x] `PopConfirm`
* [x] `Popup` https://github.com/Tencent/tdesign-vue/pull/1380

**Comment by jiazengp** [comment]
领取 `avatar`

**Comment by mark1307779** [comment]
领取`dialog` @uyarn

**Comment by YuhangLike** [comment]
领取button @uyarn

**Comment by Summer-Shen** [comment]
领取 `Form` @uyarn

**Comment by lmmlala** [comment]
@uyarn 领取 Tree

**Comment by yangchao987** [comment]
@uyarn Radio

**Comment by royal-cc** [comment]
领取Alert @uyarn

**Comment by zhangpaopao0609** [comment]
领取 Link @uyarn

**Comment by yangchao987** [comment]
@uyarn 领取 tabs

**Comment by sechi747** [comment]
领取 Badge @uyarn

**Comment by sechi747** [comment]
领取 Steps, Loading, Progress, Notification @uyarn

**Comment by Summer-Shen** [comment]
再领取一下 `Cascader`, `Checkbox`, `ColorPicker` 和 `DatePicker` @uyarn

**Comment by code-x2022** [comment]
领取Message @uyarn

**Comment by uyarn** [comment]
Attention: 由于最近目录结构调整 example目录统一到各个组件内 有领取任务并在之前拉取代码的朋友请rebase下upstream代码再继续完成：）

**Comment by vegetalbirddd** [comment]
领取layout

**Comment by uyarn** [comment]
Input/SelectInput/RangeInput/TreeSelect/Collapse/Anchor/Calendar/Drawer/ List/InputAdornment/ Skeleton/Slider/ Tag/Textarea 
- https://github.com/Tencent/tdesign-vue/pull/1674

**Comment by uyarn** [comment]
DEMO改造已完成 谢谢参与这个issue的contributors :)
