### ISSUE TITLE
[table]固定列阴影样式不能随窗口放大缩小而变化

### ISSUE THREAD

**Issue by jiason** [Tencent/tdesign-vue#1289]
### tdesign-vue 版本

0.45.2

### 重现链接

https://tdesign.tencent.com/vue/components/table

### 重现步骤

列表在小窗口可以左右滑动，固定列有阴影效果；窗口放大后，不能左右滑动，但还保留了阴影效果。反之也是。

### 期望结果

固定列阴影样式可以随窗口变化调整。

**Comment by chaishi** [comment]
信息已接收，早期处理过这个逻辑，应该后面哪里的改动影响到了

**Comment by chaishi** [comment]
React resolved in https://github.com/Tencent/tdesign-react/pull/1312

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1316

**Comment by uyarn** [comment]
fixed 0.46.1
