### ISSUE TITLE
t-icon无法离线使用

### ISSUE THREAD

**Issue by chenyueqin1010** [Tencent/tdesign-vue#129]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by uyarn** [comment]
t-icon需要依赖CDN的资源，目前的方案短期内不能在离线环境下使用，需要在离线环境下使用，请通过`tdesign-icons-vue`的包按需引用。
以close 关闭图标为例
```js
<t-icon name="close" />
```
需调整为
```js
import { CloseIcon} from 'tdesign-icons-vue'

<CloseIcon />
```
