### ISSUE TITLE
[table] 希望可以同时支持行拖拽和列拖拽

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1290]
### 这个功能解决了什么问题

希望一个表格可以同时支持行拖拽和列拖拽。
目前dragSort只能配置一种拖动形式， dragSort='row-handler’ 和 dragSort='col’行拖动和列拖动只允许一种。

### 你建议的方案是什么

希望增加支持行拖拽和列拖拽的配置模式

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1341

**Comment by xiaosansiji** [comment]
已在 0.46.2 版本实现
