### ISSUE TITLE
[Table] 在分页表格中行拖拽排序的问题

### ISSUE THREAD

**Issue by zc001111** [Tencent/tdesign-vue#1295]
### tdesign-vue 版本

0.45.2

### 重现链接

https://codesandbox.io/embed/tdesign-vue-demo-forked-53vmsi?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

第一页初始状态：
![微信图片_20220818202721](https://user-images.githubusercontent.com/111274573/185394958-33534177-bc69-46a0-a1ee-0fe7e004fa19.png)
第二页初始状态：
![1660825794230](https://user-images.githubusercontent.com/111274573/185395030-71707084-2d9b-4b59-bf12-791e24e13220.jpg)

拖拽第二页中的第一条数据（data[5]）到第二页的第二条数据（data[6]）。

### 期望结果

期望上，第二页中的第一条数据（data[5]）和第二条数据（data[6]）交换位置。

### 实际结果

实际中，拖拽将第一页中的第一条和第二条数据换了位置，而非将第二页中的第一条和第二条的位置交换。
此时第二页的排序未改变。

第二页此时的状态：
![image](https://user-images.githubusercontent.com/111274573/185395253-dded00c6-1766-4511-bf22-7ba0cc19d91b.png)

第一页此时的状态：
![1660825902503](https://user-images.githubusercontent.com/111274573/185395373-532c61bc-8818-433e-b017-721056ff0f62.jpg)

### 框架版本

vue2

### 浏览器版本

chrome

### 系统版本

windows10

**Comment by chaishi** [comment]
代码和问题描述太零散了，辛苦提供一个可以复现问题的链接，链接从哪里来呢？请看下图

<img width="886" alt="image" src="https://user-images.githubusercontent.com/11605702/184627907-4d458891-8370-4bde-ad29-141d330bb45b.png">

**Comment by zc001111** [comment]
不太会用Stackblitz，直接贴一下组件代码吧
```
<template>
  <div class="demo-container t-table-demo-sort tdesign-demo__table">
    <div>
      <t-checkbox v-model="loading">加载状态</t-checkbox>
    </div>
    <div class="item">
      <!-- 拖拽排序涉及到 data 的变更，相对比较慎重，因此仅支持受控用法 -->
      <t-table
        rowKey="id"
        :columns="columns"
        :data="data"
        :loading="loading"
        dragSort="row-handler"
        @drag-sort="onDragSort"
        :pagination="pagination"
        @page-change="onPageChange"
      >
        <template #status="{ row }">
          <p class="status" :class="['', 'warning', 'unhealth'][row.status]">
            {{ ['健康', '警告', '异常'][row.status] }}
          </p>
        </template>
      </t-table>
    </div>
  </div>
</template>

<script lang="jsx">
import { MoveIcon } from 'tdesign-icons-vue';

const columns = [
  {
    colKey: 'drag', // 列拖拽排序必要参数
    title: '排序',
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    cell: (h) => <MoveIcon />,
    width: 80,
  },
  { colKey: 'instance', title: '集群名称' },
  {
    colKey: 'status',
    title: '状态',
  },
  {
    colKey: 'survivalTime',
    title: '存活时间(s)',
  },
  { colKey: 'owner', title: '管理员' },
];

const initialData = new Array(20).fill(5).map((_, i) => ({
  id: i + 1,
  instance: `JQTest${i + 1}`,
  status: [0, 1, 2, 1][i % 4],
  owner: ['jenny;peter', 'jenny', 'jenny', 'peter'][i % 4],
  survivalTime: [1000, 1000, 500, 1500][i % 4],
}));

export default {
  data() {
    return {
      loading: false,
      data: [...initialData],
      columns,
      pagination: {
        current: 1,
        pageSize: 5,
        total: 20,
      },
    };
  },
  methods: {
    // currentData is going to be deprecated
    onDragSort({ currentIndex, current, targetIndex, target, data, newData, e }) {
      console.log('交换行', currentIndex, current, targetIndex, target, data, newData, e);
      this.data = newData;
    },
    onPageChange(pageInfo, newData) {
      // 受控用法所需
      this.pagination.current = pageInfo.current;
      this.pagination.pageSize = pageInfo.pageSize;
      console.log('page-change:', pageInfo, newData);
    },
  },
};
</script>

```

**Comment by chaishi** [comment]
你使用的是 tdesign-vue 版本：0.45.2
最新的  tdesign-vue 版本：0.46.1

仓库仅接收最新版本的问题，老的版本，辛苦自己升级下版本号。

下方是我用你提供的链接看到的结果，顺序调整没有问题。（应该只是低版本的问题）
<img width="567" alt="image" src="https://user-images.githubusercontent.com/11605702/185779504-2df462b1-7b9f-42e4-8690-d96475677b11.png">

**Comment by chaishi** [comment]
由于无法复现问题，issue 关闭
