### ISSUE TITLE
当select在modal里面的时候，出现下拉框的时候，需要在外面点击两次才能关闭，麻烦看看

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#130]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here
![image](https://user-images.githubusercontent.com/15682051/147642719-b201a080-bc29-4712-ad9d-2bfa7d0da5fc.png)

**Describe the bug**

**Additional context**

![image](https://user-images.githubusercontent.com/15682051/147642954-b415901c-420f-4761-8797-cd5dca7626f1.png)

**Comment by geff1991** [comment]
应该是一个原因
https://github.com/Tencent/tdesign-vue/issues/128

**Comment by geff1991** [comment]
https://github.com/Tencent/tdesign-vue/pull/329
