### ISSUE TITLE
[select] 当我在dialog中使用table 设置可编辑的时候使用select 点击2下才会关闭它 而我点击遮罩层的时候 dialog会关闭 select展示的下拉还会存在页面中

### ISSUE THREAD

**Issue by zhangkuangwen** [Tencent/tdesign-vue#1314]
### tdesign-vue 版本

0.45.2

### 重现步骤

当我在dialog中使用table 设置可编辑的时候使用select 点击2下才会关闭它 而我点击遮罩层的时候 dialog会关闭 select展示的下拉还会存在页面中

**Comment by zhangkuangwen** [comment]
而且同时有2个select的时候点击一个后 再次点击另一个 先点击的那个下拉列表不会关闭

**Comment by uyarn** [comment]
`当我在dialog中使用table 设置可编辑的时候使用select 点击2下才会关闭它 而我点击遮罩层的时候 dialog会关闭 select展示的下拉还会存在页面中` 可以提供个最小demo吗 这样说没法完全复现你的场景

**Comment by uyarn** [comment]
> 而且同时有2个select的时候点击一个后 再次点击另一个 先点击的那个下拉列表不会关闭

这个我们确认下..

**Comment by zhangkuangwen** [comment]
我这边将版本切换到0.46.0 就没有这个问题了
