### ISSUE TITLE
popup中含有select时，会在select选中时popup消失

### ISSUE THREAD

**Issue by rengelyes** [Tencent/tdesign-vue#133]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by chaishi** [comment]
select 选中的时候 popup 消失是不符合预期的吗？

**Comment by rengelyes** [comment]
多个select的话，我预期是全部选中才会消失，触发方式是click的场景下，我理解应该是在主动点击popup外的区域才消失才符合逻辑

**Comment by ikeq** [comment]
WIP
