### ISSUE TITLE
[button] 当为ghost时hover覆盖文字

### ISSUE THREAD

**Issue by YuhangLike** [Tencent/tdesign-vue#1331]
### tdesign-vue 版本

0.45.2

### 重现步骤

![Uploading image.png…]()

### 期望结果

覆盖后影响用户体验，hover后应该修改文字的颜色

**Comment by YuhangLike** [comment]
![image](https://user-images.githubusercontent.com/76248720/185538398-32c14db4-9872-44f4-a6e3-dce0b6166769.png)

**Comment by chaishi** [comment]
并非所有的 API 组合都支持 Ghost，Ghost 仅支持部分场景，如果要使用 ghost，请参考下方支持的情况。

**Comment by YuhangLike** [comment]
了解

**Comment by uyarn** [comment]
duplicated of https://github.com/Tencent/tdesign-vue/issues/1246 
有人正在处理这个issue
