### ISSUE TITLE
[table] 在表头数据与列表数据是异步请求的情况下，如果允许调整列宽，则设置的列宽度不生效

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1332]
### tdesign-vue 版本

0.46.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-urki26

### 重现步骤

demo是官网table组件的多级表头的表格代码，主要调整了以下代码：
1，数据延时加载，模拟请求
![image](https://user-images.githubusercontent.com/25051361/185560842-42afe7f4-ad19-4f6b-a4eb-d25035d1f22f.png)
2，配置了允许调整列宽
![image](https://user-images.githubusercontent.com/25051361/185560946-1e0457b3-b72f-47da-b58a-7be99dfdc837.png)

如果不允许调整列宽，则宽度生效，如果允许调整列宽，则宽度不生效

**Comment by chaishi** [comment]
关键点，应该不是异步或否的问题，而是 列宽调整没有支持「多级表头」

**Comment by chaishi** [comment]
相同 issue 关闭，请关注这个：https://github.com/Tencent/tdesign-vue/issues/1177

**Comment by xiaosansiji** [comment]
已在 0.4.3 版本修复
