### ISSUE TITLE
当table组件的数据是异步加载的时候，maxHeight属性不生效

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#134]
**Describe Framework**

tdesign-vue

**Describe Environment**

![image](https://user-images.githubusercontent.com/15682051/147660732-92b9dba4-f20a-4528-b700-a302c5968a00.png)

**Describe the bug**
table组件data来自计算属性的时候，maxHeight不起作用

**Additional context**

复现地址：https://codesandbox.io/s/tdesign-vue-demo-forked-yzbfc?file=/src/demo.vue

**Comment by realyuyanan** [comment]
给出的例子表现看起来是正确的。我本地也有测试，看起来没有问题。
![image](https://user-images.githubusercontent.com/22365107/147746051-806b0cca-d4c3-4d4f-82e7-a78b7e75a445.png)

**Comment by YFAnt** [comment]
我浮现一下，感觉是异步的问题https://codesandbox.io/s/tdesign-vue-demo-forked-0frqe?file=/src/demo.vue

**Comment by realyuyanan** [comment]
> 我浮现一下，感觉是异步的问题https://codesandbox.io/s/tdesign-vue-demo-forked-0frqe?file=/src/demo.vue

好的，我来看下。

**Comment by sampsonliu** [comment]
这个放在哪一个版本发布呢

**Comment by xiaosansiji** [comment]
已在 0.33.1 版本中修复
