### ISSUE TITLE
[Table] 可调整列宽功能，当前表现为 表格整体宽度不动调整相邻的列宽，期望也支持保持相邻列宽不动而调整表格宽度

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1340]
### tdesign-vue 版本

0.46.1

### 期望实现

- 新增 API `columnResizeConfig: { resizeElement: 'sibling' | 'table' }`。
- `columnResizeConfig.resizeElement = sibling` 表示调整列宽时，保持表格总宽度不变，调整相邻列的宽度
- `columnResizeConfig.resizeElement = table` 表示调整列宽时，保持相邻列的宽度不变，调整表格总宽度

默认值为 `resizeElement = table`

注意：尽量把大函数切成小函数，方便阅读

### 如何获取新的 API ？

```bash
git clone https://github.com/TDesignOteam/tdesign-api
npm run api:docs Dialog 'Vue(PC)' finalProject
```

tdesign-api 和 tdesign-vue 目录保持同级

**Comment by ZTao-z** [comment]
认领

**Comment by chaishi** [comment]
特性讨论中
