### ISSUE TITLE
[Table] 本地数据分页表格中使用拖拽排序，排序结果不正确

### ISSUE THREAD

**Issue by zc001111** [Tencent/tdesign-vue#1342]
### tdesign-vue 版本

0.46.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-9td89w?file=/src/demo.vue

### 重现步骤

操作：在第二页中，将集群名称为“JQTest6”的数据拖拽到集群名称为”JQTest7“的那行数据。

### 期望结果

”JQTest6“和”JQTest7“交换位置。

### 实际结果

【CodeSandbox环境下会有延迟卡顿，并非无法复现问题，等待页面加载完后，随后切换到第一页即可看到问题所在。】
第二页数据顺序未产生变化，第一页集群名称为”JQTest1“和”JQTest2“的数据交换了位置。
切换回第二页，可以看到”JQTest6“和”JQTest7“的位置并未改变。

### 框架版本

vue~2.6.14

**Comment by chaishi** [comment]
这个 提问很眼熟，像是重复 issue。我刚刚打开看顺序，是正常的

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11605702/185794212-f4aff2a8-ddba-4202-b478-9f94e3505f6e.png">

**Comment by zc001111** [comment]
CodeSandbox环境下会有延迟卡顿，并非无法复现问题.
【等待页面加载完，随后切换到第一页即可看到问题所在】

**Comment by chaishi** [comment]
如果 codesandbox 链接无法复现，这个链接就没有意义了。

再有，记得我上次是复制代码在本地跑的，没发现问题

**Comment by zc001111** [comment]
@chaishi 
下方是复现视频。
前20s一直是卡顿状态，20s后卡顿结束才能看到问题出现

https://user-images.githubusercontent.com/111274573/186059221-3c6f6c77-2aa6-4d86-88f5-841eed5d575f.mov

**Comment by zc001111** [comment]
说的更直白一些，在拖拽第二页的JQTest6到JQTest7之后。
`onDragSort({ currentIndex, current, targetIndex, target, data, newData, e }){}`
该方法中的current和target如下图所示：
![~YMIVOBT3G{KZ3(~6 R4E83](https://user-images.githubusercontent.com/111274573/186064624-0205f3e6-209e-4d9c-b60f-638b3e26e65e.png)
data如下图所示：
![image](https://user-images.githubusercontent.com/111274573/186064777-e85b59c9-b95c-457c-919d-a53715356e11.png)
newData如下图所示：
![image](https://user-images.githubusercontent.com/111274573/186064797-35311d38-66a1-4652-a56e-20beba3c4710.png)

**Comment by chaishi** [comment]
> @chaishi 下方是链接的复现视频。 00:04~00:20一直是卡顿状态，20s后卡顿结束才能看到问题出现

codesandbox 本身卡

**Comment by chaishi** [comment]
我再跑下看看吧

**Comment by chaishi** [comment]
需要代码，代码，截图和视频 都不能让我们快速定位问题

**Comment by uyarn** [comment]
fixed 0.49.3
