### ISSUE TITLE
[Table] 筛选功能建议

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue#1346]
### 这个功能解决了什么问题

你好，单选框是否也能添加重置的按钮呢？不然还得自己去维护一个变量；还有就是输入框筛选的时候，能否直接在head中输入，现在的head样式看起来也像是placeholder，鼠标放上去也会显示成一个可编辑的水平文本的光标。

### 你建议的方案是什么

![Snipaste_2022-08-22_15-25-28](https://user-images.githubusercontent.com/54493910/185865086-c0b1c17a-d6bf-44fd-9137-055b12bab6e0.png)

**Comment by chaishi** [comment]
> 你好，单选框是否也能添加重置的按钮呢

这个当前已支持，设置 `showConfirmAndReset: true` 就可以了，示例代码中有，仔细看下。

**Comment by chaishi** [comment]
> 能否直接在head中输入

不符合交互统一

**Comment by chaishi** [comment]
对于 header 里面输入，可以自定义表头自行实现
