### ISSUE TITLE
[Table] 新增 `column.resizable` 支持自定义任意列是否可拖拽调整宽度

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1348]
### tdesign-vue 版本

0.46.1

### 期望功能

当前仅支持 `table.resizable` 整体控制是否允许拖拽调整宽度。新增 `column.resizable` 支持自定义任意列是否可拖拽调整宽度

**Comment by ZTao-z** [comment]
认领

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1523

published at `0.48.0`，建议使用 `0.48.2+`
