### ISSUE TITLE
[table] table中rowKey建议增加function 和 string两种类型

### ISSUE THREAD

**Issue by luchuanqi** [Tencent/tdesign-vue#1353]
### 这个功能解决了什么问题

rowKey绑定id，当做update操作时，列表不更新。 只能清空data， 然后再次重绘列表

### 你建议的方案是什么

建议增加function 和 string两种类型

**Comment by chaishi** [comment]
自己处理下数据吧，不也复杂，就一行代码的事情，
组件里面也是一个 .map

**Comment by luchuanqi** [comment]
但是长列表的时候，这个会导致列表重绘。 用户体验有点差

**Comment by chaishi** [comment]
长列表的时候是什么时候，如果存在 data 的变化，无论是否 map，都会重绘

**Comment by luchuanqi** [comment]
key不变， 是不会重新渲染的。  其他table组件，都会加上function类型的， 就是回避只update一个数据，整个列表都要重新渲染

**Comment by chaishi** [comment]
> 但是长列表的时候，这个会导致列表重绘。 用户体验有点差

是开发体验差，还是用户体验差，录个屏我看下有多差

**Comment by chaishi** [comment]
> rowKey绑定id，当做update操作时，列表不更新。 只能清空data， 然后再次重绘列表

如果是 Vue2，我记得是有个方法单独更新的 `Vue.$set(xxx, xxx)` 或者 `this.$set(data[i], 'field', 'newValue')`

**Comment by luchuanqi** [comment]
table下面是tree

**Comment by chaishi** [comment]
下个月安排

**Comment by chaishi** [comment]
十分抱歉，时间有限，且有其他的解决方案，暂不支持。
