### ISSUE TITLE
[select] filterable multiple 远程搜索 多选，选中一个值后，输入框不能再次输入，无法二次搜索

### ISSUE THREAD

**Issue by yz155** [Tencent/tdesign-vue#1358]
### 重现步骤
Select选择器，设置为多选模式，开启远程搜索，输入关键字，得到数据列表，选中一个值后；想更改关键字，但是输入框无法输入。

### 期望结果
选中一值后，可更改关键字得到新数据。

### 实际结果
选中一值后无法再次输入关键字。

### 补充说明

| Environment | Info |
|---|---|
| 相关版本 | 0.46.1 |
| 框架版本 / 基础库版本 | vue(2.6.14) |
| 系统、浏览器 | macos 12.5 / chrome 版本 104.0.5112.101（正式版本） (arm64) |
| Node版本 |  |

**Comment by skytt** [comment]
目前场景是popup隐藏的时候不响应输入，你描述的选中后无法输入的场景应该是popup已经隐藏了

点击组件隐藏popup的逻辑，这块准备优化一下

**Comment by yz155** [comment]
> 目前场景是popup隐藏的时候不响应输入，你描述的选中后无法输入的场景应该是popup已经隐藏了
> 
> 点击组件隐藏popup的逻辑，这块准备优化一下

确实是这样，但我发现另一个问题。
当我选中一个值后，更改关键字，options更新，此是options不包含上次选中的值，然后只显示了个value值。

<img width="498" alt="image" src="https://user-images.githubusercontent.com/34710340/186129983-b890e41d-f2ad-47af-972c-dde68f5a51ab.png">

**Comment by skytt** [comment]
> > 目前场景是popup隐藏的时候不响应输入，你描述的选中后无法输入的场景应该是popup已经隐藏了
> > 点击组件隐藏popup的逻辑，这块准备优化一下
> 
> 确实是这样，但我发现另一个问题。 当我选中一个值后，更改关键字，options更新，此时options不包含上次选中的值，然后只显示了个value值。
> 
> <img alt="image" width="498" src="https://user-images.githubusercontent.com/34710340/186129983-b890e41d-f2ad-47af-972c-dde68f5a51ab.png">

等 #1318 这个 PR 发布以后更新 td 版本，可以利用 object 类型的 value 保留回显能力
