### ISSUE TITLE
form表单校验trigger属性似乎没有正确支持

### ISSUE THREAD

**Issue by pangao66** [Tencent/tdesign-vue#136]
**Describe Framework**

tdesign-vue

**Describe Environment**
稳定复线

**Describe the bug**
form的表单校验   trigger属性似乎是有问题的
![wecom-temp-d3561134018addc1d5f56c87ca59a0e9](https://user-images.githubusercontent.com/20113031/147718385-66071021-5ca1-4eae-8f41-1c69518a7eb7.png)
以官方文档这个demo为例,这个url的校验我想失去了焦点再校验,   这里改成blur    失去了焦点不会校验了      submit才会校验
同时 使用change校验的时候,  输入框的border会同时显示红色和蓝色  体验不好

**Additional context**
希望能正确支持表单校验的triggeer属性并修复css样式问题

**Comment by chaishi** [comment]
feature, 规划中
