### ISSUE TITLE
[Select] 使用creatable创建新条目时能否给新条目增加不同的样式区分

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1360]
### 这个功能解决了什么问题

在创建新条目时，且需要用到filterable去过滤，如果已有的下拉选项有较类似的选项，这时很难区分过滤出的选项与新条目的选项，虽然现在新条目是在第一项，但如果第一项已经是已有选项，这时候是不知道的

### 你建议的方案是什么

能否添加样式区分呢

**Comment by a-l-o-n-g** [comment]
在最新版本0.46.4中，创建的新条目无法通过上下方向键选中

**Comment by skytt** [comment]
这个交互 `0.49.4` 已经修改了，目前会通过 label 比对，创建选项在和已有选项相同时候隐藏显示
