### ISSUE TITLE
[TagInput] placeholder 显示不全

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1369]
### tdesign-vue 版本

0.46.2

### 重现链接

https://stackblitz.com/edit/angular-8gjxoa?file=src%2Fdemo.vue

### 重现步骤

对比t-input placeholder 有差异

**Comment by Tomaolala** [comment]
![image](https://user-images.githubusercontent.com/76248720/187389280-4d54c55b-2aaa-4a18-8209-44afdf5544ee.png),与input组件的text-overflow有关，是覆盖还是改动input的样式呢 @uyarn

**Comment by Tomaolala** [comment]
认领

**Comment by xiaosansiji** [comment]
> 认领

确认下何时提交 PR 哈

**Comment by Tomaolala** [comment]
> > 认领
> 
> 确认下何时提交 PR 哈

_common子模块的问题，等下我会在tdsign- common提一个pr

**Comment by xiaosansiji** [comment]
已在 0.47.0 修复
