### ISSUE TITLE
[Tree] checkable 模式下动态赋值data 没有勾选父级

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1370]
### tdesign-vue 版本

0.46.2

### 重现链接

https://stackblitz.com/edit/angular-zgaqco-18qa7c?file=src/demo.vue

### 重现步骤

重现链接 点击测试按钮 动态赋值 data  然后再赋值v-model   最上级理应要勾选上  check-strictly 为false 的情况下

**Comment by Jiachang-Cai** [comment]
还有 如何实现 动态展开与收缩
还有 如何实现 全选与全不选

**Comment by TabSpace** [comment]
示例代码错误。你配置属性：
check-strictly="false"
实际上是将字符串作为参数传递进去，转换为 Boolean 值时等价于 true 了。
正确的传值方式是:
:check-strictly="false"

**Comment by TabSpace** [comment]
示例`展开操作` 中有动画开关。
全选操作，目前没有直接提供 api, 可以用 setItem 方法操作所有根节点选中，也可以 value 属性传递所有节点 value 数组。
全不选，简单设置 value 为空数组即可。

**Comment by Jiachang-Cai** [comment]
> 示例代码错误。你配置属性： check-strictly="false" 实际上是将字符串作为参数传递进去，转换为 Boolean 值时等价于 true 了。 正确的传值方式是: :check-strictly="false"

哪怕正确方式也是有问题的 你自己测了没啊

**Comment by Jiachang-Cai** [comment]
> 示例`展开操作` 中有动画开关。 全选操作，目前没有直接提供 api, 可以用 setItem 方法操作所有根节点选中，也可以 value 属性传递所有节点 value 数组。 全不选，简单设置 value 为空数组即可。

你自己测下动态展开就知道 不会展开和收缩 没有测就下结论的嘛
