### ISSUE TITLE
[t-switch] 提供checked-value unchecked-value 支持

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1371]
### 这个功能解决了什么问题

赋值类型不局限于 boolean  也可以是数字和字符串

### 你建议的方案是什么

参考acro-design https://arco.design/vue/component/switch
<img width="997" alt="image" src="https://user-images.githubusercontent.com/8606851/186554553-16ba3187-3331-47e0-a6e0-dadf535b1690.png">

**Comment by chaishi** [comment]
请使用 `customValue` 自定义想要的任何数值，我们没有局限在你说的 boolean 类型。第一个 API 就是自定义 value
<img width="937" alt="image" src="https://user-images.githubusercontent.com/11605702/186824396-3884c17e-a7a4-4743-8c38-4c02b312668d.png">

**Comment by chaishi** [comment]
另外，辛苦仔细看文档，不同的 UI 库，API 风格不同。
TDesign 的 API 一般不会使用两个 API 定义同一种对象，都是一个数组 或者对象 整体定义。
因此，不会存在两个 `checked-value` `unchecked-value` ，只会存在一个 `customValue: ['open', 'close']`

**Comment by chaishi** [comment]
示例代码和演示效果如下：
https://stackblitz.com/edit/angular-deqmbu?file=src%2Fdemo.vue,src%2Findex.css

https://user-images.githubusercontent.com/11605702/186825847-1b6cfd84-7e24-45ce-ad77-f8aa2435004e.mov
