### ISSUE TITLE
[Table] 1.支持 columns.type = 'single' 时，自定义表头；2. 支持隐藏表头

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1372]
### 这个功能解决了什么问题

1. 目前 columns type: 'single' 不支持title 属性   title部分 空荡荡 业务上 不可做该列的提示
2. 能否支持不显示表头(columns) 只显示列部分(data) 有些时候做列表显示不需要表头又需要t-table的一些列的样式

### 你建议的方案是什么

希望都支持下。。。

**Comment by chaishi** [comment]
上述两个特性均已支持，待发布

<img width="474" alt="image" src="https://user-images.githubusercontent.com/11605702/192131673-7f79907d-8ce8-4a54-bc97-1dc47a81b60c.png">
<img width="689" alt="image" src="https://user-images.githubusercontent.com/11605702/192131718-6247379b-cba9-4633-a1d3-29e3a6d5d5c5.png">

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本实现
