### ISSUE TITLE
[Table] 给t-table列名设置className，如果type: "multiple"，则设置的类名不生效

### ISSUE THREAD

**Issue by lavender-juan** [Tencent/tdesign-vue#1377]
### tdesign-vue 版本

0.46.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-xsjvr8

### 重现步骤

1、给t-table复选框 列设置className没有生效

**Comment by RainyLiao** [comment]
认领

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
