### ISSUE TITLE
表格列在设置ellipsis之后，鼠标悬浮此时滚动，会带着提示一直移动

### ISSUE THREAD

**Issue by drugdl** [Tencent/tdesign-vue#138]
**Describe Framework**

tdesign-vue

**Describe Environment**

mac google
version ：96.0.4664.110（正式版本） (x86_64)

**Describe the bug**
Q：When the Table component sets the column property ellipsis, the scrolling Table cursor hover will always be present, even beyond the entire Table area
![image](https://user-images.githubusercontent.com/85599888/147728037-398ddf3d-750c-41c1-859f-b501d57de1d0.png)

**Additional context**
Set the columns of the table
![image](https://user-images.githubusercontent.com/85599888/147728119-ed52271a-6b53-475c-8886-a94395e2df62.png)

**Comment by chaishi** [comment]
辛苦给一个 code sandbox Demo @drugdl

**Comment by chaishi** [comment]
组件库版本号，以及示例代码

**Comment by drugdl** [comment]
抱歉环境没描述完整 ，版本 vue for web 0.32.0  我试了一下，官方示例中也有这个问题，直接用官方示例的sandbox，当给一列设置了 ellipsis，悬浮上去，此时滚动表格
![image](https://user-images.githubusercontent.com/85599888/147799684-a4ad9f57-9135-4f95-858b-e48a3abdfa4f.png)

**Comment by realyuyanan** [comment]
我看下。

**Comment by chaishi** [comment]
这个需求优待考究，Tips 如果不跟着一定移动的话，那滚动的时候，tips 指向哪一行不是就乱了么？

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365, to be published.

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验
