### ISSUE TITLE
[Tag] 希望可以自定义颜色

### ISSUE THREAD

**Issue by rjl-cli** [Tencent/tdesign-vue#1387]
### 这个功能解决了什么问题

很多场景下，哪几种肯定是不够的，可以参考下字节的效果支持传入颜色https://arco.design/vue/component/tag

### 你建议的方案是什么

新加color参数，  字体颜色是传入的color   背景色可以在传入的颜色加透明度

**Comment by chaishi** [comment]
Tag 真的是最简单的组件了，可以先自己写一个。

还有很多其他的组件功能更需要开发，优先级暂时不高，期待有兴趣的有缘人

**Comment by chaishi** [comment]
还有个办法，你可以按需引入 Arco 的 Tag 组件直接使用

**Comment by renjiali666** [comment]
> 

要是支持vue2我就用了

**Comment by renjiali666** [comment]
> Tag 真的是最简单的组件了，可以先自己写一个。
> 
> 还有很多其他的组件功能更需要开发，优先级暂时不高，期待有兴趣的有缘人

这个自己写，那个也是，那组件库意义何在？

**Comment by renjiali666** [comment]
> 还有个办法，你可以按需引入 Arco 的 Tag 组件直接使用

不是故意找事 京东的nutui，支付宝的ant ,字节的acro,饿了吗的elment都支持呀

**Comment by luwuer** [comment]
@renjiali666 自定义背景色确实是合理的功能，暂时先用样式覆盖或则自己实现，我可以为这个功能提供 PR 。不过你这里的描述_字体颜色是传入的color 背景色可以在传入的颜色加透明度_，这个字体颜色和背景色存在某种透明度绑定关系可能不太通用噢

**Comment by renjiali666** [comment]
> 

嗯嗯

**Comment by chaishi** [comment]
暂不支持
