### ISSUE TITLE
[select] 远程搜索会根据输入值过滤label自动筛选搜索结果

### ISSUE THREAD

**Issue by LuoCharlie** [Tencent/tdesign-vue#1390]
### tdesign-vue 版本

0.46.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-gu1ong?file=/src/demo.vue

### 重现步骤

远程搜索时输入某个字符串，options在search函数里被更新后，下拉框还会自动根据输入的字符串过滤opitons。

例如搜索1，在search函数中赋值options
`this.options = [ {value: 1, label: 'test'},`
但是在下拉选择框中会过滤这一条数据

### 期望结果

远程搜索不需要本地过滤，我传什么渲染什么

### 实际结果

会根据label再过滤一遍

### 框架版本

Vue2

**Comment by LuoCharlie** [comment]
您好，我是罗小莉，您的邮件我已收到，我会尽快查看并给您回复，谢谢。

**Comment by skytt** [comment]
筛选时候，列表带有过滤的效果是正常的预期，远程搜索也认为是筛选的一种场景
如果有特殊的搜索展示需求，可以通过 `filter` 参数传入自定义过滤方法来处理，issue 给的 demo 中的场景在回调中全部返回 `true` 即可
<img width="491" alt="image" src="https://user-images.githubusercontent.com/7420660/187123067-ae47f21c-3ddb-46eb-8d0c-c3389ff48921.png">
