### ISSUE TITLE
[Table] ellipsisTitle优先级低于ellipsis，与预期不符

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#1404]
### tdesign-vue 版本

0.46.2

### 重现步骤

<img width="829" alt="image" src="https://user-images.githubusercontent.com/11243798/187168025-7a78deb8-9672-46d8-a57e-771d1b693e54.png">

文档中描述 ellipsisTitle 优先级高于ellipsis (预期)，
而实际上当 ellipsis 为 false，ellipsisTitle 为 true 时并不能生效：

https://github.com/Tencent/tdesign-vue/blob/a6f5d353062880e43031f0fa8ba7163183fa2b16/src/table/hooks/useTableHeader.tsx#L62

**Comment by Tomaolala** [comment]
认领 @chaishi

**Comment by chaishi** [comment]
Vue2 已合并

issue 先别关，还有 Vue3 和 React，问题相同。需要有缘人处理

**Comment by yusongH** [comment]
如果 #1408 的处理是符合预期的，ellipsis的描述应该需要修改，ellipsis配置并不会控制表头的文字是否省略了。

例如：ellipsisTitle不配置，则为默认值undefined。ellipsis配置为true和false表头文字都是省略的

<img width="843" alt="image" src="https://user-images.githubusercontent.com/45997005/190859777-2c4f50ca-d338-4394-a29a-eff7d4e5ec4f.png">

但如果是按照当前ellipsis描述才是符合预期的，应该是判断ellipsisTitle是否配置了，没有配置则取ellipsis的值吧

```ts
const isEllipsis = (ellipsis: BaseTableCol['ellipsis'], ellipsisTitle: BaseTableCol['ellipsisTitle']) => {
  if (ellipsisTitle === undefined) {
    return ellipsis;
  }

  if (ellipsisTitle !== false && ellipsisTitle !== null) {
    return true;
  }

  return false;
};
```

**Comment by Tomaolala** [comment]
> 如果 #1408 的处理是符合预期的，ellipsis的描述应该需要修改，ellipsis配置并不会控制表头的文字是否省略了。
> 
> 例如：ellipsisTitle不配置，则为默认值undefined。ellipsis配置为true和false表头文字都是省略的
> 
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/45997005/190859777-2c4f50ca-d338-4394-a29a-eff7d4e5ec4f.png">
> 
> 但如果是按照当前ellipsis描述才是符合预期的，应该是判断ellipsisTitle是否配置了，没有配置则取ellipsis的值吧
> 
> ```ts
> const isEllipsis = (ellipsis: BaseTableCol['ellipsis'], ellipsisTitle: BaseTableCol['ellipsisTitle']) => {
>   if (ellipsisTitle === undefined) {
>     return ellipsis;
>   }
> 
>   if (ellipsisTitle !== false && ellipsisTitle !== null) {
>     return true;
>   }
> 
>   return false;
> };
> ```
![image](https://user-images.githubusercontent.com/76248720/190911328-0e247d67-0dd6-4167-8edb-b9191a6531f3.png)



> 如果 #1408 的处理是符合预期的，ellipsis的描述应该需要修改，ellipsis配置并不会控制表头的文字是否省略了。
> 
> 例如：ellipsisTitle不配置，则为默认值undefined。ellipsis配置为true和false表头文字都是省略的
> 
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/45997005/190859777-2c4f50ca-d338-4394-a29a-eff7d4e5ec4f.png">
> 
> 但如果是按照当前ellipsis描述才是符合预期的，应该是判断ellipsisTitle是否配置了，没有配置则取ellipsis的值吧
> 
> ```ts
> const isEllipsis = (ellipsis: BaseTableCol['ellipsis'], ellipsisTitle: BaseTableCol['ellipsisTitle']) => {
>   if (ellipsisTitle === undefined) {
>     return ellipsis;
>   }
> 
>   if (ellipsisTitle !== false && ellipsisTitle !== null) {
>     return true;
>   }
> 
>   return false;
> };
> ```
ellipsis配置会影响表头，走的是第一个逻辑

**Comment by yusongH** [comment]
> > 如果 #1408 的处理是符合预期的，ellipsis的描述应该需要修改，ellipsis配置并不会控制表头的文字是否省略了。
> > 例如：ellipsisTitle不配置，则为默认值undefined。ellipsis配置为true和false表头文字都是省略的
> > <img alt="image" width="843" src="https://user-images.githubusercontent.com/45997005/190859777-2c4f50ca-d338-4394-a29a-eff7d4e5ec4f.png">
> > 但如果是按照当前ellipsis描述才是符合预期的，应该是判断ellipsisTitle是否配置了，没有配置则取ellipsis的值吧
> > ```ts
> > const isEllipsis = (ellipsis: BaseTableCol['ellipsis'], ellipsisTitle: BaseTableCol['ellipsisTitle']) => {
> >   if (ellipsisTitle === undefined) {
> >     return ellipsis;
> >   }
> > 
> >   if (ellipsisTitle !== false && ellipsisTitle !== null) {
> >     return true;
> >   }
> > 
> >   return false;
> > };
> > ```
> 
> ![image](https://user-images.githubusercontent.com/76248720/190911328-0e247d67-0dd6-4167-8edb-b9191a6531f3.png)
> 
> > 如果 #1408 的处理是符合预期的，ellipsis的描述应该需要修改，ellipsis配置并不会控制表头的文字是否省略了。
> > 例如：ellipsisTitle不配置，则为默认值undefined。ellipsis配置为true和false表头文字都是省略的
> > <img alt="image" width="843" src="https://user-images.githubusercontent.com/45997005/190859777-2c4f50ca-d338-4394-a29a-eff7d4e5ec4f.png">
> > 但如果是按照当前ellipsis描述才是符合预期的，应该是判断ellipsisTitle是否配置了，没有配置则取ellipsis的值吧
> > ```ts
> > const isEllipsis = (ellipsis: BaseTableCol['ellipsis'], ellipsisTitle: BaseTableCol['ellipsisTitle']) => {
> >   if (ellipsisTitle === undefined) {
> >     return ellipsis;
> >   }
> > 
> >   if (ellipsisTitle !== false && ellipsisTitle !== null) {
> >     return true;
> >   }
> > 
> >   return false;
> > };
> > ```
> 
> ellipsis配置会影响表头，走的是第一个逻辑

但是目前的现象是，ellipsis设置为false。表头还是会省略哦

<img width="2021" alt="image" src="https://user-images.githubusercontent.com/45997005/190911873-174aa9cc-ab70-4fca-b994-24436861752a.png">

**Comment by Tomaolala** [comment]
https://github.com/Tencent/tdesign-vue/pull/1560

**Comment by chaishi** [comment]
预期是：`ellipsis` 默认控制单元格和表头，如果希望单独控制表头请使用 `ellipsisTitle`

**Comment by chaishi** [comment]
设置 
```js
ellipsis: false,
ellipsisTitle: true,
```

效果如下图所示，也是符合预期的。不明白标题为什么说 ellipsisTitle 优先级低于 ellipsis，我这边看上去都是正常的

<img width="695" alt="image" src="https://user-images.githubusercontent.com/11605702/192132060-7ef574c1-e848-4d86-9989-4763df83c280.png">

**Comment by Tomaolala** [comment]
> 设置
> 
> ```js
> ellipsis: false,
> ellipsisTitle: true,
> ```
> 
> 效果如下图所示，也是符合预期的。不明白标题为什么说 ellipsisTitle 优先级低于 ellipsis，我这边看上去都是正常的
> 
> <img alt="image" width="695" src="https://user-images.githubusercontent.com/11605702/192132060-7ef574c1-e848-4d86-9989-4763df83c280.png">

当ellipsisTitle默认为undefined 时会省略，ellipsis控制不了

**Comment by chaishi** [comment]
> ellipsis设置为false。表头还是会省略哦
需继续修复

**Comment by Tomaolala** [comment]
> 

已经提了pr了，粗心了

**Comment by chaishi** [comment]
new change [see here](https://github.com/chaishi/tdesign-vue/commit/7ff9aaa8fe89fa8f2746b73907eec78f2a3df836)

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本修复
