### ISSUE TITLE
[Input/Textarea] emoji length 计算问题

### ISSUE THREAD

**Issue by HelKyle** [Tencent/tdesign-vue#1410]
### tdesign-vue 版本

0.46.2

### 重现链接

https://tdesign.tencent.com/vue/components/input

### 重现步骤

进入 Input/Textarea 组件页面，选择带长度限制的输入框，输入 🎨🎨🎨

### 期望结果

能正常输入三个字符，长度展示为 3

### 实际结果

只能输入两个字符，长度展示为 4

### 补充说明

关联 tdesign-react 的 issue https://github.com/Tencent/tdesign-react/issues/1327

**Comment by HelKyle** [comment]
pr: https://github.com/Tencent/tdesign-vue/pull/1411/files

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
