### ISSUE TITLE
[Swiper] 组件功能失效

### ISSUE THREAD

**Issue by LuoCharlie** [Tencent/tdesign-vue#1412]
### tdesign-vue 版本

0.46.2

### 重现步骤

官网组件的代码都无法实现

**Comment by LuoCharlie** [comment]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/60652443/187344472-e4fd504b-aa91-4754-b83c-a8d4eb40042e.png">

**Comment by xiaosansiji** [comment]
> <img alt="image" width="1271" src="https://user-images.githubusercontent.com/60652443/187344472-e4fd504b-aa91-4754-b83c-a8d4eb40042e.png">

可以直接把 demo 的链接贴一下不

**Comment by LuoCharlie** [comment]
您好，我是罗小莉，您的邮件我已收到，我会尽快查看并给您回复，谢谢。

**Comment by LuoCharlie** [comment]
您好，我是罗小莉，您的邮件我已收到，我会尽快查看并给您回复，谢谢。

**Comment by Realybig** [comment]
两年了，还没有好...

**Comment by LuoCharlie** [comment]
您好，我是罗小莉，您的邮件我已收到，我会尽快查看并给您回复，谢谢。
