### ISSUE TITLE
[TSelect] 同时enable创建和过滤时，过滤功能不工作。

### ISSUE THREAD

**Issue by foreverCP3** [Tencent/tdesign-vue#1414]
### tdesign-vue 版本

0.46.1

### 重现链接

https://0_46_1-tdesign-vue.surge.sh/vue/components/select#%E5%8F%AF%E5%88%9B%E5%BB%BA%E6%96%B0%E6%9D%A1%E7%9B%AE%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

官方文档中的示例即可复现此问题，请打开复现链接。

<img width="976" alt="image" src="https://user-images.githubusercontent.com/77433045/187363766-7caf6906-affb-4985-8d24-3749dbc53cf1.png">

### 期望结果

支持创建option的同时可使用过滤功能。

### 实际结果

支持创建option时过滤功能不可用。

### 框架版本

Vue(2.6.12)

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
