### ISSUE TITLE
[Dialog] 使用插件函数式调用Dialog show时丢失淡入动画

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#1417]
### tdesign-vue 版本

0.46.2

### 重现步骤

使用 `DialogInstance.show()` 函数式展示 Dialog 时，弹窗是直接展示，没有淡入动画

### 期望结果

使用 `<Dialog>` 组件，用visible控制展示。有淡入动画，是**期望结果**：

https://user-images.githubusercontent.com/11243798/187374243-119e0c9e-a304-44a6-8362-6a854ff5fc8c.mp4

### 实际结果

使用 `DialogInstance.show()` 函数式展示 Dialog，没有淡入动画，是直接出现的，**非期望**：

https://user-images.githubusercontent.com/11243798/187373928-18ac5487-7402-4cce-b789-81a9d71f3d0f.mp4

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
