### ISSUE TITLE
📌 组件测试覆盖率提升

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-vue#1418]
## 说明
本仓库中组件代码有很多与 vue next 仓库公用，大部分测试用例代码也能复用，区别在于 vue next 已经改用 Vitest 编写用例，本仓库因为 [@vitejs/plugin-vue2](https://github.com/vitejs/vite-plugin-vue2) 只兼容到 vue 2.7.x 版本，还在使用 Jest 写用例。
因此建议认领的同学同时负责 vue2 与 vue next 两个仓库中对应组件的测试用例编写任务，如果你更熟悉 Jest 可以参照 [官方迁移指南](https://cn.vitest.dev/guide/migration.html) 来学习如何使用 Vitest。
1. 遵循 [TDesign 单元测试规范](https://github.com/Tencent/tdesign-vue/blob/develop/TEST_GUIDE.md) 进行单测开发
2. 参与贡献请在此 `issue` 中评论领取的组件，建议也在 vue next 仓库对应 [issue](https://github.com/Tencent/tdesign-vue-next/issues/768) 中评论，防止其他同学重复投入
3. 提交 PR 前请先本地确认该组件行、函数覆盖率达80%+

## 组件
* [x] `button` @chaishi https://github.com/Tencent/tdesign-vue/pull/1977
* [x] `link` @chaishi  https://github.com/Tencent/tdesign-vue/pull/1983

### 布局

* [x] `grid`
* [x] `layout` 
* [x] `divider` @chaishi https://github.com/Tencent/tdesign-vue/pull/1983
* [x] `space` @chaishi https://github.com/Tencent/tdesign-vue/pull/2026

###  导航

* [x] `affix`
* [x] `anchor` 
* [x] `breadcrumb`
* [x] `dropdown` @james-curtis https://github.com/Tencent/tdesign-vue/pull/1516
* [x]  `jumper` @HelKyle https://github.com/Tencent/tdesign-vue/pull/1511 -> rename as paginationMini
* [ ]  `menu`
* [x] `pagination` @HelKyle https://github.com/Tencent/tdesign-vue/pull/1522
* [x] `steps`
* [x] `timeline` @chaishi https://github.com/Tencent/tdesign-vue/pull/2138
* [ ] `tabs`
 

### 输入

* [x] `auto-complete` @chaishi  https://github.com/Tencent/tdesign-vue/pull/1983
* [ ] `cascader `
* [x] `checkbox`
* [ ] `color-picker`
* [x] `date-picker` 
* [ ] `form` 
* [x] `input`@chaishi https://github.com/Tencent/tdesign-vue/pull/2041
* [x]  `input-adornment`
* [x] `input-number`
* [x] `radio` @chaishi  https://github.com/Tencent/tdesign-vue/pull/2010
* [ ] `select`
* [x] `select-input` @chaishi https://github.com/Tencent/tdesign-vue/pull/2096
* [ ] `slider`
* [ ] `switch`
* [x] `tag-input` @chaishi https://github.com/Tencent/tdesign-vue/pull/2096
* [x] `textarea`
* [x] `transfer` 
* [x] `time-picker` @uyarn https://github.com/Tencent/tdesign-vue/pull/1756
* [x] `tree-select` @chaishi https://github.com/Tencent/tdesign-vue/pull/2096
* [x] `upload` @chaishi https://github.com/Tencent/tdesign-vue/pull/2058

### 数据展示

* [x]  `avatar`  https://github.com/Tencent/tdesign-vue/pull/2032
* [x]  `badge`
* [x] `calendar` 
* [x] `card` 
* [x] `collapse `@isanxia https://github.com/Tencent/tdesign-vue/pull/1536
* [x] `comment` 
* [x] `image` @chaishi https://github.com/Tencent/tdesign-vue/pull/2043
* [ ] `image-viewer`
* [x] `list` 
* [x] `loading` @uyarn  
* [x] `progress` 
* [x] `skeleton` 
* [ ] `swiper` 
* [ ] `table`  @chaishi https://github.com/Tencent/tdesign-vue/pull/2068
* [x] `tag`  @chaishi https://github.com/Tencent/tdesign-vue/pull/2096
* [ ] `tooltip`
* [ ] `tree`
* [ ] `rate`
* [ ] `watermark`

### 消息提醒

* [x] `alert`
* [ ] `dialog`
* [ ] `drawer`
* [x] `guide` @chaishi  https://github.com/Tencent/tdesign-vue/pull/2170
* [x] `message`
* [ ] `notification` 
* [x] `popconfirm`
* [x] `popup` 

### common

[tdesign-common](https://github.com/Tencent/tdesign-common/tree/develop/js) 仓库下还有部分共享的组件代码，主要是 hooks 或 utils 方法，编写用例时也请附带完善这些代码的测试用例

**Comment by HelKyle** [comment]
认领 jumper

**Comment by jiazengp** [comment]
认领 `notification`

**Comment by james-curtis** [comment]
认领 dropdown

**Comment by sechi747** [comment]
认领 `swtich`

**Comment by xiaosansiji** [comment]
> 看到[vue-next仓库](https://github.com/Tencent/tdesign-vue-next/issues/768#issuecomment-1238079521)有人领取 switch 组件了，不知道是否已经完成了？

没提交 PR，你可以看看一并搞了

**Comment by HelKyle** [comment]
认领 pagination

**Comment by isanxia** [comment]
认领collapse

**Comment by Dlame** [comment]
认领notification

**Comment by byq1213** [comment]
认领 Message, Tooltip, Popup
