### ISSUE TITLE
Document Menu highlight bug

### ISSUE THREAD

**Issue by liliukuan** [Tencent/tdesign-vue#142]
**Describe Framework**

**Describe Environment**
https://tdesign.tencent.com/vue/components/breadcrumb
Add browser version here
0.32.0
**Describe the bug**
when i clicked the "breadcrumb's page" at 
![image](https://user-images.githubusercontent.com/28745463/147739548-3a5b52d1-aa8a-4b00-b727-2fe75689cd33.png)
,menu's activing class has  no change,it should be on Menu
![image](https://user-images.githubusercontent.com/28745463/147739811-d68d1e50-f080-4bd7-93e4-0f70416ab4dc.png)

tdesign-vue

**Additional context**

**Comment by chaishi** [comment]
Menu 没有相关导航没有高亮，@leejimqiu 跟进中

**Comment by LeeJim** [comment]
这个不是 Menu 组件，属于 WebComponents 的组件， @HQ-Lin

**Comment by HQ-Lin** [comment]
This scene is a little difficult to reproduce, can you provide more information about the scene replay?
such as what was done before, or open the console to see if there are any errors, otherwise it's a little hard for me to figure out.

**Comment by chaishi** [comment]
@HQ-Lin  这个问题不复杂，就是官网的图中的面包屑示例，点击一下，跳转到了 Menu 组件页面，但是官网 Menu 的导航没有高亮。期望应该是高亮的

**Comment by HQ-Lin** [comment]
> @HQ-Lin 这个问题不复杂，就是官网的图中的面包屑示例，点击一下，跳转到了 Menu 组件页面，但是官网 Menu 的导航没有高亮。期望应该是高亮的

我理解错了，我以为是点击左侧的menu 后没有高亮，webcomponents 里面的逻辑问题，这两天处理下
