### ISSUE TITLE
[Cascader] 点击placeholder时弹窗闪动，点击其他位置时弹窗正常出现

### ISSUE THREAD

**Issue by windyboyy** [Tencent/tdesign-vue#1426]
### tdesign 版本

^0.40.3

### 重现步骤

我把Cascader包装成一个子组件，然后在父组件里调用时就会出现这样的问题

**Comment by xiaosansiji** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-dmbgfb?file=/src/targetSelect.vue 
新版本里已修复，可以升级组件库版本后体验
