### ISSUE TITLE
[Select 选择器] 过滤掉数据后，上下快捷键仍可以选择过滤外的数据

### ISSUE THREAD

**Issue by celizi** [Tencent/tdesign-vue#1433]
### tdesign-vue 版本

0.46.2

### 重现链接

https://tdesign.tencent.com/vue/components/select?tab=demo#%E5%88%86%E7%BB%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

数据过滤筛选后，使用上下快捷键可以选择其他的

### 期望结果

可见才可以选择

### 实际结果

过滤掉，隐藏的也可以选择

**Comment by celizi** [comment]
过滤后，鼠标点击change选中的结果：是未过滤数据的下标对应的元素，导致选中与实际预期不符。

**Comment by celizi** [comment]
![select过滤](https://user-images.githubusercontent.com/27724598/188073954-67541d20-c830-4348-972e-df394f892e64.gif)

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
