### ISSUE TITLE
[Table] [Affix]获取数据时，分页吸底没有根据新数据调整位置

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1437]
### tdesign-vue 版本

0.46.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-y5oh1y?file=/src/demo.vue

### 重现步骤

如示例：
1.   当table有10条数据处于分页吸底状态时，换页获取1条数据，此时分页没有自动上移到表格末尾，需要滚动一下才会移动到表格末尾。
2.   初始化获取的数据后，没有横向滚动条，必须要滚动到底部出现滚动条后，滚动条才能吸底。

https://user-images.githubusercontent.com/13745660/187846382-f1f75344-22fb-4fd0-9638-fafc6a025a23.mov

### 期望结果

期望获取数据时，可以自动调整分页吸底状态；
初始化获取数据后，横向滚动条可以出现。

### 实际结果

目前需要滚动一下才会移动到表格末尾。
初始化获取数据后，没有出现横向滚动条。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

windows

### Node版本

12.22.0

**Comment by xiaosansiji** [comment]
已在 0.48.0 修复
