### ISSUE TITLE
[Upload] multiple draggable 属性 使用问题

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1449]
### tdesign-vue 版本

0.46.3

### 重现链接

https://stackblitz.com/edit/angular-zfqjj4-mb93va?file=src/demo.vue

### 重现步骤

看代码示例备注
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/8606851/188061399-af0841e2-c280-4ecb-ae04-941a38128fa5.png">

### 期望结果

multiple draggable 等属性能组合到 任何上传样式上面

### 实际结果

不能兼容

**Comment by uyarn** [comment]
@Wen1kang 看看 设计稿目前对多文件和单文件的样式做了区分

**Comment by chaishi** [comment]
`multiple` 这个基础样式的多文件，React 已经实现了，Vue 会跟上

至于拖拽，需要再斟酌

**Comment by chaishi** [comment]
经过功能整理，支持以下 9 种场景。（multiple 和 draggable 并非所有场景都适用，交互差异很大）
<img width="908" alt="image" src="https://user-images.githubusercontent.com/11605702/195972346-f14388b4-801a-4a1f-b55d-7c1cf7efc558.png">
