### ISSUE TITLE
[TreeSelect] 如果 data 为空 v-model 赋值 如果为数字 会报错

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1450]
### tdesign-vue 版本

0.46.3

### 重现链接

https://stackblitz.com/edit/angular-nprddl?file=src/demo.vue

### 重现步骤

如果:data 为空 点击按钮再次赋值会报错
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/8606851/188081829-b42b606d-561e-4a02-bdaf-f50748fe9ffe.png">

存在 :data 为动态加载的数据 v-model 赋值早于 :data 赋值 如果值为number 就会报错

### 期望结果

不要报出错误

### 实际结果

值为 number 会报出错误

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
