### ISSUE TITLE
[DateRangePicker] 如果赋值格式不符合 会报错 且点击组件 页面直接奔溃

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1451]
### tdesign-vue 版本

0.46.3

### 重现链接

https://stackblitz.com/edit/angular-tmf6ug?file=src/demo.vue

### 重现步骤

可能存在 业务数据为Null 或空的情况
格式错误赋值会报错
![Uploading image.png…]()
会报错 的情况下 点击组件 页面直接奔溃 卡死

### 期望结果

报错不影响组件使用 以及不要导致整个页面奔溃

### 实际结果

报错后点击 导致整个页面奔溃

**Comment by Jiachang-Cai** [comment]
报错可以理解 但是 页面奔溃不理解

**Comment by HQ-Lin** [comment]
组件内部需要对数据格式化处理，dayjs并不支持空字符串的格式化，后续很多逻辑都依赖正确的时间格式做计算
我先兼容下空字符串卡死问题吧，但这种情况直接设置空数组就可以了，不明白为何还要穿空字符串

**Comment by Jiachang-Cai** [comment]
> 组件内部需要对数据格式化处理，dayjs并不支持空字符串的格式化，后续很多逻辑都依赖正确的时间格式做计算 我先兼容下空字符串卡死问题吧，但这种情况直接设置空数组就可以了，不明白为何还要穿空字符串

你要解决的是 不符合 格式的参数 直接重置为 空数组

**Comment by Jiachang-Cai** [comment]
没有解决就关闭吗

**Comment by xiaosansiji** [comment]
> 没有解决就关闭吗

对应 PR 里有写 fix #xx  就会被 GitHub 自动关闭，见：https://github.com/Tencent/tdesign-vue/pull/1453

PR 合并后我们会把 issue label 置为 `to be published`，每周的迭代版本发布后在 issue 里评论提示升级到哪个版本解决

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
