### ISSUE TITLE
[table] 分页器吸底 在 windows的firefox下样式异常

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1452]
### tdesign-vue 版本

0.46.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-kne2mo?file=/src/demo.vue

### 重现步骤

当配置了横向滚动条吸底和分页器吸底时，windows下firefox
小屏幕上存在滚动条时，展示正常。

<img width="580" alt="image" src="https://user-images.githubusercontent.com/13745660/188089260-76a59825-5cf1-48fe-86ae-e6757bc87400.png">

大屏幕上不存在滚动条时，展示异常

<img width="782" alt="image" src="https://user-images.githubusercontent.com/13745660/188090090-df780966-49ff-4015-a97f-fe561ba4da0f.png">

### 期望结果

分页器不会被遮挡

### 框架版本

Vue(2.6.0)

### 浏览器版本

firefox(104.0.1)

### 系统版本

windows

### Node版本

12.22.0

**Comment by jiazengp** [comment]
认领 @xiaosansiji

**Comment by chaishi** [comment]
@jiazengp 有进展吗

**Comment by xiaosansiji** [comment]
已在 0.49.0 版本修复
