### ISSUE TITLE
[TreeSelect] disabled 作用在父节点 子节点需要可操作

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1458]
### tdesign-vue 版本

0.46.2

### 重现链接

https://stackblitz.com/edit/angular-yx6phg-5kfa9a?file=src/demo.vue

### 重现步骤

1. 官网没有 disabled 示例 
2. disabled 不可选整个节点 不适合 在 tree 的业务逻辑上   disabled 父节点 父节点不可选 但是其子节点需要可选  目前是 disabled 父节点 整个父节点不可展开

### 期望结果

disabled  父节点 子节点可展开 以及选择

### 实际结果

disabled 父节点 整个父节点不可展开 子节点无法选择

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
