### ISSUE TITLE
[SelectInput] 筛选器输入框删除问题

### ISSUE THREAD

**Issue by Yolo9876** [Tencent/tdesign-vue#1464]
### tdesign-vue 版本

0.46.3

### 重现步骤

选择一项后，光标定位在输入框的内容中间，然后光标置于最后，此时【SelectInput】无法删除
<img width="723" alt="image" src="https://user-images.githubusercontent.com/17537393/188366680-5a07ed39-c95e-4701-9783-323d36b6010c.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/17537393/188366734-e84925e1-bef2-4372-b25a-cf6e0fb4881e.png">

**Comment by chaishi** [comment]
如果你想要的是下拉选择，请更为使用 `Select`，不建议使用 `SelectInput`。

再说，SelectInput 是一个包含 输入框(Input) 和 浮层(Popup) 的基础组件，用来自定义实现复杂的筛选过滤组件的。比如组件库内部的 Select/Cascader/TreeSelect/DatePicker/TimePicker/ 等组件都是基于 SelectInput 实现。如果你只是想要个下拉选择，清实用 `Select`。

最后，如果你是真的想要自定义复杂的筛选器，这个组件的输入框内容是可以完全由父组件决定的，也就是示例代码，或者你的业务代码。你现在看到的 `SelectInput` 只是一个简单的示例而已

**Comment by chaishi** [comment]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/11605702/188367579-4e2f45b3-e3d8-4586-bed3-1f9355b7a735.png">
