### ISSUE TITLE
[table] props形式传递的 onPageChange 参数在分页时会触发两次

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#1465]
### tdesign-vue 版本

0.46.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-ng0ww9?file=/src/demo.vue

### 重现步骤

操作分页，会执行两次分页回调函数

### 期望结果

分页只执行一次回调函数

**Comment by xiaosansiji** [comment]
已在 0.48.0 修复
