### ISSUE TITLE
[Watermark] 水印组件无法动态响应内容变化

### ISSUE THREAD

**Issue by pecliu** [Tencent/tdesign-vue#1472]
无法响应内容后期的动态变化。vue2版本0.46.3。

初始化[{text: '敏感信息'}]

后期push了一行新数据 [{text: '敏感信息'}, {text: '用户名'}]

水印组件依然只显示初始化的内容

**Comment by uyarn** [comment]
assign to @samhou1988

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
