### ISSUE TITLE
[table] 表格列配置 onColumnChange onColumnControllerVisibleChange属性返回值有误

### ISSUE THREAD

**Issue by yz155** [Tencent/tdesign-vue#1479]
### tdesign-vue 版本

0.46.3

### 重现步骤

<img width="728" alt="image" src="https://user-images.githubusercontent.com/34710340/188783105-b58ba31e-6269-4e9b-ae6b-27f540209199.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/34710340/188783401-691ee8cf-5251-490e-9e13-329f58b298df.png">
<img width="883" alt="image" src="https://user-images.githubusercontent.com/34710340/188783615-33f670bb-1a52-4dc2-a426-ceb5347a4649.png">

onColumnChange属性在我取消勾选或勾选列配置弹窗的字段后不会触发；
onColumnControllerVisibleChange会触发，但是取消按钮trigger返回confirm,确认按钮返回cancel

**Comment by sechi747** [comment]
可以给个复现地址吗？我这边用官网的demo可以触发 `onColumnChange`

**Comment by yz155** [comment]
> 可以给个复现地址吗？我这边用官网的demo可以触发 `onColumnChange`

不好意思，我又试了一下**onColumnChange**是我写的问题。您看一下**onColumnControllerVisibleChange**这个是否存在返回trigger有误的问题。

**Comment by sechi747** [comment]
> > 可以给个复现地址吗？我这边用官网的demo可以触发 `onColumnChange`
> 
> 不好意思，我又试了一下**onColumnChange**是我写的问题。您看一下**onColumnControllerVisibleChange**这个是否存在返回trigger有误的问题。

已经提交pr了

**Comment by xiaosansiji** [comment]
已在 0.46.4 版本修复
