### ISSUE TITLE
[Steps] 带图标的步骤条图标大小不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-vue#1486]
### tdesign-vue 版本

0.46.3

### 期望结果

应该是24px才对

<img width="725" alt="image" src="https://user-images.githubusercontent.com/89069385/188872928-c959ca34-b273-459c-a105-a6084a1fdbb1.png">

### 实际结果

现在却是35px

<img width="675" alt="image" src="https://user-images.githubusercontent.com/89069385/188872993-51be5c34-c13f-4f87-810d-a88b725299a0.png">

### 框架版本

0.46.3

**Comment by Tomaolala** [comment]
![image](https://user-images.githubusercontent.com/76248720/188888496-2c831709-68c7-4313-803e-4e75efdbf1c6.png)
使用默认@steps-item-t-icon-font-size-default即可，我等下在_common 提一个pr

**Comment by Wen1kang** [comment]
@Tomaolala 提问为啥会有个font- size为35的token的，按道理这个不符合规范也

**Comment by Wen1kang** [comment]
@xiaosansiji 麻烦哲哥有空看看哦～

**Comment by Micro-sun** [comment]
认领。

**Comment by uyarn** [comment]
fixed 0.48.3
