### ISSUE TITLE
[Tabs] 选中横线样式不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-vue#1487]
### tdesign-vue 版本

0.46.3

### 期望结果

上下布局选中横线height=3px；左右布局选中横线width=3px
上下布局增加圆角为2px；左右布局增加圆角2px

<img width="567" alt="image" src="https://user-images.githubusercontent.com/89069385/188884833-3769d300-5af0-43bc-9471-99d86d01dff4.png">

### 实际结果

对比设计稿样式不对

<img width="665" alt="image" src="https://user-images.githubusercontent.com/89069385/188884931-962e8ec3-c079-42c2-ae6c-39f3a32c8c7a.png">

### 框架版本

0.46.3

**Comment by jiazengp** [comment]
认领 @uyarn

**Comment by james-curtis** [comment]
认领 @xiaosansiji
