### ISSUE TITLE
[Cascader] 分割线样式不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-vue#1488]
### tdesign-vue 版本

0.46.3

### 期望结果

没有圆角，应该使用的是1px @component-stroke 的分割线

<img width="701" alt="image" src="https://user-images.githubusercontent.com/89069385/188888201-9eac4f91-947f-4ba1-9c0c-bb49231a683d.png">

### 实际结果

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/89069385/188887820-46b735e1-f580-4b06-ac63-12445496e15e.png">

### 框架版本

0.46.3

**Comment by jiazengp** [comment]
认领 @uyarn

**Comment by jiazengp** [comment]
此问题貌似已经在<https://github.com/Tencent/tdesign-common/compare/8e25593811a4c3265aeda7fa4e54801e5ba4311b...9ee48f5ddf0f51b880cdee059a054b621147577f> 中修复了 @uyarn

**Comment by xiaosansiji** [comment]
已在 0.48.0 修复
