### ISSUE TITLE
输入框提示颜色不对，且和其他输入组件提示样式不一致

### ISSUE THREAD

**Issue by daizhan** [Tencent/tdesign-vue#1492]
例如input和 textarea, 普通的文本提示通常都应该是浅灰色的，但是input 却是黑色的，不太合理。
![image](https://user-images.githubusercontent.com/5318547/189254412-a2935e5f-69f8-4cfb-99a3-d97e998c6c1c.png)
![image](https://user-images.githubusercontent.com/5318547/189254444-8205779b-e53c-4795-a3e6-9887e253f295.png)

**Comment by xiaosansiji** [comment]
是 Input 实现的有问题，应该是浅色的，下个版本会带上去可以留意下 Changelog

**Comment by xiaosansiji** [comment]
已在 0.48.0 修复
