### ISSUE TITLE
[Dialog] 模态与非模态类对话框，建议支持限定表头拖拽及模态时点击背景能显式提醒当前打开了对话框

### ISSUE THREAD

**Issue by chzhujian** [Tencent/tdesign-vue#1504]
### 这个功能解决了什么问题

1、当前拖拽是在对话框上整体都可以的，建议增加支持title上才能拖拽。
场景：1、当前的文字编辑框，在拖拽时，没办法通过鼠标划取一段文字编辑，只能鼠标双击选中后删除再编辑。对于较多文字，这个太痛苦了。2、在标题上拖拽，也符合我们平时的操作习惯，大部分网页的对话框是这样的。

2、显示模态对话框时，建议当点击网页时，模态对话框能显式突出（比如微微动一下，或者边框高亮一下，能看到有个对话框没关闭）
场景：1、当前咱们是按照主题的。一般模态对话框和背景上样式我们都会相同主题，但是如果操作时出现了模态对话框而又想去点网页上的其他地方时，操作不了，**一时又看不出怎么回事，需要看到有个背景很相似的模态**对话框开着，要去关闭才行。2、还是习惯问题，常见模态带显式提醒更容易让我们感觉舒服。

### 你建议的方案是什么

建议都已经写在上面了。
1、拖拽的建议增加一个配置，能指定到title了。也不必改掉原来的方式。
2、建议直接增加凸显就可以了。如果有的选择，可以指定凸显方式当然更好。
感谢！

**Comment by ccccpj** [comment]
问题1：在 https://github.com/Tencent/tdesign-vue/pull/1352 中已优化。

**Comment by ccccpj** [comment]
问题2：比较定制化的需求还是需要自己实现一下比较好哦～
