### ISSUE TITLE
[Upload] beforeUpload与sizeLimit无法同时生效

### ISSUE THREAD

**Issue by pecliu** [Tencent/tdesign-vue#1506]
### tdesign-vue 版本

0.47.0

### 重现步骤

设置了:beforeUpload
同时设置:sizeLimit

### 期望结果

判断玩beforeUpload逻辑通过后，也能判断sizeLimit的限制

### 实际结果

设置了1M的sizeLimit，但是无效

**Comment by uyarn** [comment]
fixed in 0.48.3
