### ISSUE TITLE
[Message] zIndex配置不生效

### ISSUE THREAD

**Issue by pecliu** [Tencent/tdesign-vue#1507]
### tdesign-vue 版本

0.47.0

### 重现步骤

```
this.$message.error({
          content: '超过平均每个页面3M图片的限制,上传失败. 请优化活动使用的图片大小',
          placement: 'center',
          zIndex: 20000,
          duration: 0,
        });
```

### 期望结果

z-index设置为20000

### 实际结果

z-index依然为默认的5000

**Comment by uyarn** [comment]
codesandbox没有复现 暂时不知道出现原因

**Comment by pecliu** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-j4c3xb?file=/src/demo.vue

首次进入是符合设置的值的。但是页面不关闭，直接修改代码，重新编译出来的ZIndex就还是首次编译的值。

同时如果刷新整体页面，zIndex又会更新成最新的

本地开发也是一样的表现，无法更新成新的

**Comment by xixileng** [comment]
> https://codesandbox.io/s/tdesign-vue-demo-forked-j4c3xb?file=/src/demo.vue
> 
> 首次进入是符合设置的值的。但是页面不关闭，直接修改代码，重新编译出来的ZIndex就还是首次编译的值。
> 
> 同时如果刷新整体页面，zIndex又会更新成最新的
> 
> 本地开发也是一样的表现，无法更新成新的

热更新的问题，codesanbox 编辑完保存一下重新编译就正常了。不是组件的 bug 哈
