### ISSUE TITLE
[DatePcker] 日期区间选择不符合操作逻辑

### ISSUE THREAD

**Issue by shikaiguo** [Tencent/tdesign-vue#1518]
### tdesign-vue 版本

0.47.0

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker#%E6%97%A5%E6%9C%9F%E5%8C%BA%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

1. 设置一次日期区间√ 
![image](https://user-images.githubusercontent.com/5564630/190549402-71f6eb38-84ad-48d4-a434-682440625ab0.png)
2. 点击左侧重新选择一个靠后的日期√
![image](https://user-images.githubusercontent.com/5564630/190549521-051ce255-21c2-478f-b340-54471e7935bc.png)
3. 选择一个更靠后的日期×
![image](https://user-images.githubusercontent.com/5564630/190549574-0abe6617-2581-445f-bbfd-d78444b5f0ae.png)
起始日期未变化，两次都更新了结束日期

2 3步骤改成点击右侧选择靠前一样有这个问题

### 期望结果

1. `2022-09-16 - 2022-09-18`
2. `2022-09-16 - 2022-09-22`
3. `2022-09-22 - 2022-09-25`

### 实际结果

1. `2022-09-16 - 2022-09-18`
2. `2022-09-16 - 2022-09-22`
3. `2022-09-16 - 2022-09-25`

**Comment by HQ-Lin** [comment]
当你左侧时间比右侧大的时候会帮你调换位置，因为组件要保持左侧时间一定比右侧小，这里会让你困惑的应该是调换了顺序后光标又从左侧变到右侧导致了你想修改开始时间还得点回第一个输入框吧？
下版本我改成二次修改不符合规范的直接清空另一侧数据吧

**Comment by shikaiguo** [comment]
> 当你左侧时间比右侧大的时候会帮你调换位置，因为组件要保持左侧时间一定比右侧小，这里会让你困惑的应该是调换了顺序后光标又从左侧变到右侧导致了你想修改开始时间还得点回第一个输入框吧？ 下版本我改成二次修改不符合规范的直接清空另一侧数据吧

个人理解，当打开编辑一条已有内容时：
如果点击了左侧，可能做的操作有2种：
1. 设置左边时间， 如 `2022-09-16 - 2022-09-18` 变更为 `2022-09-17 - 2022-09-18`
2. 重新选择一次区间，如 `2022-09-16 - 2022-09-18` 变更为 `2022-09-22 - 2022-09-25`

现有组件下，确实第二次操作是有困惑的，相当于虽然重新选择了一个区间，都是在修改右侧的数据
确实选择不符合规范的时候，清空另一侧数据重新选择是一个不错的处理方式
