### ISSUE TITLE
[Table] 分辨率变大后表格列变宽，再回到原来的宽高后恢复不回去导致列在小分辨率时渲染不全

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#1525]
### tdesign-vue 版本

0.47.0

### 重现链接

https://codesandbox.io/s/q13ufy?file=/src/demo.vue

### 重现步骤

![test](https://user-images.githubusercontent.com/8199240/190945996-3b53d1f0-c94d-4f0e-8b10-5becc1d8abca.gif)

### 期望结果

列设置了宽度应该有个min-width，在缩小分辨率时能够自动缩放。

### 框架版本

vue2.6.11

**Comment by chaishi** [comment]
看了很久很久很久很久，
没有看出来“原来的宽高恢复不回去”是什么意思，
以及“小分辨率时渲染不全” 是什么意思（没有看见哪一列有被隐藏）

**Comment by chaishi** [comment]
连蒙带猜，初步估计是说，小屏幕变化之前总宽是 A，变宽再回来时，不再是 A
