### ISSUE TITLE
[Drawer] 内容过长时，拖拽区域覆盖滚动条导致滚动条无法使用

### ISSUE THREAD

**Issue by shikaiguo** [Tencent/tdesign-vue#1526]
### tdesign-vue 版本

0.47.0

### 重现链接

https://tdesign.tencent.com/vue/components/drawer#%E5%8F%AF%E6%8B%96%E6%8B%BD%E7%9A%84%E6%8A%BD%E5%B1%89

### 重现步骤

 ```vue
<t-drawer :sizeDraggable="true">
    长文本
</t-drawer>
```
![image](https://user-images.githubusercontent.com/5564630/190970112-4663ea27-5007-4816-bfdf-6741e1eb189f.png)
滚动条被覆盖

### 期望结果

建议sizeDraggable为true时，右侧增加拖拽区域样式

**Comment by ccccpj** [comment]
https://stackblitz.com/edit/angular-ab2kea?file=src%2Fdemo.vue
感谢反馈，经排查在 0.47.0 以及最新版本均未复现 该问题，或者您需要提供更加详细的复现步骤。
