### ISSUE TITLE
[table] 浏览器窗口缩小时，表格的分页器吸底和表头吸顶后没有对齐表格

### ISSUE THREAD

**Issue by WULIbinbin** [Tencent/tdesign-vue#1529]
### tdesign-vue 版本

0.46.3

### 重现链接

https://codesandbox.io/s/upbeat-wilson-9fmrpl?file=/src/App.vue

### 重现步骤

浏览器窗口宽度缩小至小于table的宽度，拖动浏览器滚动条，表头和分页吸附后会错位。
<img width="677" alt="image" src="https://user-images.githubusercontent.com/24265957/190977906-10c43378-36d6-423e-bd01-dbea210d707e.png">

### 期望结果

拖动浏览器滚动条时，表头和分页能挨着浏览器最左侧（或者其他视觉优化方式）。

### 框架版本

vue(2.6.11)

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本修复
