### ISSUE TITLE
[swiper] swiper轮播图的多个bug

### ISSUE THREAD

**Issue by airkingZy** [Tencent/tdesign-vue#1537]
### tdesign-vue 版本

0.47.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-d0ur0b?file=/src/demo.vue

### 重现步骤

问题1.swiper 的鼠标悬停不轮播鼠标移出后还是不会轮播了。
问题2.trigger属性也没有生效，就好像只有默认的hover。
问题1，2 复现连接，官网 https://tdesign.tencent.com/vue/components/swiper?tab=demo
![image](https://user-images.githubusercontent.com/24963857/191217636-580135ba-bfa5-4a4c-84a6-f2bd75d573f2.png)

问题3.用了fade这个特效，在item里面添加click时间，获取到的数据一直会是最后一个。复现连接：https://codesandbox.io/s/tdesign-vue-demo-forked-d0ur0b?file=/src/demo.vue

### 框架版本

vue2

**Comment by xiaosansiji** [comment]
已在 0.48.0 修复
