### ISSUE TITLE
[Menu] 添加VueCompositionAPI后依旧无法渲染组件

### ISSUE THREAD

**Issue by Hsomething** [Tencent/tdesign-vue#1538]
### tdesign-vue 版本

0.47.0，0.43.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-00cfqy?file=/src/main.js

### 重现步骤

通过Vue.use引入组件，在TDesign引入前，引入VueCompositionAPI
`import Vue from "vue";
import VueCompositionAPI from "@vue/composition-api";
import TDesign from "tdesign-vue";

import "tdesign-vue/es/style/index.css";

Vue.use(VueCompositionAPI);
Vue.use(TDesign);`

报错：
![image](https://user-images.githubusercontent.com/41931172/191247151-e6e71e57-bc0f-4df3-a0ad-7182cbac2c38.png)

### 框架版本

Vue2(2.9.6)

**Comment by uyarn** [comment]
全量引入不需要手动注册ompostion-api

**Comment by Hsomething** [comment]
> 

即使注册也无法正常加载组件

**Comment by Hsomething** [comment]
> 全量引入不需要手动注册ompostion-api 局部注册才需要

即使不注册VueCompositionAPI也无法正确加载组件

**Comment by uyarn** [comment]
参考下这些DEMO 
https://codesandbox.io/s/xony43?file=/src/demo.vue 
https://codesandbox.io/s/e9i3b7?file=/src/demo.vue
https://codesandbox.io/s/stwl9u?file=/src/demo.vue
看下是否使用方式有问题

**Comment by Hsomething** [comment]
解决了，vue版本问题，更新到2.6.14就好了，在vue(2.5.2)版本就无法渲染组件，线上也一样
