### ISSUE TITLE
[ColorPicker] 颜色选择器渐变选择区域选择颜色后弹层直接关闭

### ISSUE THREAD

**Issue by zhengweicheng123zwc** [Tencent/tdesign-vue#1556]
### tdesign-vue 版本

vue next 0.22.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/color-picker

### 重现步骤

使用带触发元素的颜色选择器时，点击颜色线条上面的按钮，弹窗会立即消失

### 期望结果

使用带触发元素的颜色选择器时，点击颜色线条上面的按钮，希望可以更改该按钮的颜色

**Comment by uyarn** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/26377630/192777875-e8783eb1-2eab-41bd-ad78-1b5cb4ec0944.png">
是指这吗

**Comment by uyarn** [comment]
has been assigned to @S-mohan

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
