### ISSUE TITLE
tree 组件 可过滤的树 官方示例无效

### ISSUE THREAD

**Issue by YFAnt** [Tencent/tdesign-vue#156]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here
谷歌
**Describe the bug**
可过滤的树 官方事例无效， 由于t-input 没有input事件，@input.native="onInput" 可以改成这个
**Additional context**

**Comment by chaishi** [comment]
描述可以再清晰一点不？

官方示例具体是啥示例

**Comment by YFAnt** [comment]
![image](https://user-images.githubusercontent.com/46584057/147813049-019420d0-0aeb-47ec-b5c2-f7ac61487f50.png)
就这个功能示例，我试了一下没管用
