### ISSUE TITLE
[Select] 方向键没有过滤创建的值

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#1563]
### tdesign-vue 版本

0.48.2

### 重现链接

https://stackblitz.com/edit/angular-4ogirz-qeamdb?file=src/demo.vue

### 重现步骤

1，如下方视频链接，在同时存在过滤与创建条目的情况下，我搜索合同，通过**方向键**去选择第二个选项“合同名称”，带回的却是第一个选项“合同编号”
 https://www.yecong.com/share/1574217318429495296?stage=0 

2，如果输入的值本身是选项中的数据，则会出现两个一样的选项，不知是否正常
![image](https://user-images.githubusercontent.com/25051361/192181036-feff44a5-2524-48cf-91d4-a720a4c0aefb.png)

3，#1360能否实现呢？

**Comment by uyarn** [comment]
assign to  @skytt

**Comment by skytt** [comment]
> 1，如下方视频链接，在同时存在过滤与创建条目的情况下，我搜索合同，通过方向键去选择第二个选项“合同名称”，带回的却是第一个选项“合同编号”

已在 #1566 中修复

> 2，如果输入的值本身是选项中的数据，则会出现两个一样的选项，不知是否正常

图中上方的为用户创建的待选项，下方为列表中已经含有的已配置项，label相同，但是value不一样。这个场景我认为是合理的，如果用户有隐藏的需要可以通过自定义 <t-option/> 的方式来控制显隐，但是组件本身保留这个能力

> 3，#1360能否实现呢？

考虑后续迭代

**Comment by a-l-o-n-g** [comment]
![image](https://user-images.githubusercontent.com/25051361/192405591-0deab091-dc0b-4225-85ef-d2aeeedf480f.png)
关于第二点，如图所示，label与value其实是一样的，搜索的值正是选项中的值，而不应该是创建；反之，如果不相同，创建是合理的；

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本修复
