### ISSUE TITLE
[DatePicker日期选择器]可输入状态下

### ISSUE THREAD

**Issue by ghostzhang** [Tencent/tdesign-vue#1564]
### tdesign-vue 版本

0.48.2

### 重现链接

[https://tdesign.tencent.com/vue/components/date-picker?tab=demo](https://tdesign.tencent.com/vue/components/date-picker?tab=demo)

### 重现步骤

![2022-09-26 12 09 09](https://user-images.githubusercontent.com/194242/192193560-7676d497-65a4-4ece-a7a2-59e192bc864f.gif)

### 期望结果

全部删除后应与清除效果一致
![2022-09-26 12 29 20](https://user-images.githubusercontent.com/194242/192194154-c7c66a1d-57b0-4e61-be54-271567872839.gif)

### 实际结果

手动删除后仅是视觉上为空，实际并未清除
![2022-09-26 12 29 03](https://user-images.githubusercontent.com/194242/192194188-7b225409-8674-4683-add7-bb3a260609e4.gif)

**Comment by HQ-Lin** [comment]
这里手动清空了输入框的值后在 blur 事件并未重置成之前的时间确实有点问题，我排查下
