### ISSUE TITLE
[DatePicker] 时间区间选择器高亮背景样式问题

### ISSUE THREAD

**Issue by luwuer** [Tencent/tdesign-vue#1580]
### tdesign-vue 版本

0.48.2

### 重现链接

[官方文档](https://tdesign.tencent.com/vue/components/date-picker?tab=demo#%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9%E9%9D%A2%E6%9D%BF%E5%8D%95%E7%8B%AC%E4%BD%BF%E7%94%A8)

### 重现步骤

**问题1**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/13172641/192770237-3d8008af-6191-42c8-90c7-ccac8fc0a4e2.png">

**问题2**
https://user-images.githubusercontent.com/13172641/193024234-6c4cf0bc-4723-4e42-b269-0803d91a22df.mov

**问题3**
<img width="646" alt="image" src="https://user-images.githubusercontent.com/13172641/193024399-aa964bb8-6683-4069-bf89-016ae515fe9d.png">

### 期望结果
**问题1** 
16号的高亮效果应该和 15 号保持一致

**问题2** 
处理好边界问题，停止闪烁

**问题3** 
不应该有间隙，`*active-(start|end)` 和选择时间前后四种组合下，只有 `*active-start` 在前并且向前选择时间会出现间隙问题

### 实际结果
**问题1**
目前16号高亮效果同已选择的日期再次被选中保持一致

**问题2** 
鼠标移动到边界时，闪烁不停

**问题3** 
cell 的 `*active-start` 类名在前，并且向前选择时间时，会出现间隙

**Comment by HQ-Lin** [comment]
设计如此，选中 + hover状态颜色会更深

**Comment by luwuer** [comment]
> 设计如此，选中 + hover状态颜色会更深

『选中 + hover状态颜色会更深』没问题，但 16 号并没有被选中
