### ISSUE TITLE
[Table 表格]增强的表格吸顶有问题

### ISSUE THREAD

**Issue by renjiali666** [Tencent/tdesign-vue#1585]
### tdesign-vue 版本

0.48.4

### 重现链接

https://github.com/renjiali666/bugdemo.git

### 重现步骤

响应有点问题，如果树状开始没有滚动，展开发生滚动，无法吸顶，但是展开状态下调整窗口大小又可以了

### 期望结果

正常吸顶

### 实际结果

需要手动缩放窗口

### Node版本

16.0.0

**Comment by renjiali666** [comment]
组件有增强表格，加列配置，表格的表头消失了，应该是2个bug

**Comment by uyarn** [comment]
链接打不开喔 吸顶吸底的问题有加个resize的重新计算最新的版本 确认最新的还有这个问题吗

**Comment by chaishi** [comment]
> 加列配置，表格的表头消失了

对于这类情况，显示地设置呈现字段 `displayColumns: ['xxx']` 即可

**Comment by chaishi** [comment]
> 响应有点问题，如果树状开始没有滚动，展开发生滚动，无法吸顶

resolved in https://github.com/Tencent/tdesign-vue/pull/1633

**Comment by uyarn** [comment]
release 0.49.0
