### ISSUE TITLE
[Table] columns ellipsis 属性 支持非纯文本(包含父标签)

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1588]
### 这个功能解决了什么问题

业务体验更好

### 你建议的方案是什么

不支持的情况下我需要      ellipsis: (h, { row }) => <div>{row.name}</div> 重构 以及 无法支持省略号
<img width="476" alt="image" src="https://user-images.githubusercontent.com/8606851/193065385-bb050670-bafb-4cab-a56b-4059dd714a7c.png">
支持的正常显示
<img width="401" alt="image" src="https://user-images.githubusercontent.com/8606851/193065404-205683e3-f70a-4c63-b097-2690265f0383.png">

**Comment by chaishi** [comment]
`ellipsis: (h, { row }) => row.name` 和 `ellipsis: true` 相比，没差几个字母，不让你的工作量从今天变成明天。不作处理。

会专门新增超出省略示例代码。（Vue3 和 React 已支持并发布，Vue2 待发布 https://github.com/Tencent/tdesign-vue/pull/1633）

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/11605702/195973004-0cda2198-a33f-4871-820e-3547dc108ba9.png">
