### ISSUE TITLE
[Table] 表格文档中“基础表格”，切换尺寸无响应

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#1591]
如题。
位置：Table 表格 -> 示例 -> 基础表格 -> 切换尺寸

<img width="913" alt="image" src="https://user-images.githubusercontent.com/9960612/193221517-d7f64dfb-8562-4a30-a8ed-f1fda1745c6a.png">

**Comment by uyarn** [comment]
问题已知，Demo 没有传 size 给 table，实际支持
