### ISSUE TITLE
[Table] ellipsis 内容达到一定长度显示不全

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1603]
### tdesign-vue 版本

0.48.4

### 重现链接

https://stackblitz.com/edit/angular-nqjmoa?file=src/demo.vue

### 重现步骤

内容达到一定长度显示不全
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/8606851/194790653-5bbb2734-4aff-4a34-ad76-97a75774f7ec.png">

### 期望结果

显示全部信息

### 实际结果

显示不全

**Comment by chaishi** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/11605702/195973408-a4b41daf-522d-4be4-a2d6-ea7621d638e3.png">
