### ISSUE TITLE
DatePicker日期选择器 在跨月选择时，样式异常

### ISSUE THREAD

**Issue by smile33** [Tencent/tdesign-vue#161]
**Describe Framework**

tdesign-vue 0.32.0

**Describe Environment**

Chrome 96.0.4664.110

**Describe the bug**
官网链接：https://tdesign.tencent.com/vue/components/date-picker
1.带快捷标签的日期选择器，点击最近几天时，样式异常；
2.在选择跨月日期时，样式异常；

<img width="819" alt="企业微信截图_1efe8cf6-065f-4236-bb37-fd96e02a07c3" src="https://user-images.githubusercontent.com/11691667/147843112-62c63b2e-3e2d-4b04-9dcc-53ff364c8403.png">

<img width="812" alt="企业微信截图_b510ec58-a868-4c5f-9005-280505a8070a" src="https://user-images.githubusercontent.com/11691667/147843114-e494356f-4b95-496c-a7cf-90e8159c8ec5.png">

<img width="812" alt="企业微信截图_b510ec58-a868-4c5f-9005-280505a8070a" src="https://user-images.githubusercontent.com/11691667/147843217-c5499d4c-99a3-48e1-9dec-b997bb80b6b7.png">

**Comment by chaishi** [comment]
收到，我们处理一下
