### ISSUE TITLE
[Table] 设置默认的选中的key正常，但是值默认的undefined

### ISSUE THREAD

**Issue by renjiali666** [Tencent/tdesign-vue#1610]
### 重现链接
https://codesandbox.io/s/ekmfgd?file=/src/demo.vue

### 重现步骤
@select-change="rehandleSelectChange"触发后，   
rehandleSelectChange(value, { selectedRowData }) {
      this.selectedRowKeys = value;
      console.log(value, selectedRowData);
    },
selectedRowData的默认选中的是undefined，value正常

### 期望结果
默认的应该是默认的值

### 实际结果
默认选中的是undefined
![image](https://user-images.githubusercontent.com/111716113/194993575-55954105-97e1-4de4-ac5f-5e3396e47afb.png)

| Environment | Info |
|---|---|
| 相关版本 | 0.48.5 |
| 框架版本 / 基础库版本 | vue2.6.14 |
| 系统、浏览器 | WIN11 谷歌 |
| Node版本 | 16.0.0 |

**Comment by chaishi** [comment]
不知道描述中的 `undefined` 从哪里来的，什么时机，对表格具体做了什么操作出现的。我按照下图操作，没有问题。

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/11605702/195973690-dcb8dfc6-11b6-4bcb-87f2-7d1915731190.png">

**Comment by chaishi** [comment]
由于长时间没有回复，且无法复现问题，issue 关闭。后面有需要可以 reopen
