### ISSUE TITLE
[table] PrimaryTableCol中的filter.type为"multiple"时，resetValue设置为非空数组， 重置过滤filter-change中参数错误

### ISSUE THREAD

**Issue by luguokong** [Tencent/tdesign-vue#1611]
### tdesign-vue 版本

0.48.5

### 重现步骤

![image](https://user-images.githubusercontent.com/21010969/195014164-f658ecac-6b43-4734-ab83-7daea8ca2ee4.png)

### 期望结果

点击过滤条件重置按钮时，filter-change中参数和resetValue保持一致

### 实际结果

点击过滤条件重置按钮时，filter-change对应列的参数为空数组

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1633
