### ISSUE TITLE
[SelectInput] : breakline 换行失效

### ISSUE THREAD

**Issue by linying-cs** [Tencent/tdesign-vue#1614]
### tdesign-vue 版本

42.2

### 重现链接

https://codesandbox.io/s/mwov5g?file=/src/demo.vue

### 重现步骤

:tag-input-props="{ excessTagsDisplayType: 'break-line' }",超过输入框宽度换行，不起作用

**Comment by xiaosansiji** [comment]
已在 0.50.0 版本修复
