### ISSUE TITLE
[Transfer] 带分页的穿梭框左边全选添加至右边，右边在全选勾选回去报错

### ISSUE THREAD

**Issue by chenweiming0109** [Tencent/tdesign-vue#1615]
### tdesign-vue 版本

0.48.5

### 重现链接

https://codesandbox.io/s/hves7l?file=/src/demo.vue

### 重现步骤

带分页的穿梭框
左边全选添加至右边，右边在全选勾选回去，会报错

### 框架版本

vue2

### Node版本

node 14

**Comment by uyarn** [comment]
fixed in 0.49.4
