### ISSUE TITLE
[Dialog] Upload 图片上传后的预览弹框没有覆盖dialog 且 切换图片、关闭预览弹窗失效

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1627]
### tdesign-vue 版本

0.48.5

### 重现链接

https://stackblitz.com/edit/angular-mr3zv4?file=src/demo.vue

### 重现步骤

点击openModel
上传多张图片 点击图片预览
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/8606851/195555022-182ef428-4fd6-4592-b536-60c55ce224b5.png">

### 期望结果

覆盖在dialog 上面 且 可关闭 可切换图片

### 实际结果

没有覆盖在dialog 上面 且dialog v-if 销毁后 切换图片、关闭预览弹窗失效

**Comment by chaishi** [comment]
图片预览组件的 zIndex 层级 CSS，应当默认高于 Dialog，需要我们处理。

@Jiachang-Cai 你可以先通过 CSS 给预览组件加一个 `z-index`，拉高层级，解决问题

**Comment by Jiachang-Cai** [comment]
> 图片组件的 zIndex 层级 CSS，默认设置对话框，需要我们预先处理。
> 
> @Jiachang-Cai你可以先通过CSS给预览组件加一个`z-index`，拉高层级，解决问题

dialog v-if 后无法关闭和切换图片 要怎么处理？

**Comment by Jiachang-Cai** [comment]
> > 图片组件的 zIndex 层级 CSS，默认设置对话框，需要我们预先处理。
> > @Jiachang-Cai你可以先通过CSS给预览组件加一个`z-index`，拉高层级，解决问题
> 
> dialog v-if 后无法关闭和切换图片 要怎么处理？

层级上去了 就正常了。

**Comment by xiaosansiji** [comment]
已在 0.49.0 版本修复
