### ISSUE TITLE
[Table] 表格固定列的阴影显示有问题

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#1629]
### tdesign-vue 版本

0.46.4~0.48.5

### 重现链接

https://0_46_4-tdesign-vue.surge.sh/vue/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4%E5%92%8C%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

0.46.4 版本固定列阴影展示：
![image](https://user-images.githubusercontent.com/8199240/195588043-3fc1edcb-42eb-4f3d-8c56-6044ff540594.png)

0.48.5固定列阴影展示：
![image](https://user-images.githubusercontent.com/8199240/195588232-27f14df9-e26f-49cd-864b-fe536b864b03.png)

### 期望结果

0.46.3 版本的阴影是正常的，后续版本开始有问题。
![image](https://user-images.githubusercontent.com/8199240/195587869-66f5e179-83b9-4338-b7ea-c91d32c78662.png)

### 框架版本

vue2.6.11

**Comment by chaishi** [comment]
可以看下最新设计稿，设计如此，和腾讯文档的 Excel 保持一致
