### ISSUE TITLE
[日期范围选择组件（月份选择）] 传入同月份日期 面板左右展示年份重复

### ISSUE THREAD

**Issue by simpleAndElegant** [Tencent/tdesign-vue#1632]
### tdesign-vue 版本

0.48.5

### 重现链接

https://stackblitz.com/edit/angular-nelzxx?file=src/demo.vue

### 重现步骤

绑定值设置为同一个月份

### 期望结果

<img width="544" alt="image" src="https://user-images.githubusercontent.com/41931905/195779090-84f4ad2d-8dff-42cf-bbdf-444cc8a3d540.png">

### 实际结果

<img width="545" alt="image" src="https://user-images.githubusercontent.com/41931905/195779247-840eed53-6708-4948-9488-84821b3bb37e.png">

### 框架版本

vue2

**Comment by yaogengzhu** [comment]
![image](https://user-images.githubusercontent.com/42566669/195981217-06d6b7a9-8caf-496b-8b24-5c6a7f62a8b0.png)
似乎没问题！

**Comment by simpleAndElegant** [comment]
> ![image](https://user-images.githubusercontent.com/42566669/195981217-06d6b7a9-8caf-496b-8b24-5c6a7f62a8b0.png) 似乎没问题！

左右面板年份重复了诶，右侧面板年份应该是2023？

**Comment by yaogengzhu** [comment]
> > ![image](https://user-images.githubusercontent.com/42566669/195981217-06d6b7a9-8caf-496b-8b24-5c6a7f62a8b0.png) 似乎没问题！
> 
> 左右面板年份重复了诶，右侧面板年份应该是2023？

根据你传入的默认时间呗！

**Comment by simpleAndElegant** [comment]
> > > ![image](https://user-images.githubusercontent.com/42566669/195981217-06d6b7a9-8caf-496b-8b24-5c6a7f62a8b0.png) 似乎没问题！
> > 
> > 
> > 左右面板年份重复了诶，右侧面板年份应该是2023？
> 
> 根据你传入的默认时间呗！

我知道是根据我传入默认时间来展示的，但是左右面板重复，会导致使用体验下降，可以参考[这个Issue](https://github.com/Tencent/tdesign-vue/issues/1632#issuecomment-1279899652)，同样的问题。
