### ISSUE TITLE
[table] 表格可编辑单元格的验证错误不能被正常清除

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1637]
### tdesign-vue 版本

0.48.5

### 重现链接

tdesign vue 官方示例：可编辑单元格的表格

### 重现步骤

1. 在设置了验证规则的单元格内，进行不符合要求的输入，让错误提示出现。例如： FirstName 列要求输入不能为空，编辑该列的任意一个单元格，将输入清空后，点击页面空白处让输入框失焦，此时会出现错误提示“不能为空”。
2. 在出错的输入框内进行有效输入，然后再让输入框失焦，此时验证通过，输入结果被保存并退出编辑状态。
3. 再次点击刚才曾经出错的单元格，进入编辑状态。

### 期望结果

单元格输入验证出错后，再进行有效输入，输入成功之后应当清除错误状态与错误信息（ status 与 tips ）。

### 实际结果

此时虽然输入框内已包含有效输入，但输入框仍然处于错误状态（有红色勾边，下方依然有错误提示“不能为空”）。查看组件状态，会发现 status 、 tips 属性均保留出错时的值，并没有被清空。

### 框架版本

Vue(2.6.14)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

任意的输入验证规则都会触发可编辑单元格的上述 bug 。

**Comment by chaishi** [comment]
印象中之前开发的时候，特地处理过这个问题

经过验证。Vue3 和 React 表现正常，仅 Vue2 异常，应该是处理漏了，我来跟进下。

**Comment by uyarn** [comment]
fixed 0.49.3
