### ISSUE TITLE
[table] 吸顶表格的表头文本显示的tooltip被遮挡并且出现滚动条

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1639]
### tdesign-vue 版本

0.48.5

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-g8mkd0?file=/src/demo.vue

### 重现步骤

吸顶表格columns.title文本较长，并且配置了ellipsis: true的时候， tooltip显示不全，表头出现滚动条。
<img width="848" alt="image" src="https://user-images.githubusercontent.com/13745660/196328905-f55e283d-57a6-4873-ab57-0c2b3dbc2a96.png">

### 期望结果

tooltip能够显示全，并且不出现滚动条

### 实际结果

tooltip被遮挡，并且出现滚动条。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
如果只是表头省略，请设置 `ellipsisTitle: true`

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1702

**Comment by uyarn** [comment]
fixed 0.49.3
