### ISSUE TITLE
【Steps】组件自定义额外内容没有生效

### ISSUE THREAD

**Issue by vnues** [Tencent/tdesign-vue#164]
**Describe Framework**

tdesign-vue

**Describe Environment**
v0.32.0
Add browser version here
版本 96.0.4664.110（正式版本） (x86_64)
**Describe the bug**
貌似Steps组件自定义额外内容没有生效，另外自定义内容也没有生效，官方文档就可以复现
![image](https://user-images.githubusercontent.com/44258525/147870431-f2f6445f-42f7-41a5-bbd5-28773c351c44.png)

**Additional context**

**Comment by xiaosansiji** [comment]
see #36 可以尝试升级下 0.33.0 版本
