### ISSUE TITLE
[dialog] dialog theme属性值为非‘default’时body样式类名错误 

### ISSUE THREAD

**Issue by JackFruitxx** [Tencent/tdesign-vue#1656]
### tdesign-vue 版本

0.49.0

### 重现链接

https://tdesign.tencent.com/vue/components/dialog?tab=demo

### 重现步骤

切换theme属性值为default以外的值
![image](https://user-images.githubusercontent.com/43942771/196850486-1c3706ea-83c1-4ebe-86bc-e6d01f3dfe51.png)

### 期望结果

body类名为：t-dialog__body
![image](https://user-images.githubusercontent.com/43942771/196850540-de1033d9-16c6-442a-8575-a67923ba20d0.png)

### 实际结果

body类名为：t-dialog__body__icon
![image](https://user-images.githubusercontent.com/43942771/196850567-46d43048-ece6-41e9-a846-cbf0b2822bad.png)

**Comment by uyarn** [comment]
看目前的实现是要为和上方留出padding 虽然这个类名也得规范一下

**Comment by uyarn** [comment]
fixed 0.49.1
