### ISSUE TITLE
[Tree] onActive   配合 :treeProps="{keys: {value: 'id'}}" 返回value 异常

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1657]
### tdesign-vue 版本

0.49.0

### 重现链接

https://stackblitz.com/edit/angular-f9lgcg?file=src/demo.vue

### 重现步骤

:treeProps="{keys: {value: 'id'}}"
替换value key

### 期望结果

onActive 返回 实际value

### 实际结果

没有返回实际value

**Comment by uyarn** [comment]
@Jiachang-Cai 原来是API配错了 直接:keys就可以 不加treeProps的 
https://stackblitz.com/edit/angular-f9lgcg-kza4yx?file=src%2Fdemo.vue

**Comment by uyarn** [comment]
有问题再reopen哦
