### ISSUE TITLE
[Collapse] expandOnRowClick 失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1659]
### tdesign-vue 版本

0.49.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-nfjkux

### 重现步骤

expandOnRowClick 功能失效，点击标题不能展开面板。

### 期望结果

0.46.4版本正常

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by daizhan** [comment]
确实有问题，在官方的示例上，点击标题也不会折叠，但是标题外的空白位置可以。

**Comment by uyarn** [comment]
fixed 0.49.1
