### ISSUE TITLE
[DropDownItem] DropDownItem的click事件和vue的stop语法有冲突，必须到方法中阻止事件冒泡，无法使用修饰符

### ISSUE THREAD

**Issue by zlrui0810** [Tencent/tdesign-vue#1660]
### tdesign-vue 版本

0.49.0

### 重现步骤

<t-dropdown class="avatar-container right-menu-item hover-effect" trigger="click">
        <div class="avatar-wrapper">
          <img :src="avatar" class="user-avatar">
          <i class="el-icon-caret-bottom" />
        </div>
        <t-dropdown-menu>
          <t-dropdown-item>
            <t-link href="/user/profile">
              个人中心
            </t-link>
          </t-dropdown-item>
          <t-dropdown-item @click.stop="handleSettingShow">
            <span>布局设置</span>
          </t-dropdown-item>
          <t-dropdown-item @click.stop="logout">
            <span>退出登录</span>
          </t-dropdown-item>
        </t-dropdown-menu>
      </t-dropdown>

**Comment by xixileng** [comment]
封装组件的 click 非原生事件，无法直接 stop，如果要用 stop，可以加 native 修饰符一起用，当然这时事件就是原生的了

**Comment by zlrui0810** [comment]
尝试了stop修饰符和native修饰符一起使用，无法触发，挂载的方法不执行

**Comment by xixileng** [comment]
> 尝试了stop修饰符和native修饰符一起使用，无法触发，挂载的方法不执行

哦？你怎么写的可否给个demo呢

**Comment by zlrui0810** [comment]
<t-dropdown-item @click.native.stop="handleSettingShow">
            <span>布局设置</span>
</t-dropdown-item>

**Comment by zlrui0810** [comment]
只添加native修饰符，也无法触发

**Comment by zlrui0810** [comment]
https://xnzgfm.csb.app/

**Comment by xixileng** [comment]
Oh，在当slot用的时候，非组件 click 外的时候都被过滤了，所以加了修饰符后的事件也没了，见 useDropdownOptions.ts > getOptionsFromChildren
