### ISSUE TITLE
[table] 表格的列会动态变化时，列宽计算出现错误

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1663]
### tdesign-vue 版本

tdesign-vue 0.48.5

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-98n6s8?file=/src/demo.vue

### 重现步骤

1. 在页面上显示一个表格组件，初始时列配置 `columns` 是固定的。
2. 异步方式调整表格的列。 demo 中是在 2 秒之后为表格增加了 9 个新的列。
3. 原有的列与新增的列，均设置了 `width` 属性，也就是列的最小宽度。

### 期望结果

列发生变化后，表格自动更新列宽时，应当按照预设的各个列的 `width` 属性，控制各列的最小宽度。

### 实际结果

动态增加列之后，列宽度不会受 `width` 属性约束，可能会出现列宽被压的很窄的情况。

**备注**：如果动态删除部分列，则会有类似问题，效果相反，列宽不是变得过窄，而是变得过宽。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

查看源代码后发现，在计算列宽时， `recalculateColumnWidth()` 方法会判断 `tableElmWidth` 的值是否大于 0 。

- 若非，表示是在进行初始化处理，表格各列的宽度会遵循 `width` 属性的设置，计算出的表格宽度最终会赋值给  `tableElmWidth` 属性。
- 若是，认为表格已经初始化过，会根据 `tableElmWidth` 的值动态去调整各个列的宽度。

因此，在表格的列动态增加的情况下，计算列宽时，会使用之前已经产生的 `tableElmWidth` 值，将其作为整个表格的宽度限制。新增列之后的列宽总和会超过这个宽度限制，最后各列的宽度会根据表格宽度限制进行调整，导致列宽被压缩。

此问题目前的解决方式：

1. 可以在表格组件上设置 renderKey ，自行观察列的变化，在列变化时变更 renderKey  的值，让表格重新渲染。
2. 或者，自行观察列的变化，在变化发生时将 `tableElmWidth` 属性值重置为 0 （ `$refs.primaryTableRef.tableElmWidth` ），以便触发初始化计算。

但是以上处理方式都需要用户自行书写代码，类似于打补丁。

希望官方能考虑改进列宽的计算处理。

**Comment by chaishi** [comment]
fixed in latest version

**Comment by chaishi** [comment]
补充说明看不懂，就先略过了。

无论是否为列数量变化，都应该遵循同一个规则：
前提条件：不拉宽表格的宽度 （加宽整个表格宽度，属于另一个 feature）

1. 在表格宽度 大于 用户设置的列宽总和时， `width` 为固定值，写多少就必须是多少，`minWidth` 表示最小值。
2. 在表格宽度 小于 用户设置的列宽总和时，此时又不能拉宽整个表格，则表现为必要的压缩

**Comment by sagittarius-rev** [comment]
> 

sandbox 的示例代码已更新，在界面上放了 3 个操作按钮，可以手动点击按钮查看效果。

说明：

1. 表格宽度不是指定的，使用 `TSpace` 允许横向滚动，初始的表格宽度是根据列宽自动计算出来的。
2. 上下两个表格，上面表格的列全部设置了 `width` ，而下面表格有一列（平台）设置了 `minWidth`  。
3. 列动态发生变化时，上方表格宽度的没有自动调整，导致列宽显示过窄或过宽。
4. 列动态发生变化时，下方表格的列宽会不断自动增长，不会停止。
5. 按照 API 文档，列的 `width` 属性用于控制列的最小宽度，而 `minWidth` 仅用于控制 css 样式，并且只有少数浏览器支持。与你的说法不符。

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/2130
