### ISSUE TITLE
[table] 表格固定表头在360浏览器不兼容

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#1666]
### tdesign-vue 版本

0.47.0

### 重现链接

https://tdesign.tencent.com/vue/components/table?tab=demo

### 重现步骤

文档上的t-table 固定表头在360浏览器无法固定

### 期望结果

希望能兼容360浏览器

### 实际结果

t-table 固定表头在360浏览器无法固定

### 框架版本

2.6.11

### 浏览器版本

360浏览器

**Comment by chaishi** [comment]
可以更为使用吸顶表头
