### ISSUE TITLE
[select] 输入值为 null 时错误显示字符串 null

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1668]
### tdesign-vue 版本

tdesign-vue 0.48.5

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-o86u4v?file=/src/demo.vue

### 重现步骤

使用 TSelect 的组件，将组件的输入值（ `value` 或 `v-model` ）置为 `null` 。

### 期望结果

输入值为 `null` 时， Select 组件应当显示为“未选择”状态，和输入值为 `undefined` 时保持一致。
因为 `null` 和 `undefined` 在很多场景时作用都是类似的。
特别地，考虑到 JSON 的因素， JSON 只支持 `null` ，不支持 `undefined` ，因此组件对于 `null` 的支持应当是必要的。

### 实际结果

Select 组件显示了字符串 `"null"` ，实际上不存在这样一个选项。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

**Comment by uyarn** [comment]
fixed 0.49.1
