### ISSUE TITLE
桌面端Vue分页组件切换效果闪烁

### ISSUE THREAD

**Issue by niuhao95** [Tencent/tdesign-vue#167]
**Is your feature request related to a problem? Please describe.**

切换分页时，例如从12->10，会出现闪烁
https://tdesign.tencent.com/vue/components/pagination

**Comment by xiaosansiji** [comment]
@Wen1kang 有办法改下点击切换的效果不？

**Comment by Wen1kang** [comment]
嗯嗯，这个问题我们一起看看～

**Comment by Wen1kang** [comment]
@niuhao95 这个问题其实是因为点击选中分页时，最后一个页码选项会跳转至中间，则会造成闪一下的体验

**Comment by xiaosansiji** [comment]
我们在下个版本里先把 pagination 的点击时的背景变化动画先干掉吧，后面会看看有木有什么更好的动画效果，再加

**Comment by xiaosansiji** [comment]
已在 0.33.1 版本中修复
