### ISSUE TITLE
[textarea]设置为disabled后，t-textarea__limit处背景色显示异常

### ISSUE THREAD

**Issue by luguokong** [Tencent/tdesign-vue#1673]
### tdesign-vue 版本

0.49.0

### 重现步骤

![image](https://user-images.githubusercontent.com/21010969/197509111-cc9999e2-04bf-482c-8776-03c2ee0195ea.png)

### 期望结果

右下角字符数背景色统一美观

**Comment by uyarn** [comment]
fixed 0.49.1
