### ISSUE TITLE
[table] js语法ellipsis 如何设置样式

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#1675]
### tdesign-vue 版本

0.47.0

### 重现链接

https://tdesign.tencent.com/vue/components/table#%E5%8D%95%E5%85%83%E6%A0%BC%E8%B6%85%E5%87%BA%E7%9C%81%E7%95%A5%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

目前文档只有jsx语法设置样式，vue2 js如何给table中的ellipsis 设置样式，没有找到相关说明

### 期望结果

vue2 js给table中的ellipsis 设置样式，添加dom

### 实际结果

// 超出省略的内容显示纯文本，不带任何样式和元素
          ellipsis: (h, { row }) => row.link,
          
          
          无法设置样式

### 框架版本

2.6.11

### 浏览器版本

360浏览器

**Comment by chaishi** [comment]
目前没有插槽的方式，只有 JSX 的方式。

**Comment by 412826deng** [comment]
示例代码都是jsx语法，上面说的纯 JS 用法可以使用： ellipsis: (h, { row }) => <div><a style={{ cursor: 'pointer' }}>{row.link}</a></div>   必须安装对应loader才行，要不然就会报错

**Comment by Wonder233** [comment]
可以用 vue 的 createElement 渲染函数创建，这是纯 js 用法，不需要安装   @@loader。
https://v2.cn.vuejs.org/v2/guide/render-function.html
```javascript
ellipsis: (h, { row }) => {
  return h('div', [
    h('a', {
      style: { cursor: 'pointer' },
      on: {
        click: () => {}
      },
    }, row.link)  
  ])
}
```

**Comment by chaishi** [comment]
支持使用名为 `ellipsis` 或者 `ellipsis-<colKey>` 的插槽自定义超出省略时的浮层内容，使用方法可参考示例代码
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2717
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/3259

#### 示例代码一
插槽名为 `ellipsis-applicant`，其中拼接的 `applicant` 是指列字段 `colKey` 的值
```html
<t-table row-key="id" :data="data" :columns="columns" lazyLoad>
  <template #ellipsis-applicant="{ row, col }">
    <span>插槽定义浮层内容：{{ row[col.colKey] }}</span>
  </template>
</t-table>
```

#### 示例代码二
```html
<t-table row-key="id" :data="data" :columns="columns" lazyLoad>
  <template #ellipsis="{ row, col }">
    <span>插槽定义浮层内容：{{ row[col.colKey] }}</span>
  </template>
</t-table>
```

**Comment by xiaosansiji** [comment]
fixed in 1.6.3
