### ISSUE TITLE
[Input][Select][Pagination][Tabs][Table] table 分页器在 tabs 切换时表现异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#1678]
### tdesign-vue 版本

0.49.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-xtjhpf?file=/src/demo.vue

### 重现步骤

1、点击选项卡2
![image](https://user-images.githubusercontent.com/16223845/197737426-005b925b-55bd-428b-ab25-93e8ee9c5b29.png)

### 期望结果
分页器正常展示
![image](https://user-images.githubusercontent.com/16223845/197737536-aababace-fade-492b-be72-577ba1ae4c71.png)
_No response_

### 实际结果
![image](https://user-images.githubusercontent.com/16223845/197737869-fc5f5740-870e-4bcf-8501-0cc75c4c6cbf.png)

_No response_

**Comment by chaishi** [comment]
组件之间的依赖关系：Table + Tabs -> Pagination -> Select

初步判定是 `Select` 组件实现问题，需要排查 Select 组件在 Tabs (destroyOnHide = false)组件中的应用

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/11605702/198875318-aa3e0cc7-324e-4f9b-ba32-7e37c19037f7.png">

**Comment by yaogengzhu** [comment]
应该是 Select  中某个初始化问题导致。 v-show、v-if 会有不同表现

**Comment by skytt** [comment]
实际查了一下，和 Select 关系不大，应该是 `Input` 组件 `autoWidth` 功能在切换时候的问题，参考：
https://codesandbox.io/s/tdesign-vue-demo-forked-olgby7?file=/src/demo.vue

切换到tab2的时候，宽度默认都回到一个比较窄的值了，Select 的 value 被隐藏了一部分，"10 条/页" 的后半部分被挡住了
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/7420660/198918721-10316e2b-ce4c-4991-9178-3df749add83a.png">

**Comment by chaishi** [comment]
明白了，是 Input 组件 `autoWidth` 功能，宽度计算问题

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1749 https://github.com/Tencent/tdesign-common/pull/968


https://user-images.githubusercontent.com/11605702/200153068-55b2a16a-4a79-4c2f-87a4-17746a00a6a4.mov

**Comment by chaishi** [comment]
Vue3 错误的效果如下

https://user-images.githubusercontent.com/11605702/200153922-c2e486fd-65c8-4145-b499-f6353d361b4a.mov

Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1968

修复效果同 Vue2

**Comment by chaishi** [comment]
React 错误效果和 Vue2 一样，切换 Tab 时，分页组件的文本会被隐藏。
问题复现：https://stackblitz.com/edit/react-rlqge3?file=src%2Fdemo.jsx

https://user-images.githubusercontent.com/11605702/200154199-5ead11df-68d2-4ac1-832c-3da989ead0eb.mov

**Comment by uyarn** [comment]
fixed in 0.49.4
