### ISSUE TITLE
[Space] 删除最后一个节点时异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#1679]
### tdesign-vue 版本

0.49.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-9lr7cp?file=/src/demo.vue

### 重现步骤

1、逐个点击关闭所有提示框
![image](https://user-images.githubusercontent.com/16223845/197739985-acaef0fe-ca21-480f-9fe7-d2357b7eef74.png)

### 期望结果

可以正常关闭所有提示框

### 实际结果

最后一个提示框无法关闭
![image](https://user-images.githubusercontent.com/16223845/197740701-4be10189-a3b0-4925-a8db-bda64192363c.png)

**Comment by uyarn** [comment]
fixed 0.49.1
