### ISSUE TITLE
Execute the `td-starter init` command to report an error

### ISSUE THREAD

**Issue by xingguang2013** [Tencent/tdesign-vue#168]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**

After entering the project name and description, an error is reported

❗错误：下载模板失败
❗错误信息： Error: 'git clone' failed with status 128

**Additional context**

**Comment by uyarn** [comment]
Please execute `td-starter -v` to show me ur CLI version.
By the way, from now on, please open the issue which is related to CLI and Starter in 
https://github.com/Tencent/tdesign-vue-starter or https://github.com/Tencent/tdesign-starter-cli

**Comment by xingguang2013** [comment]
![image](https://user-images.githubusercontent.com/3281216/148499618-ce8fbb81-2879-48ae-ad3d-aac7fc8cf5bf.png)

execute `td-starter -v`, the version is `v0.0.2`

Do you mean that I need to open this question in both of the https://github.com/Tencent/tdesign-vue-starter and https://github.com/Tencent/tdesign-starter-cli ？

**Comment by uyarn** [comment]
please upgrade the CLI to version 0.0.5 :) 
no I mean any one of them is more suitable since the issues of this repo is about the components self rather than CLI.
