### ISSUE TITLE
[Upload 上传] 上传组件的file-flow模式加下载或查看

### ISSUE THREAD

**Issue by renjiali666** [Tencent/tdesign-vue#1686]
### 这个功能解决了什么问题

上传成了，无法查看

### 你建议的方案是什么

新加个文件数组，存已经上传的区分是上传还是没上传，上传的通过url可以下载或者查看

**Comment by chaishi** [comment]
文件名称可以点击查看

`fileListDisplay `可以 自定义列表，需要更多复杂功能也可以自己添加
