### ISSUE TITLE
[table] t-enhanced-table的row-edit功能失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1689]
### tdesign-vue 版本

0.49.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-b4umwv?file=/src/demo.vue

### 重现步骤

使用t-table时，row-edit 正常， 但t-enhanced-table不行

### 期望结果

希望t-enhanced-table也能支持row-edit功能

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1702
