### ISSUE TITLE
[textarea] 多行文本的 status 属性没有接收 default 值

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1692]
### tdesign-vue 版本

tdesign-vue 0.49.2

### 重现链接

无

### 重现步骤

使用 Textarea 组件，并为 `status` 属性传入 `"default"` 值。

### 期望结果

按照 API 文档， `status` 属性的可选项为：`"default"`/`"success"`/`"warning"`/`"error"` 。其中，`"default"` 表示默认状态，应当是能正常接收的属性。

### 实际结果

在开发环境中， `status` 属性传入 `"default"` 值会导致报错。

查看源代码后发现， `src/textarea/props.ts` 中的 `status` 属性类型声明，`validator` 的代码为：

```
return ['success', 'warning', 'error'].includes(val);
```

也就是 `"default"` 值不在有效范围内，会导致类型检查报错。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

**Comment by uyarn** [comment]
fixed 0.49.3
