### ISSUE TITLE
下载不了了是什么原因啊？？？

### ISSUE THREAD

**Issue by 1557812300** [Tencent/tdesign-vue#1695]
### tdesign-vue 版本

最新

### 重现链接

https://tdesign.tencent.com/starter/docs/vue/get-started

### 重现步骤

npm i tdesign-starter-cli -g安装报错

PS F:\My-space> npm i tdesign-starter-cli -g
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!

### 期望结果

给与解释或者解决

### Node版本

V16.5.0

**Comment by uyarn** [comment]
如果还有问题再打开这个issue
