### ISSUE TITLE
[tabs] 使用 list 定义的 Tabs 删除选项卡时，remove方法会不断调用 

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1696]
### tdesign-vue 版本

0.49.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-ubjnl5?file=/src/demo.vue

### 重现步骤

参考链接，使用t-tab-panel 方式， 删除选项卡时，只会触发一次。 而使用list方式定义的tabs， 删除选项卡时，remove方法会不停调用，知道报错。
<img width="736" alt="image" src="https://user-images.githubusercontent.com/13745660/198539846-e3c7364f-f6b7-478a-b07f-d2867ea850f7.png">

### 期望结果

希望使用list定义的tabs删除选项卡时， remove方法能正常只掉用一次。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.2.2

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
