### ISSUE TITLE
[tree] value-mode="all" 模式下节点值错误

### ISSUE THREAD

**Issue by printfCYQ** [Tencent/tdesign-vue#1701]
### tdesign-vue 版本

0.49.0

### 重现步骤

![Kapture 2022-10-30 at 15 06 06](https://user-images.githubusercontent.com/44568105/198866735-b9665a46-9731-4346-ad33-105a81489920.gif)

### 期望结果

在子节点不是全选状态下，也能获取父节点的值

### 框架版本

vue(2.6.0)

### 浏览器版本

firefox(106.0.1)

### 系统版本

MacOS(12.6)

### Node版本

17.4.0

**Comment by TabSpace** [comment]
按原本需求，半选节点是不计入选中态的。
@chaishi 确认下这个逻辑。
可以通过 getItem 获取节点属性，来筛选半选节点。

**Comment by printfCYQ** [comment]
> 按原本需求，半选节点是不计入选中态的。
> @chaishi 确认下这个逻辑。
> 可以通过 getItem 获取节点属性，来筛选半选节点。
