### ISSUE TITLE
[Select] 希望选项值支持布尔类型

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1708]
### 这个功能解决了什么问题

`Select` 组件目前支持的输入值类型为 `String` / `Number` / `Object` / `Array` ，但在实际应用中，可能会出现布尔类型的选项值。

参考以下示例页面：

[https://codesandbox.io/s/tdesign-vue-demo-forked-q10th0?file=/src/demo.vue](https://codesandbox.io/s/tdesign-vue-demo-forked-q10th0?file=/src/demo.vue)

这个页面允许用户自定义查询条件，去查出匹配的数据。其中 `status` 字段是布尔类型的。当这个字段作为查询条件使用，允许用户自行操作时，很有可能会使用 `Select` 组件而非 `Switch` 组件。

因为对于用户查询条件来说，实际上是三态的： `true` 、 `false` ，以及 `undefined` （或空字符串），其中最后一个表示用户未设置该字段的查询条件。单纯使用  `Switch` 组件无法完成三态的需求。

但目前为 `Select` 组件设置布尔类型的选项值，会导致控制台报错。

### 你建议的方案是什么

希望 `Select` 组件的 `value`/`modelValue` 属性，除了支持原有的数据类型外，还能支持布尔类型 `Boolean` 。

**Comment by uyarn** [comment]
为什么不用radio吧？https://codesandbox.io/s/tdesign-vue-demo-forked-hexxku?file=/src/demo.vue

**Comment by sagittarius-rev** [comment]
> 为什么不用radio？https://codesandbox.io/s/tdesign-vue-demo-forked-hexxku?file=/src/demo.vue

因为在我们的使用场景中，查询条件是基于数据自动生成的，而不是固定手写的。用 `Radio` 需要在原有的 `true` 、`false` 两个值之外再附加一个选项，而 `Select` 如果支持布尔类型的值，配合其清除功能，就可以简单实现三态。

此外还有组件占位大小、表格内单元格编辑等其他方面的考虑。

**Comment by uyarn** [comment]
这周会带上这个改动支持

**Comment by xiaosansiji** [comment]
Implemented in 1.2.6
