### ISSUE TITLE
[t-date-range-picker] 交互体验

### ISSUE THREAD

**Issue by ifAandBisC** [Tencent/tdesign-vue#1718]
### 这个功能解决了什么问题

日期时间选择需要跳转操作完成，希望集中到一屏内

### 你建议的方案是什么

![企业微信截图_3fa705bc-2fb2-48aa-bb77-82bfa9f228b4](https://user-images.githubusercontent.com/29983006/199183949-3f5316f2-fc9c-4e45-8426-1234544bcfdb.png)

**Comment by zhang20084** [comment]
一般的日期控件，支持手动修改的话，填写完新的日期后，鼠标随便点一下。值就会改掉，你们的日期控件竟然一定要回车才行。

**Comment by ccccpj** [comment]
该问题已在 0.43.0 版本得到优化，相关 PR https://github.com/Tencent/tdesign-vue/pull/1018，建议升级至最新版本
