### ISSUE TITLE
[input-number] theme 设置为 column 时 autoWidth 无效

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1720]
### tdesign-vue 版本

tdesign-vue 0.49.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-4u7r9t?file=/src/demo.vue

### 重现步骤

使用 `InputNumber` 组件，将 `theme` 属性的值设为 `"column"` ，即增减按钮出现在输入框右侧。

同时设置 `autoWidth` 属性为 `true` ，希望输入时能自动调整组件宽度。

### 期望结果

进行数值输入时，输入框自动调整组件宽度。

### 实际结果

 `theme` 值为 `"column"` 时， `autoWidth` 参数无效，输入时输入框宽度不会变化，超出部分会被截断。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

当 `theme` 值为 `"normal"` 或 `"row"` 时， `autoWidth` 属性表现正常。

vue-next 版本也有相同问题。

react 版本会出另外一个问题，单独提交 issue 。

**Comment by yaogengzhu** [comment]
https://github.com/Tencent/tdesign-common/blob/87d99048b78174699548bec58dca5c920464300c/style/web/components/input-number/_index.less#L61

这里的auto 被覆盖了！可以尝试在

    &.@{prefix}-is-controls-right {
      min-width: 88px;
      width: auto;
    }

避免!important

我尝试修改下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/969

**Comment by uyarn** [comment]
fixed in 0.49.4
