### ISSUE TITLE
tdesign-site-components这个仓库会开源嘛

### ISSUE THREAD

**Issue by fengyuchenglun** [Tencent/tdesign-vue#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaishi** [comment]
这个是官网相关的 webcomponents 组件，目前有收到网上的反馈说官网比较卡顿，说性能有问题。

性能有问题分三类：一类是 webcomponents，二类是 Vue/React 组件，三类则是官网本身。

目前，我们在看具体是哪一类引起的。

如果最后确定是因为 webcomponents，则不建议使用。

再有，webcomponents 属于做官网的衍生品，没有规范过，不能保证后面变更不大。

如果后期，业务侧对 webcomponents 有需求，且我们的人力可以支持，再考虑开源的事情。

**Comment by fengyuchenglun** [comment]
> 这个是官网相关的 webcomponents 组件，目前有收到网上的反馈说官网比较卡顿，说性能有问题。
> 
> 性能有问题分三类：一类是 webcomponents，二类是 Vue/React 组件，三类则是官网本身。
> 
> 目前，我们在看具体是哪一类引起的。如果最后确定是因为 webcomponents，则不建议使用。
> 
> 再有，webcomponents 属于做官网的衍生品，没有规范过，不能保证后面变更不大。
> 
> 如果后期，业务侧对 webcomponents 有需求，且我们的人力可以支持，再考虑开源的事情。

嗯 好的 谢谢 虽然webcomponents 还有问题 不过希望至少能够将源码能打包到npm中，这样至少大家能够npm中源码，提供一些建议

**Comment by HQ-Lin** [comment]
近期没有开源的计划，因为这个仓库主要是为官网以及各个框架文档页定制通用的 `webcomponents` 组件，甚至还会涉及一些埋点相关的代码，可以理解为只为官网服务的纯业务仓库，开源共建的意义不大。

**Comment by fengyuchenglun** [comment]
> 近期没有开源的计划，因为这个仓库主要是为官网以及各个框架文档页定制通用的 `webcomponents` 组件，甚至还会涉及一些埋点相关的代码，可以理解为只为官网服务的纯业务仓库，开源共建的意义不大。

ok  谢谢
