### ISSUE TITLE
[Upload] 是否可将组件依赖的 `UploadFile` 类型导出呢

### ISSUE THREAD

**Issue by skytt** [Tencent/tdesign-vue#1743]
### 这个功能解决了什么问题

开发的时候发现上传组件的 value 是 `UploadFile` 类型组织的数据，但是这个类型只有组件内部使用，没有导出  用起来有点不方便

### 你建议的方案是什么

希望添加 `UploadFile ` 类型导出

https://tdesign.tencent.com/vue/components/upload?tab=api#uploadfile

**Comment by chaishi** [comment]
可以，应该是 export 漏了，一般默认导出全部

https://github.com/Tencent/tdesign-vue/blob/develop/src/upload/type.ts#L265
不过当前，你可以从这个文件 import，node_modules 里面应该存在，搜一下。

**Comment by uyarn** [comment]
fixed in 0.49.4
