### ISSUE TITLE
[table] 通过push增加表格数据data，在选中时select-change方法中获取不到selectedRowData

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1747]
### tdesign-vue 版本

0.49.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-91hko2?file=/src/demo.vue

### 重现步骤

如示例中，通过push新增的表格数据，在选中该数据时，select-change方法中获取不到selectedRowData信息。
<img width="713" alt="image" src="https://user-images.githubusercontent.com/13745660/200106751-a7629a8a-38c8-4fe7-a033-0df49f028509.png">

### 期望结果

能够获取到selectedRowData数据

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
https://github.com/vuejs/core/issues/2116
Vue3 有个特殊的 watch 方法，我试试看处理
