### ISSUE TITLE
Table，本地数据分页，选择每页数量，样式问题

### ISSUE THREAD

**Issue by aivsok** [Tencent/tdesign-vue#175]
![image](https://user-images.githubusercontent.com/73453068/148322975-f1ed0394-71d7-4460-b89a-2c8c17fab7cc.png)

**Comment by uyarn** [comment]
这是codesandbox自带的样式覆盖了 不是组件问题。

**Comment by uyarn** [comment]
![image](https://user-images.githubusercontent.com/26377630/148358086-91567166-6267-4570-9148-740c07dc5a59.png)

**Comment by uyarn** [comment]
已修复codesandbox中样式不一致的问题 
https://codesandbox.io/s/9drxg?file=/src/demo.vue
