### ISSUE TITLE
[Form] FormRule TS 类型与实现不一致，缺少whitespace 属性（非官方文档公开的特性，内部讨论中）

### ISSUE THREAD

**Issue by daizhan** [Tencent/tdesign-vue#1754]
### tdesign-vue 版本

latest

### 重现链接

https://github.com/Tencent/tdesign-vue/blob/develop/src/form/type.ts#L179

### 重现步骤

类型对不上，但功能正常

TS 类型：https://github.com/Tencent/tdesign-vue/blob/develop/src/form/type.ts#L179
API 文档：https://tdesign.tencent.com/vue/components/form?tab=api#formrule
![image](https://user-images.githubusercontent.com/5318547/200468545-e174e03c-ff97-4d7b-b4a0-840eb010dedf.png)

### 期望结果

添加whitespace 属性声明，避免误报

**Comment by uyarn** [comment]
fixed in 0.49.4
