### ISSUE TITLE
[table] 选项卡来回切换时，使用虚拟滚动，滚动的高度会相互影响，导致出现空白

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#1759]
### tdesign-vue 版本

0.47.0

### 重现步骤

选项卡来回切换时，使用虚拟滚动，滚动的高度会相互影响，导致出现空白

### 期望结果

选项卡来回切换时，是否有对 Table 进行重新布局的方法

### 实际结果

选项卡来回切换时，能增加对 Table 进行重新布局的方法

**Comment by chaishi** [comment]
辛苦提供可复现问题的链接

**Comment by chaishi** [comment]
新版本的 Table 已经使用新的虚拟滚动，没有这个问题了
