### ISSUE TITLE
t-form-item上设置requiredMark属性不生效

### ISSUE THREAD

**Issue by yc910920** [Tencent/tdesign-vue#176]
bug表现：
t-form-item上设置requiredMark属性不生效，没有出现必填按钮，与文档描述不一致

**Comment by xiaosansiji** [comment]
codesanbox 例子：https://codesandbox.io/s/tdesign-vue-demo-forked-yjuo5
![image](https://user-images.githubusercontent.com/7600149/148512181-da27f731-c9f2-4b3c-a394-b82aa8207abe.png)
现有版本看起来是支持的，你可以提供下其他详细信息不？

**Comment by chaishi** [comment]
长时间收不到回复，且缺陷无法复现，issue 关闭

后面有需要，可以再打开
