### ISSUE TITLE
[table] 列宽拖拽功能，列配置的columns.resizable=false和resize.minWidth, resize.maxWidth不能限制住列宽

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1765]
### tdesign-vue 版本

0.49.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-td3sd8?file=/src/demo.vue

### 重现步骤

目前列配置的columns.resizable=false和resize.minWidth, resize.maxWidth并不能限制住该列列宽。
目前只有拖动该列右边线时，计算限制了该列宽，拖动该列左边线时依旧会造成列宽改变。

https://user-images.githubusercontent.com/13745660/200980232-ee6cc277-3cd3-4ef3-8fb3-5078876b3ca1.mov

### 期望结果

希望有方案可以限制某列宽度， minWidth和maxWidth可以限制列宽范围

### 实际结果

目前拖动该列左边线会造成列宽变动。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
如果都已经 columns.resizable=false 时，为什么还要 resize.maxWidth ？

resizable = false，意味着禁用调整宽度特性，此时设置 resize.maxWidth 没有意义

**Comment by LoopZhou** [comment]
指设置了columns.resizable=false 不调整当前列列宽 或者 设置了resize.maxWidth， resize.minWidth限制拖动范围两种情况。
<img width="361" alt="image" src="https://user-images.githubusercontent.com/13745660/200982009-dbedc4ce-36fd-425d-83f8-842700358ceb.png">

**Comment by chaishi** [comment]
columns.resizable=false 是指不能通过当前列调整宽度，而非 「不调整当前列列宽」

**Comment by ZTao-z** [comment]
columns.resizable=false 指当前列不支持调整列宽;

**Comment by chaishi** [comment]
`columns.resizable=false` resolved in https://github.com/Tencent/tdesign-vue/pull/2130

**Comment by chaishi** [comment]
columns.resizable=false 和 resize.minWidth 已经支持调整的当前列宽度限制，至于受影响的其他列暂未支持。后续单独提 issue 支持
