### ISSUE TITLE
[form] form 表单中 使用 t-input-number 、并使用:rules 校验, 对min: 0 跳过了校验

### ISSUE THREAD

**Issue by yaogengzhu** [Tencent/tdesign-vue#1769]
### tdesign-vue 版本

0.49.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-wryz7p?file=/src/demo.vue

### 期望结果

能正确校验数字0

### 实际结果

不行

### 框架版本

vue.2x

**Comment by uyarn** [comment]
fixed 0.49.6
