### ISSUE TITLE
[TreeSelect] API 中有 readonly 属性、但未实现此功能 

### ISSUE THREAD

**Issue by yaogengzhu** [Tencent/tdesign-vue#1782]
### tdesign-vue 版本

0.49.6

### 重现链接
https://tdesign.tencent.com/vue/components/tree-select

_No response_

### 重现步骤
<img width="958" alt="image" src="https://user-images.githubusercontent.com/42566669/201453565-87e22e08-4dd0-46c4-92f4-bc99742396e4.png">

_No response_

**Comment by xiaosansiji** [comment]
已在 0.50.0 版本修复
