### ISSUE TITLE
[Progress] percentage值为100会忽略status设置的值

### ISSUE THREAD

**Issue by xiaoyaojones** [Tencent/tdesign-vue#1789]
### tdesign-vue 版本

0.47.0~0.49.6

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-z6huxz?file=/src/demo.vue

### 重现步骤

查看codesandbox重现链接

### 期望结果

基于status设置的值来展示风格

### 实际结果

t-progress进度条只要percentage值为100，则会忽略status设置的值，比如error、warning

### 框架版本

2.6.14

### 浏览器版本

chrome 版本 106.0.5249.119（正式版本） (arm64)

### 系统版本

MacOS(12.6)

### Node版本

v14.20.1

### 补充说明

业务场景设定驳回申请等都结束该流程(也就是进度条100%)，期望使用error色给用户因驳回而结束流程的直接反馈

**Comment by chaishi** [comment]
组件 + 标题，仔细描述下，不要偷懒

<img width="404" alt="image" src="https://user-images.githubusercontent.com/11605702/201820701-9e965b15-741d-425f-8c7e-a7512107726e.png">

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
