### ISSUE TITLE
[textarea]多行文本的 autofocus 无效， status 为 default 时报错

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1790]
### tdesign-vue 版本

tdesign-vue 0.49.6

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-5vgy0f?file=/src/demo.vue

### 重现步骤

在页面上放置两个多行文本输入组件，第一个设置 `:autofocus="true"` ，第二个设置 `status="default"` 。

### 期望结果

1. 按 API 文档， `autofocus` 属性用于自动聚焦，值为 `true` 时应当自动获得焦点。
2. `status` 值为 `"default"` ，代表是默认状态，是 API 文档中说明的有效值。

### 实际结果

1. 输入框没有自动聚焦。
2. `status` 值为 `"default"` 会导致控制台报错。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

多行文本 `status` 值为 `"default"` 的问题，按照版本变更记录， 0.49.3 已修正此问题。但实际上， 0.49.6 版本依然会报错。

**Comment by chaishi** [comment]
`props` 确实漏了 `default`，我们补一下。
当前可以设置 `status=undefined` 达到 default 同样的效果。

<img width="507" alt="image" src="https://user-images.githubusercontent.com/11605702/201809599-d74b78a7-02bc-4c40-856c-9a6e0cccf489.png">

**Comment by chaishi** [comment]
`autofocus` 是直接透传到 html 的原生属性，我看官网有显示 autofocus。试了下效果，好像是有点遗失，需要再确认下。

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/11605702/201810025-5ec76958-933a-400a-b686-9870c85e8b3b.png">

**Comment by sagittarius-rev** [comment]
> `props` 确实漏了 `default`，我们补一下。 当前可以设置 `status=undefined` 达到 default 同样的效果。
> 
> <img alt="image" width="507" src="https://user-images.githubusercontent.com/11605702/201809599-d74b78a7-02bc-4c40-856c-9a6e0cccf489.png">

Textarea 目前我们的项目并不会直接给它设置 `status` 属性，都是间接使用的。主要包括：1. 被包含在 FormItem 中；2. 被包含在表格可编辑单元格中。这两种情况，外层组件都会给它传递值为 `"default"` 的 `status` 属性，从而导致报错。
