### ISSUE TITLE
[TagInput] 超出换行有bug，无法正常工作

### ISSUE THREAD

**Issue by skytt** [Tencent/tdesign-vue#1792]
### tdesign-vue 版本

0.49.6

### 重现链接

https://tdesign.tencent.com/vue/components/tag-input#%E6%A0%87%E7%AD%BE%E6%95%B0%E9%87%8F%E8%B6%85%E5%87%BA%E7%9A%84%E8%BE%93%E5%85%A5%E6%A1%86

### 重现步骤

官网demo可复现

### 期望结果

正常换行

### 实际结果

无法换行

### 补充说明

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/7420660/201862646-0cea5175-1c47-441a-a7ff-1ca8a2ed85de.png">

**Comment by chaishi** [comment]
Resolved in https://github.com/Tencent/tdesign-vue/pull/1793

**Comment by xiaosansiji** [comment]
已在 0.50.0 版本修复
