### ISSUE TITLE
[select] 下拉选择多选，选中项目较多时，没有折行显示

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1796]
### tdesign-vue 版本

tdesign-vue 0.49.6

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-mtve6g?file=/src/demo.vue

### 重现步骤

使用下拉多选组件，并选中较多的选项。

### 期望结果

当选中项较多时，并且组件宽度不足，应当自动折行显示。

### 实际结果

选中项没有折行显示，所有项目显示在同一行内，导致选中项与 `Select` 组件的 展开/收起 图标重叠了。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

检查后发现，之前的版本并没有这个问题。此问题是 0.49.3 版本才开始出现的。

**Comment by yaogengzhu** [comment]
似乎提供了另外的解决方案： 
可参考 minCollapsedNum 这个props属性
https://codesandbox.io/s/tdesign-vue-demo-forked-lgnmjh

**Comment by skytt** [comment]
当前版本换行有缺陷（#1792 ），今天刚合主干，下个版本应该就好了

**Comment by xiaosansiji** [comment]
已在 0.50.0 版本修复
