### ISSUE TITLE
[Table表格]可展开和收起的表格表头背景色异常

### ISSUE THREAD

**Issue by hmilyld** [Tencent/tdesign-vue#1800]
### 重现链接
https://codesandbox.io/s/3nto6q?file=/src/demo.vue

### 重现步骤
1、收起所有展开的行
2、只展开最后一行
3、收起最后一行

### 期望结果
表头背景色透明

### 实际结果
表头在收起所有行，只展开最后一行的情况色，表头会出现背景色

| Environment | Info |
|---|---|
| 相关版本 | 0.49.6 |
| 框架版本 / 基础库版本 | Vue(2.6.11) |
| 系统、浏览器 | Edge |
| Node版本 |  |

**Comment by chaishi** [comment]
正式版，已修复。issue 关闭

如果还有疑问，可以 reopen
