### ISSUE TITLE
[select] multiple 属性动态变化时，选项消失

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1802]
### tdesign-vue 版本

tdesign-vue 0.49.6

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-yde3qu?file=/src/demo.vue

### 重现步骤

使用 `Select` 组件，将 `multiple` （是否多选）属性设置为动态可变的。

### 期望结果

当 `multiple` 值变化时，组件应当正常响应。

### 实际结果

1. 当 `multiple` 值变化时（例如从 `false` 变成 `true` ）， `Select` 组件的选项会消失不见。

2. 当下拉组件设置为多选时，若输入的值不是数组，会导致代码报错。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

此问题使用可变化的 `key` 就能解决，即根据是否为多选，使用不同的 `key` 值，让 vue 重新渲染组件。

但使用过程中很容易忽略此问题，出现 bug 后第一次也较难定位问题所在。建议官方内置相关的判断处理。

**此外，若下拉组件为多选，组件内部应当检测输入值是否是数组，不是数组的情况应当按照输入无效进行处理，而不是报错。**

**Comment by skytt** [comment]
这个应该要 select-input 组件上解决，切换 `multiple` 的值以后，popup 点不出来了
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/7420660/202083770-eb10f219-b9b4-4d32-84dc-3e998188e0f3.png">

**Comment by uyarn** [comment]
这个是在什么场景要这么搞啊.. 动态表单还是那种代码平台吗？

**Comment by sagittarius-rev** [comment]
> 这个是在什么场景要这么搞啊.. 动态表单还是那种代码平台吗？

是的，动态表单 + 低代码平台。

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
