### ISSUE TITLE
[Upload] 支持配置模拟进度间隔时间，用于设置小文件上传进度触发频次

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1807]
### 这个功能解决了什么问题

适应不同文件大小的上传进度

### 你建议的方案是什么

文件上传 `xhr` 一般只会在大文件上传时才能拿到少量的上传进度，小文件上传只有 0 和 100，不利于 UI 呈现，因而新增了模拟进度的概念。

新增 API `mockProgressDuration`，模拟进度间隔时间。
可以通过配置不同的「模拟进度间隔时间」来实现不同的进度呈现。
如果是小文件，建议设置 `100` 毫秒以下。
如果是中大文件，建议设置 `300` 毫秒以上。

默认为 `300` 毫秒

**Comment by xiaosansiji** [comment]
已在 1.0.3 实现
