### ISSUE TITLE
[time-picker] 时间选择未接收 status 与 tips 参数，以及若干交互问题

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1808]
### tdesign-vue 版本

tdesign-vue 0.49.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-2kel7v?file=/src/demo.vue

### 重现步骤

在可编辑的表格内使用 `DatePicker` 与 `TimePicker` 组件，启用组件的 clearable ，进入行编辑状态。各个项均设为必填，并且初始值均为空。

1. 不输入任何值，直接点击行编辑的保存按钮。
2. 在 `TimePicker` 中选择一个时间，点击确定按钮。
3. 然后再次点击已经有值的 `TimePicker` 组件，重新打开时间选择 popup ，此时点击 `TimePicker` 的清除按钮图标。
4. 清除 `TimePicker` 组件的值之后，单击该组件重新打开时间选择 popup ，然后马上点击弹出界面的确定按钮。

### 期望结果

1. 设置必填的情况下，当输入值为空，应当显示错误提示信息，并将输入框标红。
2. `TimePicker` 已经有值的情况下，打开时间选择，然后点击清除按钮，应当清除之前输入的值，并自动关闭弹出层。
3. 在 `TimePicker` 的“确定”按钮处于可用状态时，应当将选中的值回填到输入框。

### 实际结果

1. `DatePicker` 能正常显示错误信息，并将输入框标红，但 `TimePicker` 不行。
2. `TimePicker` 已经有值的情况下，打开时间选择，然后点击清除按钮，大概率会看到清除图标与时间选择图标的闪烁切换，值被清空后又自动重新填入新值，并且弹出层不关闭。
3. `TimePicker` 若没有值，点击打开弹出层，此时“确定”按钮已经处于可用状态（没有被禁用），不选择时间的情况下直接点击确定按钮，弹出层会关闭，但没有任何值被回填。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

1. `TimePicker` 没有处理输入参数 `status` 与 `tips` ，而且 API 文档也未列出这 2 个参数。这会导致各个输入组件的行为不一致，建议改进。
2. 如果不打开 `TimePicker` 的弹出层，直接点击清除按钮，就不会出现图标闪烁与无法清除输入值的问题。
3. 对比 `DatePicker` ，在使用日期时间选择的情况下，没有值的时候直接打开弹出层，确认按钮初始时是禁用状态，无法点击。建议 `TimePicker` 的行为也进行相同处理。

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
