### ISSUE TITLE
[input-number] 数字输入框宽度设置为 100% 时，右侧按钮会超出有效区域

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1810]
### tdesign-vue 版本

tdesign-vue 0.50.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-2hz6nu?file=/src/demo.vue

### 重现步骤

将数字输入框设定为宽度 100% ，使用默认的风格，即加减按钮显示在两侧。容器设置超出隐藏样式。

### 期望结果

输入框及加减按钮应正常显示。

### 实际结果

右侧的按钮会超出容器的范围，在容器超出隐藏的控制下，按钮显示不完整。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

### 补充说明

数字输入框的宽度需要设置为 `calc(100% - 8px)` ，右侧按钮才能完整显示。

查看相关样式后发现，元素左右各带有 32px 的内边距（ padding ）。但左右按钮的宽度已经是 32 像素，并且按钮与输入框之间还有 4 像素的距离，导致整体宽度会多出 8 像素，于是右侧的按钮就超出了容器。

**Comment by chaishi** [comment]
单独使用 `InputNumber` 组件，设置 `width: 100%` 没有问题
<img width="649" alt="image" src="https://user-images.githubusercontent.com/11605702/202848586-3f06aa64-3417-4c93-8905-7783ef7b6484.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1019

**Comment by sagittarius-rev** [comment]
> 单独使用 `InputNumber` 组件，设置 `width: 100%` 没有问题
> 
> <img alt="image" width="649" src="https://user-images.githubusercontent.com/11605702/202848586-3f06aa64-3417-4c93-8905-7783ef7b6484.png">

普通容器也会有超出宽度的问题，只是没有使用 `overflow: hidden` 样式的情况下，不容易看出来。

示例代码已更新，加入了其他元素作为对照。

1. 使用普通 div ，限定宽度，设置 `overflow: hidden` ，右边按钮一样会显示不全。
2. 使用普通 div ，限定宽度，不设置超出隐藏样式。在容器内多放置一个 `Input` 输入组件作为对比，可以看到上下两个组件的宽度不一致。

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
