### ISSUE TITLE
数字删除一个后，数据类型会有Number变成String

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#1815]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/31959442/202996611-a30ec3c2-e53b-42d2-8068-99e4b3288a6f.png">
![image](https://user-images.githubusercontent.com/31959442/202996664-fc01e289-1a51-471d-a7f7-0b5e3a9e38ba.png)

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
