### ISSUE TITLE
电脑safari中gutter上下间距失效

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#1816]
如题所述，猜测是row-gap在safari中不兼容
<img width="978" alt="image" src="https://user-images.githubusercontent.com/31959442/203004707-a870ceae-41c9-4930-9e47-25905c51519f.png">

**Comment by honkinglin** [comment]
https://caniuse.com/mdn-css_properties_row-gap_flex_context
flex 中的 row-gap 属性需要safari 14.1 版本以上，确认下浏览器版本
