### ISSUE TITLE
[Menu] 当title较长时，右侧展开箭头变小

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1817]
### tdesign-vue 版本

0.50.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-r8gjnu?file=/src/demo.vue

### 重现步骤

<img width="255" alt="image" src="https://user-images.githubusercontent.com/13745660/203012402-b78fa408-d426-49c2-9931-8fe367b29136.png">
当title配置得越长， 右侧箭头变得越小

### 期望结果

希望右侧箭头大小统一

### 实际结果

当title配置得越长， 右侧箭头变得越小

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by xiaosansiji** [comment]
已在 0.50.1 版本修复
