### ISSUE TITLE
[Dialog] config-provider中配置的全局dialog属性在插件式$dialog中未起效 

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1823]
### tdesign-vue 版本

0.50.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-1gw1d7?file=/src/demo.vue

### 重现步骤

t-config-provider中配置的全局dialog属性在插件式$dialog中未起效 

### 期望结果

希望t-config-provider中配置的全局dialog属性可以直接在$dialog中起效，不用重复定义一次

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

## IssueShoot

- 预估时长: 2
- 期望完成时间: 2022-12-15
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提MR并通过验收无误
- 备注: 最终激励以实际提交 pull request 并合并为准

**Comment by uyarn** [comment]
support in 1.2.0
