### ISSUE TITLE
[ImageViewer] 鼠标滚轮和图片放缩的结合有点反直觉

### ISSUE THREAD

**Issue by Barry-Flynn** [Tencent/tdesign-vue#1826]
### 这个功能解决了什么问题

ImageViewer 图片预览时，
标滚轮向上，但预览的图片却缩小；
标滚轮向下，但预览的图片却放大；

这似乎有点反直觉，仅代表我自己来说，给了我不好的体验。

### 你建议的方案是什么

或许是多年的用户习惯，建议修改滚轮操作与图片放缩的关系，或者增加配置项，使前端开发人员自由选择鼠标滚轮与图片放大缩小的效果

**Comment by chaishi** [comment]
上文描述 上小 下大，刚好相反，导致了错误的理解。

当前表现是：上大、下小。

**Comment by chaishi** [comment]
我这边也是习惯，上小，下大。

**Comment by Barry-Flynn** [comment]
> 上文描述 上小 下大，刚好相反，导致了错误的理解。
> 
> 当前表现是：上大、下小。

可能表达的有点歧义，我对于图片预览组件的直觉是：鼠标滚轮往前推，图片应该放大；鼠标滚轮往回拨，图片应该缩小。

目前的组件效果是相反的，是因为国际上的用户习惯是这样的吗？真的感觉非常别扭

如果变成[element-ui](https://element-plus.gitee.io/zh-CN/component/image.html#%E5%9B%BE%E7%89%87%E9%A2%84%E8%A7%88)那样的图片预览效果就好了，很符合鼠标滚轮控制缩放的直觉

**Comment by Barry-Flynn** [comment]
> 我这边也是习惯，上小，下大。

如果是当前的TDesign “**鼠标滚轮往前推，图片缩小；鼠标滚轮往回拨，图片放大**” 的效果，其实仔细想一想我也能够理解，无非就是把整张图片当成具有空间透视的墙呗：

- 鼠标往前推，是让图片墙远离我们，所以图片看起来小了
- 鼠标往回拨，是让图片墙靠近我们，所以图片看起来大了

但这样确实不太符合一些人的直觉，因为很多人（包括我）直觉都是将鼠标滚轮的**上下**与图片的**大小**绑定在一起的，而不是鼠标的**前后**与图片的**远近**

**Comment by Barry-Flynn** [comment]
https://github.com/Tencent/tdesign-vue/issues/2825

https://github.com/Tencent/tdesign-vue-next/pull/3738

optimized 1.8.3

**Comment by Barry-Flynn** [comment]
optimized 1.8.3
