### ISSUE TITLE
[tabs选项卡] 当选项卡数量超出最大宽度时，如果默认给的初始值的选项卡在收缩右箭头后，选项卡无法自动滚动到选项卡

### ISSUE THREAD

**Issue by taovicky** [Tencent/tdesign-vue#1828]
### tdesign-vue 版本

最新版

### 重现步骤

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/24447967/203488703-ced84655-e276-4ccc-a893-a8a9f8cd31d0.png">
如图，如果我给的初始选项卡的值是选项卡18，初次打开这个页面时，tab选项卡，无法滚动定位到选项卡18显示，而需要用户点击后显示，这与正常的交互逻辑不匹配，我看ant-design是可以自动滚动到初始值的

### 框架版本

Vue2.26

**Comment by xiaosansiji** [comment]
已在 1.0.2 版本修复
