### ISSUE TITLE
[Menu] menu组件当菜单项为异步加载时样式异常

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#184]
**Describe Framework**

tdesign-vue

**Describe the bug**

https://codesandbox.io/s/tdesign-vue-demo-forked-s33d5?file=/src/demo.vue
![image](https://user-images.githubusercontent.com/11243798/148381846-635b7fad-9683-41ed-95a6-327752aab141.png)

![image](https://user-images.githubusercontent.com/11243798/148381825-77544a59-c979-4793-8d4f-0e9010f98492.png)

**Comment by YFAnt** [comment]
![image](https://user-images.githubusercontent.com/46584057/148472697-3d671dca-3b4e-45b5-8977-07e56f08ffbf.png)
@LeeJim  这个地方注释掉就好了， 这个地方不能让他自己撑开么

**Comment by LeeJim** [comment]
我研究一下。

**Comment by cong-min** [comment]
up

**Comment by cong-min** [comment]
0.44.1 尚未解决
