### ISSUE TITLE
[SelectInput] 多标签换行间距问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1843]
### tdesign-vue 版本

0.50.1

### 重现步骤

<img width="907" alt="image" src="https://user-images.githubusercontent.com/11605702/203799787-55845903-0fae-4cc5-915c-403a8e1affcb.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1044

**Comment by uyarn** [comment]
fixed 0.51.1
