### ISSUE TITLE
表格校验存在问题

### ISSUE THREAD

**Issue by KingSunP** [Tencent/tdesign-vue#1846]
### tdesign-vue 版本

0.49.0

### 重现链接

https://stackblitz.com/edit/angular-whqqab?file=src%2Fdemo.vue,src%2Findex.css

### 重现步骤

可编辑表格那个demo的基础上，添加一个校验全部的按钮，无法全局校验成功，只能校验行。
![334f2c4c63b532c254e69460b1086e5](https://user-images.githubusercontent.com/48407347/203923137-cea907ae-0d7d-4eaa-9c6a-d12aad05b859.jpg)
![7bc44d36a7b846336a6e36143d604bc](https://user-images.githubusercontent.com/48407347/203923150-e18e5003-e019-4ba6-8150-8179de11ff5c.jpg)
![1c6b51ece30c687ce35488f0f7952cd](https://user-images.githubusercontent.com/48407347/203923156-7b3d8bf8-27cd-47a3-a775-79de9a9ab639.jpg)

### 期望结果

期望可以进行表格校验

### 实际结果

无法进行表格全局的校验

### 框架版本

Vue2.6.14

**Comment by chaishi** [comment]
用法不对，这个示例代码不是「全部校验」，完全不同的功能，请使用 「可编辑行的表格」中的示例代码开发

**Comment by chaishi** [comment]
如果使用「可编辑行的表格」依旧有问题，可以留言 reopen issue

**Comment by KingSunP** [comment]
> 用法不对，这个示例代码不是「全部校验」，完全不同的功能，请使用 「可编辑行的表格」中的示例代码开发
> 
> <img alt="image" width="845" src="https://user-images.githubusercontent.com/11605702/203924956-cc5759c0-7a4e-46b7-a48d-5522aae7cf98.png">

那是表格单个单元格可编辑的时候不支持全局校验？？

**Comment by chaishi** [comment]
> 那是表格单个单元格可编辑的时候不支持全局校验？？

对，不支持。不用双问号。

单个单元格，编辑的就只是一个单元格，为何要去校验那些非输入的数据。校验存在于编辑之上，没有编辑就没有校验。

可编辑单元格、可以编辑行，重点在于 编辑，是编辑，不是校验，莫要本末倒置。

如果要校验非编辑的数据，就是纯粹的校验功能了，自己使用 form 组件的 validate 函数校验就行了。只需要传 2 个参数，一个数据，一个校验规则
