### ISSUE TITLE
[EnhancedTable] 希望树形结构支持点击行展开树节点

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1847]
### 这个功能解决了什么问题

1. 需要支持下 点击row也能展开收起  类似tree 组件 expandOnClickNode
2. @RowClick 不支持驼峰写法不知道是不是问题 @row-click 有效
3. treeExpandIcon 点击事件 不要透传到 row-click 事件

### 你建议的方案是什么

 - -

**Comment by chaishi** [comment]
不支持 `@RowClick`，事件始终保持中华线，全组件库统一为中华线

**Comment by chaishi** [comment]
> 需要支持下 点击row也能展开收起 类似tree 组件 expandOnClickNode

支持

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1915

**Comment by xiaosansiji** [comment]
已在 0.52.2 版本修复
