### ISSUE TITLE
[textarea] 使用 textarea 的 autosize 属性出现中文输入法时高度没撑开

### ISSUE THREAD

**Issue by 94dreamer** [Tencent/tdesign-vue#1852]
### tdesign-vue 版本

0.46.1

### 重现步骤

1、使用 textarea 的 autosize 属性 `:autosize="{ minRows: 1 }"`
2、正常的情况下字母和数字输入下，文本框高度会随着文本内容撑开高度。
3、但是在换行前使用中文输入法输入拼音，文本框高度不会随着文本内容撑开高度。

### 期望结果

使用中文输入法输入拼音，文本框高度也会自动撑开，而不是出现滚动条。

下图为 ant react的正确显示

<img width="389" alt="企业微信截图_930ae2a2-63cb-40fb-9d76-e8586bcca540" src="https://user-images.githubusercontent.com/15634204/204233191-a8eb9b73-68d3-4093-8537-7271f51f3feb.png">

### 实际结果

使用中文输入法输入拼音，文本框高度不会自动撑开，而是出现滚动条。
下图为出现滚动条，而不是撑开高度
<img width="555" alt="企业微信截图_c6765f14-22af-4d01-8baf-60fe36dfbe6b" src="https://user-images.githubusercontent.com/15634204/204232901-8982abc7-022f-4129-bf3b-3a180bb39d6a.png">

### 框架版本

Vue2

### Node版本

14

**Comment by ZWkang** [comment]
ref: #1900  @chaishi

**Comment by xiaosansiji** [comment]
已在 1.0.2 版本修复
