### ISSUE TITLE
[input-number] 启用 allowInputOverLimit 参数后，无法清空输入值

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1855]
### tdesign-vue 版本

tdesign-vue 0.50.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-sk8r4u?file=/src/demo.vue

### 重现步骤

使用 `InputNumber` 组件，设置 `max` 与 `min` 属性，同时设置 `allowInputOverLimit` 参数值为 `false` ，即用户输入不允许超过有效范围。

通过 `input-props` 属性给输入框设置清除按钮。输入值之后，点击清除按钮。

### 期望结果

用户若未输入数值，或者输入值之后将值清空，应当保留输入框内容为空。

### 实际结果

 `allowInputOverLimit` 参数值为 `false` ，同时设置了 `max` 属性，则用户清空输入之后，输入框会自动将 `max` 属性设置的值填回去。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

16.16.0

### 补充说明

`allowInputOverLimit` 是一个新功能，用于控制输入值是否允许超过有效范围。但目前来看，在做相关的处理判断过程中，没有考虑输入值为空的情况，导致无法实现清空操作。

只设置 `min` 属性而不设置 `max` 属性，不会出现这个问题。

**Comment by chaishi** [comment]
是没考虑到会有人 给 InputNumber 使用 清空按钮

**Comment by uyarn** [comment]
fixed 0.52.0
