### ISSUE TITLE
[tree] 希望树形组件支持虚拟滚动功能

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1859]
### 这个功能解决了什么问题

在我们的项目中，树形组件可能需要显示大量数据。当节点达到 1000 个时，组件已经会出现肉眼可见的较明显延迟，从加载数据完成到树形渲染完成至少需要 1 秒左右。

### 你建议的方案是什么

建议在树形组件中增加虚拟滚动功能，优化显示性能。

前提是树形组件支持 `maxHeight` 。现有树形组件的高度控制是由容器进行的，而为了实现虚拟滚动，树形组件应当自行控制高度限制与纵向滚动行为。

**Comment by chaishi** [comment]
开发同学最近正在开发中

**Comment by TabSpace** [comment]
已提供能力
https://github.com/Tencent/tdesign-vue/pull/2181

**Comment by uyarn** [comment]
supported in 1.2.0
