### ISSUE TITLE
[Table] 列宽调整问题。配置resizable，减少自定义列，表格总宽没有改变，滚动条依旧存在

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1861]
### tdesign-vue 版本

0.50.0

### 重现链接

https://stackblitz.com/edit/angular-rdhsfo?file=src/demo.vue

### 重现步骤

https://user-images.githubusercontent.com/13745660/204694800-8f3f7c7e-1dca-4d69-a5d7-35b0b18f1068.mov

当表格配置了resizable时，目前的列宽策略有以下问题

1.   减少自定义列，表格总宽没有改变，滚动条依旧存在
2.  当前列宽调整过程中，增大某列宽度会导致table宽度变大，目前没有让table宽度变小的方法。

https://user-images.githubusercontent.com/13745660/204696947-4ca5b15d-de0d-44d5-bd0d-ac014e6c13b2.mov

3.  如果有屏幕缩放操作，导致列宽变大后，无法让table总宽度变小。

### 期望结果

1. 在自定义列变化后，是否可以重新计算table总宽。
2. 能否增加某种交互策略来缩小表格总宽。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

16.17.1

**Comment by sagittarius-rev** [comment]
可以参考我之前提的 issue

#1663

**Comment by chaishi** [comment]
按理说，列数减少的时候，应该适当缩小表格宽度。

resolved in https://github.com/Tencent/tdesign-vue/pull/2130

修复效果如下，

https://user-images.githubusercontent.com/11605702/218317456-81edb174-8b55-48b9-b2b7-d575f7734f9f.mov

**Comment by xiaosansiji** [comment]
fixed in 1.1.2
