### ISSUE TITLE
[textarea]多行文本的 autofocus 无效

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1862]
### tdesign-vue 版本

tdesign-vue 0.50.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-5vgy0f?file=/src/demo.vue

### 重现步骤

使用多行文本输入组件，设置 :autofocus="true" 。

### 期望结果

按 API 文档， `autofocus` 属性用于自动聚焦，值为 `true` 时应当自动获得焦点。

### 实际结果

输入框没有自动聚焦。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

16.16.0

### 补充说明

之前已提过 issue ：#1790 

当时回复是：已传递 `autofocus` 属性给 html 的 textarea 元素。

检查源码后发现，单纯传递 `autofocus` 是不够的。对比 TDesign vue 的 `Input` 组件代码与 `Textarea` 组件，会发现 `Input` 组件额外对 `autofocus` 属性进行了观察，当值为 `true` 时会主动调用一次聚焦方法。而 `Textarea` 组件并无对应的处理，导致自动聚焦基本无法生效。

**Comment by yaogengzhu** [comment]
看起来少了一个对autofocus 的watch 。

**Comment by yaogengzhu** [comment]
@uyarn 这个一旦被关联 在PR那里是没有法取消这个自动关闭issues么？

**Comment by uyarn** [comment]
fixed 0.52.0
