### ISSUE TITLE
[Popup] Popup overlayStyle初次弹窗时不生效

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#1883]
### tdesign-vue 版本

0.51.1

### 重现链接

https://tdesign.tencent.com/vue/components/popup?tab=demo

### 重现步骤

配置overlayStyle，在弹窗初次产生时不生效

### 实际结果

在弹窗初次产生时不生效
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/5775725/205891130-f861861c-ef0c-4927-a7b2-ba5813c76314.png">

### 框架版本

2.6.x

**Comment by uyarn** [comment]
fixed 0.52.0
