### ISSUE TITLE
[TreeSelect] 选中异步加载树节点，select框中显示成了value值， 应该显示label值

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#1884]
### tdesign-vue 版本

0.51.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-vk6lh8?file=/src/demo.vue

### 重现步骤

展开节点，选中异步加载的树节点。
0.51.1版本: 显示成了value值
<img width="381" alt="image" src="https://user-images.githubusercontent.com/13745660/205913164-7e408c08-aba1-4acf-9b79-d5e5ffa8db2e.png">

0.49.6版本： 正常显示label值
<img width="389" alt="image" src="https://user-images.githubusercontent.com/13745660/205913321-185194c2-1cfd-4f2b-a291-ce528766c1be.png">

### 期望结果

0.49.6版本正常

### 实际结果

选中异步加载树节点显示错误，select框中显示的value， 不是label值

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

## IssueShoot

- 预估时长: 2
- 期望完成时间: 2022-12-15
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提MR并通过验收无误
- 备注: 最终激励以实际提交 pull request 并合并为准

**Comment by uyarn** [comment]
已修复 因为参加IssueShoot 此issue的问题会在下个版本发布 先close了
