### ISSUE TITLE
[time-range-picker] 时间范围选择，点击清除按钮时 v-model 结果异常

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#1892]
### tdesign-vue 版本

tdesign-vue 0.51.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-4u4l64?file=/src/demo.vue

### 重现步骤

使用时间的范围选择组件 `TimeRangePicker` ，并设置 `clearable` 属性为 `true` ，即允许清除输入值。

输入值之后，点击清除按钮。

### 期望结果

清除时间范围选择的输入值之后， `v-model` 的绑定值应当变为空值（ `null` 或 `undefined` ）或空数组。

### 实际结果

 `v-model` 的绑定值在点击清除按钮之后变成了对象，包含 `value` 与 `e` 等属性，其中 `e` 是点击事件（ `PointerEvent` ）。

打开控制台可以看到详细的数据。

在 sandbox 中，点击清除按钮会造成页面卡顿。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

16.16.0

**Comment by xiaosansiji** [comment]
已在 0.52.2 版本修复
