### ISSUE TITLE
[tree] 树的选中状态不正常，通过设置属性把所有的子项选中，但是父项却没有自动选中，只有在手动点击后才正常

### ISSUE THREAD

**Issue by ZS1994** [Tencent/tdesign-vue#1895]
### tdesign-vue 版本

0.51.1

### 重现步骤

首先这是第一次进入时，后台会把所有子项全部选中，但是所有的父项选中标识却无变化：
![image](https://user-images.githubusercontent.com/20389909/206383868-7c4ba449-36f6-497d-8762-0606c1a043ae.png)
然后手动点击任意项，无论是父项还是子项，这时父项的选中都会恢复正常：
![image](https://user-images.githubusercontent.com/20389909/206384043-f945d813-8c72-4a8f-8ccb-93f286d8436a.png)
![image](https://user-images.githubusercontent.com/20389909/206384070-20fef893-73de-4f56-928d-6eb483bfdee4.png)

但是这很明显是不正常的不是吗，难道不能像我手动点击一样，当我通过后台赋值所有子项选中时，父项的选中标识也应该自动的变化才对啊

### 框架版本

2.6.11

### 系统版本

win11

**Comment by ccccpj** [comment]
https://stackblitz.com/edit/angular-bvgfbu?file=src%2Fdemo.vue

在 0.51.1 及 最新版本均未复现您提及的问题，或许您能够提供更加详尽的复现链接以便排查，感谢反馈

**Comment by lybaby** [comment]
> https://stackblitz.com/edit/angular-bvgfbu?file=src%2Fdemo.vue
> 
> 在 0.51.1 及 最新版本均未复现您提及的问题，或许您能够提供更加详尽的复现链接以便排查，感谢反馈

这里用异步加载的时候是必现的，你样例里面先赋值的方式不会复现

**Comment by ccccpj** [comment]
> > https://stackblitz.com/edit/angular-bvgfbu?file=src%2Fdemo.vue
> > 在 0.51.1 及 最新版本均未复现您提及的问题，或许您能够提供更加详尽的复现链接以便排查，感谢反馈
> 
> 这里用异步加载的时候是必现的，你样例里面先赋值的方式不会复现

https://stackblitz.com/edit/angular-azpayk?file=src%2Fdemo.vue 看看这种用法是否是您想要的效果

**Comment by ZS1994** [comment]
我已经找到解决办法了，思路是我通过js先取消选中第一个选中项，然后再选中他，这样的话所有的节点状态就正常了，具体代码如下所示：
`// 初始化选中状态，因为初始化时只会选中叶子节点，父节点选中状态没有更新，所以要手动触发一次选中和不选中，让其触发更新父节点选中状态的操作
    initTreeActiveStatus() {
      const {tree} = this.$refs;
      if (this.$Vut.isNotEmpty(this.formData.permissionIdList)) {
        // 找到第一个激活的节点
        const firstNode = tree.getItem(this.formData.permissionIdList[0]);
        tree.setItem(firstNode.value, {checked: false});
        tree.setItem(firstNode.value, {checked: true});
      }
    },`

![image](https://user-images.githubusercontent.com/20389909/231968313-37e9ba92-d6ec-4391-bbb6-07ab2566290f.png)

**Comment by lybaby** [comment]
> > > https://stackblitz.com/edit/angular-bvgfbu?file=src%2Fdemo.vue
> > > 在 0.51.1 及 最新版本均未复现您提及的问题，或许您能够提供更加详尽的复现链接以便排查，感谢反馈
> > 
> > 
> > 这里用异步加载的时候是必现的，你样例里面先赋值的方式不会复现
> 
> https://stackblitz.com/edit/angular-azpayk?file=src%2Fdemo.vue 看看这种用法是否是您想要的效果

额  这里树的赋值和初始节点赋值在同一个函数里面，你再试试？

**Comment by lybaby** [comment]
> 我已经找到解决办法了，思路是我通过js先取消选中第一个选中项，然后再选中他，这样的话所有的节点状态就正常了，具体代码如下所示： `// 初始化选中状态，因为初始化时只会选中叶子节点，父节点选中状态没有更新，所以要手动触发一次选中和不选中，让其触发更新父节点选中状态的操作 initTreeActiveStatus() { const {tree} = this.$refs; if (this.$Vut.isNotEmpty(this.formData.permissionIdList)) { // 找到第一个激活的节点 const firstNode = tree.getItem(this.formData.permissionIdList[0]); tree.setItem(firstNode.value, {checked: false}); tree.setItem(firstNode.value, {checked: true}); } },`
> 
> ![image](https://user-images.githubusercontent.com/20389909/231968313-37e9ba92-d6ec-4391-bbb6-07ab2566290f.png)

这里应该是渲染先后的问题，我用了 setTimeout的方式解决的
