### ISSUE TITLE
[Space] 在windows 微信浏览器中设置不生效

### ISSUE THREAD

**Issue by brianzhang** [Tencent/tdesign-vue#1901]
### tdesign-vue 版本

0.52.0

### 重现链接

https://tdesign.tencent.com/vue/components/space

### 重现步骤

将重现链接在windows微信浏览器中打开即可看到效果
![企业微信截图_bca20d10-f667-437f-a420-3e46e05b2366](https://user-images.githubusercontent.com/766999/206410477-ef5b6530-4b7d-4e7e-8868-58c68aefdebc.png)

### 期望结果

能够正常使用<t-space>组件实现间距设置效果
<img width="582" alt="企业微信截图_00e5288b-52a0-4132-9ccb-c90b21ade6f8" src="https://user-images.githubusercontent.com/766999/206410498-ed1c041f-21bb-4174-9be4-a8a2209f6f81.png">

## 微信浏览器中无法设置间距效果

![企业微信截图_bca20d10-f667-437f-a420-3e46e05b2366](https://user-images.githubusercontent.com/766999/206410477-ef5b6530-4b7d-4e7e-8868-58c68aefdebc.png)

### 框架版本

vue 2.0

### 浏览器版本

Chrome/81.0.4044.138

### 系统版本

windows

### 补充说明

```
5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x6308010d)
```

**Comment by LTMana** [comment]
360极速版浏览器上也有这个问题，我看了好像是flex gap浏览器支持的问题，是否可以添加polyfill解决这个问题

**Comment by chaishi** [comment]
<img width="610" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/8ee77986-1643-4bdc-bad1-d3f1f46c2935">

<img width="683" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/0d2ff579-36f2-4474-ab43-15dd9289fd81">

今天尝试了一下，微信的浏览器（微信版本号 3.9.7.29），表现正常

**Comment by chaishi** [comment]
@mdxiaohu @LTMana @brianzhang
请大家留下间距无法正常显示的 UA 信息（navigator.userAgent），以便进行兼容处理

**Comment by chaishi** [comment]
Vue2 published at v1.8.0
Vue3 published at v1.7.0

**Comment by mdxiaohu** [comment]
这是已经兼容了么。没搞明白。
低版本浏览器之前试了下是不兼容的。
原因就是flex的gap属性低版本浏览器支持的问题。

**Comment by uyarn** [comment]
> 这是已经兼容了么。没搞明白。 低版本浏览器之前试了下是不兼容的。 原因就是flex的gap属性低版本浏览器支持的问题。

是的 低版本浏览器改了实现方式 不依赖gap

**Comment by Julone** [comment]
这个处理方式还存在问题，t-space--polyfill不应该设置为flex，应该为inline-flex。大部分的使用场景，space都是紧跟着元素，不应该处理成单独一行。
这样子当父节点设置样式text-align:right, 就会失效了。
![image](https://github.com/Tencent/tdesign-vue/assets/32406368/5431d30a-ae75-4378-9c66-8a67a612195c)
调整后就是对的了。
![image](https://github.com/Tencent/tdesign-vue/assets/32406368/c840a220-023e-495a-b43c-a8870f3ea079)

**Comment by chaishi** [comment]
> “space都是紧跟着元素，不应该处理成单独一行”

这句话有待考证，我们的系统里面，很多时候都是需要单独一行的，达到 90%。比如 Card 里面的 actions 区域，一定是单独一行。

@Julone 看上去你说的“问题” 是：
“是否默认换行（默认块级元素，还是行内元素）”，这似乎不是一个问题了。可以根据自己的情况，自由调整最外层的样式

**Comment by theozhang32** [comment]
> 
> @Julone 看上去你说的“问题” 是： “是否默认换行（默认块级元素，还是行内元素）”，这似乎不是一个问题了。可以根据自己的情况，自由调整最外层的样式

虽然可以自由调整外层样式，但`.t-space`默认样式就是`inline-flex`，不应该因为polyfill的引入导致默认行为的改变（引入polyfill，默认就变成`flex`了）
