### ISSUE TITLE
[Select] 全选时报错

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#1905]
### tdesign-vue 版本

0.52.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-l724k0?file=/src/demo.vue

### 重现步骤

点击下拉框的全选项

### 期望结果

可以正常全选

### 实际结果

全选无效，且控制台报错

**Comment by skytt** [comment]
目前 vue2 select 还不支持全选，近期支持下

**Comment by xiaosansiji** [comment]
已在 1.0.4 版本修复
