### ISSUE TITLE
[Dropdown] 下来框出现滚动条时次级内容错位

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#1906]
### tdesign-vue 版本

0.52.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-wlgu0q?file=/src/demo.vue

### 重现步骤

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/16223845/206613400-c874d7fb-f5cf-4c1b-b751-1e6d3bf48246.png">

1、hover按钮
2、下拉到最底部然后hover

### 期望结果

下拉到底部时次级内容不错位

### 实际结果

下拉到底部时次级内容错位

**Comment by xiaosansiji** [comment]
已在 0.52.2 版本修复
