### ISSUE TITLE
[Loading] 希望支持指令 v-loading

### ISSUE THREAD

**Issue by KKDKK513** [Tencent/tdesign-vue#1907]
### 这个功能解决了什么问题

element ui中用v-loading的指令使用，可以挂载在任意元素上，使用简单且方便。现有api需要在template中写t-loading组件或者调用this.$loading，操作复杂化且不够灵活
。获取异步请求的时候 可以用v-loading挂载在table或者任意div上，给用户更好的体验，防止请求接口时间过长让用户误以为页面卡顿，造成连点和刷新。

### 你建议的方案是什么

尽快新增v-loading指令，看到loading的api中有这个写法，但是demo还没给，希望可以将次提上日程

**Comment by chaishi** [comment]
```
<div class="content" v-loading="loading"></div>
```

和
```
<t-loading :loading="loading">
   <div class="content"></div>
<t-loading>
```

两种写法，差别有多大

**Comment by xiaosansiji** [comment]
已在 1.0.2 版本实现
