### ISSUE TITLE
[Select][Pagination] 如果是宽度自适应场景，则不需要超出省略，否则分页组件的文本会被省略

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#1912]
### tdesign-vue 版本

0.52.1

### 重现步骤

<img width="723" alt="image" src="https://user-images.githubusercontent.com/11605702/206704826-c19b5a27-89e7-4689-9ef6-e70b5a64dba7.png">

**Comment by skytt** [comment]
Select 宽度自适应的能力是透传的，最终提供逻辑的应该是 Input 组件

试了一下，图中的现象应该是 input 在计算宽度的时候小数部分被省略了，导致编辑框宽度小于文本宽度，被隐藏了，参考：https://codesandbox.io/s/tdesign-vue-demo-forked-gn8ngy

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/7420660/206956519-e76e852a-1422-4873-96c2-5b19d3064b6c.png">
文本的长度是 57.39px，编辑框长度是 57px，文本超出省略

devtools 将节点宽度手动修改到 57.39px 后可以正常显示
<img width="698" alt="image" src="https://user-images.githubusercontent.com/7420660/206956716-d3960b5d-4913-4c5f-9e9b-ebc37de679a0.png">
