### ISSUE TITLE
[List] list-item 不支持点击事件吗？

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1916]
### tdesign-vue 版本

0.52.1

### 重现链接

https://stackblitz.com/edit/angular-gqgwmq-h7yghg?file=src/demo.vue

### 重现步骤

点击 list-item 无法触发事件

### 期望结果

能够触发点击事件 又不和 action 重合

### 实际结果

点击 list-item 无法触发事件

**Comment by yaogengzhu** [comment]
看API 和 代码不支持，应该可以支持下

**Comment by xiaosansiji** [comment]
fixed in 1.1.2
