### ISSUE TITLE
[Loading] 调用多次LoadingPlugin.hide()时，会报错"TypeError: Cannot read properties of null (reading 'removeChild')"

### ISSUE THREAD

**Issue by Nice-PLQ** [Tencent/tdesign-vue#1918]
### tdesign-vue 版本

0.52.1

### 重现链接

https://stackblitz.com/edit/angular-cw75yw-3tq6uu?file=src%2Fdemo.vue

### 重现步骤

多次调用LoadingPlugin.hide()，报"TypeError: Cannot read properties of null (reading 'removeChild')"，如下图

### 实际结果

<img width="957" alt="image" src="https://user-images.githubusercontent.com/10710341/207022065-4c258b21-29a5-499c-a5c9-bd80fb27285a.png">

### 框架版本

Vue(2.6.11)

**Comment by huangpiqiao** [comment]
this.$loading(true)和LoadingPlugin(true)创建的是全局的单实例，只能hide一次
可以参考一下方式实现
https://stackblitz.com/edit/angular-cw75yw-qfq7qs?file=src%2Fdemo.vue

**Comment by Nice-PLQ** [comment]
> this.$loading(true)和LoadingPlugin(true)创建的是全局的单实例，只能hide一次 可以参考以下方式实现 https://stackblitz.com/edit/angular-cw75yw-qfq7qs?file=src%2Fdemo.vue

但是源码里是不是判断下比较好，不至于直接报错。
`loading.$el.parentNode?.removeChild(loading.$el)`

**Comment by xiaosansiji** [comment]
已在 0.52.2 版本修复
