### ISSUE TITLE
table表格有固定高度时，没有数据的情况下，表格的高度会发生变化。是否可以调整

### ISSUE THREAD

**Issue by z-oyi** [Tencent/tdesign-vue#194]
**Describe Framework**

tdesign-vue

在带有分页的场景下，当表格没有数据时，因为表格的高度会发生变化，使分页的位置会变化顶上去，导致页面太丑。是否可以优化一下。

**Comment by chaishi** [comment]
临时解决方案：业务侧可以先自行设置一下空数据的高度。让空数据元素高度和固定高度保持一致。

我们尽快优化一下

**Comment by chaishi** [comment]
处理PR：https://github.com/Tencent/tdesign-vue/pull/200

**Comment by xiaosansiji** [comment]
已在 0.33.1 版本中修复
