### ISSUE TITLE
[Table] jsx写法selectChange和rowClick事件没有触发

### ISSUE THREAD

**Issue by lgybetter** [Tencent/tdesign-vue#1944]
### tdesign-vue 版本

0.52.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-2qzeiw?file=/src/demo.vue

### 重现步骤

用createTemplate函数的jsx语法编写vue组件，table组件的selectChange和rowClick事件都没有正确触发

### 期望结果

table组件的selectChange和rowClick事件能够正确触发

### 实际结果

点击radio和table的某一行，都没有事件触发反应

### 框架版本

Vue(2.6.14)

**Comment by luguokong** [comment]
@lgybetter   事件应该用 kebab-case (短横线分隔命名)  写法。

**Comment by wenkeming** [comment]
你的写法有问题，改成横杠就好了
<img width="904" alt="image" src="https://user-images.githubusercontent.com/8252267/209930199-e7fa6c20-8ee1-4cb4-83e1-6df5f0bab7db.png">
