### ISSUE TITLE
[input] clear 事件处理函数中，获取的绑定值是清空前的值

### ISSUE THREAD

**Issue by luguokong** [Tencent/tdesign-vue#1946]
### tdesign-vue 版本

0.52.2

### 重现步骤

#1758 问题仍然存在。
应该验证的是clear事件，不是change事件。

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2000
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2231

不好意思，处理的有点晚

**Comment by xiaosansiji** [comment]
已在 1.0.3 修复
