### ISSUE TITLE
Checkbox 多选框  麻烦支持一下size属性

### ISSUE THREAD

**Issue by maclelin** [Tencent/tdesign-vue#1950]

**Comment by chaishi** [comment]
https://ant.design/components/checkbox-cn#api
AntDesign 不支持 size

https://arco.design/vue/component/checkbox
ArcoDesign 不支持 size

https://element-plus.org/zh-CN/component/checkbox.html
Element 支持 size

https://www.naiveui.com/zh-CN/light/components/checkbox
NativeUI 支持 size

**Comment by chaishi** [comment]
@maclelin 提 issue 注意以下几个点：

1.  不带任何命令、辱骂、责备的语气，谁也不欠谁
2. 不带任何恐吓、威胁的文字，谁也没有对不起谁
3. 多多使用 “期望”、“建议”等文字

**Comment by Wen1kang** [comment]
经过调研目前我们还不支持尺寸哦，未来2.0版本我们再看看～
