### ISSUE TITLE
文案过长时候省略号隐藏 好恶心

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#1953]
文案过长就省略号隐藏，文案都看不全，让别人怎么选，怎么用
select组件也有这个问题
<img width="605" alt="image" src="https://user-images.githubusercontent.com/31959442/209037171-f0a6243d-aa43-4452-ad46-955185c8cdb7.png">

**Comment by uyarn** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/26377630/209073270-35aeb06c-aa74-40d8-b330-05965817f341.png">
hover上去是有全部内容在title上的 如果你觉得这个样式不好看 可以提出其他建议

**Comment by chaishi** [comment]
@xubinglove  你的这个标题也恶心到我了， 第一次见人这么明目张胆地把 无知 当成了 底气，还有点想笑

从小家里人没人跟你讲过 教养 2 个字怎么写的，也没有学过吧
