### ISSUE TITLE
[TreeSelect] 一些bug

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1958]
### tdesign-vue 版本

0.52.2

### 重现链接

https://stackblitz.com/edit/angular-n73s3g-hywegs?file=src/demo.vue

### 重现步骤

 1. :treeProps="{keys: {value: 'id',label:'name'}}" 替换 label 值 搜索 控制台报错
<img width="818" alt="image" src="https://user-images.githubusercontent.com/8606851/209096636-ce777241-af18-4f57-8384-99d7c0573853.png">
2. onChange 与文档返回不一致 目前只能返回选中值
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/8606851/209096881-3093e06b-93be-43db-a8cc-4f6d1c2e779f.png">
3. disabled 样式 颜色有点过于淡了 都有点看不清
<img width="418" alt="image" src="https://user-images.githubusercontent.com/8606851/210698310-81b67343-0b16-4651-accb-4d50b821c85f.png">

4. filterable 如果触发选中状态 点击选中后无法触发onchange 事件
<img width="505" alt="image" src="https://user-images.githubusercontent.com/8606851/209598434-df9f85b5-1496-43d1-bb84-76437e51c651.png">
5. 动态赋值后点击组件 不会展开tree

https://github.com/Tencent/tdesign-vue/issues/1778
6. 选中值后不会清空搜索的值 arco会
<img width="536" alt="image" src="https://user-images.githubusercontent.com/8606851/211705399-47bd1808-e9f5-4221-825e-72010311849b.png">

**Comment by uyarn** [comment]
问题1 3 6 已修复 本周版本发布
问题2 是使用问题 context是第二个参数 请在onChange回调中增加第二个参数 测试正常
<img width="317" alt="image" src="https://user-images.githubusercontent.com/26377630/215433611-65fdb6cf-89ff-4ba6-8ba3-43f8c8d3d707.png">

问题4 不是缺陷 选中相同值不会触发
问题5 其他PR处理 在#1788中跟进

**Comment by Jiachang-Cai** [comment]
> 问题1 3 6 已修复 本周版本发布 问题2 是使用问题 context是第二个参数 请在onChange回调中增加第二个参数 测试正常 <img alt="image" width="317" src="https://user-images.githubusercontent.com/26377630/215433611-65fdb6cf-89ff-4ba6-8ba3-43f8c8d3d707.png">
> 
> 问题4 不是缺陷 选中相同值不会触发 问题5 其他PR处理 在 #1778 中继续跟进

问题4 还是有问题的 我如果搜索 输入的是完整的值如广州市 样式会为激活状态 但实际我还没有点击选择值  当我实际点击选择值的时候没有触发onchange 实际

**Comment by xiaosansiji** [comment]
1 3 6 已在 1.0.6 版本修复
