### ISSUE TITLE
lazy模式下不能主动加载子节点

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#1959]
比如我是lazy模式，然后选中了ID为2的子节点，记录到服务端，下次重新打开页面时候，拉取到2这个数据，但由于子节点树还没加载出来，最终就只会显示一个数字2在上面。
然后我手动点击后，子节点树就加载了，然后就能显示中文label 出来了

**Comment by chaishi** [comment]
请问是哪个组件，TreeSelect 吗

是否方便提供一下可复现问题的链接，以便尽快定位问题（一般会优先看提供了 demo  的问题）

**Comment by chaishi** [comment]
lazy 模式，就是点击后才打开子节点的。懒加载子节点的一种交互。

由于长时间没有回复，issue close

后面有需求可以再 reopen
