### ISSUE TITLE
[Tree] 如何动态改变data?

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#1966]
### tdesign-vue 版本

1.0.1

### 重现链接

https://stackblitz.com/edit/angular-d5fagm?file=src/demo.vue

### 重现步骤
如果tree 新增数据 或者删除数据 tree 重置会变更 但是数据修改的重置data 会有异常
点击动态重新赋值 tree 数据没有变更 且 actived 的值(ui上) 无法变更
<img width="402" alt="image" src="https://user-images.githubusercontent.com/8606851/209517756-09fa36d7-0850-4b27-97f1-bedaf6342d89.png">

### 期望结果

重新赋值 且不影响 actived 的值

### 实际结果
如果tree 新增数据 或者删除数据 tree 重置会变更 但是数据修改的重置data 会有异常
点击动态重新赋值 tree 数据没有变更 且 actived 的值 无法变更

**Comment by TabSpace** [comment]
composition api 重构之后，发现 data 变更后，视图绑定异常。
目前的节点缓存处理方式需要调整。
调试后暂定调整方案生成 PR：
https://github.com/Tencent/tdesign-vue/pull/1976

**Comment by xiaosansiji** [comment]
已在 1.0.3 修复
