### ISSUE TITLE
[Tree] allowFoldNodeOnFilter 不可用

### ISSUE THREAD

**Issue by xixileng** [Tencent/tdesign-vue#1970]
### tdesign-vue 版本

1.0.1

### 重现链接

https://stackblitz.com/edit/angular-ojpssk?file=src/demo.vue

### 重现步骤

t-tree 增加 allow-fold-node-on-filter 属性后，并未生效，根源在于 useTreeStore 中 storeProps 没有包含 allowFoldNodeOnFilter 属性，但加上后出现了更诡异的问题（折叠后内部节点无法筛选出；筛选子节点父节点占空间但不显示等），所以只提 issue

### 期望结果

加上后自动生效，筛选节点后可以继续展开/折叠父节点

### 实际结果

api无效

**Comment by TabSpace** [comment]
https://github.com/Tencent/tdesign-vue/pull/2181
这个 mr 已添加 tree 组件对 allowFoldNodeOnFilter 属性的支持。
allowFoldNodeOnFilter 为 true 时，节点命中不会影响到节点展开状态，需自行解决展开状态问题。
之前锁定节点被设置为 disabled，这个 pr 中 allowFoldNodeOnFilter 为 true 时，路径节点不再设为 disabled。
这导致路径节点样式与命中节点未能区分，有待进一步改造。
