### ISSUE TITLE
[Table] 某些情况下会导致报错

### ISSUE THREAD

**Issue by wenkeming** [Tencent/tdesign-vue#1978]
### tdesign-vue 版本

1.x

### 重现步骤

控制台报错
<img width="609" alt="image" src="https://user-images.githubusercontent.com/8252267/209913170-3fbcda48-8c25-43c2-9137-dc453f7c78d5.png">

报错位置
<img width="753" alt="image" src="https://user-images.githubusercontent.com/8252267/209913214-2198358e-575b-4cc8-b25c-b3346f4ab159.png">

**Comment by xiaosansiji** [comment]
已在 1.0.3 修复
