### ISSUE TITLE
[Table] 表格列为动态添加的时候，插槽内容不更新

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#1982]
https://stackblitz.com/edit/angular-gtgw1y?file=src%2Fdemo.vue
动态添加一列的时候，新列不执行插槽内容，如上例子，新加的那列应该显示 ‘新的 ’ 但结果显示的原始值test

**Comment by chaishi** [comment]
确实存在问题，我处理下

**Comment by chaishi** [comment]
当前解决方案示例代码：
https://stackblitz.com/edit/angular-gtgw1y-qbpz3d?file=src%2Fdemo.vue

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/11605702/210056070-b0fba60c-1f2f-41fb-ac9d-89ca57e5375e.png">

**Comment by xubinglove** [comment]
这个场景主要是动态读取接口返回的数据，也就是同一个表格列的情况会千变万化。所以不能预设

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2016/commits/fc7d56d8cc88cfb40a2d53719ade0bbf134e9fb1

https://github.com/Tencent/tdesign-vue/pull/2016

**Comment by xiaosansiji** [comment]
已在 1.0.4 版本修复

**Comment by syc888897** [comment]
请问修复了该问题后，我如何将该修复更新到我的项目中去呢
