### ISSUE TITLE
[Tag] 设置disabled为true后，关闭图标hover仍然高亮

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#1991]
### tdesign-vue 版本

1.0.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-e72h4b?file=/src/demo.vue

### 重现步骤

1. 鼠标移动到关闭图标上方
<img width="880" alt="image" src="https://user-images.githubusercontent.com/16223845/210317771-7a8e6d5b-3433-4c21-b471-a1fee6f18625.png">

### 期望结果

关闭图标不再高亮

### 实际结果

关闭图标仍然高亮

**Comment by chaishi** [comment]
问题收到，我们处理下

**Comment by byq1213** [comment]
已认领

**Comment by xiaosansiji** [comment]
已在 1.0.3 修复
