### ISSUE TITLE
[table] 增加横向滚动到指定列

### ISSUE THREAD

**Issue by vickyWmoon** [Tencent/tdesign-vue#1992]
### 这个功能解决了什么问题

当表格的列很多时，如果可以通过输入框输入列名滚动到指定列，则不许要拖动滚动条即可找到对应的列，查看起来更加方便

### 你建议的方案是什么

在表格上方加一个可以滚动到指定列的输入框，根据输入框的内容（列名或者列数）横向定位到指定列，如果没有则不滚动

**Comment by chaishi** [comment]
需求已收到，我周末看下

**Comment by chaishi** [comment]
当前，你可以查询到对应的 th 元素执行：

```
$0.querySelector('.t-table__th-createTime').scrollIntoView({ behavior: "smooth" })
```

实现你想要的效果

**Comment by chaishi** [comment]
新增组件实例方法 `scrollColumnIntoView(colKey: string)` 滚动到指定列，示例代码：`this.$refs.tableRef.scrollColumnIntoView('matters');`

**Comment by uyarn** [comment]
supported in 1.2.4
