### ISSUE TITLE
[Table] data更新后，选中的值仍存在

### ISSUE THREAD

**Issue by wenkeming** [Tencent/tdesign-vue#1993]
### tdesign-vue 版本

1.0.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-k1yrd9?file=/src/demo.vue

### 重现步骤

下面为复现视频

https://user-images.githubusercontent.com/8252267/210328538-6a09a76f-7244-465c-bbc9-79bd60ecef3d.mp4

**Comment by chaishi** [comment]
`<t-table data selectedRowKeys>` Table 组件的 2 个属性 `data` 和 `selectedRowKeys` ，是完全独立的 2 个属性，data 的变化不会影响到 selectedRowKeys 的变化。（有的业务希望 data 变化清空选中数据，而有的业务某些条件下不希望清空）

如果你希望数据变化的时候，清空数据，可以在数据变化的地方设置 `this. selectedRowKeys = []` 即可解决问题。

`selectedRowKeys` 是可以完全由父组件控制的，里面的值是什么，就选中什么。如果不希望选中 1,2,3,4，就把它们从数组 `selectedRowKeys` 中移除即可

**Comment by chaishi** [comment]
另外，关于 `reserveSelectedRowOnPaginate` 也可以关注下，也许用得上

<img width="887" alt="image" src="https://user-images.githubusercontent.com/11605702/210368654-ee171091-9eda-4f81-9be7-e70ea39506d0.png">
