### ISSUE TITLE
tag 

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue#20]
**Describe Framework**
- [x] tdesign-vue
- [x] tdesign-vue-next
- [x] tdesign-react

**Describe Environment**

pkg version: lts

**Describe the bug**

[codesandbox demo
](https://codesandbox.io/s/tdesign-vue-demo-forked-cxx00)

![image](https://user-images.githubusercontent.com/35833812/146668610-8440bbcc-c5cb-411b-9731-fbad95dca126.png)
no disabled style

**Comment by chaishi** [comment]
带颜色的tag没有disbaled效果
