### ISSUE TITLE
[select] minCollapsedNum属性不能正确显示

### ISSUE THREAD

**Issue by taovicky** [Tencent/tdesign-vue#2002]
### tdesign-vue 版本

最新版

### 重现链接

https://stackblitz.com/edit/angular-rsbqkd?file=src%2Fdemo.vue

### 重现步骤

请看重现链接

**Comment by chaishi** [comment]
硬是没有看出来有什么问题，怎么才算正确显示
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/11605702/210479310-55603cb1-f3ea-4e6c-aedb-c560953b0fdb.png">

**Comment by chaishi** [comment]
是标签不对么，应该显示 2 个标签?

**Comment by uyarn** [comment]
增加`displayValue`回调参数处理 会是除去collapseItem之外展示的前N个value

**Comment by xiaosansiji** [comment]
已在 1.0.4 版本修复
