### ISSUE TITLE
[TreeSelect] 一直点击input会一直触发popup-visible-change事件

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2004]
### tdesign-vue 版本

1.0.2

### 重现链接

https://codesandbox.io/s/45d7gx?file=/src/demo.vue

### 重现步骤

一直点击input

### 期望结果

只第一次触发

### 实际结果

一直触发

**Comment by xiaosansiji** [comment]
已在 1.0.6 版本修复
