### ISSUE TITLE
[EnhancedTable] 重置数据需要优化

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2005]
### tdesign-vue 版本

1.0.2

### 重现链接

https://stackblitz.com/edit/angular-fj2bvm-aslwul?file=src/demo.vue

### 重现步骤

1. 为什么一定要调用resetData 才能刷新表格数据 而非直接 更新data数据就行
2. 刷新数据需要支持保持tree展开 目前会折叠

### 期望结果

1. 直接 更新data数据就行
2. 刷新数据需要支持保持tree展开

**Comment by Jiachang-Cai** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/8606851/212063183-6fa74c08-1ab5-4da6-937d-3ddfbc007eb2.png">
尝试现有api 去实现 但是 setData 无法重置children 哪怕 children 顺序变了 或者内容变动 都无法改动

**Comment by chaishi** [comment]
信息量有点大，可以先加我企业微信，我们可能需要细聊一下

**Comment by Jiachang-Cai** [comment]
> 信息量有点大，可以先加我企业微信，我们可能需要细聊一下

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8606851/222917616-0e2ae6c3-99fd-48b8-88c8-e644b04626cf.png">
简化下问题：
1. 为什么一定要调用resetData 才能刷新表格数据
2. 刷新数据需要保持tree展开

**Comment by chaishi** [comment]
先说第 1 点（第 2 点没看懂什么意思）

稍微纠正一下，不完全是“一定要调用resetData 才能刷新表格数据”，从代码来看，只是行唯一表示发生变化，即 unique keys 变化也会刷新。

目前，暂时没有控制节点是否展开的属性。而刷新数据有几类情况：1. 删除数据；2. 更新数据；3. 新增数据。

- 如果只是更新数据的场景，data 会变化，但此时不希望影响本身已经展开的节点变化。没有必要因为某一行的数据变化，更新整棵树。
- 删除和新增数据是更大的变化，节点可能消失或新增，展开情况也较为复杂，这类场景的 data 变化，就直接重置整个树节点，包括展开等状态。

data 的变化多种多样，是否任何一丁点的数据变化都刷新整个树，有待考虑。而 resetData 意味着使用者一定期望完全重置。否则单行刷新只需要 `setData`

**Comment by Jiachang-Cai** [comment]
> 先说第 1 点（第 2 点没看懂什么意思）
> 
> 稍微纠正一下，不完全是“一定要调用resetData 才能刷新表格数据”，从代码来看，只行唯一标识发生变化，即 unique keys 变化也会刷新。
> 
> 目前，暂时没有控制节点是否展开的属性。而刷新数据有几类情况：1. 删除数据；2. 更新数据；3. 新增数据。
> 
> * 如果只是更新数据的场景，data 会变化，但此时不希望影响本身已经展开的节点变化。没有必要因为某一行的数据变化，更新整棵树。
> * 删除和新增数据是更大的变化，节点可能消失或新增，展开情况也较为复杂，这类场景的 data 变化，就直接重置整个树节点，包括展开等状态。
> 
> data 的变化多种多样，是否任何一丁点的数据变化都刷新整个树，有待考虑。而 resetData 意味着使用者一定期望完全重置。否则单行刷新只需要 `setData`（组件内部判断是某一行数据的变化，还是大量数据的变化，从开发角度看，需要花费时间精力去处理，从运行角度看，是不是每次一丁点变化都得全量遍历一遍才知道变化了什么，是否值得）

1. 其他框架都没有 resetData 操作  全是直接重置data 且不会 改变当前已展开的tree(你已点击展开的节点 因为我肯定需要保持我 删除、修改、新增 的节点展开状态 )    还有对于使用的人来说 怎么方便怎么来  赋值完data 还要再操作 resetData
1. 删除数据；2. 更新数据；3. 新增数据。 目前就是tdesign遇到问题 当前的api属性只能更改单行的数据刷新 而无法控制刷新整个tree或节点的tree   因为很多业务数据都是有个排序字段的 新增、修改、删除 都会去影响这个排序字段  肯定修改完 是要看到数据的正确排序(目前我没看到有api 支持) 然后只能去调用resetData 但是会有第二个问题会把整个tree 节点展开状态 重置  (你修改三级节点数据改完 又要重新再次手动去点开三级节点 修改量多了 体验极度不好)

**Comment by chaishi** [comment]
1. 在新版本中， data 变化会执行 resetData，全部数据重新计算（必要的时候使用）
2. 可通过 `expandedTreeNodes.sync` 和 `@expanded-tree-nodes-change` 控制展开的树形节点，如果都不传，组件内部会有自带的展开逻辑。
    注意： data 数据变化时，变化前的某个节点可能在变化后不存在，此时的需要展开的节点只有组件外部知道，故而需要在组件外部设置展开的节点，也可以一股脑设置为空 []
