### ISSUE TITLE
[TDialog] 组件无法正确的被销毁DOM元素，会伴随内存泄漏风险和业务BUG

### ISSUE THREAD

**Issue by loganylwu** [Tencent/tdesign-vue#2006]
### 重现链接
https://github.com/loganylwu/tDesign-bugs

### 重现步骤
点击首页按钮 【点击触发bug】 即可观察到在1s后，页面路由进行了切换，但是DOM并没有销毁。

### 期望结果
期望DOM伴随着组件的销毁而销毁。

### 实际结果
路由切换了，但是组件并未销毁。

### 补充说明
我观察到源代码里面有一行 setTimeout
https://github.com/Tencent/tdesign-vue-next/blob/1d2d5b2deeb5a6c04e3389707a97f1e7ec6eca49/src/dialog/dialog.tsx#L214

在Dialog组件中，销毁的时间是在150ms后，但是在150ms后，组件实例已经由于路由切换而销毁了，
此时应无法利用ref属性成功的找到对应的DOM元素而进行清除。
建议去除setTimeout。
考虑到可能会有动画效果，建议使用CSS动画来实现。

| Environment | Info |
|---|---|
| 相关版本 | 0.48.1 |
| 框架版本 / 基础库版本 | vue(^2.6.14) |
| 系统、浏览器 | 任意 |
| Node版本 | 16 LTS |

**Comment by chaishi** [comment]
`onBeforeUnmount` 不需要 setTimeout

<img width="468" alt="企业微信截图_22d7aff3-8237-4b88-8677-89f22e4812fe" src="https://user-images.githubusercontent.com/11605702/210572625-d6268087-349f-4792-a471-2350c2a3855a.png">

<img width="701" alt="企业微信截图_fdd06904-fb26-4d66-bf12-fcad6cd513ea" src="https://user-images.githubusercontent.com/11605702/210572611-73c426a9-32d2-40f4-8a18-4f1f93dd698e.png">

**Comment by chaishi** [comment]
仓库 issue 是 Vue2，提到的代码地址是 Vue3，没对上

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2011
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2242

**Comment by loganylwu** [comment]
> 

ok  似乎是我看错了地方。 不过刚刚去看了vue2 项目仓库也是一样的代码。
应该都会面临相对应的问题
https://github.com/Tencent/tdesign-vue/blob/3caf35ab01dcf4f5ee54f130f0eafbe0bc42b634/src/dialog/dialog.tsx#L217

**Comment by xiaosansiji** [comment]
已在 1.0.4 版本修复
