### ISSUE TITLE
请问官方大概多久能支持vue 2.7版本？

### ISSUE THREAD

**Issue by 104828720** [Tencent/tdesign-vue#2012]
### 这个功能解决了什么问题
期待官方能尽快适配Vue 2.7

### 你建议的方案是什么？
期待官方能尽快适配Vue 2.7

**Comment by chaishi** [comment]
由于 Vue2.7 不兼容版本，需要花费较多人力去处理相关问题。可能会在 Vue2.6 和 Vue3 逐步趋于稳定后开始。可能是 23 年下半年（上半年人力充足的或可提前）

业内有其他的仓库支持 Vue2.7 了吗

Vue 是真的麻烦，2.6 / 2.7 / 3.xx 各种不兼容版本，不知道生态还能包容多久

**Comment by yanyalin** [comment]
> 由于 Vue2.7 不兼容版本，需要花费较多人力去处理相关问题。可能会在 Vue2.6 和 Vue3 逐步趋于稳定后开始。可能是 23 年下半年（上半年人力充足的或可提前）
> 
> 业内有其他的仓库支持 Vue2.7 了吗
> 
> Vue 是真的麻烦，2.6 / 2.7 / 3.xx 各种不兼容版本，不知道生态还能包容多久

element-ui和ant-design-vue就支持vue2.7，只有小部分插槽不支持vue2.6

**Comment by catdddmouse** [comment]
是哪块不兼容呢?

**Comment by uyarn** [comment]
> 是哪块不兼容呢?

@vue/composition-api

**Comment by uyarn** [comment]
https://tdesign.tencent.com/vue/getting-started
<img width="869" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/c9ce1209-0950-474d-9cff-d3b88c0a0e4d">
2.7的支持已经发布版本了 欢迎使用
