### ISSUE TITLE
[Upload] selectChange事件回调里面获取value的值没有更新

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2014]
### tdesign-vue 版本

1.0.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-w4fzlu?file=/src/demo.vue

### 重现步骤

1.上传一个文件
2. 查看控制台
<img width="902" alt="image" src="https://user-images.githubusercontent.com/16223845/210953905-40cddcec-c445-4812-a7da-0c15ae4ab58e.png">

### 期望结果

能在selectChange回调里面正确获取到value的值

### 实际结果

在selectChange回调里获取到的value值是没有选择之前的值

**Comment by chaishi** [comment]
`onSelectChange` 中不改变 files1 的值，符合组件效果预期。

如果你希望某个事件里面获取改变后的 files，请更为使用 `onChange`
