### ISSUE TITLE
[Tree] 文档页面和实际使用中的bug

### ISSUE THREAD

**Issue by taochangle** [Tencent/tdesign-vue#2017]
### tdesign-vue 版本

1.0.3

### 重现链接

https://tdesign.tencent.com/vue/components/tree#%E8%87%AA%E5%AE%9A%E4%B9%89

### 重现步骤

![image](https://user-images.githubusercontent.com/7435144/211128144-27a5fa9f-df52-4ba2-9d4c-94a654fc4833.png)

### 期望结果

点击“ 插入节点使用高亮节点”，然后再点击插入子节点 子节点高亮

### 实际结果

页面卡死

### 框架版本

"vue": "~2.6.14",

### 浏览器版本

Microsoft Edge
版本 108.0.1462.54 (正式版本) (64 位)

### 系统版本

Windows11

### Node版本

node -v
v14.21.2

### 补充说明

把demo代码拷贝到本地。点击“ 插入节点使用高亮节点”，然后再点击“插入子节点 ”，页面果然也卡死了

**Comment by TabSpace** [comment]
节点插入自身引发了死循环。
报错信息在这个 PR 给出。
https://github.com/Tencent/tdesign-common/pull/1181
之后再更新示例。

**Comment by TabSpace** [comment]
https://github.com/Tencent/tdesign-vue/pull/2212
问题已修正
