### ISSUE TITLE
[avatar] 尺寸默认值

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-vue#2018]
### tdesign-vue 版本

任意

### 重现链接

无

### 重现步骤

文档描述 size 的默认值为 large

### 期望结果

size = large

### 实际结果

size = middle

### 补充说明

另外，AvatarGroup 的 size 优先级低于 Avatar 感觉不是很合理，应该相反？

**Comment by chaishi** [comment]
> 另外，AvatarGroup 的 size 优先级低于 Avatar 感觉不是很合理，应该相反？

应该是合理的。

一般场景下，组 Group 的优先级都是低于子组件。比如 checkbox-group.disabled 低于 checkbox.disabled

AvatarGroup 的 size 优先级低于 Avatar 可以满足一种场景。AvatarGroup 设置一个默认尺寸 small，为了突出某一个头像，想单独大一些，就可以单独设置 Avatar.size = large

**Comment by chaishi** [comment]
> 期望结果：size = large。实际结果：size = medium

为了避免 API 使用上的 breaking change，只好改文档了。文档改成默认 medium
