### ISSUE TITLE
[Table] 表头吸顶时滑动出现表头错位问题

### ISSUE THREAD

**Issue by CaptainWang98** [Tencent/tdesign-vue#2020]
### tdesign-vue 版本

1.0.2

### 重现链接

https://codesandbox.io/s/tdesigngu-ding-lie-yu-xi-ding-dao-zhi-shu-biao-tuo-dong-gun-dong-shi-biao-tou-cuo-wei-fv4238?file=/src/demo.vue:0-8930

### 重现步骤

复现路径1:
1、表头吸顶；
2、表格横向内容超出视口；
3、选中表格内容时不松开鼠标向右快速移动鼠标，让内容横向滚动；
复现路径2:
1、表头吸顶；
2、表格横向内容超出视口；
3、选中其他应用/浏览器窗口；
4、不要点击重新选中表格窗口，直接横向滑动；

### 期望结果

表头正常横向滚动

### 实际结果

表头错位

### 框架版本

2.6.14

### 浏览器版本

108.0.5359.124

### 系统版本

MacOS Big Sur 11.7

**Comment by xiaosansiji** [comment]
已在 1.0.4 版本修复
