### ISSUE TITLE
[Select][Form] 点击重置后无法双向赋值 导致组件不能使用且出现赋值异常

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2021]
### tdesign-vue 版本

1.0.3

### 重现链接

https://stackblitz.com/edit/angular-xcbjom?file=src/demo.vue

### 重现步骤

https://user-images.githubusercontent.com/8606851/211251339-cbb1fe90-d8e0-4b3e-801f-c424877d40d4.mp4

### 期望结果

重置不影响双向赋值和赋值异常

### 实际结果

影响双向赋值和赋值异常

**Comment by skytt** [comment]
看起来是初始数据字段不正确，具体检查 `course` 与 `level` 字段

另外，看代码的预期你似乎想把一个数组的 value 传入到一个单选的 Select 组件，这样的操作会导致组件无法正常使用，同时会有控制台报错，可以留意一下

我修改 demo 后，试了一下 单选 和 多选 的场景都是正常的，供参考：
单选：https://stackblitz.com/edit/angular-xcbjom-ci9ncp?file=src%2Fdemo.vue
多选：https://stackblitz.com/edit/angular-xcbjom-6noubn?file=src%2Fdemo.vue
