### ISSUE TITLE
[Menu] 提供移除点击事件触发的闪烁遮罩动画

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2034]
### 这个功能解决了什么问题

<img width="74" alt="image" src="https://user-images.githubusercontent.com/8606851/211627455-45fe13d6-4386-48a7-8fa7-623fa0bd3d57.png">
点击菜单 不需要闪烁遮罩动画

### 你建议的方案是什么

能够提供可选需不需要 ？

**Comment by uyarn** [comment]
有提供的 可以通过全局配置关闭这个动画 参考 
https://codesandbox.io/s/tdesign-vue-demo-forked-vbq076?file=/src/demo.vue
