### ISSUE TITLE
[Image] 组件内部存在中文，需进行国际化处理

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#2037]
### 这个功能解决了什么问题

国际化语言

### 你建议的方案是什么

新增 ImageConfig 及其属性，用于进行语言配置（各框架均需实现）

<img width="983" alt="image" src="https://user-images.githubusercontent.com/11605702/211730543-517c1d1e-f710-4e8b-acf5-45b23f491646.png">

**Comment by wenkeming** [comment]
另外，那些警告、错误日志都建议国际化，比如：
<img width="837" alt="image" src="https://user-images.githubusercontent.com/8252267/211775643-a371fef8-6007-45e7-a8d4-f6b12db81fda.png">

**Comment by xiaosansiji** [comment]
duplicated with https://github.com/Tencent/tdesign-vue/issues/2063 已经实现
