### ISSUE TITLE
【table】表格组件表头筛选使用自定义组件，筛选完成后再打开，之前选中项被重置了，并没有回显

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue#2038]
### 这个功能解决了什么问题

目前列配置 filter.type 决定使用哪一种筛选器，可选值有：single/multiple/input【选完关闭，再次打开有回显】
filter.component 自定义筛选组件没实现这个效果，而是关闭的时候直接销毁组件，再次打开上次选中的就没有了

### 你建议的方案是什么

建议实现这个功能

**Comment by chaishi** [comment]
只有简单的文本描述，没有可复现问题的示例代码链接，难以处理问题。

**Comment by chaishi** [comment]
在链接里面复现一下你说的问题

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue
<img width="872" alt="image" src="https://user-images.githubusercontent.com/11605702/211774708-56b5124f-d23d-44eb-ab46-f2fbeb5c3d8b.png">

**Comment by chaishi** [comment]
长时间没有收到回复，不确定是哪里的问题，issue close

如果有新的回复，可以联系我们再 reopen
