### ISSUE TITLE
[link] 容器宽度有限的情况下，文字换行后，下划线显示样式不佳

### ISSUE THREAD

**Issue by luguokong** [Tencent/tdesign-vue#2039]
### tdesign-vue 版本

1.0.4

**Comment by chaishi** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/11605702/218319106-07e4b0b9-cf29-4b16-8155-018cc64486c7.png">

试了一下换行效果，看不出来有什么问题，issue close。如果还有其他疑问可以再单独 issue
