### ISSUE TITLE
[Tooltip] 无法继承popup的delay属性

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2040]
### tdesign-vue 版本

0.51.1

### 重现步骤

<img width="873" alt="image" src="https://user-images.githubusercontent.com/9960612/212022256-be9a145f-f770-4bdb-a640-1dcb29885bfd.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/9960612/212022319-3924c082-7723-4882-baa3-464b87e468e4.png">

根据文档，预期能和popup一样设置delay，但会和tooltip本身的delay属性冲突。

### 框架版本

2.6.14

**Comment by chaishi** [comment]
`Tooltip.delay` 和 `Popup.delay` 完全等效，我们更新一下文档

https://stackblitz.com/edit/angular-onrcvl?file=src%2Fdemo.vue
新版本，我在链接里面试了一下，Tooltip.delay 延迟，可以正常使用了。
