### ISSUE TITLE
[Dialog] 由this.$dialog函数创建的弹窗，底部按钮全局配置不生效

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2042]
### tdesign-vue 版本

1.0.4

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-pqpk3b?file=/src/demo.vue

### 重现步骤

1.点击dialog plugin按钮
2. 弹窗的确定按钮没够变为danger的主题色，cancel也没变为default的主题色
<img width="571" alt="image" src="https://user-images.githubusercontent.com/16223845/212468393-d29d1e88-c53b-40f6-ba75-48ba40c0c377.png">

### 期望结果
弹窗底部按钮能根据全局配置渲染

_No response_

### 实际结果
弹窗底部按钮没有根据全局配置渲染

_No response_

**Comment by yaogengzhu** [comment]
这个关键应该是this.$dialog 获取不到全局的config

**Comment by uyarn** [comment]
这个问题要重新处理 按设计 结论更正为 theme不影响button的样式是正常行为 目前的问题是
config-provider无法影响到this.$dialog 及其他this上挂载的实例

**Comment by uyarn** [comment]
fixed in 1.2.0
