### ISSUE TITLE
[TimePicker] 时间选择器面板默认值

### ISSUE THREAD

**Issue by 879226489** [Tencent/tdesign-vue#2046]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/54408067/212798255-67ba2a95-c7cb-468b-987b-b40bb824012b.png)
在选择时间时默认值固定为当前时间 不可设置

### 你建议的方案是什么

无

**Comment by uyarn** [comment]
https://codesandbox.io/s/2v90nu?file=/src/demo.vue 这样不符合预期？

**Comment by 879226489** [comment]
> https://codesandbox.io/s/2v90nu?file=/src/demo.vue 这样不符合预期？

是在组件没有value 状态下 面板的默认值

**Comment by uyarn** [comment]
> > https://codesandbox.io/s/2v90nu?file=/src/demo.vue 这样不符合预期？
> 
> 是在组件没有value 状态下 面板的默认值

try this demo https://codesandbox.io/s/tdesign-vue-demo-forked-yi32x4?file=/src/demo.vue

**Comment by 879226489** [comment]
感谢 通过这种方式是可以符合预期的 不过还是希望可以在timePicker 组件里面提供参数

**Comment by uyarn** [comment]
这个可能不太实际 TimePicker本身就是一个整体 如果还为了这个需求分离面板和输入框的视图 会增加很多成本引入潜在的问题 所以我们把面板部分也暴露了供用户自己组合 我们可以多几个展示示例方便直接复制来使用

**Comment by uyarn** [comment]
closed as complete.
