### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by Just-do-it-LB** [Tencent/tdesign-vue#2051]
### tdesign-vue 版本

能重现

### 重现链接

https://1_0_5-tdesign-vue.surge.sh/vue/components/table

### 重现步骤

1）我只要进入有table组件的页面，鼠标在空白地方 左点击就会报错；
2）焦点失焦 也会报错。

进入其他组件的页面不会报错

### 期望结果

无报错，焦点失焦可以保存

### 实际结果

有报错
![image](https://user-images.githubusercontent.com/60215541/212911522-f666f4f2-9ff2-4c0a-a15f-1e38962d1660.png)
![image](https://user-images.githubusercontent.com/60215541/212911571-a325f9f1-f685-4039-8f86-6cb542c4409e.png)

### 框架版本

Vue2

### 浏览器版本

109.0.5414.87

### 系统版本

12.6

**Comment by chaishi** [comment]
下次注意标题

<img width="911" alt="image" src="https://user-images.githubusercontent.com/11605702/218316367-7a55786b-63d4-4e18-a469-3f6038610e3f.png">

**Comment by chaishi** [comment]
这个是因为新版浏览器删除了 e.path 属性，新版组件库已经做好了兼容，应该没有问题了。issue close

如果还有其他问题，可以再单独提 issue
