### ISSUE TITLE
[DateRangePicker] YYYY-MM 格式下赋值后 样式异常

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2054]
### tdesign-vue 版本

1.0.5

### 重现链接

https://stackblitz.com/edit/angular-dxxk73?file=src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/8606851/215257124-4868fbe9-978f-4a27-9532-7e188d356a0a.png)
<img width="662" alt="image" src="https://user-images.githubusercontent.com/8606851/215257226-6798044c-6438-469d-b78a-69ea19972022.png">
赋值后样式显示异常

### 期望结果

样式正常

### 实际结果

样式显示异常

**Comment by xiaosansiji** [comment]
已在 1.0.6 版本修复
