### ISSUE TITLE
[t-table] 表格中的可编辑文本框失去焦点时报错

### ISSUE THREAD

**Issue by liangyongxiong** [Tencent/tdesign-vue#2057]
### tdesign-vue 版本

1.0.5

### 重现链接

https://codesandbox.io/s/cnlzcf?file=/src/demo.vue

### 重现步骤

1、在 重现链接 中运行 demo 应用，并等待 demo 应用完成页面渲染
2、点击 demo 应用的页面空白处，使表格中的可编辑文本框失去焦点
3、页面提示报错  Uncaught TypeError：Cannot read properties of undefined (reading 'length')

### 期望结果

表格中的可编辑文本框失去焦点时不报错

### 实际结果

页面提示报错 Uncaught TypeError：Cannot read properties of undefined (reading 'length')

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2055

**Comment by xiaosansiji** [comment]
已在 1.0.6 版本修复
