### ISSUE TITLE
[DatePicker] 日期选择显示错位

### ISSUE THREAD

**Issue by simon1uo** [Tencent/tdesign-vue#2059]
### tdesign-vue 版本

1.0.5

### 重现步骤

不知道怎么重现，在我的项目中没有调整过该组件（或者popup组件）的样式，但是出现了如图的错位情况，查看了一下样式，是组件的padding有问题：
![](https://i.328888.xyz/2023/01/30/8fAGH.png)
![](https://i.328888.xyz/2023/01/30/8fCmt.png)
(补充：左侧贴图是官方组件实例，右侧是在我的项目中的组件的效果)

### 框架版本

Vue(2.6.14)

**Comment by uyarn** [comment]
是用starter初始化的项目吗？

**Comment by simon1uo** [comment]
> 是用starter初始化的项目吗？

对，是在starter项目拓展起来的

**Comment by uyarn** [comment]
是因为项目里有个全局影响的t-button 左边距的样式干扰了 可以增加这个来修复
.t-pagination-mini {
  .t-button + .t-button {
    margin-left: 0;
  }
}
