### ISSUE TITLE
table表头的border有错位

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#206]
**Describe Framework**

tdesign-vue

**Describe Environment**
![image](https://user-images.githubusercontent.com/15682051/148786624-34ef9166-c5e0-46a4-8f48-eca973634c01.png)

Add browser version here

![image](https://user-images.githubusercontent.com/15682051/148786549-2a0658e3-d7f4-48c8-b22f-48e1a657339c.png)

**Describe the bug**

**Additional context**

![image](https://user-images.githubusercontent.com/15682051/148745297-64843a32-595b-41e0-ba21-9643759caafd.png)

**Comment by realyuyanan** [comment]
固定表头的时候吗？用的外网包？

**Comment by sampsonliu** [comment]
> 固定表头的时候吗？用的外网包？

复现地址：https://codesandbox.io/s/tdesign-vue-demo-forked-m02sn?file=/src/demo.vue

**Comment by chaishi** [comment]
重复 issue，see https://github.com/Tencent/tdesign-vue/issues/194

处理 PR：https://github.com/Tencent/tdesign-vue/pull/200

**Comment by xiaosansiji** [comment]
已在 0.33.1 版本中修复
