### ISSUE TITLE
[Image] 组件支持 globalConfig 配置字段

### ISSUE THREAD

**Issue by honkinglin** [Tencent/tdesign-vue#2063]
### 这个功能解决了什么问题

缺少接收 `errorText` `loadingText` 全局配置字段

### 你建议的方案是什么

支持 `errorText` `loadingText` 字段全局配置

**Comment by xiaosansiji** [comment]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/7600149/215704263-c48e120f-efae-48b3-b5ee-ff848f223de9.png">
Image 和 ImageViewer 需要把现在 hard code 实现的内容 https://github.com/Tencent/tdesign-vue/blob/develop/src/image/image.tsx#L168
替换为支持全局配置的字符串变量方式，以满足多语言和其他用户全局配置诉求

**Comment by xiaosansiji** [comment]
https://github.com/Tencent/tdesign-vue/issues/2064
