### ISSUE TITLE
[Table] pagination onChange 点击分页会触发两次

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2066]
### tdesign-vue 版本

1.0.6

### 重现链接

https://stackblitz.com/edit/angular-nuzqzu-tpwndc?file=src/demo.vue

### 重现步骤

点击分页
<img width="604" alt="image" src="https://user-images.githubusercontent.com/8606851/215919561-85628a4b-4f52-44f1-bf5f-ec81aa13dafd.png">

### 期望结果

触发一次

### 实际结果

触发两次

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2130

**Comment by xiaosansiji** [comment]
fixed in 1.1.2
