### ISSUE TITLE
[Table] 可编辑表格点击报错

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#2072]
### tdesign-vue 版本

1.0.5

### 重现链接

https://codesandbox.io/s/cnlzcf?file=/src/demo.vue

### 重现步骤

官方demo中，点击非编辑单元格或者表格组件外面都报错
![image](https://user-images.githubusercontent.com/25051361/215981608-4e7bd9c4-2f71-43e0-a82b-6a111837ecae.png)

**Comment by chaishi** [comment]
这个是因为新版本的浏览器 突然去除了属性 `e.path`，tdesign-vue 新版本 `v1.0.6` 也已经做好了兼容，升级 tdesign-vue 版本可以解决问题。当前最新版本号为 `1.1.1`

<img width="458" alt="image" src="https://user-images.githubusercontent.com/11605702/218317000-cfbba8d7-7663-4e3e-8286-190fdc5523f4.png">
