### ISSUE TITLE
[TreeSelect] tips 属性值 无效

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2081]
### tdesign-vue 版本

1.0.7

### 重现链接

https://stackblitz.com/edit/angular-x2xj2f?file=src/demo.vue

### 重现步骤

tips 属性值 无效

### 期望结果

tips 属性值 有效

### 实际结果

tips 属性值 无效

**Comment by uyarn** [comment]
1.0.8 已支持

**Comment by Jiachang-Cai** [comment]
> 1.0.8 已支持

slot 记得支持下

**Comment by uyarn** [comment]
> > 1.0.8 已支持
> 
> slot 记得支持下

下个版本 selectinput底层统一支持
