### ISSUE TITLE
[Table] empty内容宽度异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2082]
### tdesign-vue 版本

1.0.6

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-s2obde?file=/src/demo.vue

### 重现步骤

1. 点击测试按钮
2. 查看empty内容
![image](https://user-images.githubusercontent.com/16223845/216220188-bc36af31-dfe0-4604-a14e-3a16682f076f.png)

### 期望结果

empty内容水平居中

### 实际结果

empty内容居中且垂直展示

**Comment by chaishi** [comment]
我处理下。

当前解决方案：可以在 Dialog 动画完成后再渲染表格，可以获取到正常宽度。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2130

**Comment by xiaosansiji** [comment]
fixed in 1.1.2
