### ISSUE TITLE
[table] 希望支持通过filterIcon插槽实现不同列配置不同的图标

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue#2088]
### 这个功能解决了什么问题

希望支持通过filterIcon插槽实现不同列配置不同的图标，目前只能设置一种图标
<template #filterIcon>
        <t-icon :name="'search'" />
</template>

### 你建议的方案是什么

希望能让我读取到row内的属性，这样我就能判断使用什么图标了
<template #filterIcon=”{row}“>
        <t-icon :name="'row.colKey === 'name' ? 'serach' : 'filter''" />
</template>

**Comment by chaishi** [comment]
支持

**Comment by jieyuming** [comment]
> 支持

是已经支持，我写法不对，还是准备支持？感谢回答

**Comment by chaishi** [comment]
是准备支持

resolved in https://github.com/Tencent/tdesign-vue/pull/2251

**Comment by uyarn** [comment]
supported in 1.2.4
