### ISSUE TITLE
[Table] 固定列表格动态设置columns报错

### ISSUE THREAD

**Issue by thinkanymore** [Tencent/tdesign-vue#2089]
### tdesign-vue 版本

1.0.8

### 重现链接

https://github.com/thinkanymore/tdesign-table-demo

### 重现步骤

npm i
npm run dev

### 期望结果

未影响功能，希望去掉不必要报错

### 实际结果

<img width="778" alt="image" src="https://user-images.githubusercontent.com/20251612/216260900-a22776f6-64ff-4de0-9af0-c9ede864ad29.png">

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(108.0.5359.124)

### 系统版本

MasOS(12.4 )

### Node版本

v12.6.0

**Comment by chaishi** [comment]
我处理下

**Comment by uyarn** [comment]
published 1.1.0
