### ISSUE TITLE
select 多选模式，点击外面两次，下拉框才能关闭

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#209]
**Describe Framework**

tdesign-vue

**Describe Environment**
0.33.0
Add browser version here
![image](https://user-images.githubusercontent.com/15682051/148876121-1f7738b5-7859-4c37-b8ae-a9cd63b4baf3.png)

**Describe the bug**
select 多选模式，点击外面两次，下拉框才能关闭
**Additional context**
![image](https://user-images.githubusercontent.com/15682051/148876230-270a4371-94f2-4810-afbe-dea9e6554362.png)

复现地址：https://tdesign.tencent.com/vue/components/select

**Comment by geff1991** [comment]
#128 一个原因，相关同事已排期 在排查中

**Comment by geff1991** [comment]
https://github.com/Tencent/tdesign-vue/pull/329

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
