### ISSUE TITLE
t-select 多个选项选中时，显示框不会自动变高，导致第二行内容不可见。

### ISSUE THREAD

**Issue by yangshangchao23** [Tencent/tdesign-vue#2095]
### tdesign-vue 版本

@gtff/tdesign-gt-vue:"0.1.25"
tdesign-vue: "0.52.3-alpha.1"

### 期望结果

像官网的案例一样，可以换行完整显示第二行选项。

### 实际结果

显示框高度没有变，第二行的选项被遮挡

### 框架版本

Vue 2.6.11

### 系统版本

windows10

**Comment by uyarn** [comment]
0.x的版本不会再长期维护了 目前LTS的版本是1.x的 且比较稳定 麻烦升级上来使用
