### ISSUE TITLE
源码进行编译不通过

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue#2098]
### tdesign-vue 版本

源码build后一直报错，人疲了

### 重现步骤

直接下载官网的源码（同时初始化子仓库git submodule init），通过npm i直接进行安装，然后什么都不修改，执行npm run build始终无法编译
### 错误1
![微信截图_20230203173058](https://user-images.githubusercontent.com/26049430/216564697-0542d84b-93df-45ac-a5f0-b3780b945949.png)
### 错误2
![微信截图_20230203173312](https://user-images.githubusercontent.com/26049430/216564719-c25b1aaa-4587-4d34-a9d7-fbc5422bb7e8.png)

### 期望结果

顺利编译成功

### 实际结果

各种报错

### 框架版本

vue2.6.10

### Node版本

14.21.1

**Comment by uyarn** [comment]
删除submodule的node_modules即可。

**Comment by raohuiyong** [comment]
@uyarn 真是一个令人头痛的问题，按照你的方法删除后，又有新的错误
![image](https://user-images.githubusercontent.com/26049430/216865614-7516e41b-7ce3-4dfe-bc46-96f32fdafb28.png)

**Comment by uyarn** [comment]
> @uyarn 真是一个令人头痛的问题，按照你的方法删除后，又有新的错误 ![image](https://user-images.githubusercontent.com/26049430/216865614-7516e41b-7ce3-4dfe-bc46-96f32fdafb28.png)

这个应该是windows上路径的问题 看起来rollup这个插件没有针对windows做兼容 我处理下

**Comment by kingzez** [comment]
> > @uyarn 真是一个令人头痛的问题，按照你的方法删除后，又有新的错误 ![image](https://user-images.githubusercontent.com/26049430/216865614-7516e41b-7ce3-4dfe-bc46-96f32fdafb28.png)
> 
> 这个应该是windows上路径的问题 看起来rollup这个插件没有针对windows做兼容 我看看能不能处理下 如果你需要构建这个项目 可以在非windows的机器上尝试。

rollup-plugin-ignore-import 这个插件不兼容 windows，有什么解决方案吗？看了下他的 repo，也没有特殊的写法。
