### ISSUE TITLE
[Avatar] 图片头像的 size 失效

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue#2099]
### tdesign-vue 版本

1.0.8

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-7ox1qn?file=/src/demo.vue

### 补充说明

![Snipaste_2023-02-03_22-39-36](https://user-images.githubusercontent.com/54493910/216631243-10e49452-7633-407c-bb9b-d7df9fe81fc8.png)

**Comment by uyarn** [comment]
published 1.1.0
