### ISSUE TITLE
[DropDown] 下拉菜单中使用 Dialog 组件，Dialog 组件失控

### ISSUE THREAD

**Issue by Joey-J3** [Tencent/tdesign-vue#2107]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-ynus3h?file=/src/demo.vue

### 重现步骤
1. 下拉菜单中点击打开弹窗
2. 点击右上方 close 按钮

### 期望结果
1. 打开弹窗后等待 3s，loading 状态变更为 "内容"；
2. 点击 close 弹窗消失

### 实际结果
1. loading 状态没有变更；
2. 点击 close 按钮无响应；

### 补充说明
dialog 放到 dropdown 外面就没有这个问题，初步判断是菜单消失后删除了 vnode 子节点，导致 dialog 失控。

| Environment | Info |
|---|---|
| 相关版本 | 0.49.3 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | MacOS(Ventura 13.2)、Chrome(109.0.5414.119) |
| Node版本 |  |

**Comment by vkm0303** [comment]
应该也不算bug，出现这种情况的原因是由于`t-dropdown`组件中使用`popup`组件时默认`destroyOnClose的值为`true`，通过透传属性给popup即可
```vue
<t-dropdown :popupProps="{ destroyOnClose: false }"></t-dropdown>
```

**Comment by ccccpj** [comment]
确实如此
