### ISSUE TITLE
[Image] 希望支持 click 事件 和 图片预览

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue#2108]
### 这个功能解决了什么问题

API 补全

### 你建议的方案是什么

参照 element image 的 preview-src-list 参数：https://element.eleme.cn/#/zh-CN/component/image

**Comment by chaishi** [comment]
图片预览请使用 ImageViewer，为保障组件按需引入，不会给 Image 组件重复添加预览。
