### ISSUE TITLE
[DateRangePicker] 如何设置默认结束时间为 23：59：59

### ISSUE THREAD

**Issue by qyhever** [Tencent/tdesign-vue#2112]
### tdesign-vue 版本

1.0.3

### 重现步骤
```vue
<t-date-range-picker
  v-model="params.effectiveDate"
  :placeholder="['开始时间', '结束时间']"
  valueType="YYYY-MM-DD HH:mm:ss"
  enableTimePicker
  clearable
/>
```

### 期望结果
如何实现结束日期 的时间部分默认为23:59:59，这样就不用拉到最底下选择 23:59:59 的时间了
![image](https://user-images.githubusercontent.com/35389587/217185206-4fdefad0-56d9-46c0-be32-d6dd1962407c.png)
_No response_

**Comment by honkinglin** [comment]
看起来得新增一个 `defaultTime` 来控制时间选择器的默认值

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue/pull/2215

**Comment by uyarn** [comment]
support in 1.2.1
