### ISSUE TITLE
[Tooltip] 当content为空时，还存在黑色背景

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2118]
### tdesign-vue 版本

1.0.8

### 重现链接

https://stackblitz.com/edit/angular-lp59wa?file=src%2Fdemo.vue

### 重现步骤

1. 输入框聚焦
<img width="975" alt="image" src="https://user-images.githubusercontent.com/16223845/217458268-2be30e92-e6fd-402f-875f-4c02f1533a1e.png">

### 期望结果

content为空时黑色背景隐藏

### 实际结果

content为空时还存在黑色背景

**Comment by chaishi** [comment]
当前解决方案：可以先试用 Popup 组件代替，Popup 没有这个问题
