### ISSUE TITLE
[TreeSelect] 选择框首次聚焦，下拉框快速闪过

### ISSUE THREAD

**Issue by xiuse-liutao** [Tencent/tdesign-vue#2123]
### tdesign-vue 版本

1.1.0

### 重现链接

https://codesandbox.io/embed/tdesign-vue-demo-jlz0xb?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

1. tree-select的输入框失焦状态下点击输入框

### 期望结果

1. 下拉项显示

### 实际结果

下拉项隐藏

### 框架版本

2.6.14

### 浏览器版本

Chrome(110.0.5481.77)

### 系统版本

win10

### 补充说明

官网体验时发现

**Comment by chaishi** [comment]
信息已收到，我们处理下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2126
