### ISSUE TITLE
[Table] 行高改变时，virtual scroll卡顿

### ISSUE THREAD

**Issue by ifAandBisC** [Tencent/tdesign-vue#2135]
### tdesign-vue 版本

1.1.1

### 重现步骤

企业微信 flyswifxjsu

### 实际结果

滚动结束后，会卡顿两次，并位移，估计是虚拟滚动的位置计算bug

### 框架版本

vue2

**Comment by ifAandBisC** [comment]
tx内部的，留了企业微信ID，我跟sheepluo沟通过了，可以找我发下录屏

github-actions[bot] ***@***.***> 于2023年2月13日周一 17:20写道：

**Comment by chaishi** [comment]
预计本月底或下月初处理

**Comment by ifAandBisC** [comment]
辛苦👍

sheepluo ***@***.***> 于2023年2月15日周三 22:24写道：

**Comment by chaishi** [comment]
时间有限，一直没能找到合适的时间处理。

解决方案：可以在行高改变的时候，重新拉取数据，让表格重新渲染。（每一次的新数据，只会渲染前面几十行，不会卡顿）
