### ISSUE TITLE
[table] table没有处理容错处理

### ISSUE THREAD

**Issue by taovicky** [Tencent/tdesign-vue#2136]
### tdesign-vue 版本

最新版

### 期望结果

不要出现报错，需要兼容处理一下，value存在时，再去调用该方法

### 实际结果

<img width="1634" alt="企业微信截图_58e2887c-6f75-4cf2-94f7-770bd1429e6b" src="https://user-images.githubusercontent.com/24447967/218441313-069844e3-279e-4b25-bcff-a0da9af4db8d.png">

### 框架版本

Vue2.26

**Comment by chaishi** [comment]
这个问题之前有同学处理过了，检查一下你的版本号是不是太老了。

https://tdesign.tencent.com/vue/changelog

这里有所有的版本号

**Comment by chaishi** [comment]
或者提供一下可以复现你看到的问题的 demo

**Comment by taovicky** [comment]
tdesign-vue 1.0.8版本，我升级一下最新版1.1.1试一下

**Comment by uyarn** [comment]
这是<0.48.1的版本存在的问题 后面的版本已经加上可选链了 可以打开报错的文件 最上方是有注入tdesign@x.y.z的版本信息的 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/26377630/218456547-5fd08dde-1c71-4449-a2aa-d634c41c91c6.png">
