### ISSUE TITLE
[ColorPicker] 新增参数控制渐变色梯度不再增加

### ISSUE THREAD

**Issue by mdxiaohu** [Tencent/tdesign-vue#2139]
### 这个功能解决了什么问题

业务场景：
1.假如，现有数据10条，在地图大屏上分级展示，有个渐变的颜色过渡。
2.用户使用ColorPicker渐变色选择器，可以调整渐变色的开始颜色和结束颜色。
3.当用户调整完渐变色后，ColorPicker选择器的值仅有两种颜色，linear-gradient(45deg, 颜色一 0%, 颜色二 100%)。
4.前端拿到ColorPicker选择器的值，过滤出颜色一和颜色二，再根据数据进行颜色赋值即可完成过渡颜色效果。

用户体验：
现有ColorPicker渐变色选择器，当用户去点击顶部渐变滑块的时候，操作变成了新增渐变色梯度，则ColorPicker渐变色选择器的值变为了linear-gradient(45deg,颜色一 0%,颜色二 100%,颜色三 100%...颜色四 100%)，似乎可以无限叠加渐变色梯度。一般业务场景渐变色选择器，常用是两种颜色，渐变开始颜色到渐变结束颜色。多梯度渐变色容易对用户使用造成困扰，用户本身只想改变渐变的开始颜色和结束颜色，但单点击顶部滑块后变为了新增颜色梯度，建议对该行为增加参数控制。
![微信图片_20230214100620](https://user-images.githubusercontent.com/42248614/218620536-15ca1457-11f2-4eb4-bb38-f983837c26bd.png)
![Snipaste_2023-02-14_10-08-35](https://user-images.githubusercontent.com/42248614/218620553-38456875-b1f7-4d41-b013-ad3256f62958.png)

### 你建议的方案是什么

增加ColorPicker选择器渐变色梯度控制属性，例如：gradient属性，当它的值为true时用户使用ColorPicker渐变色选择器的时候，点击顶部滑块可以新增渐变色梯度，为false的时候不可新增渐变色梯度，只允许用户修改已有的两种颜色。

当然如果想再完善一下的话，gradient属性的值为数字的时候，例如：:gradient="3", 则颜色梯度最多增加到3。我随便想的，这个额外的，可不采纳。

建议优先开发vue2版本~

**Comment by mdxiaohu** [comment]
@uyarn 日常催进度~加油啊，大兄弟~

**Comment by uyarn** [comment]
supported in 1.2.3
