### ISSUE TITLE
Form 组件 表单验证方法只可以在表单上触发吗？ 官方例子中都是在表单上触发的。

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#214]

**Comment by chaishi** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/11605702/148912705-5705adb5-8456-4c5a-ab3f-86112ff8f0ff.png">


可以直接自由触发，实例方法参考 API 文档 FormInstanceFunction，`this.$refs.form.submit();`

**Comment by chaishi** [comment]
如果后续没有疑问，辛苦关一下 issue

**Comment by codenotkey** [comment]
好的，感谢，官网中这里是不是写错了？
![image](https://user-images.githubusercontent.com/49895922/148913171-4facf6d0-2c65-4c9b-8f4e-a00868f7f63e.png)

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/223
