### ISSUE TITLE
[Table] hover头部出现首列右边框不对齐问题

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2141]
### tdesign-vue 版本

1.1.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-s2pbsy

### 重现步骤

1. 表格内容横向滚动
2. hover表头

<img width="674" alt="image" src="https://user-images.githubusercontent.com/16223845/218629966-a211920c-5a19-477e-bd64-df4bb3114bf7.png">

### 期望结果

首列的右边框对齐

### 实际结果

首列的右边框没有对齐

**Comment by chaishi** [comment]
信息已收到，我下一波处理 table 的一起看

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1197

fixed at `v1.2.2`
