### ISSUE TITLE
[Select] Select组件支持过滤的交互异常

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#2145]
### tdesign-vue 版本

1.1.1

### 重现链接

https://tdesign.tencent.com/vue/components/select#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

可过滤的选择框
1、选择一个选项
2、点击输入框，input的value不是变为空，而是变成所选的label值
3、删除输入内容，删至空时，input的value值自动变为所选项的label值

对比1.0.9和1.1.0版本，交互明显异常。

### 框架版本

vue 2.6

**Comment by uyarn** [comment]
1.1.1 tag-input逻辑影响

**Comment by xiaosansiji** [comment]
fixed in 1.1.3
