### ISSUE TITLE
[Message] 文档中 MessageOptions 相关属性不生效

### ISSUE THREAD

**Issue by KMethod** [Tencent/tdesign-vue#2149]
### tdesign-vue 版本

1.1.1

### 重现链接

https://codesandbox.io/embed/tdesign-vue-demo-forked-qhens1?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

Message 函数式调用中，MessageOptions 部分属性和文档说明不一致，设置不生效，如className、style、MessageProps等

**Comment by chaishi** [comment]
MessageProps 应该是正常的，链接里面的内容太多了，没有看出来具体哪一个 props 没有生效

**Comment by chaishi** [comment]
`className/style` supported in https://github.com/Tencent/tdesign-vue/pull/2151

预计下周发布

**Comment by xiaosansiji** [comment]
fixed in 1.1.3
