### ISSUE TITLE
[table] 表格数据较少时，吸顶滚动异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2153]
### tdesign-vue 版本

1.1.2

### 重现链接

https://stackblitz.com/edit/angular-cgnake-mpyfwg?file=package.json,src%2Fdemo.vue,package-lock.json

### 重现步骤

1、表格轻微向下滚动
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/16223845/219261288-a0445b0c-de72-4a27-bd99-37dff69b26c1.png">

### 期望结果

表格能正常吸顶

### 实际结果

表格头部不见了

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-cgnake-qejfvh?file=package.json,src%2Fdemo.vue,package-lock.json

这样写就好了，`headerAffixedTop.offsetTop` 是相对于滚动容器的位置，设置 `.wrap` 为滚动容器时，`headerAffixedTop.offsetTop` 的值应当为 `0`。

效果如下，


https://user-images.githubusercontent.com/11605702/221561681-d7e04ff2-2028-4f05-bba1-4b0d83002a8d.mov
