### ISSUE TITLE
[table] 可编辑单元格的表格，下拉选择、日期时间等组件进行操作时，会退出编辑状态

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#2155]
### tdesign-vue 版本

tdesign-vue 1.1.2

### 重现链接

https://tdesign.tencent.com/vue/components/table

### 重现步骤

1. 使用官方示例“可编辑的表格”，单元格编辑模式。
2. 不设置 `abortEditOnEvent` 属性，在官方示例中，第三列“申请事项”就没有使用这个属性（书写了但已被注释）。
3. 点击“申请事项”列的单元格，进入编辑状态。
4. 操作单元格内的下拉组件进行选择。

### 期望结果

由于没有指定 `abortEditOnEvent` 属性，因此在单元格进入编辑状态时，需要点击输入组件之外的区域，才会退出编辑状态。

在下拉选择组件中进行选择时，应当能正常操作。

### 实际结果

单元格内的下拉选择组件，无论点击什么选项，都会退出编辑状态。

对于多选下拉来说，每做一次操作，都会退出编辑状态。如果需要调整多个选项的选择，每次自动退出编辑后，需要再次点击进入编辑状态，重复操作多次，非常繁琐。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(109.0.5414.120)

### 系统版本

Windows 10

### Node版本

16.16.0

### 补充说明

1. 此问题不仅在下拉选择中存在，日期时间等组件也有相同问题。
2. 较旧的版本不会有这个问题。经过检查，发现 `1.0.5` 版本的功能还是正常的，从 `1.0.6` 版本开始出问题。

参考链接：
[1.0.5](https://1_0_5-tdesign-vue.surge.sh/vue/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC)
[1.0.6](https://1_0_6-tdesign-vue.surge.sh/vue/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC)

**Comment by chaishi** [comment]
经过验证，如果没有设置 `abortEditOnEvent: [‘onChange’]` 确实依然会退出编辑，我们处理下

**Comment by chaishi** [comment]
fixed at `v1.2.2`
