### ISSUE TITLE
[tree] 设置draggable时，支持对子节点的控制

### ISSUE THREAD

**Issue by dfgong** [Tencent/tdesign-vue#2156]
### 这个功能解决了什么问题

1、支持可以根据节点的信息决定该节点是否可拖拽
2、支持可以根据放置的节点的信息，决定是否可以放置
3、目前默认支持三种放置方式（放置在节点上方、下方、里面），提供可修改的配置策略。比如我现在的需求是叶子节点表示文件，非叶子节点表示文件夹，要求叶子节点不能在添加子节点，目前无法实现
4、顺带咨询下：通过appendTo、insertAfter、insertBefore、remove操作节点后，绑定的data的数据并没有变化，怎么可以获取操作后树对应的数据结构

### 你建议的方案是什么

无

**Comment by TabSpace** [comment]
1, 3 其实是同一个问题，调用 tree.setItem(value, {draggable: false}) 可以实现。
2，未做直接拦截，方案有待实现。有 onDrop 事件，紧急情况下可用还原数据的形式替代。
4，tree.getItems 可以获取全部节点，用节点 api 梳理后取得期望的树结构。

**Comment by uyarn** [comment]
tree item draggable的API已经新增 待发布
