### ISSUE TITLE
[select] 单选可过滤输入无法清除输入文字

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2157]
### tdesign-vue 版本

1.1.1

### 重现链接

https://tdesign.tencent.com/vue/components/select#%E5%8F%AF%E5%88%9B%E5%BB%BA%E6%96%B0%E6%9D%A1%E7%9B%AE%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

创建新条目并选中后，在输入框delete全部字符，输入框的值无法清除

### 期望结果

输入框置空

**Comment by uyarn** [comment]
1.1.1版本引入的问题 下个版本会修复

**Comment by xiaosansiji** [comment]
fixed in 1.1.3
