### ISSUE TITLE
能增加Table表头的吸顶功能吗

### ISSUE THREAD

**Issue by liugongxun** [Tencent/tdesign-vue#216]
目前大都采用设定表格高度的的固定表头做法，在不同屏幕分辩率下体验并不好。如果能再增加一个表头的吸顶功能，就完美了。

**Comment by chaishi** [comment]
怎么好像回复过这个 issue，还是有一模一样的 issue？

后续会支持的

**Comment by liugongxun** [comment]
太好了。
从TDesign Starter&nbsp;搬过来了。

**Comment by liugongxun** [comment]
邮件已收到

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365

**Comment by chaishi** [comment]
resolved in 0.39.1
