### ISSUE TITLE
[Table] 同一个页面两个table 分页组件会互相影响导致 点击分页严重卡顿

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2161]
### tdesign-vue 版本

1.1.1

### 重现链接

https://stackblitz.com/edit/angular-hig7h7?file=src/demo.vue

### 重现步骤

随便点击哪个table分页 两个table 数据都会改变  且点击会出现严重卡顿

a 表有分页 b 表没分页 也是会影响到 b表数据变动

### 期望结果

各自独立 不要互相影响

### 实际结果

随便点击哪个table分页 两个table 数据都会改变  且点击会出现严重卡顿

**Comment by chaishi** [comment]
待确认

**Comment by ccccpj** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/39974142/220959580-3fe99d26-4abf-4bcf-8b47-09072a6bb58e.png">
在您提供的示例中，表 1 中的 onPageChange 方法触发了 函数 fetchData()；同时您在 函数中 修改了 表 2 的数据所以 表 2 会有变化。
卡顿情况我猜有可能跟数据大小或者请求来源有关。
在下面这个示例中 两个表格 同时存在并拥有分页是显示正常的。
https://stackblitz.com/edit/angular-emtvt7?file=src%2Fdemo.vue

**Comment by Jiachang-Cai** [comment]
> <img alt="image" width="452" src="https://user-images.githubusercontent.com/39974142/220959580-3fe99d26-4abf-4bcf-8b47-09072a6bb58e.png">
> 
> 在您提供的示例中，表 1 中的 onPageChange 方法触发了 函数 fetchData()；同时您在 函数中 修改了 表 2 的数据所以 表 2 会有变化。 卡顿情况我猜有可能跟数据大小或者请求来源有关。 在下面这个示例中 两个表格 同时存在并拥有分页是显示正常的。 https://stackblitz.com/edit/angular-emtvt7?file=src%2Fdemo.vue

重现链接我调整了下  这个示例没搞好 你再点击第一个表的分页 会非常卡顿
