### ISSUE TITLE
[Dialog] 提示反馈类型弹窗确认按钮颜色异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2162]
### tdesign-vue 版本

1.1.2

### 重现链接

https://tdesign.tencent.com/vue/components/dialog#%E5%8F%8D%E9%A6%88%E7%B1%BB%E5%AF%B9%E8%AF%9D%E6%A1%86

### 重现步骤

1. 官网选择Dialog组件，滑至反馈类对话框
<img width="914" alt="image" src="https://user-images.githubusercontent.com/16223845/219993553-ea84ffcc-f27e-45f2-9ea7-dc22afe87f9d.png">

### 期望结果

反馈类对话框的确认按钮默认背景颜色为蓝色

### 实际结果

反馈类对话框的确认按钮默认背景颜色为白色

**Comment by xiaosansiji** [comment]
fixed in 1.1.3
