### ISSUE TITLE
[Upload] progess事件在windows上无法触发

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2167]
### tdesign-vue 版本

1.1.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-3vud6u

### 重现步骤

1. 点击选择文件
2. 查看控制台输出

### 期望结果

progess事件被触发

### 实际结果

progess无法触发

### 系统版本

windows 10

**Comment by chaishi** [comment]
原生的进度事件，只有大文件才会存在。
小文件，请设置模拟进度
