### ISSUE TITLE
[table] 右侧固定列且设置表格resizable 时，拖拽右边固定列修改宽度表现异常

### ISSUE THREAD

**Issue by KMethod** [Tencent/tdesign-vue#2168]
### tdesign-vue 版本

1.1.2

### 重现链接

https://codesandbox.io/s/o0w3nh?file=/src/demo.vue

### 重现步骤

官网demo即可复现

https://tdesign.tencent.com/vue/components/table#%E5%9B%BA%E5%AE%9A%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC

**Comment by uyarn** [comment]
fixed in 1.2.0
