### ISSUE TITLE
[Table] 表格列出现fixed时，初始没有出现横向滚动条，需要上下滚动表格才出现滚动条

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2175]
### tdesign-vue 版本

1.1.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-sqzvhm?file=/src/demo.vue

### 重现步骤

主要观察表格的横向滚动条

https://user-images.githubusercontent.com/16223845/220316069-d27dfc12-5a1c-45b2-bece-d632eb001b79.mp4

### 期望结果

表格列出现fixed时，能正常出现滚动条

### 实际结果

表格列出现fixed时，初始没有出现滚动条

### 浏览器版本

chrome110.0.5481.104

### 系统版本

windows 10

### 补充说明

不同特别注意浏览器版本

**Comment by chaishi** [comment]
v1.2.0 没有复现这个问题, issue close
