### ISSUE TITLE
[t-tree]树组件带过滤功能，进行过滤时无法收起命中的节点，无法展开命中的节点，展示其子级

### ISSUE THREAD

**Issue by yangshangchao23** [Tencent/tdesign-vue#2178]
### tdesign-vue 版本

1.1.3

### 重现步骤

树组件带过滤功能，进行过滤时无法收起命中的节点，无法展开命中的节点，展示其子级
已经设置了 expandOnClickNode 和 allowFoldNodeOnFilter都无法生效

### 期望结果

进行过滤时可以收起命中的节点，和展开命中的节点，展示其子级。

### 实际结果

进行过滤时无法收起命中的节点，无法展开命中的节点，展示其子级

### 框架版本

Vue 2.6.11

**Comment by ccccpj** [comment]
感谢反馈～后续可关注 issue #2164 的修复情况
