### ISSUE TITLE
[Tree] allowFoldNodeOnFilter属性设置为true无效

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2179]
### tdesign-vue 版本

1.1.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-pur8n5

### 重现步骤

1. 在输入框输入1.1
2. 点击展开收起图标没反应

**Comment by ccccpj** [comment]
感谢反馈～此问题会在 issue #2164 中统一处理修复

**Comment by huangpiqiao** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-pur8n5?file=/src/demo.vue
