### ISSUE TITLE
[组件名称] Select 选择器 

### ISSUE THREAD

**Issue by zhangkuangwen** [Tencent/tdesign-vue#2185]
### tdesign-vue 版本

1.1.3

### 重现步骤

当我使用t-select时会直接报错

### 实际结果

inject() can only be used inside setup() or functional components.

found in

---> <TSelect>
       <Header> at src/layouts/childrens/header.vue
         <THeader>
           <TLayout>
             <Index> at src/layouts/index.vue
               <App> at src/App.vue
                 <TConfigProvider>
                   <Root>

### 框架版本

Vue(2.6.11)

### 浏览器版本

edge(110.0.1587.50)

### 系统版本

windows10

### Node版本

14.2.0

**Comment by chaishi** [comment]
Vue2 发布了 Vue2.7.x，和 Vue2.6.x 存在不兼容更新。

这个错误是因为你实际安装了 Vue2.7，而 TDesign 仅支持 Vue.6.x。

https://tdesign.tencent.com/vue/getting-started
<img width="901" alt="image" src="https://user-images.githubusercontent.com/11605702/221541785-86facabd-5f67-4c7b-b471-82ccbd7ff78c.png">
<img width="967" alt="image" src="https://user-images.githubusercontent.com/11605702/221541824-ebe05cdb-e3ff-4919-b9bc-2146b98a51b0.png">
