### ISSUE TITLE
[Dialog] config-provider下配置dialog的confirmBtnTheme失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#2188]
### tdesign-vue 版本

1.1.3

### 重现链接

https://codesandbox.io/s/t9xfnr?file=/src/demo.vue

### 重现步骤

官网示例可复现，1.1.3版本confirmBtnTheme配置不起效， 1.1.2版本正常。

另外，在不配置confirmBtnTheme的时候，1.1.2版本默认dialog的确定按钮和dialog的theme一样；
查看figma设计的都是primary，是按figma调整成默认确定按钮都是primary的样式了吗？

### 期望结果

config-provider配置dialog的confirmBtnTheme起效

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

16.17.1

**Comment by uyarn** [comment]
fixed in 1.2.0
