### ISSUE TITLE
[cascader] value-type=‘full’、multiple、min-collapsed-num=“1” 三个参数同时使用控制台报错，组件卡死

### ISSUE THREAD

**Issue by zhangkeven** [Tencent/tdesign-vue#2203]
### tdesign-vue 版本

重现

### 重现链接

https://stackblitz.com/edit/angular-jh3pac?file=src%2Fdemo.vue

### 重现步骤

#<t-cascader
multiple
      :min-collapsed-num="1"
value-type="full"
/>
按照上述步骤调用级联组件，传入多选和折叠，并且value类型传入full，此时打开控制即可看到空指针，导致选择器无法回显所选内容

### 期望结果

期望多选、折叠、全路径三者可以同时使用，组件正常

### 实际结果

多选、折叠、全路径三者同时使用组件报错，空指针

### 框架版本

Vue2.6.11

### 浏览器版本

Chrome 109.0.5414.120

### 系统版本

Win10

### Node版本

v12.13.1

**Comment by xiaosansiji** [comment]
fixed in 1.2.7
