### ISSUE TITLE
[DateRangePicker] 日期区间选择器的面板不能正确地响应用户的输入值

### ISSUE THREAD

**Issue by guxi11** [Tencent/tdesign-vue#2204]
### tdesign-vue 版本

1.1.3

### 重现链接

https://codesandbox.io/s/m98zvl?file=/src/demo.vue

### 重现步骤

在日期区间选择器中输入日期时，月份有两种格式：填充0或者不填充。在所有的21（9x2+3）种月份的可输入值中，有两种输入是有问题的：01会选择12月，1会没有响应。下图展示的是其中一种情况。
<img width="623" alt="WeChatWorkScreenshot_82159f43-c9b6-44ed-b9ad-0a30cc978cb7" src="https://user-images.githubusercontent.com/21690043/222422371-1c14dbb0-7bdb-4014-9deb-25f0b3826ad1.png">
这看起来是个bug，因为日期选择器的面板能很好地理解当前的输入值，如下图所示。
<img width="286" alt="WeChatWorkScreenshot_44eedb02-b089-411b-ab4c-91b9f8e752c6" src="https://user-images.githubusercontent.com/21690043/222423754-7b9542ee-02d1-48d7-96e5-db7920a77e49.png">
日期无法被选中也是一个问题，这里用户对于输入交互的预期应该是和日期选择器一样的。
<img width="599" alt="WeChatWorkScreenshot_1627d240-976d-4f81-8c9b-432b29fdbc4c" src="https://user-images.githubusercontent.com/21690043/222424546-930c09dc-970f-47bb-ac17-6c0856e0a34d.png">

### 期望结果

期望日期区间选择器的面板能想日期选择器的那样，正确地响应用户的输入。

### 实际结果

不能正确反映输入月份和选中输入日期

### 框架版本

vue 2.6.14

### 浏览器版本

Chrome Version 110.0.5481.177 (Official Build) (arm64)

### 系统版本

macOS 12.2.1 (21D62)

### Node版本

16.16

**Comment by ccccpj** [comment]
感谢反馈，该问题已在 1.2.1 版本修复 建议升级至最新版本
