### ISSUE TITLE
[DateRangePicker] 周范围选择器，选择一年的最后一周的时候，开始和结束时间会互换位置

### ISSUE THREAD

**Issue by xzj5426** [Tencent/tdesign-vue#2207]
### tdesign-vue 版本

1.2.0

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker?tab=demo#周选择器

### 重现步骤

在年周范围选择器中，不选择当年最后一周的情况下，选择后，默认都是开始时间在前面，结束时间在后面。如下图
![QQ截图20230303131907](https://user-images.githubusercontent.com/35951641/222637917-3664bf8e-7983-46a0-b69f-59942114246a.png)
但是一旦选择了当年的最后一周，开始时间和结束时间的位置就会互换，变成结束时间在前面，开始时间在后面。如下图
![QQ截图20230303131926](https://user-images.githubusercontent.com/35951641/222638110-0a730a0c-d9fd-48ed-bf5c-b62960f7d02f.png)
**当前问题在官方文档中的示例就有出现**

### 期望结果

固定开始时间在前面，结束时间在后面

### 实际结果

开始时间和结束时间的位置在变换，这样的话，取开始时间和结束时间的时候，还需要对两者进行大小排序后再能正确获取开始和结束时间

**Comment by honkinglin** [comment]
我看下
