### ISSUE TITLE
引用CDN，Table表格边框线、斑马纹，不起作用

### ISSUE THREAD

**Issue by liugongxun** [Tencent/tdesign-vue#222]
引用CDN，Table表格边框线、斑马纹，不起作用。
![01](https://user-images.githubusercontent.com/12267517/149043844-ed4a3862-5d7e-4fca-a08f-6031a761cca3.png)
![image](https://user-images.githubusercontent.com/12267517/149043858-281122a3-f15f-4748-a634-16ba95a223d8.png)

强制加线后，表头有错位。
![image](https://user-images.githubusercontent.com/12267517/149043947-365ef9f4-9efd-4e69-a7a0-10327f3c62d4.png)
![image](https://user-images.githubusercontent.com/12267517/149043925-cd932587-6606-4090-9aaa-65f408a2d473.png)

**Comment by chaishi** [comment]
@xiaosansiji @uyarn  看看是不是样式打包的时候，漏了什么

**Comment by xiaosansiji** [comment]
已在 0.33.2 版本中修复，清空下浏览器缓存拉到新的 cdn 资源应该就可以了：https://codepen.io/xiaosansiji/pen/PoJxJaX
