### ISSUE TITLE
[TreeSelect] label 未实现

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2221]
### tdesign-vue 版本

1.2.0

### 重现链接

https://stackblitz.com/edit/angular-cwdn6f?file=src/demo.vue

### 重现步骤

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/8606851/223904731-a46648cb-155a-4133-a160-a93312fe755a.png">

### 期望结果

需要支持下

### 实际结果

没有支持

**Comment by xiaosansiji** [comment]
fixed in [1.2.2](https://github.com/Tencent/tdesign-vue/releases/tag/1.2.2)
