### ISSUE TITLE
[DatePicker] 控制台警告Invalid prop: custom validator check failed for prop "status".

### ISSUE THREAD

**Issue by zhaobo-98** [Tencent/tdesign-vue#2224]
### tdesign-vue 版本

1.2.1

### 重现步骤

使用DatePicker组件，控制台警告Invalid prop: custom validator check failed for prop "status".

found in

---> <TRangeInputPopup>
       <TDateRangePicker>

### 框架版本

2.6.12

### 系统版本

MacOS13.2.1

### Node版本

16.14.0

**Comment by ccccpj** [comment]
官网未复现您提到的告警，可以的话请尽量提供复现代码方便排查

**Comment by admin424344** [comment]
<t-date-range-picker v-model="" :presets="presets" allow-input enable-time-picker />
在使用时间区间选择器会出现，使用非时间区间选择时不会出现这个问题

**Comment by admin424344** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/49614720/224247847-09fe1575-c2f1-4686-b004-a78f1e9eb31c.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/49614720/224247767-706da608-4149-4f03-abeb-992df8b7d431.png">

**Comment by admin424344** [comment]
`<t-date-range-picker v-model="" :presets="presets" allow-input enable-time-picker />`

**Comment by ccccpj** [comment]
> 

https://stackblitz.com/edit/angular-qy8tnz?file=package.json,src%2Fdemo.vue
是了一下未复现，或者你在 stackblitz 上复现一下试试

**Comment by admin424344** [comment]
在选择时间的时候会报错：Invalid prop: type check failed for prop "selectedValue". Expected String with value "Wed Mar 08 2023 17:18:50 GMT+0800 (中国标准时间)", got Date

**Comment by isyoungxl** [comment]
版本 1.0.1 也会有，但奇怪的是 codesandbox并不会复现。鼠标滑动选择日期时会不停的报错 status

![image](https://user-images.githubusercontent.com/40622507/232696162-b9a292fb-8491-423a-99a2-a157893dfa15.png)

**Comment by liubiliubi** [comment]
`<t-popup placement="bottom">
      <svg-icon
        class="icon"
        icon-class="shaixuan"
        :class="visible || (value && value.length > 0) ? 'is-active' : ''"
      />
      <template #content>
        <t-date-range-picker
          v-model="value"
          allow-input
          :presets="presets"
          enable-time-picker
        />
      </template>
    </t-popup>`

我在使用el-date-range-picker同样遇到了这个报错，与原作者不同的是在外面嵌了一层t-popup,用的版本库是"tdesign-vue": "1.2.1", "vue": "2.6.10"
![e18f95cb-b208-487d-b3b5-9443e97ecf71](https://github.com/user-attachments/assets/365b44a3-5970-419b-891d-96f0bb8cfd25)

**Comment by liubiliubi** [comment]
> `<t-popup placement="bottom"> <svg-icon class="icon" icon-class="shaixuan" :class="visible || (value && value.length > 0) ? 'is-active' : ''" /> <template #content> <t-date-range-picker v-model="value" allow-input :presets="presets" enable-time-picker /> </template> </t-popup>`
> 
> 我在使用t-date-range-picker同样遇到了这个报错，与原作者不同的是在外面嵌了一层t-popup,用的版本库是"tdesign-vue": "1.2.1", "vue": "2.6.10" ![e18f95cb-b208-487d-b3b5-9443e97ecf71](https://private-user-images.githubusercontent.com/145520617/353667449-365b44a3-5970-419b-891d-96f0bb8cfd25.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTI1MzMsIm5iZiI6MTcyMjM5MjIzMywicGF0aCI6Ii8xNDU1MjA2MTcvMzUzNjY3NDQ5LTM2NWI0NGEzLTU5NzAtNDE5Yi04OTFkLTk2ZjBiYjhjZmQyNS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDIxNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBkZGU0ZTk0OWM2YjNkY2YxMGMzZDhmYjNlY2QyMjE5MjYzMGQ4ZjQ4Yzg3OGQyODQ2NDk3N2RjNzE0NGVmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QBn2nMz2i7rpzfJsZy_LSClgD73Qh1_hkZ0HNhdM1Vk)
