### ISSUE TITLE
[Select] 以slot方式传入的t-option元素，会校验tag，能否支持自定义

### ISSUE THREAD

**Issue by sc-qh** [Tencent/tdesign-vue#2226]
### 这个功能解决了什么问题

https://github.com/Tencent/tdesign-vue/blob/develop/src/select/hooks/useSelectOptions.ts#L63
以slot方式传入的t-option元素，这行代码会检查componentOptions.tag
当我们以t-option为模板重新注册一个新的组件时，需要定义新的组件名，tag会被重写，导致无法渲染出来

示例：
https://codesandbox.io/s/tdesign-vue-demo-forked-s2k84c?file=/src/demo.vue

### 你建议的方案是什么

建议判断逻辑的tag支持自定义传参

**Comment by uyarn** [comment]
你把你自己封装的Option注册成t-option也可以解决吧？

**Comment by skytt** [comment]
或者是 t-option 组件不太好支持的场景是什么呢？如果只是样式上的需要，可以通过 slot 的方式传入节点到 t-option 中

t-select 组件本身会和 t-option 进行一些逻辑上的嵌套，自己封装的话可能还需要处理一下组件本身的逻辑，不太建议
