### ISSUE TITLE
[Upload]上传多次同一张图片，第三次以后点击上传无反应

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#2232]
### tdesign-vue 版本

1.2.1

### 重现步骤

官网示例：
基础图片上传（允许选择多张图片文件上传，最多只能上传 3 张图片），上传2次同一张图片以后，再次点击上传时能复现

### 期望结果

能上传成功

### 实际结果

上传多次以后，无反应

### Node版本

14.18.2

**Comment by yanxugong** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/35914225/226153294-7b7c14e6-8813-413c-8357-75a62f28baaa.png">
设置 allowUploadDuplicateFile 试试呢？
