### ISSUE TITLE
Tabs 选项卡切换时@change事件会触发两次

### ISSUE THREAD

**Issue by jerrywangalready** [Tencent/tdesign-vue#224]
**Describe Framework**

tdesign-vue

**Describe Environment**

macOS Big Sur 11.6.2
Chrome 97.0.4692.71

**Describe the bug**
Tabs 选项卡切换时@change事件会触发两次

**Additional context**

**Comment by chaishi** [comment]
报缺陷的时候，当前使用的组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号，组件库版本号


，组件库版本号 ，组件库版本号，组件库版本号，组件库版本号 很重要，一定要带上哦～ 感谢配合

**Comment by start940315** [comment]
麻烦把你的代码发一下，我来看看具体原因
