### ISSUE TITLE
[Form] 一个字段的校验存在多种触发类型时异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2242]
### tdesign-vue 版本

1.2.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-2k6ywr

### 重现步骤

1、输入'2222'
2、点击外部让input失焦，错误校验被清除了

https://user-images.githubusercontent.com/16223845/225540244-67015db5-a9e4-423b-9cc3-4b8d0d826347.mov

### 期望结果

错误校验没被清除

### 实际结果

错误校验被清除了

**Comment by Simon-He95** [comment]
@huangpiqiao  Setting trigger blur can solve this problem

**Comment by ccccpj** [comment]
trigger blur 的触发方式覆盖了 change，建议使用相同的触发方式 或者使用自定义校验规则
