### ISSUE TITLE
[Popup] 修改完时间以后，再次修改，只修改开始时间，点击空白处必须2次才会关闭日历

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#2245]
### tdesign-vue 版本

1.2.1

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker?tab=demo#%E6%97%A5%E6%9C%9F%E5%8C%BA%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

带快捷标签的日期选择器，
修改时间选择器以后，再次修改时间，先修改了开始时间，点击确定以后，鼠标点击其他空白处，点2次日期弹窗才会关闭

### 期望结果

点1次日期弹窗关闭

### 实际结果

点2次日期弹窗才会关闭

### 浏览器版本

版本 110.0.5481.178（正式版本） （32 位）

**Comment by 412826deng** [comment]
是否有主动关闭日期弹窗事件

**Comment by uyarn** [comment]
fixed in 1.2.4 by @ikeq
