### ISSUE TITLE
[select]修改选项以后，必须点击2次才会关闭下拉框

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#2246]
### tdesign-vue 版本

1.2.1

### 重现步骤

多选选择器，修改选项以后，必须点击2次才会关闭下拉框
![image](https://user-images.githubusercontent.com/24506873/225786266-b5dc318e-eb59-4dc7-8449-1ffb0faf9c5a.png)

### 期望结果

点击1次关闭下拉框

### 实际结果

点击2次关闭下拉框

**Comment by uyarn** [comment]
duplicate issue of popup https://github.com/Tencent/tdesign-vue/issues/2245
