### ISSUE TITLE
是否可以提供折叠组件

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#225]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YFAnt** [comment]
我早上看见了，他们有规划正在做

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150728491-bd9cfe4f-50e7-4af0-b6d6-d02ebb20d61e.png)

@sampsonliu  这是你们想要的折叠组件效果吗？

**Comment by colaiven** [comment]
> ![image](https://user-images.githubusercontent.com/11605702/150728491-bd9cfe4f-50e7-4af0-b6d6-d02ebb20d61e.png)
> 
> @sampsonliu 这是你们想要的折叠组件效果吗？

是我想要的，顺便适配下表单组件
![image](https://user-images.githubusercontent.com/46585176/153829338-69c74d8b-f357-4304-8032-441f3a59be84.png)
