### ISSUE TITLE
[DatePicker] 控制台警告 [Vue warn]: Invalid prop: type check failed for prop "selectedValue". Expected String, got Date

### ISSUE THREAD

**Issue by zhaobo-98** [Tencent/tdesign-vue#2253]
### tdesign-vue 版本

1.2.2

### 重现链接

https://stackblitz.com/edit/angular-cwdn6f-r8ff1k?file=package.json,src%2Fdemo.vue,src%2Findex.css

### 重现步骤

点击时间选择框后，鼠标移动改变位置，控制台会出现警告

### 框架版本

2.6.12

### 系统版本

MacOS13.2.1

### Node版本

16.14.0

**Comment by ccccpj** [comment]
代码中初始化数据有问题
<img width="518" alt="image" src="https://user-images.githubusercontent.com/39974142/226240749-30ce3084-4865-4237-96c5-ef042c0ea912.png">
与报错中描述一致
