### ISSUE TITLE
[cascader] 选择任意项的级联选择器，有时需要点击两次才能关闭弹出层

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#2254]
### tdesign-vue 版本

tdesign-vue 1.2.2

### 重现链接

tdesign vue 官方示例：选择任意一项的级联选择器

### 重现步骤

点击级联选择器，点击选择任意项目。

### 期望结果

选中项目后，点击空白处一次，就可以关闭级联的弹出层，确认选择。

### 实际结果

有时需要点击空白处两次，才能关闭弹出层并确认选择结果。

试验后发现：

- 弹出选择时，如果只点击一次就选中了目标选项，就需要点击空白处两次才能收起。
- 如果弹出选择时点击了不止一次才选中目标选项，那么在空白处点击一次就可以收起弹出层。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(109.0.5414.120)

### 系统版本

Windows 10

### Node版本

16.16.0

### 补充说明

希望能改进这个特性，无论什么情况，点击空白处一次就可以关闭弹出层并确认选择结果，保证交互一致。

**Comment by uyarn** [comment]
是popup的问题 已经fixed 待发布 看看这个效果是不是正常
https://preview-pr2247-tdesign-vue.surge.sh/vue/components/cascader
