### ISSUE TITLE
[Tabs] theme card 缺少外边框 不知是否合理

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2259]
### tdesign-vue 版本

1.2.2

### 重现链接

https://stackblitz.com/edit/angular-tuckmx?file=src/demo.vue

### 重现步骤

<img width="607" alt="image" src="https://user-images.githubusercontent.com/8606851/226283749-8cb9a851-08f2-43d2-b9ef-7155b03f7af4.png">

### 期望结果

<img width="743" alt="image" src="https://user-images.githubusercontent.com/8606851/226283811-ab3f545d-8c8d-41c4-9be1-5a15617a6728.png">

### 实际结果

缺少外边框

**Comment by Wen1kang** [comment]
@Jiachang-Cai TD在设计之初就是没有顶描边的哦，我们不太建议卡片主题的tab使用在页面外，希望是在页面内使用（并且上是顶边，没有padding），详情可以看组件的demo的实现形式，如果非要使用在外，需要自行覆盖样式。
