### ISSUE TITLE
[Feature Request] 需要一个Collapse折叠面板组件

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#226]
**Is your feature request related to a problem? Please describe.**
与缺陷无关

**Describe the solution you'd like**
希望能够提供一个TDesign风格的折叠面板组件，可通过点击按钮切换内部详细内容是否展开，具体的交互、设计类似于Element UI里面的Collapse组件，可参考链接
https://element.eleme.io/#/zh-CN/component/collapse

**Describe alternatives you've considered**
我理解是类似交互形式的组件已经属于比较通用且高使用频率的了，希望TDesign能推动开发一下；另外由于项目设计使用了类似的组件，亟需使用到，希望能尽快推动哈。

**Additional context**
暂无

**Comment by pattybaby110** [comment]
有的，设计已输出了准备开发

**Comment by uyarn** [comment]
duplicate of #225

**Comment by uyarn** [comment]
Duplicate of #225
