### ISSUE TITLE
[DatePicker] 日期手动输入值后，选择其他日期后，重新手动输入显示值有问题

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#2268]
### tdesign-vue 版本

1.2.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-nrh9c0

### 重现步骤

官网示例可复现：
1. 手动输入日期
2. 选择其他日期
3. 重新选择时，输入框中是第一次输入的日期，不是新的日期

https://user-images.githubusercontent.com/13745660/227824860-fd8a107c-8d56-4f3f-9a56-d7d16552223a.mov

### 期望结果

希望输入框中显示成当前选择的日期

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

16.17.1

**Comment by xiaosansiji** [comment]
fixed in 1.2.5
