### ISSUE TITLE
[Cascader] 下拉选项options能否支持自定义样式

### ISSUE THREAD

**Issue by Dh8888** [Tencent/tdesign-vue#2269]
### 这个功能解决了什么问题

UI框架：Vue2.x

TD版本：0.49.3

期望结果： 如题，cascader组件下拉选项的样式支持自定义

![image](https://user-images.githubusercontent.com/65747132/227872992-acfab14f-2e3a-4006-9f90-95fca172c8d4.png)

### 你建议的方案是什么

是否可以提供类似 selectinput panel 类似的属性，支持cascader下拉选项的样式自定义

**Comment by Dh8888** [comment]
请问td目前支持自定义cascade自定义下拉选项的样式吗
？

**Comment by uyarn** [comment]
> 请问td目前支持自定义cascade自定义下拉选项的样式吗 ？

理论上是要支持的

**Comment by uyarn** [comment]
supported in 1.3.2
