### ISSUE TITLE
[SelectInput]  筛选器输入框， backspace 行为异常

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#2272]
### tdesign-vue 版本

tdesign-vue 1.2.3

### 重现链接

官方范例“选中项数量超出的输入框”

### 重现步骤

使用 `SelectInput` 组件，将组件设置为允许输入，并且绑定内部输入框的 `change` 事件，对输入变化进行监听处理（例如官方范例“选中项数量超出的输入框”）。

1. 点击输入框获得焦点，输入一个字符，然后按下键盘上的退格键（ backspace ）。
2. 点击输入框获得焦点，输入多个字符，然后按退格键（ 多次 ）。

### 期望结果

1. 仅输入一个字符时，按一次退格键，应当删除刚才输入的字符，并且不产生其他后果。
2. 输入多个字符时，按退格键将输入全部删除之后，再按一次退格键，就可以删除前一个选中的标签。

### 实际结果

1. 仅输入一个字符时，按一次退格键，实际上不但删除了刚才输入的字符，而且将最后一个选中标签也删除了。
2. 输入多个字符时，按退格键将输入全部删除之后，再按一次退格键，没有产生任何效果。此时需要再多按一次退格键，才能删除前一个选中的标签。

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(109.0.5414.120)

### 系统版本

Windows 10

### Node版本

16.16.0

### 补充说明

查看组件的事件输出，可以看到：
1. 仅输入一个字符后按一次退格键， `change` 事件会额外产生一次 `trigger` 为 `"backspace"` 的输出。理论上此时只是删除了刚才输入的字符，不应当触发 `"backspace"` 事件。
2. 输入多个字符后，按退格键删除所输入的字符，例如输入 3 个字符后按 3 次退格键，按第 4 次退格键时，应当有 `"backspace"` 事件被触发，但实际上此时不会收到事件。需要按第 5 次退格键才会收到事件。

输入一个字符与多个字符，退格键的行为均有异常，而且表现出来的状态相反。

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue/issues/2261 和这个看起来是一个问题

**Comment by uyarn** [comment]
fixed in 1.2.4 by @chiyu1996
