### ISSUE TITLE
[Table]  columns align: "center" 内嵌 input、select 组件 如果设置内联width 无法居中是否合理

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2273]
### tdesign-vue 版本

1.2.3

### 重现链接

https://stackblitz.com/edit/angular-ngwat9?file=src/demo.vue

### 重现步骤
<img width="394" alt="image" src="https://user-images.githubusercontent.com/8606851/228173335-c9043cdb-6f2b-4f79-9936-ed3e83acbf01.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/8606851/228173037-fe9dd79b-faf1-4b9f-a25c-ef18bda4620e.png">

### 期望结果

能居中

### 实际结果

无法居中

**Comment by chaishi** [comment]
辛苦仔细看下`<t-input />` 的样式，是 `display: block`，不是内联元素。请设置 `<t-input style="width: 100%, margin: 0 auto" />` 居中显示
https://stackblitz.com/edit/angular-ngwat9?file=src%2Fdemo.vue

**Comment by Jiachang-Cai** [comment]
> 辛苦仔细看下`<t-input />` 的样式，是 `display: block`，不是内联元素。请设置 `<t-input style="width: 100%, margin: 0 auto" />` 居中显示 https://stackblitz.com/edit/angular-ngwat9?file=src%2Fdemo.vue
> 
> <img alt="image" width="464" src="https://user-images.githubusercontent.com/11605702/228594490-ff675c00-d419-4f9b-9a0a-d578d6568a9b.png">

arco 有做兼容 是否参考下？
