### ISSUE TITLE
[DatePicker] inputProps中的onChange、onBlur等事件无效

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2274]
### tdesign-vue 版本

1.2.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-zmvmej?file=/src/demo.vue

### 重现步骤

1. 选择新日期，没触发onChange事件
2. 触发失焦，没触发onBlur事件

### 期望结果

inputProps属性的所有事件能正常触发

### 实际结果

inputProps属性的部分事件无法触发

**Comment by ccccpj** [comment]
直接使用 DatePicker 的 API 就可以了
