### ISSUE TITLE
[DatePicker] DatePickerPanel 使用enable-time-picker属性添加timePick，时分秒的双向绑定无效

### ISSUE THREAD

**Issue by assemline** [Tencent/tdesign-vue#2279]
### tdesign-vue 版本

1.2.1

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker

### 重现步骤

DatePickerPanel 使用enable-time-picker属性添加timePick，时分秒的双向绑定无效

**Comment by xiaosansiji** [comment]
fixed in 1.3.0
