### ISSUE TITLE
[DatePicker] 时间戳提示

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2283]
### tdesign-vue 版本

1.2.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-i0cbwh?file=/src/demo.vue

### 重现步骤

选中时间后,再次打开选择面板出现错误提示

### 实际结果

![image](https://user-images.githubusercontent.com/29624966/228798716-b5c7f567-9a36-4d0c-b75d-af88491c5f8f.png)

### 框架版本

2.6

### 浏览器版本

edge

### 系统版本

windows

**Comment by xiaosansiji** [comment]
fixed in 1.2.7
