### ISSUE TITLE
[Form] 重置之后 data 中多了一个 undefined key

### ISSUE THREAD

**Issue by Joey-J3** [Tencent/tdesign-vue#2295]
### tdesign-vue 版本

0.43.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-bebdcv?file=/src/demo.vue

### 重现步骤

重置之后提交，查看控制台输出，打印出来的 data 中多了一个 undefined key

### 期望结果

表单值不应该有 undefined 

### 实际结果

`{name: "",
tel: "",
gender: "",
course: Array(0),
status: undefined,
undefined: undefined}`

### 框架版本

2.6.14

### 浏览器版本

Chrome(111.0.5563.146 (Official Build) (arm64))

### 系统版本

MacOS(12.6)

**Comment by Joey-J3** [comment]
切换到最新版本也有同样的问题 1.2.3

**Comment by xiaosansiji** [comment]
fixed in 1.2.5
