### ISSUE TITLE
[dreaw] 手动修改visible不会触发close事件

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2297]
### tdesign-vue 版本

1.2.4

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-4dv8wi?file=/src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/29624966/229678215-c1b9c23a-1d50-448a-baef-41e123143a42.png)
关闭事件是否应该值抽屉关闭,漏掉了单独修改visible事件?

### 期望结果

正常触发close事件

### 框架版本

2.6

**Comment by uyarn** [comment]
关闭事件是在具体动作上触发的 手动修改visible是你把drawer的可见属性受控了 不会触发的
