### ISSUE TITLE
cascader组件中popupProps无效

### ISSUE THREAD

**Issue by zhutengfei1990** [Tencent/tdesign-vue#230]
复现demo：
https://codesandbox.io/s/tdesign-vue-demo-forked-ds2l1?file=/src/demo.vue

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150727240-51ce7572-e06a-46a4-add8-dada10de6f2a.png)

https://codesandbox.io/s/tdesign-vue-demo-forked-cmm9g?file=/src/demo.vue

`v0.33.2` 版本已经实现支持 `popupProps`，showArrow 和 abc 类名都有，trigger: 'hover' 我们继续处理一下

**Comment by chaishi** [comment]
关于 `trigger: 'hover'` 无效问题，see https://github.com/Tencent/tdesign-vue/issues/334
