### ISSUE TITLE
Table 同时固定表头和列时样式缺失

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#231]
**Describe Framework**

tdesign-vue

**Describe Environment**

Chrome

**Describe the bug**
同时固定表头和列时，表格内容最后一行缺失border-bottom，线框未闭合，内容行过少时表现明显异常；同时最后一列缺失border-right。
https://tdesign.tencent.com/vue/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4%E5%92%8C%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC-1

**Comment by scope9Ri** [comment]
在线示例： https://codesandbox.io/s/tdesign-vue-demo-forked-nzb50?file=/src/demo.vue

**Comment by realyuyanan** [comment]
![image](https://user-images.githubusercontent.com/22365107/149269969-60e5a0b1-81cf-42df-a399-c1e5eca15948.png)
![image](https://user-images.githubusercontent.com/22365107/149270009-1d033e5a-e8a0-4877-b05f-8aa0a83a7bf9.png)

楼主说的是表格内容高度比`height`小的情况吗？看起来是正常的，推荐maxHeight

**Comment by scope9Ri** [comment]
> ![image](https://user-images.githubusercontent.com/22365107/149269969-60e5a0b1-81cf-42df-a399-c1e5eca15948.png) ![image](https://user-images.githubusercontent.com/22365107/149270009-1d033e5a-e8a0-4877-b05f-8aa0a83a7bf9.png)
> 
> 楼主说的是表格内容高度比`height`小的情况吗？看起来是正常的，推荐maxHeight

设置`height`或`maxHeight`之后最后一行样式被设置为border-bottom:0，应该保留border-bottom: 1px soilid;最后一列border-right被设置为0，我觉得仍然应该保留1px。
 另外在内容高度大于或等于设置高度时，会出现两个border-bottom重合的情况，这种情况需要特殊处理。

**Comment by realyuyanan** [comment]
> 

是期望这样？
![image](https://user-images.githubusercontent.com/22365107/149912645-e71b9f43-b229-4833-9bc9-c8543802c582.png)

**Comment by chaishi** [comment]
@scope9Ri 什么样的业务场景需要这样的 UI 效果呢？

**Comment by chaishi** [comment]
resolved in `v0.39.1`
