### ISSUE TITLE
日期快捷方式位置可以放在侧边吗？ 日期按周选后面会有嘛？

### ISSUE THREAD

**Issue by zhangningself** [Tencent/tdesign-vue#232]
![image](https://user-images.githubusercontent.com/26316530/149257706-0c6cdf59-0d32-4ef1-8a87-c5de50b6686d.png)
![image](https://user-images.githubusercontent.com/26316530/149257788-8d2501bc-eec3-4bd5-806b-8f1c24be9e7a.png)
![image](https://user-images.githubusercontent.com/26316530/149257831-7bf73cbc-6554-4850-801e-e7baa7c5cced.png)

**Comment by xiaosansiji** [comment]
datepicker 的设计稿在重构，@Wen1kang 可以考虑下这里

**Comment by pattybaby110** [comment]
> datepicker 的设计稿在重构，@Wen1kang 可以考虑下这里

@Athenaqin

**Comment by Wen1kang** [comment]
后续会有这个能力的，我们正在改进datepicker的问题

**Comment by Athenaqin** [comment]
日期选择期的控件交互形式和布局，接下来会根据通用场景和用户使用频率的情况进行优化，快捷选择的能力会结合您的意见进行考虑。

**Comment by zhangningself** [comment]
好的

**Comment by zhangningself** [comment]
> 日期选择期的控件交互形式和布局，接下来会根据通用场景和用户使用频率的情况进行优化，快捷选择的能力会结合您的意见进行考虑。

好的

**Comment by zhangningself** [comment]
> 后续会有这个能力的，我们正在改进datepicker的问题

好的

**Comment by chaishi** [comment]
1. 以后会支持自由配置快捷日期的位置：上下左右
2. 是否支持周选择，正在和设计师沟通
