### ISSUE TITLE
[t-table] scroll 类型为 virtual 时 selected-row-keys 为空数组会导致table 选择框失效

### ISSUE THREAD

**Issue by 202780181** [Tencent/tdesign-vue#2321]
### tdesign-vue 版本

1.2.5

### 重现链接

https://codesandbox.io/s/divine-thunder-5qbvk2?file=/src/components/HelloWorld.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/27540653/231050132-7a5fae19-dd5b-49dc-9d54-3e4a1cf5156c.png)

1. 当设置selected-row-keys 属性时列表无法被选中，去掉此属性则正常选中

### 期望结果

在虚拟滚动的表格时选择框依然可用

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(112.0.5615.49)

### 系统版本

MacOS(13.0)

**Comment by chaishi** [comment]
```
<t-table :selected-row-keys.sync="selectedRowKeys" />
```

或者
```
<t-table :selected-row-keys="selectedRowKeys" @select-change="onSelectChange" />

function onSelectChange(val) {
  this.selectedRowKeys = val;
}
```
