### ISSUE TITLE
[table] 虚拟滚动的表格拖动列宽变更时表体列宽没有跟随调整

### ISSUE THREAD

**Issue by chuyueZhang** [Tencent/tdesign-vue#2327]
### tdesign-vue 版本

1.2.5

### 重现链接

https://tdesign.tencent.com/vue/components/table#%E8%99%9A%E6%8B%9F%E6%BB%9A%E5%8A%A8%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

https://user-images.githubusercontent.com/22291419/231382120-025dfdca-a51c-4ab6-8a61-df0470de41ff.mov

### 期望结果

拖动调整列宽时表体列宽跟随表头列宽一起调整

### 实际结果

拖动调整列宽时只调整了表头列宽，没有调整表体

### 框架版本

Vue2.7

**Comment by chaishi** [comment]
我试了下 "tdesign-vue": "1.4.8", 表现正常
https://stackblitz.com/edit/hy81er?file=src%2Fdemo.vue




https://github.com/Tencent/tdesign-vue/assets/11605702/d151f20a-f0de-4a6c-a044-372520351608
