### ISSUE TITLE
[Select] 1.2.5版本，t-select，里面传入t-option，再通过vue-cli-service(我是3.0.0版本)打包后(vue-cli-service build)无法正常显示下拉选项？

### ISSUE THREAD

**Issue by ArthurHsing** [Tencent/tdesign-vue#2330]
1.2.5版本，t-select，里面传入t-option(v-for渲染多个)，再通过vue-cli-service(我是3.0.0版本)打包后(vue-cli-service build)无法正常显示下拉选项？

本地跑(通过vue-cli-service serve)没问题，但是打包发到线上就有问题。是什么原因？

把传入t-option标签更改为options传入下拉配置在线上又可以正常显示了。

0.X版本不会有这个问题

1.X版本都有这个问题...

是什么原因呢...

vue 版本是2.6.14, vue-template-compiler也是2.6.14, vue-cli-service版本是3.12.1

**Comment by uyarn** [comment]
看看控制台有没有报什么错

**Comment by uyarn** [comment]
@ArthurHsing https://tdesign.tencent.com/vue/getting-started 
看来这个问题应该还是composition-api这个包引起的 刚刚发布的新版本已经带上了新的文档 这里有说明 如果用插件形式 还是需要手动引入这个包 不如构建的时候可能会因为这个包的缺失导致涉及的组件功能异常
<img width="841" alt="image" src="https://user-images.githubusercontent.com/26377630/231704266-0e39ab2a-faf9-4ced-879b-aa8b00673093.png">

**Comment by ArthurHsing** [comment]
> @ArthurHsing https://tdesign.tencent.com/vue/getting-started 看来这个问题应该还是composition-api这个包引起的 刚刚发布的新版本已经带上了新的文档 这里有说明 如果用插件形式 还是需要手动引入这个包 不然构建的时候可能会因为这个包的缺失导致涉及的组件功能异常 <img alt="image" width="841" src="https://user-images.githubusercontent.com/26377630/231704266-0e39ab2a-faf9-4ced-879b-aa8b00673093.png">

好的，我还没试过这种方法，不过还是感谢～
