### ISSUE TITLE
[DatePicker] 启用时间选择，value设置timestamp，点开panel，时间展示invalid Date

### ISSUE THREAD

**Issue by cz799** [Tencent/tdesign-vue#2331]
### tdesign-vue 版本

是

### 重现步骤

Sandbox网络报错，所有配置如下：

DatePicker props: 
· v-model="filterData.startTime"
· enable-time-picker
· allow-input
· clearable
· valueType="time-stamp"

data:
filterData = { startTime: 1681358714550 }

### 期望结果

panel中正常展示时分秒

### 实际结果

panel中展示invalid Date

### 框架版本

Vue2.6

### Node版本

16

**Comment by xiaosansiji** [comment]
fixed in 1.3.0
