### ISSUE TITLE
[select-input] 多选情况下就算allowInput为true也无法输入

### ISSUE THREAD

**Issue by Ericleungs** [Tencent/tdesign-vue#2336]
### tdesign-vue 版本

1.2.6

### 重现链接

https://tdesign.tencent.com/vue/components/select-input?tab=demo#%E5%A4%9A%E9%80%89%E7%AD%9B%E9%80%89%E5%99%A8%E8%BE%93%E5%85%A5%E6%A1%86

### 重现步骤

勾选是否允许输入，输入字符

### 期望结果

有字符输入

### 实际结果

无字符输入

**Comment by uyarn** [comment]
fixed 1.9.5
