### ISSUE TITLE
[Upload] theme="image" multiple 图片之前缺少间距，且文件名不可点击

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2338]
### tdesign-vue 版本

1.2.6

### 重现链接

https://stackblitz.com/edit/angular-eh1pvu?file=src/demo.vue

### 重现步骤

<img width="728" alt="image" src="https://user-images.githubusercontent.com/8606851/232361627-93e14519-49d3-48b0-8015-49eab09ff465.png">

### 期望结果

需要正常显示

### 实际结果

显示不正常

**Comment by chaishi** [comment]
尝试访问最新官网，问题应该已经解决。issue close
<img width="416" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/34679a32-b982-45fb-ab42-6d0562e67ade">

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/2568
support fileName can be clicked
