### ISSUE TITLE
[popup] HTMLElementis not defined

### ISSUE THREAD

**Issue by SungZYP** [Tencent/tdesign-vue#2340]
### tdesign-vue 版本

1.2.5 & 1.2.6

### 重现步骤

在Nuxt中全局引入tdesign-vue

### 期望结果

正常使用popup组件

### 实际结果

ReferenceError
HTMLElementis not defined

node_modules/tdesign-vue/cjs/popup/plugin.js
open in editor
657585960616263
665
6667
visibleState: false,
contentClicked: false
props: _objectSpread(_objectSpread([}， popup_props["default"])，[}，[
triggerEl: HTMLElement
10
computed:
hasTrigger: function hasTrigger() freturn triggerType(this.trigger);
Object../node_modules/tdesign-vue/cjs/popup/plugin.js@61:

### 框架版本

Vue(2.6.14), Nuxt(2.15.8)

### 系统版本

Windows10

### Node版本

14.18.0

**Comment by SungZYP** [comment]
![bfddcca9ef8f9309380493c775af4b7](https://user-images.githubusercontent.com/28947466/232661724-746dbccc-b202-4e1d-ae68-3dee65ed78c9.png)

**Comment by uyarn** [comment]
迭代中有地方没处理SSR 我们修复下 谢谢反馈

**Comment by xiaosansiji** [comment]
fixed in 1.2.7
