### ISSUE TITLE
[Dialog] vue2 没有实现  mode=full-screen

### ISSUE THREAD

**Issue by QL2023** [Tencent/tdesign-vue#2348]
### 这个功能解决了什么问题

"tdesign-vue": "1.2.6"

vue2 的 t-dialog 需要支持 mode=full-screen

### 你建议的方案是什么

https://codesandbox.io/s/tdesign-vue-demo-forked-dfox1l?file=/src/demo.vue

**Comment by xiaosansiji** [comment]
为 Vue2 版本实现 `Dialog.mode = full-screen` 特性，实现效果如 vue next： https://tdesign.tencent.com/vue-next/components/dialog

**Comment by QL2023** [comment]
有计划什么时候支持这个功能吗？

**Comment by uyarn** [comment]
published in 1.4.5
