### ISSUE TITLE
[Input] 快速输入字符，有些字符会被选中然后替换

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2350]
### tdesign-vue 版本

1.2.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-8ng1qn?file=/src/demo.vue

### 重现步骤

快速输入字符，可明显看到有被选中的字符

https://user-images.githubusercontent.com/16223845/233589579-a8e1b6ff-b873-49b6-a454-99c40422c19a.mov

### 期望结果

快速输入不会被覆盖某些字符

### 实际结果

快速输入导致某些字符被覆盖

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
