### ISSUE TITLE
[Select] 设置disabled之后已选择内容过长时无法查看到全部内容

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2351]
### tdesign-vue 版本

1.2.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-slowgj?file=/src/demo.vue

### 重现步骤

hover组件无法查看过长的内容

### 期望结果

希望能加个title，hover时能看到全部内容

### 实际结果

hover时看不到全部内容

**Comment by xiaosansiji** [comment]
fixed in 1.3.0
