### ISSUE TITLE
[Dropdown] 搭配t-head-menu後只能觸發一次

### ISSUE THREAD

**Issue by MarkGor** [Tencent/tdesign-vue#2352]
### tdesign-vue 版本

1.2.7

### 重现链接

https://stackblitz.com/edit/angular-asuhkv?file=src%2Fdemo.vue

### 重现步骤

搭配各種佈局組件，Dropdown 首次觸發正常，然後就沒然後了

### 期望结果

每一次都能觸發

### 实际结果

只觸發一次

### 框架版本

2.6.14

**Comment by uyarn** [comment]
请问使用场景是不是点击触发？
刚好公司内有业务遇到类似的问题 因为dropdown默认是hover触发 如果是通过点击触发 麻烦加下trigger="click" 否则会影响计算逻辑 在某些设备有影响

**Comment by uyarn** [comment]
如果还有问题 麻烦再开issue

**Comment by MarkGor** [comment]
> 请问使用场景是不是点击触发？ 刚好公司内有业务遇到类似的问题 因为dropdown默认是hover触发 如果是通过点击触发 麻烦加下trigger="click" 否则会影响计算逻辑 在某些设备有影响

抱歉，剛才看到，
當時可以測試的都試過，結果是一樣的，就如上面複現的demo，剛嘗試增加trigger="click"后，第一次沒問題，第二次選擇的時候不會觸發。

**Comment by MarkGor** [comment]
![image](https://github.com/Tencent/tdesign-vue/assets/2922335/0be95345-3ccd-43a5-b5ad-045ece9e3af3)
複現流程：
1、點擊t-head-menu，顯示了t-menu-item，隨便點擊選擇一個t-menu-item。 【此時觸發正常】
2、再次點擊t-head-menu，不顯示任何t-menu-item出來。

**Comment by uyarn** [comment]
> ![image](https://user-images.githubusercontent.com/2922335/251054943-0be95345-3ccd-43a5-b5ad-045ece9e3af3.png) 複現流程： 1、點擊t-head-menu，顯示了t-menu-item，隨便點擊選擇一個t-menu-item。 【此時觸發正常】 2、再次點擊t-head-menu，不顯示任何t-menu-item出來。

menu 没有trigger这个配置

**Comment by loganylwu** [comment]
<img width="1685" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26224399/0b471a5c-ff03-45fd-95ae-137db9c48453">

**Comment by xiaosansiji** [comment]
fixed in 1.5.0
