### ISSUE TITLE
[Table] 表格组件 SSR 服务端渲染报错

### ISSUE THREAD

**Issue by lgybetter** [Tencent/tdesign-vue#2355]
### tdesign-vue 版本

1.2.7

### 重现链接

https://codesandbox.io/p/sandbox/thirsty-morning-xp1q12?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A15%7D%5D

### 重现步骤

![image](https://user-images.githubusercontent.com/18067476/233881700-daf4e4fb-752a-48e2-8269-032e9e492dba.png)

### 期望结果

Table组件能够正常渲染不报错

### 实际结果

目前Table组件在SSR阶段使用了window变量，导致报错。

### 框架版本

Vue(2.6.14)

### 补充说明

![企业微信截图_16822641028106](https://user-images.githubusercontent.com/18067476/233881813-a479b991-d70e-4247-bc63-eb5fe7b967bb.png)
1.0.5 版本之前的 useResizeObserver 是没有 window 变量进行判断的，自从 1.0.6 版本后就开始有异常。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2357

**Comment by xiaosansiji** [comment]
fixed in 1.3.0
