### ISSUE TITLE
[t-input-adornment] t-input-adornment添加prepend或append的内容为空时，依旧存在灰色空区

### ISSUE THREAD

**Issue by Co-Kyo** [Tencent/tdesign-vue#2356]
### tdesign-vue 版本

1.2.7

### 重现步骤

- 官网示例codeSandbox进入 添加prepend或append内容为空时，出现灰色空白
![Snipaste_2023-04-24_10-03-40](https://user-images.githubusercontent.com/76800873/233885572-55dc152c-16ae-45a2-a9ad-12259a163813.png)

### 期望结果

![Snipaste_2023-04-24_10-23-53](https://user-images.githubusercontent.com/76800873/233885757-69768548-30e9-4606-ad63-36ad18e32fb3.png)

### 框架版本

vue2.6.14

### 浏览器版本

Chrome(112)

### 系统版本

windows10

**Comment by Co-Kyo** [comment]
### 期望结果补充
![Snipaste_2023-04-24_10-23-53](https://user-images.githubusercontent.com/76800873/233887144-134a082f-c2ec-4ef8-8b9c-4e543b1ec3cf.png)

**Comment by MarkGor** [comment]
`
:preappend="null"
`

**Comment by Co-Kyo** [comment]
> `:preappend="null"`
实测可以解决，但还是希望能够实现不需要改变数据类型的方法（当接收参数为字符串类型时，空字符串能够实现），我在补充一下期望效果吧
### 期望效果补充（2）
![Snipaste_2023-04-25_09-53-49](https://user-images.githubusercontent.com/76800873/234155543-54cb8e21-d9ea-4f5f-acfc-7e45640f0944.png)

**Comment by uyarn** [comment]
fixed 1.3.4
