### ISSUE TITLE
[Textarea 多行文本框] v-model绑定的值如果是动态获取重新赋值的，那么会导致autosize失效

### ISSUE THREAD

**Issue by zhanyabin** [Tencent/tdesign-vue#2358]
### tdesign-vue 版本

1.2.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-s0o5k4

### 重现步骤

<t-textarea
        v-model="test"
        placeholder="测试"
        :autosize="{ minRows: 1, maxRows: 3 }"
        :style="{ width: '200px' }"
      />

mounted() {
    setTimeout(() => {
      this.test = '11112312312312312312312312312312312312312312311231231231231231111231231231231231231231231231231231231231231123123123123123'
    }, 5000)
  },

就能复现改问题

### 期望结果

溢出应该最大三行。

### 实际结果

实际上只有一行。

### 框架版本

~2.6.14

### 浏览器版本

112.0.5615.138（正式版本） （64 位）

### 系统版本

win11

### Node版本

v14.21.0

**Comment by xiaosansiji** [comment]
fixed in 1.4.3
