### ISSUE TITLE
[t-input] 當type=number時產生錯誤

### ISSUE THREAD

**Issue by MarkGor** [Tencent/tdesign-vue#2361]
### tdesign-vue 版本

1.2.7

### 重现步骤

tdesign-vue.js?v=d4497699:24029:35，
`
.vxe-table--render-default .vxe-table--body-wrapper, .vxe-table--render-default .vxe-table--footer-wrapper{
	background-color: var(--td-bg-color-container);
}
    handleInput: function handleInput(e) {
      var _this5 = this;
      this.preValue = this.inputValue + e.data;
      var val = e.currentTarget.value;
      var preCursorPos;
      if (this.composingRef) {
        this.composingRefValue = val;
      } else {
        if (this.type !== "number") {
          val = this.getValueByLimitNumber(val);
        }
        emitEvent(this, "change", val, {
          e,
          trigger: "input"
        });
        if (!this.isIE) {
          var inputRef = this.$refs.inputRef;
          preCursorPos = inputRef.selectionStart;
          setTimeout(function() {
            **inputRef.selectionEnd = preCursorPos;**
          });
        }
        this.$nextTick(function() {
          _this5.setInputValue(_this5.value);
        });
      }
`

當input[type="number"]時候，是沒有selectionEnd 方法的，

控制台報錯：
DOMException: Failed to set the 'selectionEnd' property on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at http://localhost:3001/node_modules/.vite/deps/tdesign-vue.js?v=d4497699:24029:35
(匿名) @ input.tsx:373
setTimeout(异步)
handleInput @ input.tsx:372
invokeWithErrorHandling @ vue.runtime.esm.js:1863
invoker @ vue.runtime.esm.js:2188
original._wrapper @ vue.runtime.esm.js:6961

### 期望结果

不報錯

### 实际结果

報錯

### 框架版本

Vue2.6

**Comment by MarkGor** [comment]
上述代碼亂了，重新補充：
index.ts 355行:
`
    handleInput(e: InputEvent | CompositionEvent) {
      this.preValue = this.inputValue + e.data;
      let {
        currentTarget: { value: val },
      }: any = e;
      let preCursorPos: number;
      if (this.composingRef) {
        this.composingRefValue = val;
      } else {
        if (this.type !== 'number') {
          val = this.getValueByLimitNumber(val);
        }
        emitEvent<Parameters<TdInputProps['onChange']>>(this, 'change', val, { e, trigger: 'input' });
        // 受控，重要，勿删 input无法直接实现受控
        if (!this.isIE) {
          const inputRef = this.$refs.inputRef as HTMLInputElement;
          preCursorPos = inputRef.selectionStart;
          setTimeout(() => {
            inputRef.selectionEnd = preCursorPos;
          });
        }

        this.$nextTick(() => {
          this.setInputValue(this.value);
        });
      }
    },`

**Comment by MarkGor** [comment]
規避方案：使用input-number,theme="none"的方法避開

**Comment by chaishi** [comment]
<img width="523" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/88563374-483c-4fd8-b4cb-56c73388c9d9">
