### ISSUE TITLE
[Table] columns fixed 浏览器兼容和体验问题

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2362]
### tdesign-vue 版本

https://stackblitz.com/edit/angular-cjgqac?file=src/demo.vue

### 重现步骤

1. fixed colKey 如果重复会直接显示空白 虽然重复key是不合理的
<img width="412" alt="image" src="https://user-images.githubusercontent.com/8606851/234207610-cea1043d-0691-4c05-92c2-3475d168ea42.png">
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/8606851/234208554-c467d920-bb2f-4f0c-804a-ac6abb745d4d.png">

2. fixed 在Safari浏览器 如果不写width 当前列不显示
<img width="284" alt="image" src="https://user-images.githubusercontent.com/8606851/234207669-7dc5cfc8-d798-40dc-8106-06acf075d120.png">

**Comment by chaishi** [comment]
1. 暂不处理不存在 key 的情况
2. 不知道该如何复现
