### ISSUE TITLE
[TreeSelect 树选择 ]选中子集选项，文本框显示value值而不是name

### ISSUE THREAD

**Issue by wanda-feng** [Tencent/tdesign-vue#2365]
### tdesign-vue 版本

1.2.7能重现

### 重现链接
https://stackblitz.com/edit/angular-zrlwjw?file=src%2Fdemo.vue,package.json

_No response_

### 重现步骤

官网异步加载demo就能重现此问题：
异步加载
通过透传实现异步加载树节点

因为demo用的子节点的value,lable值是一样的，所以看不出问题，只要改成不一样的，就能重现问题，选中子节点后，离开焦点，再次点击select框，选中值会变成value,，而不是name

### 期望结果

选中子集后，文本框展示子集的name，而不是value，并且重新打开树，选中的子集节点为上一次打开状态，而不是每次又要重新从一级开始重新打开，才能最后定位到上一次选中的值

### 实际结果

选中子集，文本框显示的是value，不是name，每次重新打开树，都会自动关闭子集，又要重新一级一级的选下去，才能找到上一次选中的值

### 框架版本

2.6.10

### 浏览器版本

112.0.5615.138

**Comment by wanda-feng** [comment]
补充：选中子节点后，选中框先显示name值，失去焦点后，显示的就是value值

**Comment by uyarn** [comment]
fixed 1.3.2
