### ISSUE TITLE
[Watermark] 暗夜模式下水印文字被覆蓋了

### ISSUE THREAD

**Issue by MarkGor** [Tencent/tdesign-vue#2367]
### 这个功能解决了什么问题

官網示例，開啟暗夜模式，单行文本水印 模式下文字和背景色重複導致無法顯示，

### 你建议的方案是什么

希望能識別到暗夜模式情況下，增加filter:invert(80%)的css屬性對水印文字進行反色

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
