### ISSUE TITLE
[TreeSelect] filterable 无法精准定位搜索值

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2374]
### tdesign-vue 版本

1.3.0

### 重现链接

https://stackblitz.com/edit/tcara5?file=src/demo.vue

### 重现步骤

1.  应该显示无数据
<img width="777" alt="image" src="https://user-images.githubusercontent.com/8606851/235036006-f9295d24-46e3-4a33-8062-cc8e17d7a353.png">
2. 应该选中搜索值并隐藏其他选项
<img width="822" alt="image" src="https://user-images.githubusercontent.com/8606851/235036124-eaa802c7-e995-48f7-b928-6b4ec4f83c1a.png">

arco 正确示例
https://user-images.githubusercontent.com/8606851/235036446-171cf61f-bdfc-432a-bf87-aaa97c0b253c.mp4

### 期望结果

搜索不出问题

### 实际结果

搜索只能检索第一次后面输入无法检索

**Comment by uyarn** [comment]
fixed 1.3.2
