### ISSUE TITLE
[Select 选择器] 表单中使用多选选择器时折叠项无法正常显示

### ISSUE THREAD

**Issue by PyrrhaNkos** [Tencent/tdesign-vue#2378]
### tdesign-vue 版本

1.3.0

### 重现步骤

form中使用选择器，设置多选并且设置选中项折叠

### 期望结果

折叠tag正常显示

**Comment by uyarn** [comment]
没有复现出这个问题 麻烦你在这个codesandbox复现下这个issue 描述的问题 https://codesandbox.io/s/tdesign-vue-demo-forked-kjeyxl?file=/src/demo.vue:0-7589

**Comment by PyrrhaNkos** [comment]
感谢对于我提出的这个问题的反馈，我现在发现好像是因为我是循环生成的表单项，绑定的变量需要动态生成，无法在data中定义成数组形式导致的bug，不知道您对于这种使用场景，组件可否进行适配性改动。




EiKi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月29日(星期六) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378)





 
没有复现出这个问题 麻烦你在这个codesandbox复现下这个issue 描述的问题 https://codesandbox.io/s/tdesign-vue-demo-forked-kjeyxl?file=/src/demo.vue:0-7589

**Comment by PyrrhaNkos** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-5wwnv0?file=/src/demo.vue
引用的td上面form表单的demo，我不确定在定义的变量不是数组时是不是就会有这样的问题，如果是的话我期望可以取消这样的限制，因为我目前的使用场景定义无法提前定义，因为表单项式循环动态生成的。




EiKi
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月29日(星期六) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378)





 
你好 @PyrrhaNkos, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

**Comment by PyrrhaNkos** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-5wwnv0?file=/src/demo.vue
引用的td上面form表单的demo，我不确定在定义的变量不是数组时是不是就会有这样的问题，如果是的话我期望可以取消这样的限制，因为我目前的使用场景定义无法提前定义，因为表单项式循环动态生成的。




EiKi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EiKi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月29日(星期六) 晚上11:22
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378)



感谢对于我提出的这个问题的反馈，我现在发现好像是因为我是循环生成的表单项，绑定的变量需要动态生成，无法在data中定义成数组形式导致的bug，不知道您对于这种使用场景，组件可否进行适配性改动。




EiKi
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月29日(星期六) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378)





 
没有复现出这个问题 麻烦你在这个codesandbox复现下这个issue 描述的问题 https://codesandbox.io/s/tdesign-vue-demo-forked-kjeyxl?file=/src/demo.vue:0-7589

**Comment by uyarn** [comment]
> https://codesandbox.io/s/tdesign-vue-demo-forked-5wwnv0?file=/src/demo.vue 引用的td上面form表单的demo，我不确定在定义的变量不是数组时是不是就会有这样的问题，如果是的话我期望可以取消这样的限制，因为我目前的使用场景定义无法提前定义，因为表单项式循环动态生成的。 EiKi ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "EiKi" ***@***.***&gt;; 发送时间:&nbsp;2023年4月29日(星期六) 晚上11:22 ***@***.******@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;回复： [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378) 感谢对于我提出的这个问题的反馈，我现在发现好像是因为我是循环生成的表单项，绑定的变量需要动态生成，无法在data中定义成数组形式导致的bug，不知道您对于这种使用场景，组件可否进行适配性改动。 EiKi ***@***.*** &nbsp;
> ------------------ 原始邮件 ------------------ 发件人: "Tencent/tdesign-vue" ***@***.***&gt;; 发送时间:&nbsp;2023年4月29日(星期六) 晚上10:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tencent/tdesign-vue] [Select 选择器] 表单中使用多选选择器时折叠项无法正常显示 (Issue #2378) 没有复现出这个问题 麻烦你在这个codesandbox复现下这个issue 描述的问题 https://codesandbox.io/s/tdesign-vue-demo-forked-kjeyxl?file=/src/demo.vue:0-7589 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

了解了 这里其实有个非数组类型导致的问题 看起来在表单里还需要再优化一下 下周更新我们看看怎么修复它 谢谢反馈

**Comment by xiaosansiji** [comment]
fixed in v1.3.1
