### ISSUE TITLE
[DatePicker] 设置arrowInput后，键盘输入日期按enter确定，value多了一个空格

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2386]
### tdesign-vue 版本

1.3.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-3ukzy5?file=/src/demo.vue

### 重现步骤

1. 点击输入框，用键盘输入20220112，点击enter键确认
2. 选中控制台打印出来的value，明显可以看见最后面多出一个空格

<img width="295" alt="image" src="https://user-images.githubusercontent.com/16223845/236125053-00405cf0-d1f5-4878-b94e-cb8f9253c067.png">

### 期望结果

输出的值没有额外的空格

### 实际结果

输出的值多了额外的空格

**Comment by honkinglin** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/24469546/236214150-90543018-84c4-48b9-872e-ceb856fd1ff1.png">
