### ISSUE TITLE
[Select] 多选下拉框默认禁用,解开禁用clearable不生效

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2392]
### tdesign-vue 版本

1.3.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-pm798n?file=/src/demo.vue

### 重现步骤

且第一个示例全选后会无响应

### 框架版本

2.6

### 浏览器版本

laster

### 系统版本

windows

**Comment by uyarn** [comment]
"且第一个示例全选后会无响应" 这个是codesandbox的问题 忽略

**Comment by xiaosansiji** [comment]
fixed in v1.3.1
