### ISSUE TITLE
[t-select] 滚动触底事件不生效

### ISSUE THREAD

**Issue by 412826deng** [Tencent/tdesign-vue#2398]
### tdesign-vue 版本

1.3.0

### 重现链接

https://tdesign.tencent.com/vue/components/select?tab=demo#%E9%80%9A%E8%BF%87%E6%BB%9A%E5%8A%A8%E4%BA%8B%E4%BB%B6%E5%8A%A0%E8%BD%BD%E9%80%89%E9%A1%B9%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

select滚动触底事件不生效on-scroll-to-bottom

### 期望结果

select滚动触底事件生效

### 实际结果

select滚动触底事件不生效

### 框架版本

2.6.11

### 浏览器版本

版本 112.0.5615.138（正式版本） （32 位）

### 系统版本

Windows 10 专业版

### 补充说明

![image](https://user-images.githubusercontent.com/24506873/237014715-76efb7c7-1171-4e1c-b4d6-26d573a817fe.png)

**Comment by uyarn** [comment]
已知scrollTop在windows下的兼容问题 本周会修复

**Comment by xiaosansiji** [comment]
fixed in v1.3.1
