### ISSUE TITLE
[transfer] 支持draggable

### ISSUE THREAD

**Issue by ifAandBisC** [Tencent/tdesign-vue#2402]
### 这个功能解决了什么问题

目前的方案只能通过transfer + tree draggable 来实现，但触发drag后也不更新value数据 https://codesandbox.io/s/tdesign-vue-demo-forked-z57vxc?file=/src/demo.vue

期望直接支持draggable

### 你建议的方案是什么

期望直接支持draggable

**Comment by xiaosansiji** [comment]
Implemented in 1.5.0
