### ISSUE TITLE
多选框

### ISSUE THREAD

**Issue by duhaoranc** [Tencent/tdesign-vue#241]
多选框是否可以增加一种样式  按钮样式的多选框

**Comment by pattybaby110** [comment]
<img width="188" alt="image" src="https://user-images.githubusercontent.com/88708072/149464184-252636d3-01bd-4103-b7b9-88b9bfc09e9d.png">
类似这种吗？

**Comment by duhaoranc** [comment]
![1642147704(1)](https://user-images.githubusercontent.com/37980297/149473201-ec92c9c1-f9c9-48de-98e3-52566e9c94b1.png)
这种就ok啊

**Comment by chaishi** [comment]
Radio 这种不行，建议给一个参考图，示意一下

**Comment by xiaosansiji** [comment]
感觉更类似 tag？多选，但又是 button 形态：
可以选择的 tag
https://tdesign.tencent.com/vue/components/tag#%E5%8F%AF%E9%80%89%E6%8B%A9%E6%A0%87%E7%AD%BE

**Comment by duhaoranc** [comment]
![1642755090(1)](https://user-images.githubusercontent.com/37980297/150496275-de93c89b-97f0-4f21-9395-87013c0f3390.png)
elementui这种按钮多选框

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150726943-983822d1-764f-43dc-8c1c-cc39ba13f11e.png)

这个样式的按钮，看着怪怪的

**Comment by pattybaby110** [comment]
我大概明白意思，这要pmc 讨论一下
