### ISSUE TITLE
[treeSelect] 默认过滤规则异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2411]
### tdesign-vue 版本

1.3.1

### 重现链接

https://codesandbox.io/s/dstuds?file=/src/demo.vue

### 重现步骤

1. 输入“州”字
2. 再输入“广”字

https://github.com/Tencent/tdesign-vue/assets/16223845/510e58ff-2c1a-453d-bcee-d3565c167fae

### 期望结果

能正确搜索

### 实际结果

过滤结果不正确

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue/issues/2374

**Comment by huangpiqiao** [comment]
加了treeProps.allowFoldNodeOnFilter:true后，搜索默认收起了；应该默认展开才对 @uyarn

**Comment by uyarn** [comment]
fixed 1.3.2
