### ISSUE TITLE
什么时候能支持^2.7呢，有无计划时间

### ISSUE THREAD

**Issue by mark980828** [Tencent/tdesign-vue#2414]
### 这个功能解决了什么问题

什么时候能支持^2.7呢，有无计划时间

### 你建议的方案是什么

什么时候能支持^2.7呢，有无计划时间

**Comment by uyarn** [comment]
正在进行

**Comment by uyarn** [comment]
https://tdesign.tencent.com/vue/getting-started
<img width="869" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/c9ce1209-0950-474d-9cff-d3b88c0a0e4d">
2.7的支持已经发布版本了 欢迎使用

**Comment by mark980828** [comment]
> https://tdesign.tencent.com/vue/getting-started <img alt="image" width="869" src="https://user-images.githubusercontent.com/26377630/244583249-c9ce1209-0950-474d-9cff-d3b88c0a0e4d.png"> 2.7的支持已经发布版本了 欢迎使用



> https://tdesign.tencent.com/vue/getting-started <img alt="image" width="869" src="https://user-images.githubusercontent.com/26377630/244583249-c9ce1209-0950-474d-9cff-d3b88c0a0e4d.png"> 2.7的支持已经发布版本了 欢迎使用

nice
