### ISSUE TITLE
select[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by sizq-it** [Tencent/tdesign-vue#2416]
### tdesign-vue 版本

1.3.1

### 重现步骤

runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-props attributes (size) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <TSelectPanel ref=Ref< Proxy(Object) > size="medium" multiple=false  ... > 

### 实际结果

更新td版本致1.3.1后，使用select组件就会出现这个警告

### 框架版本

"vue": "^3.2.31"

### 浏览器版本

Chrome 113.0.5672.93（64 位）

### Node版本

v16.14.0

**Comment by uyarn** [comment]
提错仓库咯 这个是vue2的仓库 问题已经处理了 升级到1.3.3就可以了
