### ISSUE TITLE
[TreeSelect] 异步加载选择后再触发下来，输入框的值从label变成了value

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2417]
### tdesign-vue 版本

1.3.1

### 重现链接

https://stackblitz.com/edit/hayqw9?file=src%2Fdemo.vue

### 重现步骤

1. 点击输入框
2. 选择“选择1”=>"选择1.1"=>"选择1.1.1"
3. 再点击输入框

https://github.com/Tencent/tdesign-vue/assets/16223845/1b8b3671-f824-4510-ada6-dcc60f6235fd

### 期望结果

输入框能一直展示label的值

### 实际结果

再次选择时输入框变成了value的值

**Comment by uyarn** [comment]
fixed in 1.3.2
