### ISSUE TITLE
【table组件】首列数据跨行合并时会导致同行数据前移

### ISSUE THREAD

**Issue by sinbadmaster** [Tencent/tdesign-vue#242]
**Describe Framework**

tdesign-vue 0.33

**Describe Environment**

chrome 版本 97.0.4692.71

**Describe the bug**
table组件使用合并单元格功能时，首列数据跨行合并时，会导致同行的数据向左侧收缩。

**Additional context**
<img width="1490" alt="bug" src="https://user-images.githubusercontent.com/40019023/149462325-b74c7d91-f2d3-42cc-992c-85f69376c134.png">

**Comment by realyuyanan** [comment]
我看下

**Comment by sinbadmaster** [comment]
大佬 这个问题近期会发布新版本吗？

**Comment by realyuyanan** [comment]
> 大佬 这个问题近期会发布新版本吗？

应该会跟下一个版本发布。

**Comment by chaishi** [comment]
今天发布

**Comment by xiaosansiji** [comment]
已在 0.33.2 版本中修复
