### ISSUE TITLE
[StickyTool] 控制台报错以及sticky-item 不支持click 事件

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2421]
### tdesign-vue 版本

1.3.1

### 重现链接

https://stackblitz.com/edit/7bxg4m?file=src/demo.vue

### 重现步骤

控制台报错
<img width="1210" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/e3577e58-f8ba-46ad-a779-9ab8e3ea2c91">

无法给t-sticky-item 设置点击事件

### 期望结果

控制台报错 不报错
t-sticky-item 支持点击事件

### 实际结果

控制台报错 报错
t-sticky-item 不支持点击事件

**Comment by uyarn** [comment]
fixed 1.3.4
