### ISSUE TITLE
[t-timeline] 连线无法正常显示

### ISSUE THREAD

**Issue by qinshenxue** [Tencent/tdesign-vue#2425]
### tdesign-vue 版本

1.3.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-l2mgph?file=/src/demo.vue

### 重现步骤

```  html
    <t-timeline :layout="direction" mode="same">
      <t-timeline-item label="2022-01-01" :key="item" v-for="item in list"
        >事件一</t-timeline-item
      >
    </t-timeline>
```

如果list延迟赋值，t-timeline-item的连线无法正常显示。

![image](https://github.com/Tencent/tdesign-vue/assets/10354498/b55f5153-47d4-417d-8ae3-83ac3f505da2)

查看dom，每个item都有 -last class，导致不能显示连线

![image](https://github.com/Tencent/tdesign-vue/assets/10354498/e573a409-c2b2-4168-99cd-c4bc18d6dc1d)

### 期望结果

能够正常显示连线

### 实际结果

无法正常显示。

### 浏览器版本

chrome 113

### 系统版本

windows 10

### Node版本

nodejs 14

**Comment by xiaosansiji** [comment]
fixed in 1.4.2

**Comment by qinshenxue** [comment]
ok 👍👍
