### ISSUE TITLE
[t-table] 超出省略的内容省略号无法正常显示，cell中通过样式设置出现省略号之后，悬浮框又无法正确展示

### ISSUE THREAD

**Issue by PyrrhaNkos** [Tencent/tdesign-vue#2428]
### tdesign-vue 版本

1.3.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-u1c9vr?file=/src/demo.vue

### 重现步骤

columns配置项中通过cell自定义标签，设置样式之后，比如颜色等，省略号就无法展示，样式设置使省略号出现后，悬浮框又无法展示

### 补充说明

a标签不会受影响，但是其他标签似乎就会有影响，目前仅测试了p标签，其他标签未做尝试

**Comment by chaishi** [comment]
超出省略的条件有 2 个：
1. 要出现省略号的元素，必须是内联元素，即：`display: inline`。
2. 子元素内容超出父元素。（明确父元素是哪个，子元素是哪个，子元素相对于父元素有没有超出）

**Comment by chaishi** [comment]
按照示例代码的写法可以实现你的需求。
示例代码：https://codesandbox.io/s/tdesign-vue-demo-forked-x5pydf?file=/src/demo.vue
<img width="1344" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/3d162e4d-9329-4909-9c46-fc31e43a9ec5">
