### ISSUE TITLE
[Bug][Transfer] 两边穿梭框存在数据时，中间按钮样式出错

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-vue#243]
**Describe Framework**

tdesign-vue、tdesign-vue-next、tdesign-react

**Describe Environment**

Add browser version here：Chrome 97.0.4692.71

**Describe the bug**
两边穿梭框同时拥有勾选内容时，中间按钮激活后会跳动挤压宽度，详情看动图
![Kapture 2022-01-14 at 15 35 47](https://user-images.githubusercontent.com/89069385/149469397-afe17edf-018b-4187-97b9-e52664810ca9.gif)

**Comment by YFAnt** [comment]
1px 边框

**Comment by chaishi** [comment]
已修复并发布至 `0.33.2`
