### ISSUE TITLE
能否对Input组件添加一个远程搜索提示

### ISSUE THREAD

**Issue by x-zhao-res** [Tencent/tdesign-vue#2431]
### 这个功能解决了什么问题

目前组件Input框只能输入，无输入提示功能
举例：
输入：热
效果：自动联想(也可根据字典或联网补齐) “热狗” “热气球” 等

### 你建议的方案是什么

1. 新增OptionBoolean：控制是否出现搜索提示框
2. 新增OptionData：控制当前提示框内的内容，类型为数组或其他。

如此可以监听input框focus事件或者输入触发事件，从远程搜索结果并返回给前端展示到搜索提示框中

**Comment by MarkGor** [comment]
SelectInput 
[SelectInput ](https://tdesign.tencent.com/vue/components/select-input?tab=demo)

**Comment by x-zhao-res** [comment]
> SelectInput [SelectInput ](https://tdesign.tencent.com/vue/components/select-input?tab=demo)

I'm very sorry, I didn't notice that the search prompt was listed as a separate component
Thanks for you replay.

**Comment by chaishi** [comment]
SelectInput is not designed for remote search, it designed for complicated filter components.

What you need might be `AutoCompolete` component
https://tdesign.tencent.com/vue/components/auto-complete

<img width="868" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/3c58b720-5b62-4b3a-b250-cf69c7c79985">
