### ISSUE TITLE
[Menu] 收起时菜单超出屏幕时样式有问题且无法滚动

### ISSUE THREAD

**Issue by zhutengfei1990** [Tencent/tdesign-vue#2435]
### tdesign-vue 版本

1.3.1

### 重现链接

https://stackblitz.com/edit/6acns6?file=src%2Fdemo.vue 

### 重现步骤

添加重现链接即可复现

### 期望结果

菜单很多时，收缩可正常滚动

### 实际结果

收起时菜单超出屏幕时样式有问题且无法滚动

### 框架版本

vue2

### 浏览器版本

Chrome 113

### 系统版本

Windows

### Node版本

node无关

### 补充说明

无

**Comment by xiaosansiji** [comment]
https://github.com/Tencent/tdesign-vue/pull/2461 重构后的 Menu 可以修复这个问题，变动比较大，相关样式问题在验证修复中，预计下周二的 1.4.0 版本中发布

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
