### ISSUE TITLE
[INPUT] 快速输入字符，或者同时摁下两个字符。输入会出错

### ISSUE THREAD

**Issue by RomenMark** [Tencent/tdesign-vue#2436]
### tdesign-vue 版本

1.3.2

### 重现步骤

官网例子。
输入得很快很快
或者
同时摁下两个字母
会被吞字

### 框架版本

vue(2.6.12)

### 系统版本

win10

### Node版本

14.17.0

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue/issues/2350

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
