### ISSUE TITLE
是否考虑增加一个scrollbar 滚动条组件？

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue#2437]
### 这个功能解决了什么问题

dialog过高，无法指定页面标签滚动

### 你建议的方案是什么

希望增加一个跟element 一样的el-scrollbar滚动条组件

**Comment by uyarn** [comment]
有计划的

**Comment by uyarn** [comment]
在这边同步进度 https://github.com/Tencent/tdesign/issues/220
