### ISSUE TITLE
[select]  select 中 options 组件多一个span 节点

### ISSUE THREAD

**Issue by yaogengzhu** [Tencent/tdesign-vue#2438]
### tdesign-vue 版本

1.3.3

### 重现步骤

https://github.dev/Tencent/tdesign-vue/blob/5e5ce675a1e889ca67be473729dc79368ef17a23/src/select/option.tsx#L223-L224

### 期望结果

直接用户节点就好了

### 补充说明

https://github.dev/Tencent/tdesign-vue/blob/5e5ce675a1e889ca67be473729dc79368ef17a23/src/select/option.tsx#L223-L224

**Comment by yaogengzhu** [comment]
<img width="510" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/42566669/1c7c8dda-4586-4eec-9387-089088329136">

自定义时，多了一个span 包裹div 🤣

**Comment by uyarn** [comment]
这个节点是为了做点击动画存在的

**Comment by uyarn** [comment]
可以考虑自定义节点的时候不加 默认是要有的

**Comment by yaogengzhu** [comment]
现在的需求是就 自定义节点多了一个span 不太合理，是否可以干掉？，非自定义的话 span 可行的。

**Comment by uyarn** [comment]
发现本身确实多出了一个span节点 一块去掉了

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
