### ISSUE TITLE
[Tree] 节点拖拽功能希望支持限制部分节点禁止拖拽，拓展范围限制同级拖拽

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue#2444]
### 这个功能解决了什么问题

目前tree组件支持通过draggable属性，设置节点可拖拽。实际场景是1级目录禁止拖拽，二级目录的拖拽的范围只能在同级目录（需要限制把三级目录拖到二级目录来）

### 你建议的方案是什么

需要tree组件能拓展能力，新增2个属性：
1.判断节点能否被拖拽
2.限制同级目录拓展

例如element plus支持
![image](https://github.com/Tencent/tdesign-vue/assets/21232961/81cfbf1b-1028-472a-8472-8ef20715a689)

**Comment by zhangvj** [comment]
同有这个需求 +1

**Comment by zhoulujun** [comment]
这个需求能支持一下吗？

**Comment by Found-404** [comment]
同有这个需求 +1

**Comment by zhangvj** [comment]
@uyarn 大佬麻烦关注下这个需求

**Comment by uyarn** [comment]
tree的开发同学这个月会排期来处理tree的相关需求

**Comment by uyarn** [comment]
support allowDrop 1.9.5

**Comment by Found-404** [comment]
> 支持`allowDrop`API 1.9.5

请问vue3何时可以支持呢？

**Comment by uyarn** [comment]
也是下个版本 https://github.com/Tencent/tdesign-vue-next/pull/4312

**Comment by Jinsdw** [comment]
> > 支持`allowDrop`API 1.9.5
> 
> 请问vue3何时可以支持呢？

这个问题，你不用就可以了，手搓一个tree
