### ISSUE TITLE
[ColorPicker] 在表单中使用切换显示隐藏页面报错

### ISSUE THREAD

**Issue by colaiven** [Tencent/tdesign-vue#2445]
### tdesign-vue 版本

1.3.4

### 重现链接

https://stackblitz.com/edit/vwk5yj-qwxxh4?file=src%2Fdemo.vue

### 重现代码

```
<template>
  <div>
    <t-form v-show="expend">
      <t-form-item label="颜色">
        <t-color-picker />
      </t-form-item>
    </t-form>
    <button @click="expend = !expend">切换显示</button>
  </div>
</template>
<script setup>
import { ref } from 'vue';
const expend = ref(false);
</script>
```

### 重现步骤

在form-item中使用color-picker，切换组件的显示隐藏，页面就报错了，报错信息如下：

Uncaught runtime errors:
×
ERROR
ResizeObserver loop limit exceeded
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:271:7)
![image](https://github.com/Tencent/tdesign-vue/assets/46585176/2b9ef226-7492-4b70-ad6b-2a2300643d98)

单独使用color-picker  或者改用v-if不存在这个问题，另外这个问题貌似只存在用webpack打包的方式，用vite没有复现这个bug

**Comment by xinller** [comment]
给table组件传pagination属性也会出现这个问题
