### ISSUE TITLE
[timePicker] 时间选择器打开直接确认没有反应

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2446]
### tdesign-vue 版本

1.3.3

### 重现链接

https://tdesign.tencent.com/vue/components/time-picker

### 重现步骤

官方示例,打开面板直接点击确认

**Comment by uyarn** [comment]
嗯 可以优化下 没有时间不允许点确认会好点

**Comment by furylee** [comment]
> 嗯 可以优化下 没有时间不允许点确认会好点

默认打开不就是00:00上面吗,非得再选一下这交互有点僵硬吧

**Comment by uyarn** [comment]
> > 嗯 可以优化下 没有时间不允许点确认会好点
> 
> 默认打开不就是00:00上面吗,非得再选一下这交互有点僵硬吧

不是 你如果有预设的时间 预设个时间 0000并不是预设的存在

**Comment by furylee** [comment]
> > > 嗯 可以优化下 没有时间不允许点确认会好点
> > 
> > 
> > 默认打开不就是00:00上面吗,非得再选一下这交互有点僵硬吧
> 
> 不是 你如果有预设的时间 预设个时间 0000并不是预设的存在 只是最后兜底的位置

好奇怪啊,打开面板我想选00:00,必须先选其他的值才能选择00:00

**Comment by uyarn** [comment]
> > > > 嗯 可以优化下 没有时间不允许点确认会好点
> > > 
> > > 
> > > 默认打开不就是00:00上面吗,非得再选一下这交互有点僵硬吧
> > 
> > 
> > 不是 你如果有预设的时间 预设个时间 0000并不是预设的存在 只是最后兜底的位置
> 
> 好奇怪啊,打开面板我想选00:00,必须先选其他的值才能选择00:00

嗯 也挺奇怪的 我找交互再看看有没有什么优化方式

**Comment by xiaosansiji** [comment]
fixed in 1.4.0
