### ISSUE TITLE
treeSelect同时设置了keys和valueType object后选中不了

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#2454]
https://stackblitz.com/edit/rlake1?file=src%2Fdemo.vue
<img width="1319" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/31959442/77769bb7-c218-4da7-8c42-e9ddfd5feb3d">

**Comment by xiaosansiji** [comment]
fixed in 1.4.2
