### ISSUE TITLE
【radio】会报 Cannot read property 'stopPropagation' of undefined，偶现

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#246]
![image](https://user-images.githubusercontent.com/8199240/149700614-166d586f-568c-4dd5-b76f-dd4411108f3c.png)

在 sentry 上查到源码处：
![image](https://user-images.githubusercontent.com/8199240/149700683-a96718c7-a673-4640-8c28-395d44ac5cbf.png)

**Comment by xiaosansiji** [comment]
是在使用 select 组件的时候么？

**Comment by chaishi** [comment]
辛苦 @geff1991 跟进一下

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
