### ISSUE TITLE
[dropdown] vue2版本组件无法使用，报错

### ISSUE THREAD

**Issue by xinller** [Tencent/tdesign-vue#2474]
### tdesign-vue 版本

1.3.4

### 重现步骤

1、直接 vue create test-app 起一个vue2版本的项目
2、node 14.19.0
3、安装 npm i tdesign-vue 此时会提示 vue/vue-loader-v15 not define in npm 
4、改成yarn add tdesign-vue
5、main.js 引入 
import TDesign from 'tdesign-vue'
import 'tdesign-vue/es/style/index.css'
Vue.use(TDesign)

6、直接复制官网的代码

<t-dropdown :options="options" @click="clickHandler">
      <t-button variant="text">
        <span class="tdesign-demo-dropdown__text">
          更多
          <chevron-down-icon size="16" />
        </span>
      </t-button>
    </t-dropdown>

控制台报错：

### 实际结果

控制台报错如下：
vue.runtime.esm.js:4605 [Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <TDropdown>
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "dropdownClass" is already declared.

found in

---> <TDropdown>
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "handleMenuClick" is already declared.

found in

---> <TDropdown>
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "isPopupVisible" is already declared.

found in

---> <TDropdown>
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "handleVisibleChange" is already declared.

found in

---> <TDropdown>
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: Invalid prop: type check failed for prop "visible". Expected Boolean, got Object 

found in

---> <TPopupMapprops>
       <TDropdown>
         <App> at src/App.vue
           <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: Invalid prop: type check failed for prop "visible". Expected Boolean, got Object 

found in

---> <TPopup>
       <TPopupMapprops>
         <TDropdown>
           <App> at src/App.vue
             <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: Invalid prop: type check failed for prop "visible". Expected Boolean, got Object 

found in

---> <Anonymous>
       <TPopup>
         <TPopupMapprops>
           <TDropdown>
             <App> at src/App.vue
               <Root>
warn @ vue.runtime.esm.js:4605
2vue.runtime.esm.js:4605 [Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "dropdownClass" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "dropdownMenuClass" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "handleItemClick" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "menuRef" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "isOverMaxHeight" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "handleScroll" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "scrollTopMap" is already declared.

found in

---> <TDropdownMenu>
       <Anonymous>
         <Anonymous>
           <TPopup>
             <TPopupMapprops>
               <TDropdown>
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <TDropdownItem>
       <TDropdownMenu>
         <Anonymous>
           <Anonymous>
             <TPopup>
               <TPopupMapprops>
                 <TDropdown>
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js:4605
vue.runtime.esm.js:4605 [Vue warn]: The setup binding property "itemRef" is already declared.

### 框架版本

^2.6.14

### Node版本

14.19.0

**Comment by uyarn** [comment]
目前tdesign-vue暂时只支持vue2.6+ 中使用 这个报错是你使用了2.7的vue导致的 https://tdesign.tencent.com/vue/getting-started#faq
<img width="903" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/ed25a3be-52c7-4b1e-bcfb-6eb44c5bc8f6">
接下来我们会支持在2.7中使用 目前需要你把vue保持在2.6+的版本

**Comment by xinller** [comment]
果然如此，没注意到^

**Comment by uyarn** [comment]
close as complete
