### ISSUE TITLE
icon 代码存在错误？

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#248]
**Describe Framework**

tdesign-vue

**Describe Environment**
"tdesign-vue": "^0.33.0",

**Describe the bug**
其他页面进入带有`t-icon`标签的页面可正常显示图标，但含有`t-icon`标签的页面刷新就出现引用报错。
![image](https://user-images.githubusercontent.com/49895922/149726332-40d4cbd1-c73a-47eb-9fad-850b7da5e05f.png)

**Comment by uyarn** [comment]
`其他页面进入带有t-icon标签的页面可正常显示图标，但含有t-icon标签的页面刷新就出现引用报错` 没读懂这个复现路径

**Comment by uyarn** [comment]
fixed in tdesign-icons-vue 0.0.8
