### ISSUE TITLE
[Dialog] 弹出不能通过DialogPlugin(options)直接调用

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2487]
### tdesign-vue 版本

1.3.3

### 重现步骤

文档显示，支持 DialogPlugin(options)的调用方式，但实际使用时，报错显示：DialogPlugin is not a function

<img width="762" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/b775ccde-b4a9-4fdd-ad1d-9407586e5694">

### 框架版本

2.6.14

**Comment by uyarn** [comment]
`import { DialogPlugin } from 'tdesign-vue';` 要先引入哦

**Comment by uyarn** [comment]
如果还有问题再打开或者提供复现链接~

**Comment by vonlyinno** [comment]
> 

引入了的。
DialogPlugin.xx 都可以调用，但DialogPlugin() 直接调用就不行。
