### ISSUE TITLE
[Cascader] options设置为空时报错

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2492]
### tdesign-vue 版本

1.3.3

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.vue

### 重现步骤

将options设为空数组，focus时会报错 TypeError: Cannot read properties of undefined (reading 'length')

### 框架版本

2.6.14

**Comment by xiaosansiji** [comment]
fixed in 1.4.2
