### ISSUE TITLE
[ColorPicker] 线性渐变模式下值绑定错误

### ISSUE THREAD

**Issue by mdxiaohu** [Tencent/tdesign-vue#2498]
### tdesign-vue 版本

1.4.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-6j9lcz?file=/src/demo.vue

### 重现步骤

修改color3的值为undefined或者null，改变面板的值，则为linear-gradient(0deg,)

### 期望结果

希望支持undefined或者null默认值，改变值后正常显示

### 实际结果

linear-gradient(0deg,)

### 框架版本

Vue(2.6.14)

### 浏览器版本

谷歌(98.0.4758.9)

### 系统版本

Windows10

### Node版本

15.0.1

### 补充说明

不支持undefined或者null，意味着无法清空选择器的值。

**Comment by xiaosansiji** [comment]
fixed in 1.4.2
