### ISSUE TITLE
table展开的时候，colspan设置错误导致里面的元素无法填充满整个页面，下钻越来越小

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#250]
**Describe Framework**

tdesign-vue

**Describe Environment**
0.33.1
Add browser version here
![image](https://user-images.githubusercontent.com/15682051/149764063-c4560025-0051-4739-87aa-9dfb1b94a7d5.png)

**Describe the bug**
<img width="609" alt="企业微信截图_16424186162866" src="https://user-images.githubusercontent.com/15682051/149764104-896030bc-71aa-40a7-b511-a36b45b29da7.png">
<img width="440" alt="企业微信截图_16424187248104" src="https://user-images.githubusercontent.com/15682051/149764112-63caca04-e4f2-4a25-a495-f5aa60078cd9.png">

**Additional context**

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/255

**Comment by xiaosansiji** [comment]
已在 0.33.2 版本中修复
