### ISSUE TITLE
t-table column resizable 列宽变动

### ISSUE THREAD

**Issue by nzj19910102** [Tencent/tdesign-vue#2502]
### 这个功能解决了什么问题

外部需要记录列宽。

### 你建议的方案是什么

在列宽变动的时候可否添加一个回调事件

**Comment by chaishi** [comment]
2023-06-27 `v1.4.5` 已支持 `onColumnResizeChange`

https://tdesign.tencent.com/vue/changelog

<img width="1132" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/dc9c67dd-274a-4423-b718-6203695f580f">
