### ISSUE TITLE
[ColorPicker] 当我使用带触发元素的颜色选择器时点击触发元素会报一个警告并无法弹出颜色选择板

### ISSUE THREAD

**Issue by Wind-Breaker1** [Tencent/tdesign-vue#2503]
### tdesign-vue 版本

1.4.0-naruto

### 重现链接

[https://codesandbox.io/s/tdesign-vue-demo-forked-jddpjt](https://codesandbox.io/s/tdesign-vue-demo-forked-jddpjt?file=/package.json)

### 重现步骤

1.通过执行pnpm i tdesign-vue@naruto安装依赖；
2.在main.js中全量注册组件；
3.在页面中正常使用带触发元素的颜色选择器；
4.点击触发元素；

### 期望结果

能够正常弹出颜色选择板

### 实际结果

报了一个警告，并且没有正常弹出颜色选择板
![1686541812858](https://github.com/Tencent/tdesign-vue/assets/95519003/2239f5e1-5d21-474f-9f69-47d59c62c6e0)

### 框架版本

Vue（2.7.7）

### 浏览器版本

Edge（114.0.1823.41）

### 系统版本

win11

### Node版本

16.16.0

**Comment by xiaosansiji** [comment]
fixed in 1.4.2
