### ISSUE TITLE
[tabs] tabs组件放在在dialog下，首次打开dialog时，tab标题下面的tab-bar(蓝色的条)不能正常显示。

### ISSUE THREAD

**Issue by ArthurHsing** [Tencent/tdesign-vue#2505]
### tdesign-vue 版本

1.2.5

### 重现步骤

随便个dialog，里面放一个tabs组件。可稳定重现。

### 期望结果

tabs组件的tab-bar在dialog首次打开时能够正常显示。

### 实际结果

tabs组件的tab-bar在dialog首次打开时不能能够正常显示。

我现在是这么解决的，在打开dialog时，在nextTick里面设置当前的tab，tab-bar就会正常出来。

建议排查一下tab-bar的width的计算时机。

<img width="846" alt="" src="https://github.com/Tencent/tdesign-vue/assets/42834985/2aa47027-e6d3-4ecc-80ef-6b79d3bc7604">
<img width="842" alt="" src="https://github.com/Tencent/tdesign-vue/assets/42834985/3992ac4c-6ab8-4f5a-bf43-d0595b2ece22">

### 框架版本

vue 2.6.14

**Comment by xiaosansiji** [comment]
fixed in 1.5.0
