### ISSUE TITLE
[Menu] 竖直方向模式，内容可以左右滑动

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#2509]
### tdesign-vue 版本

1.4.0

### 重现链接

https://tdesign.tencent.com/vue/components/menu

### 重现步骤

https://github.com/Tencent/tdesign-vue/assets/16223845/1c91a49e-d5b8-46df-8c01-33dc1009b61b

### 期望结果

menu内容水平方向不能滑动

### 实际结果

menu内容水平方向可以滑动

**Comment by xiaosansiji** [comment]
fixed in 1.4.2
