### ISSUE TITLE
[Popup] Popup中的元素使用tooltip包裹，在元素中hover快速移动会导致popup消失

### ISSUE THREAD

**Issue by zhutengfei1990** [Tencent/tdesign-vue#2518]
### tdesign-vue 版本

1.4.2

### 重现链接

https://stackblitz.com/edit/zqwayp?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue/assets/4726857/ddf42f41-2936-47b1-905e-90e869b460da)
鼠标在图中选中的位置快速移动

### 期望结果

popup保持显示

### 实际结果

popup消失了

### 框架版本

vue2

### Node版本

node无关

**Comment by chaishi** [comment]
看不明白问题

**Comment by uyarn** [comment]
> 看不明白问题

快速hover过几个tooltip

**Comment by xiaosansiji** [comment]
fixed in 1.4.7
