### ISSUE TITLE
form组件行内布局的时候，label是不是可以紧挨着组件，设置了labelWidth，遇到label文字比较少的时候，留着大片的空白，不好看

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#252]
**Describe Framework**

tdesign-vue

**Describe Environment**
0.33.1
Add browser version here
![image](https://user-images.githubusercontent.com/15682051/149764655-e963bf10-2559-4214-bf28-815bf120ed21.png)

**Describe the bug**
![image](https://user-images.githubusercontent.com/15682051/149764711-43ad9767-bfaa-476b-a9ba-93c96f55b3fe.png)

**Additional context**

element ui 的form组件行内布局的时候，不用设置labelWidth就做到了label紧挨着旁边的组件
https://element.eleme.io/#/zh-CN/component/form#form-item-methods
![image](https://user-images.githubusercontent.com/15682051/149765320-d9cb7b8b-cb79-43ab-8656-89474a52ce6b.png)

**Comment by chaishi** [comment]
有的业务，希望紧挨着，有的业务希望多行对齐

你们的业务因为都是紧凑的，所以希望紧挨着

有的业务，一行就显示三个查询条件，会显示多行，每一行的每一个还要对齐

**Comment by chaishi** [comment]
写个 label-width: auto ，是不是就可以满足需求了

**Comment by sampsonliu** [comment]
> 

那你们不要施加style可以么，这样用户就容易覆盖css了，组件很少施加style的

**Comment by chaishi** [comment]
@HQ-Lin 咱们把 inline 模式的 margin-left 的 style 去掉可以不
