### ISSUE TITLE
[Textarea ] 多行文本框不能响应设置 value 后 autoheight 自适应

### ISSUE THREAD

**Issue by pylist** [Tencent/tdesign-vue#2522]
### tdesign-vue 版本

1.4.2

### 重现链接

https://codesandbox.io/embed/tdesign-vue-demo-forked-kmk4pm?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

```
<t-textarea v-model="value" :autosize="{minRows:2}" />
```
使用组件在首次渲染的时候, 如果value有值的话, 高度不会自动撑开, 需要输入一个字符串才可以撑开正确的高度

![image](https://github.com/Tencent/tdesign-vue/assets/52667561/dae65551-d6e6-46f4-975a-89bf9d2c2ee8)

### 期望结果

在首次渲染的时候能够识别出正确的高度

### 实际结果

撑开高度不够

### 框架版本

vue(2.6.10)

**Comment by xiaosansiji** [comment]
fixed in 1.4.3
