### ISSUE TITLE
[Select] 多选情况下按下Enter键后触发了focus事件而不是enter事件

### ISSUE THREAD

**Issue by C-puqing** [Tencent/tdesign-vue#2525]
### 重现链接
https://stackblitz.com/edit/ah7mtd?file=src%2Fdemo.vue

### 重现步骤
点击输入框后，按下【Enter】键即可在控制台观察到日志输出

### 期望结果
按下Enter后在控制台看到如下输出：
handleEnter:   KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: false, …} 

### 实际结果
实际输出：
handleFocus:  [] KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: false, …}

| Environment | Info |
|---|---|
| 相关版本 | 1.2.5 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | MacOs、Chrome(114.0.5735.106) |
| Node版本 |  |

**Comment by skytt** [comment]
`Select` 是基于 `SelectInput` 构建的，试了一下这个问题应该是在 `SelectInput` 事件上有误
