### ISSUE TITLE
[Table] EnhancedTable 同一行key相同的数据更新后，视图不更新

### ISSUE THREAD

**Issue by xinller** [Tencent/tdesign-vue#2526]
### tdesign-vue 版本

1.3.4

### 重现步骤

用EnhancedTable时，传入data属性，当手动修改data数组中某一行数据时，视图不更新，查看vue-devtool发现，增强型表格内嵌套了primaryTable，在primaryTable中发现传入的data数据未更新，应该是主表格中未进行data的深度监听导致

### 框架版本

2.6.14

### Node版本

14.19.0

**Comment by chaishi** [comment]
从当前描述内容评估，无法处理问题。

请提供可复现问题的代码，我们再处理。

**Comment by xinller** [comment]
看看这个例子： https://codesandbox.io/s/musing-dawn-99npty?from-embed=&file=/src/App.vue

**Comment by xinller** [comment]
请问这个问题有解决了吗

**Comment by chaishi** [comment]
深度监听是有代价的，要给全部对象的全部属性的全部层级添加监听，消耗较大，故而组件内部不会做深度监听。

数据更新官网有单独的方法，请仔细阅读文档。
https://tdesign.tencent.com/vue/components/table?tab=demo
<img width="933" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/663fb216-e28c-48d9-8fd7-524fe9d57801">
