### ISSUE TITLE
[dialog] footer的button可以增加disable功能吗？

### ISSUE THREAD

**Issue by ArthurHsing** [Tencent/tdesign-vue#2531]
### 这个功能解决了什么问题

一个dialog，其中可能有一些网络请求，我得等请求完毕后，footer的'确认'按钮才允许被点击。
现在只有手动更改样式和添加disable逻辑。

### 你建议的方案是什么

增加footer中button的disable功能。

**Comment by chaishi** [comment]
可以。示例代码见官网：https://tdesign.tencent.com/vue/components/dialog。标题「异步加载类对话框」。

```
<t-dialog
  :visible.sync="visible"
  header="保存"
  body="保存中，请稍后"
  :confirmBtn="{
    content: '保存中...',
    theme: 'primary',
    loading: true,
  }"
  :onConfirm="onConfirm"
  :onClose="close"
/>
```
<img width="877" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/969a8bb9-0185-43b1-af9e-072e470aa5d1">


和 Loading 加载状态同理，禁用状态也可以这样写。

```
<t-dialog
  :visible.sync="visible"
  header="保存"
  body="保存中，请稍后"
  :confirmBtn="{
    content: '保存中...',
    theme: 'primary',
    disabled: true,
  }"
  :onConfirm="onConfirm"
  :onClose="close"
/>
```
