### ISSUE TITLE
[Table] 表格使用固定高度最后一行样式缺失

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2538]
### tdesign-vue 版本

1.4.4

### 重现链接

https://stackblitz.com/edit/tpqaaj?file=src%2Fdemo.vue

### 重现步骤

底部border丢失
![image](https://github.com/Tencent/tdesign-vue/assets/29624966/47fe607d-0a4e-4f9b-85c1-31ab716d7247)

### 框架版本

2.6

**Comment by chaishi** [comment]
这个问题，我记得在群里回复过。属于使用不规范，暂时不做处理，以后很长时间也不会处理。

最后一行边线没有缺失，只是在最底部而已。为避免内容足够的时候，底部出现 两条灰色线条，组件不再重复添加。

解决办法一：对于存在内容不足的情况，不建议使用 `height` 设置高度，更为使用 `max-height` 更合适。

解决办法二：如图所示，一定要 height，导致底部出现空白，业务可以自行根据内容是否存在空白，来添加底部线条。内容足够不添加，内容不够就添加。（由于表格行高可能不同，组件内部判断远没有外部判断来得简单，很可能因为处理这个问题，后面又来了一堆底部重复边线的 issue bug）
其实，即使强制使用 `height`， 最后实现的效果，和 `max-height` 也没有什么区别。对于分页，可以通过样式设置固定在底部某个位置。
