### ISSUE TITLE
[t-table] 表头自定义过滤器本地调试环境没问题，打包到线上环境后出现打开下拉选择器再点击外部，选择器弹窗节点没移除

### ISSUE THREAD

**Issue by zzq15813315224** [Tencent/tdesign-vue#2543]
### tdesign-vue 版本

1.3.4

### 重现步骤

t-table 表头自定义过滤器本地调试环境没问题，打包到线上环境后出现打开下拉选择器再点击外部，选择器弹窗节点没移除
代码如下：
import { Select} from 'tdesign-vue';

filter = {
                type: 'custom',
                component: Select,
                props: {
                  options: res.data.map(l=>{
                    return {
                      value:l.name,
                      label:l.name
                    }
                  }),
                  multiple:true,
                  filterable:true,
                  reserveKeyword:true,
                  minCollapsedNum:1,
                  clearable:true,
                },
                // 是否显示重置取消按钮，一般情况不需要显示
                showConfirmAndReset: true,
                // 日期范围是一个组件，重置时需赋值为 []
                resetValue: [],
              }

### 期望结果

打开下拉选择器再点击外部，选择器弹窗节点正常移除，我是看到组件库源码是有移除逻辑的，但是到正式环境没生效

### 实际结果

正式环境，打开下拉选择器再点击外部，选择器弹窗节点没有正常移除，移除逻辑失效

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(114.0.5735.134)

### 系统版本

Windows(11)

### Node版本

12.13.0

**Comment by chaishi** [comment]
没有课复现问题的 demo 链接，暂时复现问题，定位问题，进而也无法解决问题。

如需解决问题，请点击下图，任意两个按钮，进去复现问题，保存代码，复制链接到 issue。
<img width="329" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/7c968415-892c-4f44-ac44-a0644b08da96">

**Comment by chaishi** [comment]
尝试官网最新版本，关闭筛选器后，相关元素会被移除，如何期望。如下视频所示。issue close
https://github.com/Tencent/tdesign-vue/assets/11605702/13c9d602-3f2d-4901-9958-bf666d13c9fb
