### ISSUE TITLE
[Table] 新增表格内容的对齐方式

### ISSUE THREAD

**Issue by zyqq** [Tencent/tdesign-vue#2555]
### 这个功能解决了什么问题

<img width="1095" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/15664576/d43a95e8-6dc9-4e38-b084-3eb07214646c">
没有针对某一列的内容设置对齐方式

### 你建议的方案是什么

<img width="850" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/15664576/9caf91e4-117a-44e5-9402-e4575f03ceee">
参照elementui的设计，在column配置中align为对列内容横向对齐方式的配置，header-align为对列表头的对齐方式配置

**Comment by chaishi** [comment]
看上去 TDesign 的截图是，自定义列配置场景的图。而期望和 ElementUI 的截图内容是指纵向对齐方式。

由于表格基本设计规范为：数字右对齐、文本左对齐，表头随内容对齐。故而 align 和 header-align 不同是不符合规范的。暂不支持。

如果希望表头有单独的对齐方式，一定要做不符合一般设计规范的样式。请通过类名使用 CSS 直接设置样式。每一个表头都有属于自己的类名，实现简单。示例代码：`.t-table th.t-table__th-status { text-align: left }`
<img width="765" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/bf98b083-3b25-43bd-988b-4fcf4221b7ed">
