### ISSUE TITLE
swiper组件----navigation的type无效果

### ISSUE THREAD

**Issue by ninannansheng** [Tencent/tdesign-vue#2559]
### tdesign-vue 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-lj8qzr?file=/src/demo.vue

### 重现步骤

type=”dots/dots-bar“没有出效果

### 框架版本

vue2

### 浏览器版本

109.0.5414.120

### 系统版本

window11

### Node版本

16.14.2

**Comment by xiaosansiji** [comment]
版本太过久远，可以升级下较新的版本试下
