### ISSUE TITLE
[Transfer] 穿梭框存在默认已选择且已选择数据不允许移除的场景，在加入数据时，将已选择数据给移除了

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#2564]
### tdesign-vue 版本

1.4.5

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-3n462j?file=/src/demo.vue:462-481

### 重现步骤

如示例，已选择数据“内容1”添加禁用，不允许用户在穿梭框右侧将”内容1“移除；用户在穿梭框左侧选择“内容2”加入到穿梭框右侧。

### 期望结果

默认已选择且禁用的数据不从右侧移除。

### 实际结果

最终目标数据列表数据中将我默认选中的“内容1”给移除到了穿梭框左侧。

### 框架版本

2.6.14

### 浏览器版本

114

### 系统版本

13.4.1

### Node版本

16.15.1

### 补充说明

穿梭框存在默认已选择且已选择数据不允许移除的场景

**Comment by xiaosansiji** [comment]
fixed in 1.5.0
