### ISSUE TITLE
[Loading] app.loading(false) 会创建新的loading

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2566]
### tdesign-vue 版本

1.4.2

### 重现步骤

loading的全局函数调用：LoadingPlugin(false)

如果指定了false，预期就是不展示loading。
但页面如果因为一些异步的执行时序，导致LoadingPlugin(false)执行时，已经没有实例了，结果是创建了新的loading。并不符合预期。

查看了仓库代码：
<img width="1086" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/cd635c53-8352-412a-8044-255e40fa6f69">

### 期望结果

LoadingPlugin(false)，如果指定了false，预期就是不展示loading。

### 实际结果

创建了新的loading实例

### 框架版本

2.6.14

**Comment by uyarn** [comment]
fixed in 1.6.5
