### ISSUE TITLE
[t-alert] 意外消失

### ISSUE THREAD

**Issue by dntzhang** [Tencent/tdesign-vue#2569]
### tdesign-vue 版本

latest 1.4.6

### 重现链接

 https://stackblitz.com/edit/sxrzm5?file=src%2Fdemo.vue

### 补充说明

<img width="1332" alt="企业微信截图_aad15d09-5a72-4dcc-bd6b-a4cab2a85894" src="https://github.com/Tencent/tdesign-vue/assets/7917954/008e89aa-a98a-4a0f-8fe2-dd46d56894f3">

移到链接上就会消失

**Comment by xiaosansiji** [comment]
fixed in 1.4.7
