### ISSUE TITLE
【Textarea】缺少默认背景，与 Input 表现不一致

### ISSUE THREAD

**Issue by fython** [Tencent/tdesign-vue#257]
**Describe Framework**

tdesign-vue 0.33.1

**Describe Environment**

Chrome 97.0.4692.71 (Release)

**Describe the bug**

![image](https://user-images.githubusercontent.com/3166782/149860527-21b735b4-4ea3-40c1-a59c-87ea7da6bafa.png)

Codesandbox: <https://codesandbox.io/s/tdesign-vue-0-33-1-bug-textarea-transparent-bg-zzdq6?file=/src/components/HelloWorld.vue>

**Additional context**

No

**Comment by xiaosansiji** [comment]
textarea 应该跟 input 一样，浅色模式下填充白色背景，暗色模式下无填充，背景色 token 应该也要用 `--td-bg-color-specialcomponent`

**Comment by chaishi** [comment]
已发布至 `0.33.2`
