### ISSUE TITLE
[Tree] 树中的高亮节点，再次点击不应该取消高亮状态

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#2572]
### tdesign-vue 版本

1.4.5

### 重现链接

官方demo

### 重现步骤

当某一节点被选中时，处于高亮状态，再次点击当前节点

### 期望结果

当前节点还是处于高亮状态

### 实际结果

高亮状态被取消了

### 框架版本

2.6.14

### 浏览器版本

114

### 系统版本

13.4.1

### Node版本

16.15.1

**Comment by TabSpace** [comment]
@chaishi 这个期望涉及到原有逻辑变化和 breaking change。
考虑是否需要新增一个属性来实现该能力？

**Comment by TabSpace** [comment]
@chaishi 麻烦先确认下这里预期的逻辑，将排在下次更新中。

**Comment by Loinver** [comment]
插眼

**Comment by 1079265662** [comment]
版本：1.9.4
解决方案：可以通过给actived高亮节点值来实现持续高亮状态，actived是一个数组在非多选情况下直接push选中的值即可

![Snipaste_2024-09-19_15-25-00](https://github.com/user-attachments/assets/47c98281-4bba-454c-881a-6db9c4beeade)
