### ISSUE TITLE
[TimePicker] 特定时间区间需要限制时分秒选择，不知是否应使用disableTime实现

### ISSUE THREAD

**Issue by princeppl** [Tencent/tdesign-vue#2578]
### tdesign-vue 版本

1.3.4

### 重现链接

无

### 重现步骤

无

### 期望结果

https://blog.csdn.net/mrsun_web/article/details/120621518

### 实际结果

不知如何实现期望结果

### 框架版本

Vue(2.6.1)

### Node版本

16.17.1

**Comment by xiaosansiji** [comment]
Implemented in 1.5.0
