### ISSUE TITLE
icon中 translate的两个图标找不到

### ISSUE THREAD

**Issue by ScumbagMNO** [Tencent/tdesign-vue#2593]
### tdesign-vue 版本

1.4.8

### 重现步骤

<t-icon name="translate-1"></t-icon>

### Node版本

16.15.1

**Comment by uyarn** [comment]
你是需要translate的图标？

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-7mn55j?file=/src/demo.vue  可能是你当前图标版本的问题 translate是后面新增的图标 可以尝试重新安装下icon包升级上来
