### ISSUE TITLE
[t-dropdown] 无法展开

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#2594]
### tdesign-vue 版本

1.4.8

### 重现链接

https://stackblitz.com/edit/vkudyu?file=src%2Fdemo.vue

### 重现步骤

复现路径：hover上去再出去，再hover就再也出现不了展开项了。（先移动到按钮上方，再移动到按钮下面，似乎要滑过按钮，然后展开项自动关闭，但dropdown组件可能认为当前还没关，再hover上去后就展不开了）
![popup不显示](https://github.com/Tencent/tdesign-vue/assets/8199240/e8634c78-df11-4042-95a2-1bbff3616323)

### 框架版本

vue2.6.11

**Comment by xiaosansiji** [comment]
fixed in 1.6.4
