### ISSUE TITLE
[t-checkbox] 升级到1.4.8后报错。 "TypeError: Cannot read properties of undefined (reading 'propsData')"

### ISSUE THREAD

**Issue by qinshenxue** [Tencent/tdesign-vue#2597]
### tdesign-vue 版本

1.4.8

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-gmt5hv?file=/src/demo.vue

### 重现步骤

在1.4.8版本之前使用t-checkbox-group，插槽内结构自定义无报错。

``` html
 <t-checkbox-group size="small" v-model="checked">
        <div class="dates-table">
          <div class="row head">
            <div class="col" v-for="i in week" :key="i">
              {{ i }}
            </div>
          </div>
          <div class="body">
            <div class="row">
              <div class="col" v-for="(item, index) in calendar" :key="index">
                <t-checkbox
                  :key="index"
                  v-if="item && item.date"
                  :value="item.date"
                >
                  <span>{{ item.date.slice(5) }}</span>
                </t-checkbox>
              </div>
            </div>
          </div>
        </div>
      </t-checkbox-group>
```
正常的时候应该渲染如下图
![image](https://github.com/Tencent/tdesign-vue/assets/10354498/e716e38a-ebd5-46e4-901d-11f64bad2ead)

升级到1.4.8之后，上面代码无法正常渲染，控制台报错
![image](https://github.com/Tencent/tdesign-vue/assets/10354498/9f495859-a484-471a-9bc8-d23126f4a7a0)

### 期望结果

能够像1.4.8版本之前正常渲染，无报错

### 实际结果

报错，无法正常渲染

### 框架版本

Vue(2.6.14)

### 浏览器版本

chrome 114

### 系统版本

windows 10

### Node版本

nodejs 14

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2604
