### ISSUE TITLE
[DropDown] 组件悬停出现列表后，某些情况下会出现变量错误，导致后续悬停功能失效

### ISSUE THREAD

**Issue by loganylwu** [Tencent/tdesign-vue#2598]
### 重现链接
https://tdesign.tencent.com/vue/components/dropdown

参考操作手法
https://github.com/Tencent/tdesign-vue/issues/2598#issuecomment-1643350965
经过我测试发现，其实在https://github.com/Tencent/tdesign-vue/issues/2352 是最稳定的复现逻辑了，错误原因也是一样

### 重现步骤
复现步骤比较麻烦，请参考视频

### 期望结果
悬停能正常显示

### 实际结果
悬停不能正常显示

| Environment | Info |
|---|---|
| 相关版本 | 1.4.8 |
| 框架版本 / 基础库版本 | vue(2.6.x) |
| 系统、浏览器 | 全部 |
| Node版本 | 全部 |

**Comment by loganylwu** [comment]
https://github.com/Tencent/tdesign-vue/assets/26224399/b02c38dc-cde6-494a-b34d-a014ae26170a

**Comment by loganylwu** [comment]
## 协助处理问题

经过调试和分析，我得出结论
无法打开悬停内容，是因为
https://github.dev/Tencent/tdesign-vue/blob/f516ae83ef2604552ea1b7f0624892945715d0d9/src/popup/popup.tsx#L310
此处判断变量 mouseInRange为true，导致直接return了。
**组件命名已经关闭了，为什么还会出现mouseInRange=true的情况呢？**
  - 因为在下拉框关闭期间，是有使用setTimeout(delay)的逻辑的，我怀疑是在delay期间，鼠标恰巧进入到了下拉框元素内，而此时由于没有屏蔽掉.popup.tsx中的onMouseEnter/onMouseLeave，导致mouseInRange变量被修改为true。
  

https://github.dev/Tencent/tdesign-vue/blob/f516ae83ef2604552ea1b7f0624892945715d0d9/src/popup/popup.tsx#L316

**Comment by loganylwu** [comment]
#2594

**Comment by loganylwu** [comment]
#2280

**Comment by loganylwu** [comment]
#2352

**Comment by loganylwu** [comment]
测了一下，1.6.4版本依然会有问题，多点击2次就出现了
https://stackblitz.com/edit/angular-asuhkv-fzdpmh?file=package.json

**Comment by uyarn** [comment]
fixed in 1.8.0
