### ISSUE TITLE
select多选选中状态的时候，下拉框选项中，总有一个颜色有问题

### ISSUE THREAD

**Issue by zhangningself** [Tencent/tdesign-vue#260]
![image](https://user-images.githubusercontent.com/26316530/149889155-502c7439-8dee-423b-ba0b-410cb3263120.png)

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150675723-0ccab44a-4c16-4527-8882-9c7b747b341e.png)

@zhangningself 没有在官网复现这个问题，为了更快速的定位问题，辛苦给一个 codesandbox 链接

**Comment by geff1991** [comment]
这个是键盘事件上下键选中已选项时的展示效果，上下键移动时，这个样式会变， @chaishi 这里样式要不要调下。
我也优化下这里，初始打开弹出层 没按下上下按键时，不默认出现这种样式。

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
