### ISSUE TITLE
[Dialog] 弹窗组件如果初始默认显示，按esc关不掉

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2608]
### tdesign-vue 版本

1.4.7

### 重现链接

https://stackblitz.com/edit/igrydh?file=src%2Fdemo.vue

### 重现步骤

弹窗组件初始默认显示，或者使用了v-if，不会触发 esc的监听。

应该是默认显示或者v-if，导致visible初始就是true，没有触发组件内部对visible的watch

<img width="1427" alt="企业微信截图_f80a9e8a-9aa6-4664-8308-8d586cfd5ec0" src="https://github.com/Tencent/tdesign-vue/assets/9960612/9d0c2ff0-c65a-4e98-961f-4bda3d9dc6f1">

### 框架版本

2.6.14

**Comment by Zhanjiachun** [comment]
认领该任务，截止时间23号前完成提交

**Comment by uyarn** [comment]
fixed in 1.6.5
