### ISSUE TITLE
[input-number] 设置decimalPlaces属性后，如果父组件设置InputNumber的value值，会触发InputNumber的change事件

### ISSUE THREAD

**Issue by luguokong** [Tencent/tdesign-vue#2616]
### tdesign-vue 版本

1.4.8

### 重现步骤

应该是源码useInputNumber中，watch逻辑判断错误导致

![image](https://github.com/Tencent/tdesign-vue/assets/21010969/31201a49-99a3-4817-b762-c679396068a5)

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2617

**Comment by xiaosansiji** [comment]
fixed in 1.5.0
