### ISSUE TITLE
[Table] 表格头部筛选TableColumnFilter，期望能支持设置attrs

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2627]
### tdesign-vue 版本

1.4.7

### 重现步骤

表格的表头筛选，支持自定义组件并设置props，但存在某些自定义组件是基于基础组件二次封装的，会透传所有$attrs给基础组件（比如我们封装的员工选择器基于基础select），但目前无法设置attrs。
<img width="1000" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/a232e6f3-b644-4edf-82dc-cd306a409bec">

查看源代码，发现即使指定 attrs，也会强行转为props传递，不符合预期。
<img width="771" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/72e3cd37-d6f2-4042-af1d-12edeb8f6ca9">

### 期望结果

表格的表头筛选，能设置component的attrs

### 框架版本

2.6.14

**Comment by chaishi** [comment]
Vue3 单独可以自动识别 props/attrs，Vue2 确实需要单独实现一下。

**Comment by vonlyinno** [comment]
> Vue3 单独可以自动识别 props/attrs，Vue2 确实需要单独实现一下。

求尽快支持，感谢

**Comment by vonlyinno** [comment]
再咨询下，上面截图中，对自定义组件取props，第二个参数为什么只支持将attrs作为props透传呢？如果我同时设置了props或者其他属性比如class，会被丢弃
`const tProps = typeof b === 'object' && 'attrs' in b ? b.attrs : {};`

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2629

**Comment by chaishi** [comment]
> 再咨询下，上面截图中，对自定义组件取props，第二个参数为什么只支持将attrs作为props透传呢？如果我同时设置了props或者其他属性比如class，会被丢弃
> `const tProps = typeof b === 'object' && 'attrs' in b ? b.attrs : {};`

不同的写法，走不同的 分支代码。

<img width="1185" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/0286a492-88fa-4962-b96d-3e0279ffd3b6">

**Comment by xiaosansiji** [comment]
fixed in 1.5.1
