### ISSUE TITLE
[Link] 不支持设置download属性

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2628]
### tdesign-vue 版本

1.4.7

### 重现步骤

t-link基于a标签封装，但不支持设置a标签的原生属性

<img width="1024" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/198cf8cf-96bc-461b-bfaa-27e7e81e2d37">

### 框架版本

2.6.14

**Comment by xiaosansiji** [comment]
resolved in 1.6.0
