### ISSUE TITLE
[Menu] Vue2.7下使用MenuItem 点击报错

### ISSUE THREAD

**Issue by xiaoyi510** [Tencent/tdesign-vue#2633]
### tdesign-vue 版本

v1.5.0

### 重现步骤

我无法正常使用t-menu中的t-menu-item 的to 
使用后点击菜单就会报错

![image](https://github.com/Tencent/tdesign-vue/assets/20254874/42bd43ab-51e7-45e8-975e-237d99766f08)

![image](https://github.com/Tencent/tdesign-vue/assets/20254874/9fa88272-46a3-4c32-b89a-d1b6fee35d42)

getCurrentInstance(); 返回null

### 期望结果

可以正常点击

### 实际结果

会报错

### 框架版本

vue(2.7)

### 浏览器版本

Chome(110)

### 系统版本

Macos(11)

### Node版本

18

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-8hldff?file=/src/demo.vue 可以在这个codesandbox复现下吗？不知道怎么触发这个Bug

**Comment by xiaoyi510** [comment]
代码如下
```
<template>
  <div class="box">
    <t-menu>
      <t-menu-item
        key="PageEnmu.AdminCompanyPageName"
        :to="{ path: '/admin/company' }"
        name="测试"
        value="/admin/company"
      >
      </t-menu-item>
    </t-menu>
  </div>
</template>

<script>

export default {
  components: {
  },
  methods: {
  
  },
};
</script>

```

**Comment by xiaoyi510** [comment]
报错如下
```
Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of null (reading 'proxy')"

found in

---> <TMenuItem>
       <TMenu>
         <TMenuMapprops>
           <Demo> at /src/demo.vue
             <Root>
```

**Comment by xiaoyi510** [comment]
@uyarn

**Comment by uyarn** [comment]
1.5.2-naruto已经修复 升级下
