### ISSUE TITLE
[Select] @vue/composition-api开发的组件，单独使用没有问题，和其他插件结合则下拉框失效

### ISSUE THREAD

**Issue by mdxiaohu** [Tencent/tdesign-vue#2635]
### tdesign-vue 版本

1.5.0

### 重现步骤

当组件和其他基于@vue/composition-api开发的三方插件使用的时候，则组件下拉框不再展示。
例如：vue-echarts

### 期望结果

可以正常展示下拉框

### 实际结果

下拉框不展示

### 框架版本

Vue(2.6.14)

### 浏览器版本

谷歌(98.0.4758.9)

### 系统版本

Windows10

### Node版本

15.0.1

### 补充说明

真的太坑了~

**Comment by skytt** [comment]
方便请提供一下 CodeSandbox 链接或最小复现仓库

**Comment by mdxiaohu** [comment]
我升级了vue-cli现在可以了~
