### ISSUE TITLE
[dialog] 反馈类对话框丢失 css class

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue#2636]
### tdesign-vue 版本

tdesign-vue 1.4.7

### 重现链接

无

### 重现步骤

使用反馈类对话框，即 `Dialog` 的 `theme` 设置为 `"info"`/`"warning"` 等。

### 期望结果

对话框内容元素应携带 css class `t-dialog__body` 。

### 实际结果

对话框内容元素只带有 css class `t-dialog__body__icon` ， 而没有 `t-dialog__body` 。

查看之前的版本，使用反馈类对话框时，内容元素上会同时带有  `t-dialog__body__icon` 与 `t-dialog__body` ，但现在后者丢失了。这样导致我们一些定制的样式受到了影响，

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(109.0.5414.120)

### 系统版本

Windows 10

### Node版本

16.16.0

**Comment by xiaosansiji** [comment]
fixed in 1.5.1
