### ISSUE TITLE
[Upload]上传组件拖拽上传时无法设置accept属性，设置accept属性不会触发事件

### ISSUE THREAD

**Issue by xinller** [Tencent/tdesign-vue#2646]
### tdesign-vue 版本

1.5.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-mhsmqz?file=/src/demo.vue:713-1160

### 重现步骤

 <t-upload
        v-model="files"
        :autoUpload="autoUpload"
        :theme="display"
        :data="{ extra_data: 123, file_name: 'certificate' }"
        :abridgeName="[10, 8]"
        draggable
        accept='.docx, .doc, .zip'
        action="https://service-bv448zsw-1257786608.gz.apigw.tencentcs.com/api/upload-demo"
        :formatResponse="formatResponse"
        @cancel-upload="onCancelUpload"
        @remove="onRemove"
      />

### 期望结果

希望拖拽上传能够同时支持accept属性，希望尽快修复。1.4.7就说修复了实际并未生效问题仍然存在

### 框架版本

2.6.14

### Node版本

14.19.0

**Comment by weitapianzhi** [comment]
确实有这个问题

**Comment by 366799861zhaowei** [comment]
我也遇到的了这个问题，除了用beforeUpLoad,还有别的方法吗？老版本浏览器的兼容性不行。

**Comment by chaishi** [comment]
我尝试了一下，可以。

https://github.com/Tencent/tdesign-vue/assets/11605702/4562ce65-8fda-4938-8b51-616fe359c2e6

**Comment by xinller** [comment]
那你试试传.docx的文件也不会上传

**Comment by chaishi** [comment]
> 那你试试传.docx的文件也不会上传

所以，问题在这里。（之前看了很久没有看明白什么意思）

**Comment by xinller** [comment]
对对对 就是要传的类型也传不了，去掉就可以传

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1547

**Comment by xiaosansiji** [comment]
fixed in 1.5.1
