### ISSUE TITLE
[select] 点击选项框下拉出现无法通过点击框内收起展开的菜单

### ISSUE THREAD

**Issue by 202780181** [Tencent/tdesign-vue#2649]
### tdesign-vue 版本

1.5.0

### 重现步骤

点击下拉框 打开下拉菜单  无法通过再次点击菜单框收起下拉菜单

### 期望结果

未展开时点击下拉框展开 展开后点击时收起下拉菜单

### 框架版本

Vue(2.6.14)

**Comment by uyarn** [comment]
没有复现这个问题

**Comment by uyarn** [comment]
知道你的问题了 这个是现在的交互设计 暂时不打算改动
