### ISSUE TITLE
“下拉”框交互延迟看着非常难受，给人点击之后卡一下的感觉

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign-vue#265]
“下拉”框交互延迟看着非常难受，给人点击之后卡一下的感觉。看着是先 focus 高亮动画完成再浮层 fade out，整个过程有 300+ms 感知明显，不知道是浮层动画曲线的原因还是串行动画

**Comment by uyarn** [comment]
已经优化了 https://github.com/Tencent/tdesign-common/pull/106 有问题再reopen吧。
