### ISSUE TITLE
[Feature Request] 是否有规划做一个通用的 pageHeader

### ISSUE THREAD

**Issue by backrunner** [Tencent/tdesign-vue#266]
隔壁 ant-design-vue 有提供 PageHeader 组件，使开发者可以非常快速地在页面里添加一个契合整个框架设计风格的页头。
如果 tdesign 也能有类似组件的话，一方面开发者的效率能提升，另一方面官方提供这种组件也能保持整个页面看起来设计风格一致，自己实现的页头可能会和组件库看起来不那么搭。

功能上期望这个组件能够和 ant-design-vue 的 PageHeader 能力类似，至少要有基本的标题、返回、面包屑、标题栏尾部自定义。

**Comment by chaishi** [comment]
需求已收到，我们讨论一下
