### ISSUE TITLE
[Select] 组件搜索性能存在严重问题

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#2663]
### tdesign-vue 版本

1.5.2

### 重现步骤

官方的懒加载示例（10000 option），增加filterable属性，支持搜索。

### 实际结果

搜索会严重卡顿，影响输入，有很大的优化空间。

同样的10000 option，在antd中搜索时，几乎感知不到卡顿现象。

### 框架版本

2.6.x

**Comment by xiaosansiji** [comment]
fixed in 1.6.3
