### ISSUE TITLE
[t-table] 开启虚拟滚动功能后表格横向拖动时表头没有一起移动

### ISSUE THREAD

**Issue by yudishengsheng** [Tencent/tdesign-vue#2670]
### tdesign-vue 版本

1.5.2

### 重现步骤

1、copy 文档中虚拟滚动的表格代码，
2、运行正常，
3、修改 columns ，增加字段，使表格可以横向滚动
4、横向滚动表格，表头没有移动

### 期望结果

横向滚动时，表头同步移动

### 实际结果

横向滚动时，表头没有移动

### 框架版本

Vue(2.7.13)

### 浏览器版本

Chrome(115.0.5790.99)

### 系统版本

Windows 11 (22H2)

### Node版本

14.18.0

### 补充说明

没有任何其他背景的情况下，直接使用该功能就会出现该问题

**Comment by chaishi** [comment]
提 issue 的时候，辛苦提供可以复现问题的链接。

由于没有提供可复现问题的链接，只能自己猜测尝试，但依旧没有复现描述中的问题。
这是正常表现的示例代码：https://stackblitz.com/edit/ngbeh6?file=src%2Fdemo.vue

示例代码表现如下，表头可以一起拖动，符合预期。
https://github.com/Tencent/tdesign-vue/assets/11605702/01fca564-5d36-4e95-aa82-37be8dda1a9e
