### ISSUE TITLE
[Table] row-click触发问题

### ISSUE THREAD

**Issue by ZhiZunJava** [Tencent/tdesign-vue#2671]
### tdesign-vue 版本

1.5.2

### 重现链接

http://139.155.251.50/product

### 实际结果

使用TDesign的Table组件有个需求是行点击展开一个Drawer抽屉，是可以进行触发的，但是在多选复选框和操作列中的链接组件点击也会进行触发，理论来说应该不会进行触发会影响用户体验的

### 框架版本

Vue（2.6.10）

### 浏览器版本

Edge（115.0.1901.188）

### 系统版本

Windows10（22H2）

### 补充说明

行点击触发的问题

**Comment by ZhiZunJava** [comment]
我想要的需求就是：触发点击事件且能拿到行数据方便操作（复选框或者说行中的某个列不受点击事件影响）

**Comment by ZhiZunJava** [comment]
我想要的需求就是：触发点击事件且能拿到行数据方便操作（复选框或者说行中的某个列不受点击事件影响）

**Comment by chaishi** [comment]
你在不需要触发行点击事件的时候，添加列配置 `stopPropagation` 阻止事件冒泡。

<img width="935" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/ba32ce08-50ce-40c6-a642-bababcb8fa2c">
