### ISSUE TITLE
[ImageViewer] 图片旋转或者缩放后,切换到下一张图片还是保持这种状态

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#2679]
### tdesign-vue 版本

1.5.2

### 重现链接

https://tdesign.tencent.com/vue/components/image-viewer?tab=demo

### 重现步骤

图片旋转或者缩放后,切换到下一张图片还是保持这种状态

### 期望结果

是否清除这种状态?或者每一张单独保存状态?

**Comment by chaishi** [comment]
如果支持，可能会新增一个 API，`keep-image-state`
