### ISSUE TITLE
[t-table] 自定义empty插槽中的内容在生产环境下不生效

### ISSUE THREAD

**Issue by XinYtimor** [Tencent/tdesign-vue#2682]
### tdesign-vue 版本

1.4.0

### 框架版本

vue2.6.11

### 补充说明

```javascript
  <template #empty>
            <div class="empty">
              <span >
                暂无数据、
              </span>
               <t-link
            theme="primary"
            hover="color"
            @click=""> 点击新增 </t-link>            
      </div> 
</template>
```
#
该段代码在生产环境下不生效

**Comment by chaishi** [comment]
变更日志：https://tdesign.tencent.com/vue/changelog

#### 提供信息过少，无法处理（官网也是正常环境，表现正常）请查看变更日志，升级到最新版本后，看看是否正常
<img width="849" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/23bb77f1-02d4-4b44-a049-24fe600b35ea”>
