### ISSUE TITLE
用了合并单元格表格设置高度height就会出现最后一条数据下面的边框线不出来

### ISSUE THREAD

**Issue by Zhangjinfan123** [Tencent/tdesign-vue#2698]
![image](https://github.com/Tencent/tdesign-vue/assets/47026296/ac86ac86-57f5-4952-82d0-62b47ec5034c)

**Comment by chaishi** [comment]
https://stackblitz.com/edit/1tyq9v?file=src%2Fdemo.vue
在这个链接里面复现一下你提到的问题（代码修改后记得保存）
