### ISSUE TITLE
[CheckboxGroup] options 为空时会控制台报错

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2700]
### tdesign-vue 版本

1.6.0

### 重现链接

https://stackblitz.com/edit/6qdls3?file=src%2Fdemo.vue

### 重现步骤

options 如果是异步加载的话 一开始是空数组会触发错误
<img width="1206" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/f24e4c06-c38e-4c95-9654-407614e571d6">

### 期望结果

不报错

### 实际结果

控制台报错

**Comment by chaishi** [comment]
fixed in `v1.6.2`
