### ISSUE TITLE
[TreeSelect] value 为数字时 options 为空时会控制台报错

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2701]
### tdesign-vue 版本

1.6.0

### 重现链接

https://stackblitz.com/edit/ye3zh1?file=src%2Fdemo.vue

### 重现步骤

options 异步会触发控制台报错
<img width="1535" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/a49e1544-9abc-49f8-b434-1a0bfa41e0f0">

### 期望结果

不报错

### 实际结果

报错

**Comment by uyarn** [comment]
fixed in 1.8.0
