### ISSUE TITLE
[t-Image] 动态加载的src不会实时更新

### ISSUE THREAD

**Issue by zhanyabin** [Tencent/tdesign-vue#2703]
### tdesign-vue 版本

1.6.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-7q9mlh?file=/src/demo.vue

### 重现步骤

用定时器模拟接口后发现无法更新

### 期望结果

动态更新src图片能够被更新

### 实际结果

以前的1.3.x版本没有问题，更新到1.6.1版本之后出现问题，图片无法实时更新

### 框架版本

~2.6.14

### 浏览器版本

112.0.5615.138（正式版本） （64 位）

### 系统版本

win11

### Node版本

v14.21.0

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/2709

**Comment by vonlyinno** [comment]
同遇到 求修复

**Comment by chaishi** [comment]
fixed in `v1.6.2`
