### ISSUE TITLE
[CheckboxGroup] 动态赋值 disabled 失效

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2704]
### tdesign-vue 版本

1.6.0

### 重现链接

https://stackblitz.com/edit/6uklfd?file=src%2Fdemo.vue

### 重现步骤

<img width="924" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/f9df4790-de92-4946-8416-175507566577">
<img width="1041" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/5831df5b-731a-41b8-818b-c4bc0f0b83cc">

### 期望结果

disabled 有效

### 实际结果

disabled 无效

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/assets/11605702/89b810c9-59ce-4414-82bf-f6114ab16f80


https://stackblitz.com/edit/xt22tc?file=src%2Fdemo.vue
我尝试了一下 `"tdesign-vue": "1.6.1",`，正常

**Comment by Jiachang-Cai** [comment]
> 2023-08-17.15.50.56.mov 
> https://stackblitz.com/edit/xt22tc?file=src%2Fdemo.vue 我尝试了一下 `"tdesign-vue": "1.6.1",`，正常

同样的示例 1.6.1 也不正常

**Comment by chaishi** [comment]
both two bugs resolved in https://github.com/Tencent/tdesign-vue/pull/2706

**Comment by chaishi** [comment]
fixed in `v1.6.2`
