### ISSUE TITLE
[Menu] 菜单收起之后，三级及以后菜单在鼠标移动稍快的时候容易消失、跳走

### ISSUE THREAD

**Issue by ferdinandhuang016** [Tencent/tdesign-vue#2713]
### tdesign-vue 版本

1.6.2

### 重现链接

https://tdesign.tencent.com/vue/components/menu

### 重现步骤

鼠标快速从二级菜单移动到弹出的三级菜单
[https://1drv.ms/v/s!Ao8Tz3mjbDiJlKpF-eim1hOA6SZrJQ?e=gPHopX](url)

### 期望结果

菜单保持弹出状态及位置

### 实际结果

二级菜单消失，三级菜单出现在左上角

### 框架版本

Vue(2.6.10)

### 系统版本

Windows/Mac OS

### Node版本

14.19.0

**Comment by uyarn** [comment]
fixed in 1.8.0
