### ISSUE TITLE
[表格] 排序图标不一致

### ISSUE THREAD

**Issue by ghostzhang** [Tencent/tdesign-vue#2727]
### tdesign-vue 版本

1.6.2

### 重现链接

https://tdesign.tencent.com/vue/components/table

### 重现步骤

https://tdesign.tencent.com/vue/components/table#%E5%A4%9A%E5%AD%97%E6%AE%B5%E6%8E%92%E5%BA%8F
https://tdesign.tencent.com/vue/components/table#%E6%9C%AC%E5%9C%B0%E6%95%B0%E6%8D%AE%E6%8E%92%E5%BA%8F

### 期望结果

非自定义图标，是否应该保持一致比较合理

### 实际结果

![image](https://github.com/Tencent/tdesign-vue/assets/194242/4a5a7435-9e05-44b0-a076-8d426c35358a)

**Comment by xiaosansiji** [comment]
![image](https://github.com/Tencent/tdesign-vue/assets/7600149/42054123-ce77-4700-9aca-2492b6482d0c)
这里并不是组件实现有差异，下面这个例子是要演示用 `globalLocale` 更改默认的排序箭头，可能没有上面的文字描述产生误解了。。

**Comment by chaishi** [comment]
就是为了演示可以通过全局配置，一次性全局修改表格图标特地写的示例 `GlobalConfigProvider`
从组件本身的功能上来说，没有问题
