### ISSUE TITLE
全局配置datePicker.format不生效

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#273]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by uyarn** [comment]
timepicker.format没有全局配置。

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue/blob/develop/src/config-provider/type.ts

**Comment by huangpiqiao** [comment]
api文档里面写了，更新一下咯

**Comment by uyarn** [comment]
![image](https://user-images.githubusercontent.com/26377630/150068745-703a90ae-709d-4d61-ba60-c9143dbd2585.png)
哪里呀？一直没有支持format全局配置额

**Comment by huangpiqiao** [comment]
![image](https://user-images.githubusercontent.com/16223845/150073372-49758cdf-2d3f-4221-a7dd-6754b03ee526.png)
写错了，应该是datePick

**Comment by uyarn** [comment]
噢 改下title reopen

**Comment by xiaosansiji** [comment]
看起来是生效的呀：https://codesandbox.io/s/rdh7d?file=/src/demo.vue @huangpiqiao

**Comment by huangpiqiao** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-u7e6r?file=/src/demo.vue
全局的不生效，不是组件的不生效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] 全局配置datePicker.format不生效 (Issue #273)





 
看起来是生效的呀：https://codesandbox.io/s/rdh7d?file=/src/demo.vue @huangpiqiao
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
