### ISSUE TITLE
[Select]select组件visible-change事件触发异常

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#274]
**Describe Framework**

tdesign-vue

**Describe Environment**
v0.32.0

Add browser version here

**Describe the bug**
select组件在选中下拉框其中一个选项后，下拉框隐藏，但是visible-change事件没有触发，不符合文档中事件触发时机的描述（下拉框隐藏/显示时触发）

示例如下所示：
https://codesandbox.io/s/tdesign-vue-demo-forked-qd0eg?file=/src/demo.vue

**Additional context**

**Comment by chaishi** [comment]
已修复并发布至 `0.33.2`
