### ISSUE TITLE
[popup] 当NODE_ENV环境变量为'test'时，切换路由时会导致窗口无法关闭

### ISSUE THREAD

**Issue by xinller** [Tencent/tdesign-vue#2749]
### tdesign-vue 版本

1.5.2

### 重现链接

https://github.com/Tencent/tdesign-vue/blob/develop/src/popup/container.tsx

### 重现步骤

打开t-popup时，不进行关闭窗口的操作时，此时切换路由到其他的页面时，该窗口无法关闭

### 期望结果

  destroyed() {
    if (typeof process !== 'undefined' && process.env?.NODE_ENV === 'test') return;
    this.unmountContent();
  },

建议：源码popupt/container.tsx这个文件中去掉这边环节变量判断，不理解为什么加上这个判断，巧了我们业务测试环境正好是test，虽然说可以改，但是不去看源码 ，根本找不到这个问题原因

**Comment by uyarn** [comment]
fixed in 1.6.5
