### ISSUE TITLE
[Dialog] this.$dialog.confirm 无法动态更改options值

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2751]
### tdesign-vue 版本

1.6.4

### 重现链接

https://stackblitz.com/edit/tvmnz9?file=src%2Fdemo.vue

### 重现步骤

点击确认无法更改loading 状态

### 期望结果

更改loading 状态

### 实际结果

点击确认无法更改loading 状态

**Comment by chaishi** [comment]
示例用法：
https://stackblitz.com/edit/tvmnz9-pmxchd?file=src%2Fdemo.vue

**Comment by chaishi** [comment]
未来更多解决方案：
https://github.com/Tencent/tdesign-vue/pull/2769

**Comment by Jiachang-Cai** [comment]
> 后续更多解决方案： #2769

这个解决方案能解决更改动态按钮文字？
