### ISSUE TITLE
[EnhancedTable] expandedTreeNodes.sync 配合 expandTreeNodeOnClick 有问题

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2756]
### tdesign-vue 版本

1.6.4

### 重现链接

https://stackblitz.com/edit/bfcnfa?file=src%2Fdemo.vue

### 重现步骤

点击非icon 展开不会更新expandedTreeNodes值
<img width="1398" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/df319ead-5138-4242-8ba8-3cb7b66805c4">

### 期望结果

更新expandedTreeNodes值

### 实际结果

点击非icon 展开不会更新expandedTreeNodes值

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2767/commits/17cc50f092c68dd8216e0f1b5c68523b50456bfc
