### ISSUE TITLE
[checkbox] 同时有多个checkbox-group时，选中值显示异常

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2761]
### tdesign-vue 版本

1.4.8以上

### 重现链接

https://stackblitz.com/edit/a5z96v?file=src%2Fdemo.vue,package.json

### 重现步骤

页面添加多个checkbox-group，点击的和选中的不是同一个checkbox-group

<img width="349" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/c1d4e065-0e24-4f40-ab9a-044a9e149296">

### 框架版本

2.6.14

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2768
