### ISSUE TITLE
【Table】tableLayout设置为auto之后，表格头部和表格内容错位

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign-vue#278]
tableLayout设置为auto之后，表格头部和表格内容错位
![1](https://user-images.githubusercontent.com/96863479/149899104-f5b05d18-09de-4c68-b835-fa489cb4ec3c.png)

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150647652-598e30c4-289b-431d-a6c0-eaced2d702ca.png)

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/365

to be published

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验

**Comment by chaishi** [comment]
resolved in `v0.39.1`
