### ISSUE TITLE
[popover与tooltips] 当触发他的元素不再可视区域内，自动隐藏。

### ISSUE THREAD

**Issue by zhoulujun** [Tencent/tdesign-vue#2781]
### 这个功能解决了什么问题
比如button 添加了tootips ，当button滚动到不可见区域，或者上面被东西覆盖了。自动隐藏。

![image](https://github.com/Tencent/tdesign-vue/assets/4243366/47f78fdb-cda2-4269-abf8-8b5f46f18542)

### 你建议的方案是什么

用 IntersectionObserver 监听他的触发容器，当元素不可见，自动隐藏触发内容。

**Comment by uyarn** [comment]
popup底层的位置是依赖popperjs来控制的；
https://popper.js.org/docs/v2/modifiers/hide/ 如果不需要它自动做modifier的位置变化，可以通过这个样式设置来满足需求
