### ISSUE TITLE
[table] table 表格宽度配置自适应增多配置：1、自适应表头列文字宽度、2、可以配置不换行，文本省略展示。

### ISSUE THREAD

**Issue by zhoulujun** [Tencent/tdesign-vue#2783]
### 这个功能解决了什么问题

1、
**增加配置**：可以配置表格单元格不文字不换行、每个单元格都展示一行文字。超出省略。省略的问题，hover tootlips展示全部文本。
**解决问题**： 单元格高度都统一。
2
**增加配置**：表头单元格可以根据表头内容的宽度，每一个列表头内容多长，这一列都展示多宽。
**解决问题**： 可以设置min-width。但是我希望表头展示一行，都全部展示出来。表头不希望换行。

### 你建议的方案是什么

计算文本宽度。可以  参考：https://github.com/zhoulujun/textOverflowTitle/tree/main/packages/utils

**Comment by chaishi** [comment]
第 1 点的功能，文本单行超出省略支持的哦，设置 ellipsis: true，或者 titleEllipsis: true 就可以了

**Comment by chaishi** [comment]
第 2 点，很少听说列宽是根据表头的宽度来设定，大多是根据内容，暂未收到其他业务有类似的需求。暂不支持。
