### ISSUE TITLE
按需引入时会默认修改部分功能的全局配置（配置名称相同），例如绑定在 this 上的 $message 方法

### ISSUE THREAD

**Issue by zhangvj** [Tencent/tdesign-vue#2785]
### tdesign-vue 版本

1.6.5

### 重现步骤

1.  项目的 main.js 已经全局引入 element-ui
2. 在项目的子组件中（或者靠后加载的页面）参照官方文档按需引入 t-tree 组件并使用
3.  在未使用 TDesign 组件的页面调用 this.$message.warning 方法，页面正常显示 element-ui 的消息弹窗
4. 进入含有 TDesign 组件的页面之后，再次 调用 this.$message.warning ，调用的是 TDesign 的消息弹窗组件

目前经测试：this 上的 $message 方法，以及指令 v-loading 会被 TDesign 中同名方法及指令覆盖

### 期望结果

按需引入 TDesign 组件时，绑定在 vue 原型上的同名方法和指令不受影响

### 实际结果

按需引入 TDesign 组件时，绑定在 vue 原型上的方法和指令受到 TDesign 同名方法和指令所覆盖

### 框架版本

Vue2（2.6.*）

### 浏览器版本

116.0.5845.179

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/issues/2786
