### ISSUE TITLE
按需引入时会默认修改部分功能的全局配置（配置名称相同），例如绑定在 this 上的 $message 方法

### ISSUE THREAD

**Issue by zhangvj** [Tencent/tdesign-vue#2786]
### tdesign-vue 版本

1.6.5

### 重现步骤

1.  项目的 main.js 已经全局引入 element-ui
2. 在项目的子组件中（或者靠后加载的页面）参照官方文档按需引入 t-tree 组件并使用
3.  在未使用 TDesign 组件的页面调用 this.$message.warning 方法，页面正常显示 element-ui 的消息弹窗
4. 进入含有 TDesign 组件的页面之后，再次 调用 this.$message.warning ，调用的是 TDesign 的消息弹窗组件

目前经测试：this 上的 $message 方法，以及指令 v-loading 会被 TDesign 中同名方法及指令覆盖，其他暂时未知

### 期望结果

**按需引入 TDesign 组件时，绑定在 vue 原型上的同名方法和指令不受影响。**
**希望这些绑定在 vue 原型 上的方法及指令能够支持按需引用配置**

### 实际结果

按需引入 TDesign 组件时，绑定在 vue 原型上的方法和指令受到 TDesign 同名方法和指令所覆盖

### 框架版本

Vue2（2.6.*）

### 浏览器版本

116.0.5845.179

### 系统版本

MacOS（10.15.7）

### Node版本

16.17.0

### 补充说明

在老项目中为了减少打包体积以及减少对原有功能的影响，基本都会使用按需引入的方式，希望能尽量减少全局配置方面的修改

**Comment by zhangvj** [comment]
目前我的解决办法是在 main.js 中先按需引入我要使用的 TDesign 组件，再去引入注册 element-ui 的组件

**Comment by wishzhang** [comment]
指令没有命名空间，都用v-loading，组件库之间冲突了并且tdesign的没法覆盖
