### ISSUE TITLE
[Form] required和pattern同时出现时格式校验无效

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue#2789]
### tdesign-vue 版本

1.6.5

### 重现链接

https://codesandbox.io/s/ge-shi-xiao-yan-vtlvzw?file=/src/App.vue

### 重现步骤

校验内容  rtsp://admin:admin123@172.20.4.16:8554/live1.h264

根据自定义校验规则流地址path必须使用rtsp开头，然而当required和pattern同时出现时无法正确进行校验，根据[重现链接](https://codesandbox.io/s/ge-shi-xiao-yan-vtlvzw?file=/src/App.vue)我提供了两个方案，方案一输入值不为空无论输入什么内容都可以通过校验，方案二只有输入正确的格式才允许通过校验

### 期望结果

方案一输入正确的格式才允许通过校验

### 实际结果

方案一输入值不为空无论输入什么内容都可以通过校验

### 框架版本

2.6.12

### Node版本

16

**Comment by chaishi** [comment]
https://codesandbox.io/s/ge-shi-xiao-yan-forked-fyxxrj
这样写就对了，一个规则一个数组项。required/pattern/validator/max/min/... 等都是独立项存在

```
{
  required: true,
  message: "此项必填",
},
{
  pattern: /^rtsp:\/\/([a-z0-9A-Z]{0,20}:[a-z0-9A-Z]{0,20}@)?(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5]):[0-9]{1,5}/,
  type: "error",
  message: "rtsp地址格式错误！",
},
```

又或者这样
```
{
  validator: (val) => val && /^rtsp:\/\/([a-z0-9A-Z]{0,20}:[a-z0-9A-Z]{0,20}@)?(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5]):[0-9]{1,5}/.test(val),
  type: "error",
  message: "rtsp地址格式错误！",
},
```
