### ISSUE TITLE
[checkbox] 异步options导致初始值无效

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2792]
### tdesign-vue 版本

1.6.5

### 重现链接

https://stackblitz.com/edit/vujh77?file=src%2Fdemo.vue,package.json

### 重现步骤

实际使用时，表单的value和checkbox的options都是异步请求的数据，如果options耗时更久，设置的初始值初始未勾选且无法check。

<img width="999" alt="企业微信截图_2ae642b4-592a-4b27-86e4-53d77c5d0325" src="https://github.com/Tencent/tdesign-vue/assets/9960612/eb4f4660-2513-463e-8a83-6bc4b7977d5e">

### 期望结果

初始值能正常渲染

### 框架版本

2.6.14

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/2793
