### ISSUE TITLE
[input] 加上 type="number" 报错

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-vue#2796]
### tdesign-vue 版本

1.3.0

### 重现链接

https://codesandbox.io/s/l52527?file=/src/demo.vue

### 重现步骤

打开重现链接

在 
`<t-input Label="价格:" suffix="元" /> `

中加 

`type="number"`

<img width="1542" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/4584905/ae152dd4-564e-4e26-9fcc-bd5f4f95a573">

然后在输入框输入数字，检查控制台

<img width="1508" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/4584905/860d8cff-5702-4bc9-a776-2fc52a3f9050">

### 期望结果

不报错

### 实际结果

控制台报错

InvalidStateError
Failed to set the'selectionEnd' property on'HTMLInputElement': The input element's type ('number')does not support selection.

**Comment by chaishi** [comment]
为何不使用 InputNumber 呢？ 专门输入数字的

**Comment by uyarn** [comment]
fixed in 1.8.0
