### ISSUE TITLE
组件没有使用icon组件但是还是不断重复请求icon的js资源

### ISSUE THREAD

**Issue by better-pz** [Tencent/tdesign-vue#2799]
### tdesign-vue 版本

    "@tencent/tdesign-icons-vue": "0.0.4",     "@tencent/tdesign-vue": "0.27.2",

### 重现步骤

<img width="911" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/68367439/e2d7df3f-9c94-4e4d-ad79-44c34239d5a5">

### 期望结果

我使用本地的fonts/index.js文件资源后，不再重复请求远程的js资源

### 实际结果

一直不断请求，我并没有使用icon组件，是否是其他Tdesgin组件中自带了icon

**Comment by uyarn** [comment]
有可能是之前的版本对icon的使用不规范 使用了icon-font导致的 新的版本都是规范的用法 
但是目前不再维护0.x的版本了 如果可以请升级到1.x以上的版本
