### ISSUE TITLE
[Table] 树形结构表格onExpandedTreeNodesChange回调事件不触发

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue#2800]
### tdesign-vue 版本

1.6.0

### 重现步骤

点击行的回调row-click触发了，但树折叠展开回调onExpandedTreeNodesChange不触发
源代码：
<t-enhanced-table ref="table" rowKey="Id" :data="data" :columns="columns"
      :tree="{ childrenKey: 'Children', treeNodeColumnIndex: 0, expandTreeNodeOnClick: true }"
      @row-click="rowClick" @onExpandedTreeNodesChange="onExpandChange" height="370px"></t-enhanced-table>
  </div>

### 期望结果

希望帮忙看看这个问题

### 框架版本

Vue(2.6.0)

### Node版本

14.2.0

**Comment by chaishi** [comment]
变更日志：https://tdesign.tencent.com/vue/changelog
最新版本号：v1.6.6

`expandedTreeNodes.sync`  `expandTreeNodeOnClick` `@expanded-tree-nodes-change` 是在 v1.6.4 和 v1.6.5 中完整统一支持的。

**Comment by chaishi** [comment]
关于 Issue 中提到的 “重现链接” 没有填写，无法确定是组件的问题。当前 issue close。
请在下面的链接中尝试复现你的问题，如果可以复现再单独提 issue，或者 reopen 当前 issue。

https://stackblitz.com/edit/y7yjkw?file=src%2Fdemo.vue
代码修改可复现问题后，保存代码，粘贴新的链接到 issue。

后续反馈问题也希望可以可能提供这样的可复现问题链接。
<img width="329" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/f2f180d2-1744-4388-a00b-2ec96fcef309">
