### ISSUE TITLE
table template 无法渲染

### ISSUE THREAD

**Issue by akssmaw** [Tencent/tdesign-vue#2802]
### tdesign-vue 版本

https://unpkg.com/tdesign-vue/dist/tdesign.min.js

### 重现链接

https://codepen.io/mesuper/pen/MWZmGBp

### 重现步骤

  <template #user-name>
    123
  </template> 
123无法渲染 我试了在template #userName 也不行

我使用的是vue.js 版本 没有用cli 使用脚手架是开可以的 
请问我在vue.js  html里面用什么写法才能渲染

### 框架版本

https://unpkg.com/vue@2.6.14/dist/vue.js

**Comment by uyarn** [comment]
<img width="923" alt="WeChatWorkScreenshot_9b0ef480-7c1e-4ccb-8ef5-33bd9c6997cb" src="https://github.com/Tencent/tdesign-vue/assets/26377630/a50359ae-f9c4-4799-8ebf-0a679acbfab4">
umd的用法还需要@vue/composition-api哦

**Comment by akssmaw** [comment]
您好 我这边已经使用了  这次报错；

**Comment by akssmaw** [comment]
> <img alt="WeChatWorkScreenshot_9b0ef480-7c1e-4ccb-8ef5-33bd9c6997cb" width="923" src="https://user-images.githubusercontent.com/26377630/267308154-a50359ae-f9c4-4799-8ebf-0a679acbfab4.png"> umd的用法还需要@vue/composition-api哦
您好 我这边已经使用了 这次报错；

**Comment by akssmaw** [comment]
![image](https://github.com/Tencent/tdesign-vue/assets/48310423/251cbdda-1c65-4c4b-be8e-21a98c92f02c)
我在本地shi'le'yi'xia试了一下 采用全部小写的格式提示正确 驼峰命名出现错误

**Comment by uyarn** [comment]
驼峰命名是指组件还是props?

**Comment by akssmaw** [comment]
> 驼峰命名是指组件还是props?

template  无法驼峰命名  改成小写可以

**Comment by uyarn** [comment]
这个可能不是我们组件影响的问题 umd这种使用方式也比较少 麻烦用小写的方式来使用

**Comment by akssmaw** [comment]
好的
