### ISSUE TITLE
[t-menu菜单组件] vue组件最新版本的t-menu菜单在mac safari下展开箭头不会变

### ISSUE THREAD

**Issue by lavender-juan** [Tencent/tdesign-vue#2804]
### tdesign-vue 版本

1.6.6最新版

### 重现链接

https://tdesign.tencent.com/vue/components/menu 官网链接在mac safari下即可复现

### 重现步骤

<img width="474" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/55191916/dd72e35a-790b-48b0-a0cf-3027a758579d">

### 期望结果

同chrome等浏览器展示时，箭头方向跟着变化

### 浏览器版本

safari版本16.6 (18615.3.12.11.2)

**Comment by uyarn** [comment]
已知问题 因为为了达到从中间直接向下反转的视觉效果 目前的箭头是通过改动svg的d属性来实现的 safari无法支持这个动画 暂时也不打算修改
