### ISSUE TITLE
[hooks] useResizeObserver.ts 判断 container 是否存在有误

### ISSUE THREAD

**Issue by loganylwu** [Tencent/tdesign-vue#2805]
https://github.com/Tencent/tdesign-vue/blob/49fe24e02335052aa72408a341e19e816494ff12/src/hooks/useResizeObserver.ts#L4

**Comment by loganylwu** [comment]
若 container 是Ref<xxxx> 
那么判断是否应该 if(container.value)?

[  if (container) {](https://github.com/Tencent/tdesign-vue/blob/49fe24e02335052aa72408a341e19e816494ff12/src/hooks/useResizeObserver.ts#L25)

**Comment by chaishi** [comment]
是的，缺了个 `.value`

**Comment by chaishi** [comment]
此处使用 `container` 判断没有问题，当前元素存在时，才会添加 observer 监听。更为 `container.value` 在元素默认不显示场景，无法给出正确判断

回滚 PR: https://github.com/Tencent/tdesign-vue-next/pull/3411
