### ISSUE TITLE
[TagInput] 选项超长 & scroll滚动时，无法删除中间项

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2807]
### tdesign-vue 版本

1.6.5

### 重现链接

https://stackblitz.com/edit/mls3na?file=src%2Fdemo.vue

### 重现步骤

条件：tag-input的选项超长 & 超长scroll滚动时，
问题：无法选到中间的某一项删除，只能滑到最前面或最后面

### 框架版本

2.6.14

**Comment by chaishi** [comment]
或可增加左右键切换光标在标签之间的位置

**Comment by uyarn** [comment]
supported in 1.7.0
