### ISSUE TITLE
[Collapse] 传了value,默认展开所有失效

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2811]
### tdesign-vue 版本

1.6.6

### 重现链接

https://stackblitz.com/edit/jgu9a7?file=src%2Fdemo.vue

### 重现步骤

给折叠面板设置props如下，默认展开所有会失效
<img width="1186" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/0e15b7ec-5d6a-438d-8a6a-bf367f8f873e">

### 期望结果

能默认展开所有面板

**Comment by uyarn** [comment]
目前的逻辑受控非受控判断逻辑没法支持这种使用方式 传了value就会进入受控模式的
