### ISSUE TITLE
[Select] 远程搜索时，本地筛选失效

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2813]
### tdesign-vue 版本

1.6.6

### 重现链接

https://stackblitz.com/edit/jxs66z?file=src%2Fdemo.vue

### 重现步骤

select开启filter + search，本地筛选失效。
<img width="267" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/0e6cc484-78b4-48a2-b1e9-1f99a7cc98ac">

1.6.0是正常的。

### 期望结果

https://stackblitz.com/edit/yvhvfh?file=src%2Fdemo.vue

**Comment by uyarn** [comment]
已沟通 系1.6.1的修复
