### ISSUE TITLE
[ImageViewer] 关闭时偶尔会出现抖动现象

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue#2815]
### tdesign-vue 版本

1.6.6

### 重现链接

https://tdesign.tencent.com/vue/components/image-viewer

### 重现步骤

官网提供的“基础图片查看器”中打开预览窗口，通过Esc进行关闭（上述步骤重复多次），偶尔会出现画面抖动的现象，主要表现在图片隐藏动画执行过程中图片突然变大

### 期望结果

关闭后预览图不会出现抖动

### 框架版本

 2.6.14

### Node版本

16

**Comment by uyarn** [comment]
fixed in 1.7.0
