### ISSUE TITLE
[Table] 表格筛项的表头为自定义内容时触发显示内容出错

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue#2822]
### tdesign-vue 版本

1.6.7

### 重现链接

初始页面模板 + /list/filter

### 重现步骤

`<template #new_title>
          <t-tooltip content="合同状态tooltip">
            <help-circle-icon style="color: orange"/>
            合同状态
          </t-tooltip>
        </template>`

`{
          // title: '合同状态',
          title: 'new_title',
          colKey: 'status',
          width: 200,
          cell: { col: 'status' },
          filter: {
            type: 'single',
            showConfirmAndReset: true,
            list: [
              {label: '审核失败', value: 0},
              {label: '待审核', value: 1},
              {label: '待履行', value: 2},
              {label: '履行中', value: 3},
              {label: '已完成', value: 4}
            ],
          }
        }`

页面点击选项后确认  列表第一行显示：搜索“[object Object]：审核失败”，找到 79 条结果。

### 期望结果

搜索“合同状态：审核失败”，找到 79 条结果

### 实际结果

搜索“[object Object]：审核失败”，找到 79 条结果

### 补充说明

表格帅选项的表头为自定义内容时触发

**Comment by china-chaim** [comment]
![1](https://github.com/Tencent/tdesign-vue/assets/35481087/46524fc8-2712-4e94-a5aa-20ffb4084c69)
![2](https://github.com/Tencent/tdesign-vue/assets/35481087/815fb751-8ed1-4d4a-b96c-54b34b6d0c3b)
![3](https://github.com/Tencent/tdesign-vue/assets/35481087/b2cc475c-5bdf-496b-b0e2-ecc751385061)

**Comment by uyarn** [comment]
这个问题我记得已经支持过？@chaishi

**Comment by chaishi** [comment]
没有可复现问题的链接，无法处理
