### ISSUE TITLE
[ImageViewer] 预览滚轮缩放风格

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue#2825]
### 这个功能解决了什么问题

适配windows使用习惯，在windows中滚轮向前是放大，滚轮向内是缩小。目前预览时却是相反的，使用起来体验不是很好

### 你建议的方案是什么

内部代码处理滚轮缩放事件时，根据使用的系统（mac或windows）进行滚轮放大和缩小的逻辑处理
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-12-14 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by Barry-Flynn** [comment]
这个建议我在2022年6月提过（#1826），当时好像说有待讨论，至今无下文...哈哈

**Comment by uyarn** [comment]
optimized 1.8.3
