### ISSUE TITLE
虚拟滚动很卡。可编辑表格下，有46列，虚拟滚动阈值为50，当展示100行数据时滚动会很卡

### ISSUE THREAD

**Issue by wcccode** [Tencent/tdesign-vue#2834]
初步判断卡点为以下代码，需要触发滚动事件和内容动态渲染，会很耗时，而且连续滚动基本动不了，非常卡。看下这段代码是否可以优化
https://github.com/Tencent/tdesign-vue/blob/94262746e0f759b6a6778053c709ef3d34dfca34/src/hooks/useVirtualScrollNew.ts#L91
https://github.com/Tencent/tdesign-vue/blob/94262746e0f759b6a6778053c709ef3d34dfca34/src/hooks/useVirtualScrollNew.ts#L92

**Comment by uyarn** [comment]
@wcccode 可以贴下table具体使用的配置复现下吗？是开启懒加载的模式吗 100行也不是很多 列数很多的话 可能是每列渲染内容过复杂的影响

**Comment by uyarn** [comment]
没有更多回复 这里先关闭了 如果看到了再回复下再reopen哈

**Comment by wcccode** [comment]
您好，您的来信我已收到，谢谢！！！
