### ISSUE TITLE
[ImageViewer] 打开图片预览弹窗，点击浏览器后退按钮，弹窗卡住无法关闭

### ISSUE THREAD

**Issue by huxiao0802** [Tencent/tdesign-vue#2838]
### tdesign-vue 版本

1.6.7

### 重现链接

https://tdesign.tencent.com/vue/components/image-viewer

### 重现步骤

https://tdesign.tencent.com/vue/components/image-viewer
点击预览出现图片预览弹窗
点击浏览器的后退按钮页面返回当前域名下上一级页面
预览弹窗没有被关闭，且手动点击关闭按钮无法关闭

### 期望结果

浏览器前进后退可以自动关闭预览弹窗

### 实际结果

预览弹窗没有被关闭，且手动点击关闭按钮无法关闭

**Comment by uyarn** [comment]
意思是后退之前 要同时把imageViewer关闭吗？
