### ISSUE TITLE
tdesign-vue\lib\grid\row.js 文件存在 window not defined

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#284]
**Describe Framework**

tdesign-vue
"tdesign-vue": "^0.33.1",

**Describe the bug**
![image](https://user-images.githubusercontent.com/49895922/150094231-174e5640-8165-4c90-b51b-42b9eedb66d4.png)

**Comment by chaishi** [comment]
已发布至 `v0.33.2`
