### ISSUE TITLE
[Cascader] value 为数字时 options 为空时会控制台报错

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2840]
### tdesign-vue 版本

1.6.7

### 重现链接

https://stackblitz.com/edit/n7qafi?file=src%2Fdemo.vue

### 重现步骤

<img width="1339" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/6133bd8a-8534-439f-a927-1d35cd1f6010">

### 期望结果

不报错

### 实际结果

报错

**Comment by uyarn** [comment]
先string转一下 之前底层移除了input组件对number类型的支持（因为很多大数处理） 但是现在看来这个改动值得商榷 我们看看怎么处理好点

**Comment by uyarn** [comment]
fixed in 1.8.0
