### ISSUE TITLE
[Tree] 数据延迟加载的时候，v-model的值有子节点的时候，当子节点通过接口返回来却不会勾选上，点击的时候才显示勾选

### ISSUE THREAD

**Issue by Nickywrx** [Tencent/tdesign-vue#2841]
### tdesign-vue 版本

1.6.7

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue/assets/23066399/c6ef0c7d-7101-41cf-b73c-78c4f2147be2)
数据延迟加载当v-model的值含有子节点，但是子节点是通过点击父节点才请求回来的时候，展开子节点却不会自己勾选上，这个案例也是有问题的，当我点击子节点的时候，然后自己有自动勾选上了，明显是回显有问题，你可以自己去试试这个【数据延迟加载】这个案例

### 期望结果

【数据延迟加载】时，子节点通过异步请求回来时，v-model如果一开始就有子节点的id，希望子节点请求回来的时候，默认帮我勾选上

### 实际结果

异步请求的子节点并没有自己勾选上

**Comment by uyarn** [comment]
fixed 1.8.1
