### ISSUE TITLE
[Select] 设置 autoWidth 后，下拉面板宽度没有自适应

### ISSUE THREAD

**Issue by zyqq** [Tencent/tdesign-vue#2842]
### tdesign-vue 版本

1.6.3

### 重现步骤

设置autoWidth

### 期望结果

下拉面板宽度与选择器宽度一致

### 实际结果

下拉面板宽度比选择器宽度不一致

### 框架版本

2.6.14

### 补充说明

![image](https://github.com/Tencent/tdesign-vue/assets/15664576/fb26f004-9f3b-456b-887a-79984bbc62a3)

**Comment by chaishi** [comment]
如果有宽度需求，可以自行给 Select 组件设置一个 minWidth，用来设定默认宽度

**Comment by zyqq** [comment]
设置了minWidth不生效
