### ISSUE TITLE
[Checkbox] 动态disabled设置失效

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2843]
### tdesign-vue 版本

1.6.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-3q8dn6?file=/src/demo.vue

### 重现步骤

checkbox的disabled动态变化时失效

### 框架版本

2.6.14

**Comment by chaishi** [comment]
先试试这样写
https://codesandbox.io/s/tdesign-vue-demo-forked-3q8dn6?file=/src/demo.vue

<img width="1397" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/ff8116ac-6bbf-4baf-b639-cf39397f60e3">

**Comment by uyarn** [comment]
fixed in 1.7.1
