### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by ninannansheng** [Tencent/tdesign-vue#2851]
### tdesign-vue 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-rc853m?file=/src/demo.vue

### 重现步骤

format格式填写为YYYY-MM-DD HH:mm:ss，时间选择面板会空白
![image](https://github.com/Tencent/tdesign-vue/assets/95465051/5f3f88e2-c193-44a3-8542-b93f8ffdbac5)

### 期望结果

希望能够兼容下format的格式

### 框架版本

vue2

### 浏览器版本

chrome(109.0.5414.120)

### 系统版本

window11

### Node版本

16.14.2

**Comment by uyarn** [comment]
版本有点老了 0.x的版本都不是LTS的 麻烦升级一下 如果升级有困难 也可以私聊我们帮忙处理问题
