### ISSUE TITLE
[Checkbox] 点过滤后，checkbox显示选不上，然后实际上选中了 并且越选越多

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#2853]
https://stackblitz.com/edit/qvykn9-2a4sjq?file=src%2Fdemo.vue
<img width="1467" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/31959442/69cc6d09-aa00-4c26-9236-ffa241d3be4c">

**Comment by chaishi** [comment]
https://stackblitz.com/edit/qvykn9-uppum2?file=src%2Fdemo.vue
<img width="1036" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/11605702/12c07f8a-c7ef-4bcb-9324-f12a5106e58d">
