### ISSUE TITLE
[Checkbox] 代码删除绑定值后，使用 value.splice 设置值，界面不会取消选中，点击取消也点不动

### ISSUE THREAD

**Issue by xubinglove** [Tencent/tdesign-vue#2854]
https://stackblitz.com/edit/g3dgnq-w1ongz?file=src%2Fdemo.vue
<img width="1413" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/31959442/b3cd8169-2b40-467b-bb85-d1148a8aa709">

**Comment by chaishi** [comment]
我尝试了一下 Demo，可以正常点击

**Comment by chaishi** [comment]
似乎只有 value.splice 这类直接操作数据的方式表现会有点奇怪，而数组直接赋值表现正常

表现正常的代码：
```js
mounted() {
  setTimeout(() => {
    this.value1 = [];
  }, 1000);
},
```

表现正常的代码：
```
mounted() {
  setTimeout(() => {
    const newValue = [...this.value1];
    newValue.splice(0, 1);
    this.value1 = newValue;
  }, 1000);
},
```

表现异常的代码：
```js
mounted() {
  setTimeout(() => {
    this.value1.splice(0, 1);
  }, 1000);
},
```

**Comment by chaishi** [comment]
已在 https://github.com/Tencent/tdesign-vue/pull/2896 中支持 `this.value.splice` 用法，待发布

**Comment by uyarn** [comment]
fixed 1.7.2
