### ISSUE TITLE
[Layout] 没有右边区块吗？

### ISSUE THREAD

**Issue by az6161311** [Tencent/tdesign-vue#2856]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-vue/assets/9971676/ee38b2a6-2bcb-4f0b-a71b-4888f44506b2)

想实现这样的布局。

### 你建议的方案是什么

可以在区块之间的拖曳改变容器宽高..

**Comment by uyarn** [comment]
暂时没有
