### ISSUE TITLE
[cascader] 选项disabled修改后，选项不是禁用状态

### ISSUE THREAD

**Issue by lxc-orange** [Tencent/tdesign-vue#2859]
### tdesign-vue 版本

1.7.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-77nzcc?file=/src/demo.vue

### 重现步骤

<img width="1080" alt="截屏2023-10-20 00 20 06" src="https://github.com/Tencent/tdesign-vue/assets/108909689/c38de515-d447-45e5-82fa-26f1b171d650">
选中选项三后，在change事件中修改options中每一个选项的disabled为true，options中的数据已经被修改，但不是禁用状态。

### 框架版本

vue(~2.6.14)

**Comment by uyarn** [comment]
已修复 今天发布个版本

**Comment by lxc-orange** [comment]
你好，针对 Issue #2859 的cascader选项动态禁用的问题，在1.7.1版本中并没有彻底修复，1.7.1版本在动态修改disabled后是没有显示禁用状态的，只是不能选中，效果如下：
https://i.imgs.ovh/2023/10/24/FLdqT.png
导致这个的原因是，没有实时修改 panels 中的 disabled ，没有同步 props 中的 options 数据


如果要添加禁用状态是需要在 src/cascader/hooks.ts 中监听options中添加一个深度监听，效果如下：https://i.imgs.ovh/2023/10/24/FLDHu.png













在 2023-10-20 11:14:34，"wū yāng" ***@***.***> 写道：

已修复 今天发布个版本

**Comment by uyarn** [comment]
fixed 1.7.2
