### ISSUE TITLE
[Select] Select折叠项内容 collapsedItems 期望抛出移除折叠标签事件

### ISSUE THREAD

**Issue by ubloglab** [Tencent/tdesign-vue#2862]
### tdesign-vue 版本

1.7.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-lt4ng6?file=/src/demo.vue:1121-1165

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue/assets/37498563/dc13ff39-df28-457a-9aef-1461bcaf9c25)

**Comment by uyarn** [comment]
这个需要增加API 需要在API平台进行修改 https://github.com/tdesignoteam/tdesign-api

**Comment by uyarn** [comment]
supported 1.7.2
