### ISSUE TITLE
[Table] 可拖拽行表格能否实现动态开启/关闭拖拽排序功能

### ISSUE THREAD

**Issue by zhaobo-98** [Tencent/tdesign-vue#2866]
### 这个功能解决了什么问题

有些场景需要动态开启/关闭排序功能

### 你建议的方案是什么

提供一个属性，动态控制

**Comment by chaishi** [comment]
如果要关闭，传递 dragSort=undefined，同时 columns 不要传 `colKey: 'drag'`
如果要生效，传递 `dragSort=row` 或者 `row-handler`
`<t-table  :dragSort="A ? 'row' : undefined " />`

```
<t-table
  rowKey="index"
  :columns="columns"
  :data="data"
  :pagination="pagination1"
  :dragSort="A ? 'row' : undefined "
  @drag-sort="onDragSort"
  @page-change="onPageChange"
>
```
