### ISSUE TITLE
[Table] pagination 从 undefined 切换为有值时，表格分页功能不生效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#2867]
### tdesign-vue 版本

1.6.5

### 重现链接

https://stackblitz.com/edit/qfxu4a-jhe2jr?file=src%2Fdemo.vue

### 重现步骤

如示例，实现table没有数据时不显示分页，有数据才显示分页组件。

文档显示类型是object,  
![image](https://github.com/Tencent/tdesign-vue/assets/13745660/476c33bf-2a49-4fc8-9a4c-0caaadbd14b5)

尝试初始化pagination配置false和‘’功能起效，但是类型报错
尝试初始化pagination配置null或undefined，分页赋值后不起效， 报错Cannot convert undefined or null to object

### 期望结果

希望明确不显示分页时，pagination为空的赋值和类型

### 实际结果

目前配置false是可实现功能，但是类型报错

### 框架版本

vue2

### 浏览器版本

Chrome(117.0.5938.149)

### 系统版本

MacOS

### Node版本

16.17.0

**Comment by chaishi** [comment]
:pagination="undefined" 应该是可以的才对，默认值就是 undefined，不会显示分页
