### ISSUE TITLE
ERROR: 无法获取未定义或 null 引用的属性“ripple”

### ISSUE THREAD

**Issue by brianzhang** [Tencent/tdesign-vue#287]
该判断在某些情况下会出现el.dataset为null，导致异常。

https://github.com/Tencent/tdesign-vue/blob/54bbfa32fa7d7fca93413497ad0bf6b6a983a82b/src/utils/ripple.ts#L33

**Comment by brianzhang** [comment]
![image](https://user-images.githubusercontent.com/766999/150257790-5e8d4a1f-1249-4b9f-8603-9a83eb4aa77a.png)

**Comment by xiaosansiji** [comment]
在 IE 下使用么？https://caniuse.com/?search=dataset
![image](https://user-images.githubusercontent.com/7600149/150259276-dcb0faae-29fc-49c4-9cf7-4fb1ecd5916d.png)

**Comment by brianzhang** [comment]
是的，IE10下

**Comment by xiaosansiji** [comment]
pr: https://github.com/Tencent/tdesign-vue/pull/288
