### ISSUE TITLE
[Tree] 动态赋值data 无法获取 items 导致无法setItem

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2870]
### tdesign-vue 版本

1.7.1

### 重现链接

https://stackblitz.com/edit/s3fhsh-pdsqzn?file=src%2Fdemo.vue

### 重现步骤

<img width="748" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/01a39de3-f8f3-4cbd-beed-2b96212ef1be">

### 期望结果

动态赋值data 能获取到节点信息

### 实际结果

动态赋值data 不能获取到节点信息

**Comment by TabSpace** [comment]
tree 数据池使用了回流策略减少变更带来的状态计算，这样数据更新存在一个时间延迟，比 nextTick 晚，比 setTimeout 早。
可以以下面方式调用：
    setTimeout(() => {
      this.onSetItem();
    });

https://stackblitz.com/edit/s3fhsh-pqrcyf?file=src%2Fdemo.vue

**Comment by uyarn** [comment]
fixed 1.7.2
