### ISSUE TITLE
[Select] 多选时，搜索后，选择一个选项会清空搜索条件

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#2871]
### tdesign-vue 版本

1.7.1

### 重现步骤

官网搜索示例可复现

### 期望结果

搜索时，选择一个搜索结果后，搜索条件保留，在popup关闭的时候，才清空搜索条件

**Comment by uyarn** [comment]
可以配置`reserveKeyword`这个API来保持搜索条件
