### ISSUE TITLE
[Table] 可选表格点击复选框时，row-click与select-change事件同时触发

### ISSUE THREAD

**Issue by zhaobo-98** [Tencent/tdesign-vue#2875]
### tdesign-vue 版本

2.6.12

### 框架版本

2.6.12

### 浏览器版本

Chrome(118.0.5993.96)

### 系统版本

MacOS14.0

### Node版本

16.14.0

**Comment by chaishi** [comment]
如果不设置`selectOnRowClick` ，就不会同时触发了
