### ISSUE TITLE
[Tree] 返回数据数组，当第一项checked:true时，所有子项都会被选中

### ISSUE THREAD

**Issue by Super-Boom** [Tencent/tdesign-vue#2877]
### tdesign-vue 版本

1.7.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-7fmvhq?file=/src/demo.vue

### 重现步骤

如下设置数据
children: [
  {
    value: "1.1.1.1",
    label: "1.1.1.1",
    checked: true,
  },
  {
    value: "1.1.1.2",
    label: "1.1.1.2",
  },
],

**Comment by TabSpace** [comment]
问题: 子节点初始化数据设置 checked 为 true 时。分支下所有节点被选中了。
解决方案: 梳理初始化流程状态，避免父节点过早被影响选中态

**Comment by uyarn** [comment]
fixed in 1.8.3
