### ISSUE TITLE
[Link] SuffixIcon垂直方向不居中

### ISSUE THREAD

**Issue by cfool** [Tencent/tdesign-vue#2880]
### tdesign-vue 版本

1.7.1

### 重现链接

官网示例

### 期望结果

suffix icon与文本一致，垂直居中

### 实际结果

<img width="272" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/5775725/fe85d58f-6b7a-4b20-8a5b-6625e1be517c">

**Comment by uyarn** [comment]
fixed 1.7.2
