### ISSUE TITLE
[Popup] Popup 的实现导致 Popup 和基于它的弹窗（比如 Tooltip ）容易再也不会出现

### ISSUE THREAD

**Issue by guxi11** [Tencent/tdesign-vue#2897]
### tdesign-vue 版本

1.7.1

### 重现链接

https://tdesign.tencent.com/vue/components/tooltip

### 重现步骤

以 Tooltip 为例，Popup 的复现步骤和它一样：

1. 在 tooltip 的 demo 中勾选 destroyOnClose
<img width="270" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/21690043/06545b3b-1e5b-4ad5-bebe-139cb985a2e0">

2. 鼠标 hover 上去，然后移开鼠标，在 popup 淡化离开的过程中再将鼠标移上去，就会触发此 bug 。后续再讲鼠标 hover 上去，popup 也不会出现。
<img width="189" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/21690043/16900d2d-fd2d-414e-a312-ae25118415fb">
<img width="171" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/21690043/a4fda905-8ae2-42dd-9ee6-a4cb86e4915d">
<img width="140" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/21690043/8d39a754-24a8-4a28-8609-f37f3ea1df0e">

完整的演示视频如下：
https://github.com/Tencent/tdesign-vue/assets/21690043/9111e2a4-216c-485c-be58-24c59e61c026
可以看到 destroyOnClose = false 的时候没有这个问题。

### 期望结果

期望结果是，每次鼠标 hover 触发器时， Popup 内容都能出现。

### 实际结果

在 destroyOnClose 的值为 true 的时候，在 popup leaving 的时候鼠标 hover 上去后，popup 将再也不会出现。

### 框架版本

Vue(3.2.0)

### 浏览器版本

Chrome(8.213.231.123)

### 系统版本

MacOS(11.2.3) 

### 补充说明

在业务中，用户反馈 tooltip 消失不见的问题，经过复现之后，发现业务中配置的 tooltip 的位置和内容大小，经常容易导致用户在它们消失的过程中将鼠标移动上去，导致 tooltip 消失。

**Comment by guxi11** [comment]
在我们的业务里，我们之前是用这种方法临时修复的这个问题：
```less
.t-tooltip.t-popup--animation-leave-active { /* 覆写组件样式，修复tooltip丢失问题 */
    pointer-events: none;
}
```

**Comment by chiyu1996** [comment]
之前在table的ellipisi:true时弹出tooltip有遇到类似的问题，老是显示一次就不再显示了

**Comment by uyarn** [comment]
> 之前在table的ellipisi:true时弹出tooltip有遇到类似的问题，老是显示一次就不再显示了

@chiyu1996 应该是一个问题 hover过快会影响 这个版本应该就修复了
