### ISSUE TITLE
[select] 文档描述异常

### ISSUE THREAD

**Issue by sinbadmaster** [Tencent/tdesign-vue#2899]
### tdesign-vue 版本

1.7.2

### 重现链接

https://tdesign.tencent.com/vue/components/select?tab=api#select-props

### 重现步骤

打开select的描述文档，会看到collapsedItems的描述信息显示异常

### 期望结果

正常显示描述信息

### 实际结果

![企业微信截图_25c57933-4d16-45ea-ae34-cbb185a7cec8](https://github.com/Tencent/tdesign-vue/assets/40019023/ea5f8839-7b9b-4ba8-b52f-73592fc89149)

**Comment by uyarn** [comment]
fixed
