### ISSUE TITLE
【table组件】多级表头，单独一列样式缺右侧线

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#290]
**Describe Framework**

tdesign-vue

**Describe Environment**

macos chrome   97.0.4692.71

**Describe the bug**
多级表头，单独一列样式缺右侧线

<img width="823" alt="wecom-temp-4bf6c77a85a527a8739cfc7fd3684ce5" src="https://user-images.githubusercontent.com/13745660/150301739-8dadc738-be08-4f13-9a17-dbbeccb94b0b.png">

<img width="349" alt="wecom-temp-07152358e15d653794f58217db895899" src="https://user-images.githubusercontent.com/13745660/150301775-b327d960-78ab-4fd5-ae43-7d49a069f3ca.png">

**Comment by chaishi** [comment]
辛苦给一个 codesandbox 链接复现问题，方便我们排查问题

https://codesandbox.io/s/8nyjm?file=/src/demo.vue 在这里面复现一下问题

<img width="919" alt="image" src="https://user-images.githubusercontent.com/11605702/150302095-0b502403-a984-4393-82ea-05cdaa3db0e1.png">

**Comment by LoopZhou** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-ukpm7?file=/src/demo.vue

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150520621-30c7a35f-9dff-4a35-a69e-bb3dc3168a00.png)

https://codesandbox.io/s/tdesign-vue-demo-forked-v5f9j?file=/src/demo.vue

这个，是你想要的结果吗？

**Comment by chaishi** [comment]
@LoopZhou 辛苦给一个你想要的表头最终效果，然后我们输出一个代码示例给你

**Comment by LoopZhou** [comment]
希望表格：
![image](https://user-images.githubusercontent.com/13745660/150523495-d2adff77-5748-4fca-a7a7-b03c7a39dbce.png)
目前我的实现发现序号和平台差了边线

**Comment by realyuyanan** [comment]
> 

稍等，我这边在自测了。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/324

**Comment by chaishi** [comment]
已发布至版本 `v0.33.2`
