### ISSUE TITLE
[Select] 文档API出问题

### ISSUE THREAD

**Issue by zyqq** [Tencent/tdesign-vue#2903]
### tdesign-vue 版本

1.6.3

### 重现步骤

<img width="1437" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/15664576/a18368ae-f027-4c75-a587-aaccb84a4f27">

**Comment by zyqq** [comment]
<img width="947" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/15664576/30da30b5-f3bf-48bc-ba51-c6a47ea86ba7">
还有一处

**Comment by uyarn** [comment]
fixed
