### ISSUE TITLE
[CheckBoxGroup] :max导致组件禁用行为不正确

### ISSUE THREAD

**Issue by sumy7** [Tencent/tdesign-vue#2908]
### tdesign-vue 版本

1.7.2

### 重现链接

https://codesandbox.io/s/6mgspc?file=/src/demo.vue

### 重现步骤

文档中 联动多选框 的示例代码，添加属性 :max=2 后，选中数量 >=2 时，会出现选项框禁用
![image](https://github.com/Tencent/tdesign-vue/assets/3841747/b21fb422-6968-43aa-b14f-44bea7729585)
取消其中一个选中后，其余不会恢复
![image](https://github.com/Tencent/tdesign-vue/assets/3841747/1bf4efcb-7663-42d5-aaa9-f2cefd201407)
继续选中后，所有选项被禁用
![image](https://github.com/Tencent/tdesign-vue/assets/3841747/1322a924-b6de-4671-a95f-689cc81a82e6)
点击重置按钮没有恢复
![image](https://github.com/Tencent/tdesign-vue/assets/3841747/26ece5f6-3ece-4756-9b86-6b60cb11bc1e)

### 期望结果

超过限制数量后
选中的checkbox除了本身设置disabled的组件外，应该展示为非disabled；
非选中状态的checkbox为disabled状态；
设置v-model后，需要能够重置组件的disabled状态

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2911 待发布 to be published
