### ISSUE TITLE
[table] 固定列影响视频全屏

### ISSUE THREAD

**Issue by RomenMark** [Tencent/tdesign-vue#2913]
### tdesign-vue 版本

1.7.2

### 重现步骤

1.一个t-table表格，有列左固定
2.表格中video元素，video元素全屏事件闪退。
3.无论video是否处于固定列，只要表格中含有固定列，就无法将video全屏

### 期望结果

1.希望固定属性不影响表格内部视频元素全屏

### 框架版本

vue(2.6.12)

### 浏览器版本

Chrome(112.0.5615.138)

### Node版本

14.17.0

**Comment by chaishi** [comment]
给你的“内部视频元素全屏” 加一个更高的 zIndex 层级
