### ISSUE TITLE
【Swiper】navigation属性无效

### ISSUE THREAD

**Issue by tansentcn** [Tencent/tdesign-vue#292]
**Describe Framework**

tdesign-vue

**Describe Environment**

win10, chrome

**Describe the bug**
prop - navigation 没有被正确接收。

**Additional context**
代码
![image](https://user-images.githubusercontent.com/38307150/150461900-b69e5057-55a4-4d20-9546-fbb626098bf3.png)
结果（并没有被 prop 接收）
![image](https://user-images.githubusercontent.com/38307150/150461950-903e2035-f532-4864-9ed8-beb3fb456c3e.png)

**Comment by chaishi** [comment]
收到，我们处理下

**Comment by tansentcn** [comment]
补充：
引入方式
![image](https://user-images.githubusercontent.com/38307150/150462035-6264441a-e0ac-4fe5-bded-3fbc46b2c69e.png)

**Comment by tansentcn** [comment]
> 

看起来是的

**Comment by start940315** [comment]
这个组件在重新开发中了，欢迎开发完之后体验，到时候功能都会齐全

**Comment by chaishi** [comment]
为避免误导，近期会下掉 Swiper 组件，敬请期待开发完成的 Swiper 组件
