### ISSUE TITLE
[ImageViewer] 无法配置默认最小缩放比例

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#2928]
### tdesign-vue 版本

1.8.0

### 重现链接

https://stackblitz.com/edit/s2wp5c?file=src%2Fdemo.vue

### 重现步骤

<img width="1496" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/0d484747-9cec-458b-a911-52045ddebe7c">
配置1.5 还是 100%

### 期望结果

配置1.5 为150%

### 实际结果

配置1.5 还是 100%

```[tasklist]
### Tasks
```

**Comment by sinbadmaster** [comment]
跟进中

**Comment by sinbadmaster** [comment]
默认显示的为图片原始尺寸的大小，也就是没有缩放。设置最小缩放为1.5，是想要将默认缩放设置为1.5吗？更建议是增加可以设置默认缩放比例的props

**Comment by Jiachang-Cai** [comment]
> 默认显示的为图片原始尺寸的大小，也就是没有缩放。设置最小缩放为1.5，是想要将默认缩放设置为1.5吗？更建议是增加可以设置默认缩放比例的props

只要实现打开就默认1.5的业务场景就行

**Comment by uyarn** [comment]
supported 1.8.4
