### ISSUE TITLE
【input】希望输入框组件增加配置输入文本靠左靠右的配置

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#293]
**Describe the solution you'd like**
希望输入框组件能够增加一个props入口用于配置输入文本是靠左还是靠右显示

**Additional context**
<img width="660" alt="wecom-temp-8082c6057d3d6d444592e06e02cb6015" src="https://user-images.githubusercontent.com/13745660/150462773-bd816371-21ba-473d-b6b7-082806015db3.png">

<img width="548" alt="wecom-temp-b72b087f00bd7a6e66d7042a8f9343b2" src="https://user-images.githubusercontent.com/13745660/150462779-059eae6c-7333-46f8-a3d4-b5bfcae81c21.png">

**Comment by AvenirZheng** [comment]
什么情况下会有从右到左输入的场景的？ @LoopZhou

**Comment by LoopZhou** [comment]
还是从左到右的输入。只是文本右对齐。

场景： 
在表格中添加一行数据， 上几行的内容是右对齐的文本。输入的文本则是左对齐的。产品是希望文本能对齐。

方便看一下是否在组件中实现这种配置吧。

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150636636-d7c3686d-e174-4713-81f2-aa399cf03fe2.png)

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/320 and https://github.com/Tencent/tdesign-common/pull/165

**Comment by xiaosansiji** [comment]
已在 0.33.2 版本中实现
