### ISSUE TITLE
[Upload] 上传过程中，点击取消上传后，无法删除和重新上传

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2955]
### tdesign-vue 版本

1.8.0

### 重现链接

https://stackblitz.com/edit/e6ijmz?file=src%2Fdemo.vue

### 重现步骤

1. 用代理给图片的action接口加上延时，
2. 在图片上传过程中点击“取消上传”后，只剩下“取消上传”按钮，无法删除和重传

<img width="364" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/a707439d-d041-45a2-a4f3-06a6fe366900">

### 期望结果

保留如下按钮或恢复初始状态

<img width="287" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/90e677cb-b395-49fc-8955-0f6f696cbae1">

### 框架版本

2.6.14

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/2966
