### ISSUE TITLE
[高级搜索] 实现前端对后台and or数据联动

### ISSUE THREAD

**Issue by mansai** [Tencent/tdesign-vue#2957]
### 这个功能解决了什么问题

前端输出json格式，例如：
{logic: "And", filters:
   [
    {field: "name", operator: "Contains", value: "test"},
    {field: "age", operator: "Equal", value: "15"},
    {logic: "Or", filters:[{field: "time", operator: "Equal", value: "2023-01-01"}]}
    ]
}

### 你建议的方案是什么

图片参考![7718814a0ce78099cda720ab5ba6feb](https://github.com/Tencent/tdesign-vue/assets/3213405/53a368b6-76c9-4da3-8bb5-af0171b0b8e6)

**Comment by uyarn** [comment]
这个属于pro或者二次封装组件的功能 组件库本身暂时不会做这个的
