### ISSUE TITLE
[Table] BaseTableInstanceFunctions 组件实例方法中没有“refreshTable”了

### ISSUE THREAD

**Issue by yangyigit** [Tencent/tdesign-vue#2970]
### tdesign-vue 版本

1.8.1

### 重现步骤

控制台打印table组件，发现没有 文档中说的 “全部重新渲染表格”的refreshTable方法了
![image](https://github.com/Tencent/tdesign-vue/assets/17756314/4caa5093-214f-4cec-a36e-a09753a76ccf)
![image](https://github.com/Tencent/tdesign-vue/assets/17756314/b26685cc-b74f-4198-b1e7-012e0d9efed6)

### 期望结果

若改名，或者删除了 请在文档中说明

### 实际结果

打印结果和文档不一致

**Comment by chaishi** [comment]
BaseTable 还是 PrimaryTable ？

**Comment by uyarn** [comment]
fixed 1.9.1
