### ISSUE TITLE
[tooltip] 希望支持自定义class类名

### ISSUE THREAD

**Issue by iiimix** [Tencent/tdesign-vue#2973]
### 这个功能解决了什么问题
现有的自定义类名呈现元素不对，给定了tooltip组件，最终呈现在了target元素上
![image](https://github.com/Tencent/tdesign-vue/assets/29354860/719186f2-9068-426f-936a-53e6f516fbcc)

tooltip组件content支持自定义类名
https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-5n6445?file=%2Fsrc%2Fdemo.vue%3A12%2C17
### 你建议的方案是什么

同时支持tooltip组件自定义类名和slot=content自定义类名

**Comment by ghostcode** [comment]
1.tooltip 组件是通过 popup 组件实现的：https://github.com/Tencent/tdesign-vue/blob/develop/src/tooltip/tooltip.tsx#L106
2.通过 https://github.com/Tencent/tdesign-vue/blob/develop/src/tooltip/tooltip.tsx#L18 这里看出，传递给 popup 的属性可以直接用在 tooltip 上。这里是 popup 的 api: https://tdesign.tencent.com/vue/components/popup?tab=api。

**Comment by uyarn** [comment]
是的  如@ghostcode 所说 是可以通过overlayClassname来实现的 class被应用在target上 是因为vue本身透传class实现的效果
