### ISSUE TITLE
[table] 在移动端网页中使用固定表头当表头固定后无法跟随表格横向滚动

### ISSUE THREAD

**Issue by Jin-da** [Tencent/tdesign-vue#2976]
### tdesign-vue 版本

1.8.1

### 重现步骤

https://github.com/Tencent/tdesign-vue/assets/69777107/35f803b2-72d8-410f-bbdf-5cf0d42eb892

### 框架版本

Vue(2.6.14)

### 浏览器版本

多浏览器

### 系统版本

ios17.0.3

### Node版本

v16.19.0

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/3739
https://github.com/Tencent/tdesign-vue-next/pull/3748/files
看上去和这个问题类似，Vue3 已经修了，Vue2 在路上

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2990

**Comment by uyarn** [comment]
fixed 1.8.4
