### ISSUE TITLE
[Form表单] onSubmit事件回调中的validateResult不是bool

### ISSUE THREAD

**Issue by limengning** [Tencent/tdesign-vue#2979]
### tdesign-vue 版本

1.8.1

### 重现步骤

Form控件 @submit 事件回调，返回的validateResult不是bool，而是一个对象
![image](https://github.com/Tencent/tdesign-vue/assets/10029844/5b4b51a9-fe61-40a0-9b6d-adeae4ed6995)

### 期望结果

返回检验是否通过的bool

### 实际结果

返回检验结果的对象

### 框架版本

Vue(2.7.15)

### 浏览器版本

MS Edge(120.0.2210.61)

### 系统版本

Win11

### Node版本

12

**Comment by chaishi** [comment]
是的，不是 bool 类型，符合预期。
大多数业务是需要明确告知用户具体哪里校验没通过，不能返回一个简单的 bool 类型，这将无法满足其他的业务场景。
