### ISSUE TITLE
【table组件】 带合并单元格的表格  合并第一列单元格时，最后一列内容丢失偏移。

### ISSUE THREAD

**Issue by QJBChou** [Tencent/tdesign-vue#298]
https://codesandbox.io/s/tdesign-vue-demo-forked-i1i5u?file=/src/demo.vue

**Comment by chaishi** [comment]
已知问题，已修复，今天发布新版本

**Comment by QJBChou** [comment]
okk

**Comment by chaishi** [comment]
看错了，不是这个问题，我找 小于看下这个问题

**Comment by QJBChou** [comment]
好吧

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150675988-3017160f-0500-4348-9268-6a422621de2d.png)

https://codesandbox.io/s/tdesign-vue-demo-forked-7r2qn?file=/src/demo.vue

已修复，并发布至 `v0.33.2`，上面的 codesandbox 链接中可体验

**Comment by QJBChou** [comment]
好的
