### ISSUE TITLE
[Table] 表头筛选,值为0时，筛选漏斗未高亮

### ISSUE THREAD

**Issue by vonlyinno** [Tencent/tdesign-vue#2987]
### tdesign-vue 版本

1.8.1

### 重现链接

https://stackblitz.com/edit/hcdrqs?file=src%2Fdemo.vue

### 重现步骤

配置表格的列筛选，list里枚举值存在为0的情况，选中该值，表头未高亮

<img width="566" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/9960612/ed2025a1-03f2-4392-bcf8-97b0a26dea08">

### 框架版本

2.6.14

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2990

**Comment by uyarn** [comment]
fixed 1.8.4
