### ISSUE TITLE
[TreeSelect] 树选择组件的选项disabled，禁用父级时，子级全部都被禁用了

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#2993]
### 这个功能解决了什么问题

有禁用父级，但是还能选择子级的场景。如ant组件库：

<img width="1339" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8012098/4c94cf74-2570-494d-8cf6-c2ad9333eb91">

### 你建议的方案是什么

选项的disabled，只禁用当前选项节点，与子级无关。

**Comment by uyarn** [comment]
可以通过设置`checkStrictly` 来满足你的需求 
```
<tree-select
:treeProps="{ checkStrictly:true }"
/>
```
refer to https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-dq9xpj?file=%2Fsrc%2Fdemo.vue%3A19%2C1
