### ISSUE TITLE
[t-select] 添加属性 :min-collapsed-num="2" 后报错 Error in render: "TypeError: Cannot read properties of undefined (reading 'find')"

### ISSUE THREAD

**Issue by MagicReader** [Tencent/tdesign-vue#2994]
### tdesign-vue 版本

"tdesign-vue": "^1.8.0-naruto"

### 重现步骤

选择三个选项
```

    <t-select
      v-if="options.length === 0"
      v-model="valueView"
      style="width: 100%;margin: 0 0 0 6px;"
      multiple
      filterable
      placeholder="未选择"
      clearable
      :min-collapsed-num="1"
      @change="handleValueViewChange"
    >
      <t-option
        v-for="item, index in valueArray"
        :key="index"
        :label="item[`${fieldDataText}`]"
        :value="String(item[`${fieldDataValue}`])"
      />
    </t-select>
```

### 期望结果

可以正常展示折叠情况

### 实际结果

![image](https://github.com/Tencent/tdesign-vue/assets/33999813/f757e5c8-ad1b-463b-bc35-937ee678b628)
选中第三个后组件报错

### 框架版本

Vue2.7

### 系统版本

Window10

### Node版本

14.16.0

### 补充说明

**异常信息：**
![image](https://github.com/Tencent/tdesign-vue/assets/33999813/30f0d3e1-8ba3-4eac-a40e-b9aad48d74e9)

**Comment by uyarn** [comment]
fixed 1.8.4-naruto
