### ISSUE TITLE
官网

### ISSUE THREAD

**Issue by zbb99** [Tencent/tdesign-vue#302]
![image](https://user-images.githubusercontent.com/41665507/150503616-8465660a-5d52-4dfe-a7bd-528673acb431.png)
官网这块滑动时有较强的顿挫感，感觉不够流畅

**Comment by HQ-Lin** [comment]
页面滚动有分瞬移和平滑模式，这边基于页面刷新后锚点定位的即时性选择了瞬移的方式，如果是因为正上方的彩色进度条会让人觉得有顿挫感可以去掉
