### ISSUE TITLE
[文本框下拉表格]用于下拉框多列显示表格

### ISSUE THREAD

**Issue by mansai** [Tencent/tdesign-vue#3020]
### 这个功能解决了什么问题

在官网上没有找到类似的下拉表格功能

### 你建议的方案是什么

参考地址：
https://www.jeasyui.cn/document/form/combogrid.html
https://blog.csdn.net/zrk1000/article/details/46560791

**Comment by uyarn** [comment]
这个不会做成组件 可以自己通过 SelectInput 配合 Table 来实现下 https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-rmp7t3?file=%2Fsrc%2Fdemo.vue

**Comment by mansai** [comment]
> 这个不会做成组件 可以自己通过 SelectInput 配合 Table 来实现下 https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-rmp7t3?file=%2Fsrc%2Fdemo.vue

这个链接打不开
