### ISSUE TITLE
[Loading] LoadingPlugin多次hide或者LoadingPlugin(false)报错

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#3023]
### tdesign-vue 版本

1.8.4

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-gmrfvg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr4ampah00063b6ido3y249h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr4ampah00023b6icz8l2vsw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr4ampah00033b6ije47lgxw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr4ampah00053b6inroiqv88%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr4ampah00023b6icz8l2vsw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr4ampag00013b6iia7bwd8j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr4ampah00023b6icz8l2vsw%2522%252C%2522activeTabId%2522%253A%2522clr4ampag00013b6iia7bwd8j%2522%257D%252C%2522clr4ampah00053b6inroiqv88%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr4ampah00043b6idq380d0l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr4ampah00053b6inroiqv88%2522%252C%2522activeTabId%2522%253A%2522clr4ampah00043b6idq380d0l%2522%257D%252C%2522clr4ampah00033b6ije47lgxw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr4ampah00033b6ije47lgxw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

1.  LoadingPlugin调用hide， 第二次点击handleClick1后，获取不到hide方法
![image](https://github.com/Tencent/tdesign-vue/assets/13745660/768164c7-00a7-42d9-b207-8b6c9fd1a021)
![image](https://github.com/Tencent/tdesign-vue/assets/13745660/17eb9606-84ef-4093-b729-a2fe7bde8938)

2. LoadingPlugin(false), 点击handleClick2，多次执行LoadingPlugin(false)，报错
![image](https://github.com/Tencent/tdesign-vue/assets/13745660/d6781445-717a-4165-a94c-be4905df9cb1)
![image](https://github.com/Tencent/tdesign-vue/assets/13745660/01e9bede-ba11-49ca-a8d6-82048ae330b7)

### 期望结果

判断fullScreenLoadingInstance是否存在，可以多次执行hide或者LoadingPlugin(false) 不报错

### 框架版本

vue2

### 浏览器版本

Chrome

### 系统版本

MacOS

### Node版本

16.17.0

**Comment by uyarn** [comment]
fixed 1.9.0
