### ISSUE TITLE
[t-tree-select]  使用 TDesign 的 TreeSelect进行多选和异步加载（点击节点才加载数据）时，无法选择节点，只有当其子节点展示完才能选择节点

### ISSUE THREAD

**Issue by zzyyhh22lx** [Tencent/tdesign-vue#3028]
### tdesign-vue 版本

最新版本也存在

### 重现链接

[链接](https://stackblitz.com/edit/jdvepk-jyrc28?file=src%2Fdemo.vue)

### 重现步骤

异步加载需要设置children为true，但是如果设置了children为true的话，就无法选中未全部展示的节点

这里一直异步加载children，所以无法选择这个节点，只有当节点全部展示完才可以选中

![image](https://github.com/Tencent/tdesign-vue/assets/102452253/d3e52d0e-4dcf-4262-a8db-04097f8c8805)

![image](https://github.com/Tencent/tdesign-vue/assets/102452253/cefc394c-0bb7-4e8d-b18e-6dc485386c3d)

### 期望结果

可以直接选中

### 实际结果

无法选中未全部展示的节点

### 补充说明

当遇到异步加载数据时，无法直接选中前面的值，而且拿到的值是一个vue的watch的监听对象__obj__，出现bug

**Comment by maoyiluo** [comment]
需要使用`checkStrictly`属性，通过treeProps传递

```
<template>
  <t-tree-select
    :data="options"
    multiple
    v-model="value"
    placeholder="请选择"
    :treeProps="{ load: loadFunc, checkStrictly: true }"
  />
</template>
```

https://stackblitz.com/edit/jdvepk-5ult6u?file=src%2Fdemo.vue
