### ISSUE TITLE
[tree-select] 多选的时候可否加一个父子节点取消关联的参数

### ISSUE THREAD

**Issue by wangshaojie** [Tencent/tdesign-vue#3033]
### 这个功能解决了什么问题

[tree-select] 多选的时候可否加一个父子节点取消关联的参数

### 你建议的方案是什么

:check-strictly="true"

**Comment by uyarn** [comment]
透传tree-props="{ checkStrictly: true }" 就可以啦
<img width="813" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/ed963f4b-7db4-4a68-8898-8b8d8e5ff3fb">

**Comment by wangshaojie** [comment]
谢谢
