### ISSUE TITLE
[button] 支持设置按钮禁用时间，防止重复提交，单位毫秒

### ISSUE THREAD

**Issue by you-hei-mi** [Tencent/tdesign-vue#3037]
### 这个功能解决了什么问题

开发人员经常在做表单提交等功能场景时，不加防抖、节流或加载动画，导致容易出现多次重复提交。

### 你建议的方案是什么

添加一个reset-time属性， 设置按钮禁用时间，防止重复提交，单位毫秒

**Comment by uyarn** [comment]
这个不考虑在组件内增加 请在具体业务逻辑中添加
