### ISSUE TITLE
Select多选选择器的:minCollapsedNum="2"属性 可以给他加一个tooltip的功能吗 我想说的是

### ISSUE THREAD

**Issue by iimpzz** [Tencent/tdesign-vue#3038]
### 这个功能解决了什么问题

我目前使用的一个组件  就是远程搜索+多选select 

### 你建议的方案是什么

我目前使用的一个组件  就是远程搜索+多选select

**Comment by uyarn** [comment]
<img width="887" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/939dae40-5f54-4d6f-8416-8abfd21171f1">
https://codesandbox.io/s/lwywdd?file=/src/demo.vue
可以参考这个例子

**Comment by iimpzz** [comment]
我这里更换了你所说的方式 我这里是用了远程搜索+折叠选项&nbsp; &nbsp;第一次输入搜索关键词和进行搜索时是没问题的&nbsp; &nbsp;但是第二次换一个搜索关键词搜索时 会出现报错&nbsp; 这里的代码我需要改成value替换为collapsed...不






龙仔
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] Select多选选择器的:minCollapsedNum="2"属性 可以给他加一个tooltip的功能吗 我想说的是 (Issue #3038)





 image.png (view on web) https://codesandbox.io/s/lwywdd?file=/src/demo.vue 可以参考这个例子

**Comment by iimpzz** [comment]
你好 请忽略我刚刚的问题 我已经解决了 谢谢你的解答&nbsp; &nbsp;

龙仔
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Tencent/tdesign-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue] Select多选选择器的:minCollapsedNum="2"属性 可以给他加一个tooltip的功能吗 我想说的是 (Issue #3038)





 image.png (view on web) https://codesandbox.io/s/lwywdd?file=/src/demo.vue 可以参考这个例子
