### ISSUE TITLE
[select] 自定义折叠选中项选择器

### ISSUE THREAD

**Issue by iimpzz** [Tencent/tdesign-vue#3040]
### tdesign-vue 版本

"tdesign-vue": "^1.6.3-naruto",

### 重现步骤

我想删除被折叠的选项发现方法里的Onclose打印成undefined

### 期望结果

可以正常关闭折叠项

### 实际结果

实际上报错无反应

### 补充说明

collapsedItems(h, {
      value, count, collapsedSelectedItems, onClose,
    }) {
      console.log('collapsedItems: ', value, collapsedSelectedItems, count, onClose);
      if (!count) return;
      // hover展示全部已选项
      return (
        <t-popup>
          <div slot="content">
            {collapsedSelectedItems.map((item, index) => (
              <p style="padding: 2px;">
                <t-tag
                  closable={true}
                  onClick={() => {
                    onClose(index + 1);
                  }}
                >
                  {item.label}
                </t-tag>
              </p>
            ))}
          </div>
          <span v-show={count > 0} style="color: #ED7B2F; margin-left: 8px">
            +{count}
          </span>
        </t-popup>
      );
    },

**Comment by uyarn** [comment]
版本问题 你升级上来 1.7.2以上版本的naruto
<img width="810" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/2ea59c9c-f0ab-4a3f-96b0-42ac7a641aad">
