### ISSUE TITLE
[Iconfont] 地址404

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3043]
### tdesign-vue 版本

1.8.4

### 重现步骤

<img width="1564" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8012098/0d888251-1441-4abf-a3a1-a8f77304d205">

**Comment by Loinver** [comment]
<img width="523" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8012098/28a0ea5e-5688-4c0f-bb61-08688524f526">
tdesign-starter这几张图现在还是404

**Comment by uyarn** [comment]
> <img alt="image" width="523" src="https://private-user-images.githubusercontent.com/8012098/297560453-28a0ea5e-5688-4c0f-bb61-08688524f526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Mzk4MDEsIm5iZiI6MTcwNTUzOTUwMSwicGF0aCI6Ii84MDEyMDk4LzI5NzU2MDQ1My0yOGEwZWE1ZS01Njg4LTRjMGYtYmI2MS0wODY4ODUyNGY1MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDA1ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAwMGIxNmQ4MmQyYjI3ZjM5M2YxNWY0YzU3NDE2MzgwMWZhNGFmYTI3NjA2NTc5NjhiODdhNjk2MGY5YjQ5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YZODf9R918QQaHUZ6XAEC5BQ30CG0Y82RzbVOoYiBYQ"> tdesign-starter这几张图现在还是404

先恢复下 这几个资源后面不再提供CDN服务了 我们会把他们放到项目里 项目也尽快调整下吧

**Comment by Loinver** [comment]
好的
