### ISSUE TITLE
[Textarea] 通过value绑定值，加上autosize配置后，无法输入中文

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#3049]
### tdesign-vue 版本

1.8.4

### 重现链接

https://stackblitz.com/edit/ggljbd-pujrre?file=src%2Fdemo.vue

### 重现步骤

如示例，通过value绑定值，加上autosize配置后，无法输入中文，之后就无法编辑了

### 期望结果

可以正常输入中文

### 框架版本

vue2

### 浏览器版本

Chrome

### 系统版本

MacOS

### Node版本

16.17.0

**Comment by uyarn** [comment]
fixed 1.9.0
