### ISSUE TITLE
[Descriptions 描述] vue2使用后报错The setup binding property "title" is already declared as a prop.

### ISSUE THREAD

**Issue by slamdunk77** [Tencent/tdesign-vue#3063]
### tdesign-vue 版本

1.9.0

### 重现步骤

<t-descriptions title="Shipping address">
    <t-descriptions-item label="法定代表人">{{companyInfo.legalPersonName}}</t-descriptions-item>
    <t-descriptions-item label="经营状态">-</t-descriptions-item>
    <t-descriptions-item label="英文名">{{companyInfo.nameEn ? companyInfo.nameEn : "-"}}</t-descriptions-item>
 </t-descriptions>
 vue2使用descriptions组件，报错The setup binding property "title" is already declared as a prop.

### 期望结果

解决该报错

### 框架版本

Vue2.6.14

**Comment by slamdunk77** [comment]
代码是这样写的：
<img width="1000" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/62142444/648c28d1-10b7-475a-8665-542d910300a1">
报错如图：
<img width="715" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/62142444/efdd15b4-cf7f-48fb-8121-52da3a541ba7">

**Comment by uyarn** [comment]
fixed 1.9.1
