### ISSUE TITLE
[ColorPicker] 渐变效果下透明度只能设置一半

### ISSUE THREAD

**Issue by 673019334** [Tencent/tdesign-vue#3085]
### tdesign-vue 版本

1.9.0-naruto

### 重现链接

https://tdesign.tencent.com/vue/components/color-picker?tab=demo

### 重现步骤

1.使用渐变模式，开启enableAlpha=true
2.当设置渐变色的透明度时，仅有一半透明，另一半渐变不透明
<img width="755" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/54474073/f9947033-bf5b-4c3c-8db9-d556184d2d0b">

### 期望结果

期望设置透明度时，渐变色可以全部透明透明
<img width="758" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/54474073/ea3b7201-5e69-4480-a7cd-0194298fa5a8">

### 实际结果

如图所示
<img width="758" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/54474073/6523d6da-5a4b-4bfe-91a6-968e5e7dbf0c">

### 框架版本

Vue(2.7)

### 浏览器版本

chrome(121.0.6167.139)

### 系统版本

maxos(13.2)

### Node版本

14.3.0

**Comment by maoyiluo** [comment]
点击上方的横条上的圆圈，可以调整起点/终点的颜色和透明度
![image](https://github.com/Tencent/tdesign-vue/assets/43943796/634aff1c-e4a7-4a67-b113-35ef4684ac0a)
选择要调整的阶段然后再用下方的透明度调节即可
