### ISSUE TITLE
[Cascader ] options 数据中存在无children 组件还显示之前的列表 应该不显示

### ISSUE THREAD

**Issue by zhangningself** [Tencent/tdesign-vue#3091]
### tdesign-vue 版本

1.9.0

### 重现链接

https://codesandbox.io/p/devbox/tdesign-vue-demo-forked-hjh6hj?file=%2Fsrc%2Fdemo.vue%3A8%2C7-8%2C14

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-06-09 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by maoyiluo** [comment]
sandbox链接失效了

**Comment by zhangningself** [comment]
https://codesandbox.io/p/devbox/tdesign-vue-demo-forked-hjh6hj?file=%2Fsrc%2Fdemo.vue%3A12%2C15


https://github.com/Tencent/tdesign-vue/assets/26316530/15786c6d-1671-4ff5-95cb-9d44ee3fc681

**Comment by 1379255913** [comment]
认领

**Comment by uyarn** [comment]
fixed 1.9.5
