### ISSUE TITLE
[TreeSelect] 给collapsedItems属性加入onClose参数

### ISSUE THREAD

**Issue by mdxiaohu** [Tencent/tdesign-vue#3092]
### tdesign-vue 版本

1.9.0

### 重现步骤

请参考Select组件的collapsedItems，开放onClose方法

### 框架版本

Vue(2.6.14)

### 浏览器版本

谷歌(98.0.4758.9)

### 系统版本

Windows10

### Node版本

15.0.1

**Comment by uyarn** [comment]
会在Taginput上增加

**Comment by uyarn** [comment]
已在1.9.2支持
