### ISSUE TITLE
[Descriptions] 一些异常

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#3099]
### tdesign-vue 版本

1.9.0

### 重现链接

https://stackblitz.com/edit/juxasv?file=src%2Fdemo.vue

### 重现步骤

1. t-descriptions-item 会提示没有 t-description-item 不会
<img width="458" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/eaff768a-aa90-4fd9-86d2-18a108ce15eb">

2. .t-descriptions__body 不是根据.t-descriptions 的宽度进行平铺的  等于无法自适应宽度
<img width="1112" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/b250c8f6-ef5d-430f-b690-d81c1e805134">

### 期望结果

不要有这些问题

### 实际结果

有这些问题

**Comment by uyarn** [comment]
accepted
