### ISSUE TITLE
table(bug): fiexd col no shadow with ellipsis

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue#31]
**Describe Framework**
- [x] tdesign-vue
- [x] tdesign-vue-next
- [x] tdesign-react

**Describe Environment**

![image](https://user-images.githubusercontent.com/35833812/146859868-271542a8-5eed-4917-8524-1d49843e4b15.png)

[codesandbox
](https://codesandbox.io/s/tdesign-vue-demo-forked-itn4s?file=/src/demo.vue。)

**Comment by pengYYYYY** [comment]
宽屏下样式表现异常

![image](https://user-images.githubusercontent.com/35833812/146861136-3ca8a2b2-ef3a-4978-8577-b8962921a445.png)


https://codesandbox.io/s/q0y6w?file=/src/demo.vue

**Comment by chaishi** [comment]
处理 PR：https://github.com/Tencent/tdesign-vue/pull/82

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
