### ISSUE TITLE
[Tabs] 支持active样式的根据文字为基础

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#3110]
### 这个功能解决了什么问题

<img width="1024" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/82fc8527-28cb-41d5-8b40-5150aa2cd80e">
<img width="912" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/bfce13e0-207d-4762-b24e-a8b99844d87a">

### 你建议的方案是什么

支持一下

**Comment by uyarn** [comment]
refer to https://codesandbox.io/s/2qdpkw?file=/src/demo.vue
