### ISSUE TITLE
[Dialog] 插件函数式调用例子建议给销毁或者使用提醒，否则很容易造成使用者内存泄漏

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#3112]
### tdesign-vue 版本

1.9.1

### 重现步骤

重复点击函数式调用的插件后会产生非常多 Dom。这里建议文档里给下文案提示，以免使用者直接复制代码使用没考虑到DOM元素未销毁的情况。
![image](https://github.com/Tencent/tdesign-vue/assets/8199240/6177c94f-e4d0-4860-baf4-17e0954e11cf)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-03-30 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
好的
