### ISSUE TITLE
[Transfer] 穿梭框与树结合使用，并且开启穿梭框的搜索功能之后，只能搜索树的一级数据，二级或是更低层级的数据无法通过关键字搜索

### ISSUE THREAD

**Issue by Blackraven1994** [Tencent/tdesign-vue#3113]
### tdesign-vue 版本

1.7.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-v34dyr?file=/src/demo.vue

### 重现步骤

Transfer与Tree结合使用，并且开启Transfer的搜索功能之后，只能搜索Tree的一级数据，二级或是更低层级的数据无法通过关键字搜索

### 期望结果

Transfer与Tree结合使用，并且开启Transfer的搜索功能之后，支持搜索所有Tree层级的数据

### 框架版本

Vue(2.6.14)

### Node版本

14.21.3

**Comment by Loinver** [comment]
有相同需求

**Comment by uyarn** [comment]
已在1.9.2版本支持
