### ISSUE TITLE
[Tree] 激活状态样式可以配置到tree-item不

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue#3114]
### 这个功能解决了什么问题

业务场景就是通讯录
很多tree的通讯录
整个行为激活状态
<img width="260" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/cd3ddee7-8878-48cf-9206-56faee285f7d">
目前的tree的激活状态样式是到node
<img width="976" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8606851/a1f76aec-c6cd-4d23-8272-c0bfeaeccd77">

### 你建议的方案是什么

能够满足目前通讯录业务场景的样式

**Comment by uyarn** [comment]
这个暂时不考虑支持
