### ISSUE TITLE
[table] 配置了header-affixed-top，当表格有横向滚动条时，windows的chrome表头会有滚动条

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#3116]
### tdesign-vue 版本

1.9.1

### 重现链接

https://stackblitz.com/edit/awkykr?file=src%2Fdemo.vue

### 重现步骤

官网示例可复现，当配置了表头吸顶，windows的chrome表头会有滚动条
<img width="987" alt="windows-table-headerAffixedTop吸顶问题" src="https://github.com/Tencent/tdesign-vue/assets/13745660/82124ef5-2849-4ca6-9ec9-a63602a791bc">

### 期望结果

隐藏吸顶表头的滚动条

### 框架版本

vue2

### 浏览器版本

Chrome(122.0.6261.129)

### 系统版本

windows

### Node版本

16.17.0

**Comment by KoolPt** [comment]
在项目全局style.less中添加以下代码即可。
`body {
     /* table固定头部样式重写*/
     .t-table {
        .t-table__affixed-header-elm-wrap, .t-table__affixed-header-elm {
           z-index: 0;
       }
  }
}`
添加前效果：
![1212](https://github.com/Tencent/tdesign-vue/assets/112840050/ed0b5d94-6cfe-4f8b-bce0-41e586022336)
添加后效果：
![2323](https://github.com/Tencent/tdesign-vue/assets/112840050/d8b59c86-edeb-41b6-8c29-14c375dbbafd)

**Comment by uyarn** [comment]
fixed 1.9.2

**Comment by jQuery0009** [comment]
@uyarn 
![企业微信截图_17128239253454](https://github.com/Tencent/tdesign-vue/assets/38718845/f44dad9b-c128-446f-b8be-1840f147647b)
已经升级1.9.2版本，表格还是有横向滚动条。未解决！！
![image](https://github.com/Tencent/tdesign-vue/assets/38718845/03647a06-2772-4256-8900-0d05f0585be9)

**Comment by uyarn** [comment]
> @uyarn ![企业微信截图_17128239253454](https://private-user-images.githubusercontent.com/38718845/321555869-f44dad9b-c128-446f-b8be-1840f147647b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcyNjUsIm5iZiI6MTcxMjg0Njk2NSwicGF0aCI6Ii8zODcxODg0NS8zMjE1NTU4NjktZjQ0ZGFkOWItYzEyOC00NDZmLWI4YmUtMTg0MGYxNDc2NDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE0NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTNhZmVjNGMyNTQyMjdlODRmODRhYTUxOTI2MGQyMzYxMTg3MmNmMjMzMWZhNjUxMmI5ODViNjM0YmUxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwrSzXuax3TIY6DPutLTvLh2Li4cXMGlQn4QU9fP6Zk) 已经升级1.9.2版本，表格还是有横向滚动条。未解决！！ ![image](https://private-user-images.githubusercontent.com/38718845/321556423-03647a06-2772-4256-8900-0d05f0585be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcyNjUsIm5iZiI6MTcxMjg0Njk2NSwicGF0aCI6Ii8zODcxODg0NS8zMjE1NTY0MjMtMDM2NDdhMDYtMjc3Mi00MjU2LTg5MDAtMGQwNWYwNTg1YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE0NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNTk3MmExNTJiY2Q1NGM1MzAyMTNiMDhiNWI2YzEyMmM2ZWQwOGQ0YjEzNTllYTg5ZDJlNGVlYjJkMjE1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sf5ah6h-7k3wxdJFnQvQR_MCtA-Bsg9Kfokh8rkZMTw)

你这个是vue-next  这是vue的仓库 vue-next 等下周1.9.4发布哈
