### ISSUE TITLE
[Transfer 穿梭框] @search的时候 回车的时候type返回 任然是“input”

### ISSUE THREAD

**Issue by qlynick** [Tencent/tdesign-vue#3117]
### tdesign-vue 版本

1.9.1

### 重现链接

https://codesandbox.io/p/devbox/tdesign-vue-demo-forked-fplh7l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu0oc2zc00093b6h27116urn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu0oc2zb00023b6hkcd6dz9f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu0oc2zc00063b6h6hut8syx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu0oc2zc00083b6h6sjxqzki%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu0oc2zb00023b6hkcd6dz9f%2522%253A%257B%2522id%2522%253A%2522clu0oc2zb00023b6hkcd6dz9f%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu0oc2zc00083b6h6sjxqzki%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0oc2zc00073b6hjxufmase%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clu0oc2zc00083b6h6sjxqzki%2522%252C%2522activeTabId%2522%253A%2522clu0oc2zc00073b6hjxufmase%2522%257D%252C%2522clu0oc2zc00063b6h6hut8syx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0oc2zc00033b6htaqq831e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu0oc2zc00043b6hdt5ivodr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu0m4wre000kdlfwc2405a85%2522%257D%252C%257B%2522id%2522%253A%2522clu0oc2zc00053b6hf53gxb81%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu0m6laf000odlfw0n4mg43o%2522%257D%255D%252C%2522id%2522%253A%2522clu0oc2zc00063b6h6hut8syx%2522%252C%2522activeTabId%2522%253A%2522clu0oc2zc00033b6htaqq831e%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

搜索框里填写的时候 trigger为 input
回车的时候也是input

### 期望结果

文档里描述的是trigger: 'input' | 'enter';
回车的时候应该是enter才对吧？

### Node版本

18.12.0

### 补充说明

![image](https://github.com/Tencent/tdesign-vue/assets/1582245/75bb7135-e3e3-4043-9a91-4cdd8f1ef62d)

**Comment by uyarn** [comment]
fixed 1.9.2
