### ISSUE TITLE
[DatePicker] windows年份下拉选项文字被遮挡，不能全部展示

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#3121]
### tdesign-vue 版本

1.9.1

### 重现链接

官网示例可复现

### 重现步骤

<img width="643" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/13745660/d65e161c-ef62-4284-bbfc-f18410d053ae">

windows下升级chrome浏览器，datePicker 年份下拉选项文字被遮挡，不能全部展示

复现浏览器：
谷歌版本浏览器：123.0.6312.86
edge版本：122.0.2365.92

### 期望结果

年份能正常显示

### 实际结果

下拉框width太短

### 框架版本

vue2

**Comment by uyarn** [comment]
fixed 1.9.2
