### ISSUE TITLE
[Transfer] 穿梭框内tree属性传入function无效

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3123]
### tdesign-vue 版本

1.9.1

### 重现链接

https://codesandbox.io/p/devbox/tdesign-vue-demo-forked-9cjgtn?file=%2Fsrc%2Fdemo.vue%3A72%2C5

### 重现步骤

传入方法返回tree节点无效

### 期望结果

能像slot插入tree一样

### 实际结果

不生效

### 框架版本

2.6.14

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-05-23 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
fixed 1.9.5
