### ISSUE TITLE
不能用在vue3中吗，npm install tdesign-vue@naruto 总是报错

### ISSUE THREAD

**Issue by wangjuanlsx** [Tencent/tdesign-vue#3136]
### tdesign-vue 版本

不能用在vue3中吗，npm install tdesign-vue@naruto 总是报错

### 重现步骤

不能用在vue3中吗，npm install tdesign-vue@naruto 总是报错

### 期望结果

不能用在vue3中吗，npm install tdesign-vue@naruto 能下载

### 实际结果

不能用在vue3中吗，npm install tdesign-vue@naruto 总是报错

### Node版本

16

### 补充说明

不能用在vue3中吗，npm install tdesign-vue@naruto 总是报错
```[tasklist]
### Tasks
```
![image](https://github.com/Tencent/tdesign-vue/assets/18136723/1e620fc8-9ee3-4e49-989c-70b55fa85387)

```[tasklist]
### Tasks
```

**Comment by furylee** [comment]
tdesign-vue-next

**Comment by uyarn** [comment]
vue3 请看这个文档 https://tdesign.tencent.com/vue-next/overview
