### ISSUE TITLE
t-select value 绑定Boolean值 报错

### ISSUE THREAD

**Issue by Corgis** [Tencent/tdesign-vue#3146]
### tdesign-vue 版本

1.9.2

### 重现链接

https://stackblitz.com/edit/29tbze?file=src%2Fdemo.vue

### 重现步骤

打开控制台，点击下拉选择，控制台报错如下
![image](https://github.com/Tencent/tdesign-vue/assets/13865529/0eaaadc7-3b88-4329-b08f-cd77a56d4943)

### 期望结果

根据文档描述 value可以绑定 Boolean值，希望不报错

### 实际结果

控制台报错

### 框架版本

2.6.14

### 浏览器版本

Chrome 123.0.6312.123

### 系统版本

Windows 10 家庭版

### Node版本

v18.20.1

**Comment by XBIsland** [comment]
https://github.com/Tencent/tdesign-vue/blob/22715f4cbf47b2bcda9587e4c62f6324904f4dbb/src/input/type.ts#L208

不支持 `Boolean`。
没找到文档说支持的地方，能否提供下截图。

**Comment by Corgis** [comment]
> https://github.com/Tencent/tdesign-vue/blob/22715f4cbf47b2bcda9587e4c62f6324904f4dbb/src/select/props.ts#L42-L44
> 
> 不支持 `Boolean`。 没找到文档说支持的地方，能否提供下截图。

![image](https://github.com/Tencent/tdesign-vue/assets/13865529/62c22ead-c7a8-46d7-9215-fbdf3205d0aa)

**Comment by Corgis** [comment]
![image](https://github.com/Tencent/tdesign-vue/assets/13865529/3a859887-786a-48b5-8777-83b0c961a852)

**Comment by uyarn** [comment]
@Corgis 下个版本会修复告警 目前应该可以使用但是控制台有报错

**Comment by uyarn** [comment]
fixed 1.9.3
