### ISSUE TITLE
tree-select 自定义key值后 select框默认值回显有问题

### ISSUE THREAD

**Issue by Corgis** [Tencent/tdesign-vue#3147]
### tdesign-vue 版本

1.9.2

### 重现链接

https://stackblitz.com/edit/uwf2qf?file=src%2Fdemo.vue

### 重现步骤

value1的值为12 正常进来回显应该是广州市 而现在显示的是12
![image](https://github.com/Tencent/tdesign-vue/assets/13865529/fbc5277d-1f18-4c5c-8a91-50e3db756efb)

### 期望结果

期望显示正常

### 实际结果

![image](https://github.com/Tencent/tdesign-vue/assets/13865529/805ef290-e71a-42a9-b4bf-269b92652418)

### 框架版本

2.6.14

### 浏览器版本

123.0.6312.123

### 系统版本

Windows 10 家庭版

### Node版本

v18.20.1

**Comment by Corgis** [comment]
发现问题了 children 不能设置别名 否则 初始化的显示会有问题

**Comment by uyarn** [comment]
不支持children rename哈
