### ISSUE TITLE
组件： Dialog

### ISSUE THREAD

**Issue by Evashasha** [Tencent/tdesign-vue#3152]
问题描述：
使用dialog的示例调用方法setConfirmLoading无效

复现地址：
https://stackblitz.com/edit/react-47anst-dymfos?file=src%2Fdemo.jsx

**Comment by uyarn** [comment]
仓库错了 react未实现 已经在react仓库实现了 https://github.com/Tencent/tdesign-react/pull/2883 此issue关闭
