### ISSUE TITLE
[Select] 未双向绑定value时显示false

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#3165]
### tdesign-vue 版本

lastest

### 重现链接

https://tdesign.tencent.com/vue/components/select

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue/assets/29624966/8267b992-59c8-4d5d-a29b-f9abae0d1493)
官方示例第一个

**Comment by uyarn** [comment]
fixed in 1.9.4
