### ISSUE TITLE
[ImageViewer] 按需加载组件报错

### ISSUE THREAD

**Issue by hy212** [Tencent/tdesign-vue#3166]
### tdesign-vue 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/utbvev?file=src%2Fmain.js,package.json,src%2Fdemo.vue,.eslintrc.js

### 重现步骤

npm i
npm run serve
页面报错，点击预览无反应。
![image](https://github.com/Tencent/tdesign-vue/assets/44251941/ebad69fb-a640-464b-9170-358b70323167)

ImageViewer组件trigger slot抛出的open()方法不存在。

### 期望结果

期望能够按需加载使用

### 框架版本

Vue(2.6.14)

**Comment by uyarn** [comment]
由于使用了`@vue/composition-api`开发组件，按需引入的场景需要手动引入一次`@vue/composition-api`并注册使用
https://tdesign.tencent.com/vue/getting-started#faq
<img width="912" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/26377630/56852ad7-03f8-4290-8f70-fe3af386a30d">
