### ISSUE TITLE
[Select] multiple 多选模式下拉列表中 Checked 项样式问题

### ISSUE THREAD

**Issue by fython** [Tencent/tdesign-vue#3168]
### tdesign-vue 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/gwtw5e?file=src%2Fdemo.vue

### 重现步骤

1. Select 组件 options 参数包含 `disabled: true` 的选项
2. 被禁用的选项 value 存在于 Select 组件的 `value/v-model` 中
3. 打开下拉列表

### 期望结果

被禁用的选项背景保持透明/背景色，而非高亮色。

**Nice to have:** 其他已勾选但未禁用的项的背景也保持透明/背景色，仅在 hover/activated 状态下展示背景色

### 实际结果

被禁用的选项背景是高亮色，仅勾选图标灰色显示禁用，体验不好
<img width="322" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/d1a1f8ac-765b-401a-b7b1-8a83f6541234">

## 问题分析

<img width="390" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/0d9f00fe-4673-4930-bb29-3194d6d2eb53">

从 DevTools 上看，`.t-select-option.t-is-disabled` 样式有单独定义，但是优先级低于 `.t-select-option.t-is-selected`，导致字体颜色/背景色都被选中状态样式覆盖了

## 对比案例

业界其他组件/UI 的下拉列表选项仅在 hover/activated 状态下显示高亮背景色，而非全部 Checked 项都显示

### Element UI

<img width="352" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/4d2f2593-b1dc-4a06-b3c5-2c3d3e176905">

### View Design (iView UI)

<img width="295" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/7db3430c-1373-4b38-8473-c6dc45ff83d5">

**Comment by uyarn** [comment]
fixed 1.9.4, thanks for @fython
