### ISSUE TITLE
[DateRangePicker] suffix 图标可能未居中对齐

### ISSUE THREAD

**Issue by fython** [Tencent/tdesign-vue#3170]
### tdesign-vue 版本

1.9.3

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker#%E6%97%A5%E6%9C%9F%E5%8C%BA%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

官网示例 - DatePicker 日期选择器 - 日期区间选择器

### 期望结果

像普通的日期选择器（DatePicker）一样居中对齐

<img width="1330" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/acfcd3fb-3ada-4ef5-b271-779cacd9c1c6">

### 实际结果

DateRangePicker 的 suffix 图标高度跟随了父 DOM 样式的 `line-height: 22px`，导致**可能**比设计预期高了 6px

<img width="1356" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/c6f95009-6be7-4697-8f06-ce7615c21865">

### 框架版本

TDesign 官网所使用的 Vue.js 2.x 版本

### 浏览器版本

Chrome(124.0.6367.119)

### 系统版本

macOS 14.4.2

**Comment by uyarn** [comment]
fixed 1.9.4, thanks for @fython, and we look forward to future collaboration with you
