### ISSUE TITLE
[Input] prefix/suffix 字体大小未跟随组件 size 设定

### ISSUE THREAD

**Issue by fython** [Tencent/tdesign-vue#3171]
### tdesign-vue 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/yo4rvx?file=src%2Fdemo.vue

### 重现步骤

同时使用 `prefix`/`suffix` 和 `size` 属性：

```vue
<t-input
  v-model="count"
  size="small"
  label="价格："
  type="number"
  suffix="元"
/>
```

### 期望结果

prefix/suffix 字体大小对齐

### 实际结果

![image](https://github.com/Tencent/tdesign-vue/assets/3166782/c340acbe-1245-48f4-b113-6301a97f20e6)

实际渲染时 `.t-input.t-size-s` 定义的 `font-size` 值被 `.t-input.t-input--prefix > .t-input__prefix` 覆盖：

![image](https://github.com/Tencent/tdesign-vue/assets/3166782/61995328-05cf-4bb9-a20c-94f4760150b8)

### 框架版本

Vue 2.x

### 浏览器版本

Chrome(124.0.6367.158)

### 系统版本

Windows 11

**Comment by fython** [comment]
`.t-input.t-input--prefix > .t-input__prefix` 是否不需要单独定义 font-size？

**Comment by uyarn** [comment]
确实可以去掉 应该是没必要的
