### ISSUE TITLE
[Select] 当valueType为object的时候，value值不是完整的option项

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3188]
### tdesign-vue 版本

1.9.4

### 重现链接

https://stackblitz.com/edit/71mbwi?file=src%2Fdemo.vue,package.json

### 重现步骤

 valueType="object"且options为: [
        { label: '架构云', value: '1', title: '架构云选项' },
        { label: '大数据', value: '2', title: '大数据选项' },
        { label: '区块链', value: '3', title: '区块链选项' },
        { label: '物联网', value: '4', disabled: true },
        { label: '人工智能', value: '5', title: '人工智能选项' },
      ],

### 期望结果

下拉框绑定的value是完整的option对象 { label: '架构云', value: '1', title: '架构云选项' }

### 实际结果

仅有 { label: '架构云', value: '1' }

### 框架版本

2.6.14

### 浏览器版本

谷歌 120

### 系统版本

macos 14.4

### Node版本

16.x

**Comment by uyarn** [comment]
这个不是缺陷 valueType object 如文档所说 是 需要输出选中值包含 label 时使用，如果需要获取整个选项的全部内容，可以通过onchange回调的第二个参数中的option属性获取
