### ISSUE TITLE
[t-table] thClassName 失效

### ISSUE THREAD

**Issue by MarkGor** [Tencent/tdesign-vue#3198]
### tdesign-vue 版本

1.9.4

### 重现步骤

設置columns裡的thClassName 並不生效，查看table的ts類型，裡面也沒有這個屬性

### 期望结果

和文檔一致

### 实际结果

和文檔不一致

### 框架版本

Vue(2.7)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-07-14 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
published 1.9.9
