### ISSUE TITLE
[table] 官网table表格文档界面能否优化下 每次打卡整个浏览器都卡住 i5-8代  16gb内存  浏览器Edge 版本 122.0.2365.80 (正式版本) (64 位)

### ISSUE THREAD

**Issue by duhaoranc** [Tencent/tdesign-vue#3199]
### tdesign-vue 版本

1.9.4

### 重现链接

https://tdesign.tencent.com/vue/components/table#%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84%E7%9A%84%E8%A1%A8%E6%A0%BC

**Comment by uyarn** [comment]
官网的示例都加了lazyload 如果还是很卡 可以用 https://tdesign.tencent.com/vue/demos/table 可以用这个路径打开单个demo
对应的代码和这个一一对应 https://github.com/Tencent/tdesign-vue/tree/develop/src/table/_example
