### ISSUE TITLE
[tree] 1.9.5版本中不使用allowDrop  API的时候控制台会报错

### ISSUE THREAD

**Issue by yangyigit** [Tencent/tdesign-vue#3211]
### tdesign-vue 版本

1.9.5

### 重现步骤

tree组件目前不使用allowDrop的时候控制会出现报错
![SCR-20240626-kmbu](https://github.com/Tencent/tdesign-vue/assets/17756314/14f4bf84-4dda-4ffc-bc0c-53b91cd1275b)

### 期望结果

不是强制使用allowDrop方法

### 实际结果

tree组件目前不使用allowDrop的时候控制会出现报错
![SCR-20240626-kmua](https://github.com/Tencent/tdesign-vue/assets/17756314/b0b93324-9e19-451a-bae9-84080fa353c0)

### 框架版本

2.6.14

### Node版本

14.18.2

**Comment by uyarn** [comment]
已修复 使用1.9.6版本
