### ISSUE TITLE
[Dialog] SSR报错

### ISSUE THREAD

**Issue by qqw78901** [Tencent/tdesign-vue#3216]
### tdesign-vue 版本

latest

### 重现步骤

因为watch的visible中设置了immediate，所以ssr必然会执行visible的handler，里面读取了n个document对象
(比如addKeyboardEvent clearStyleFunc)
希望在visible的handler里能加上server的判断跳过执行

### 期望结果

SSR正常运行

**Comment by uyarn** [comment]
fixed 1.9.7
