### ISSUE TITLE
[Input] 输入框禁用时，交互错误

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3218]
### tdesign-vue 版本

1.9.5

### 重现链接

https://stackblitz.com/edit/fq82ux?file=package.json,src%2Fdemo.vue

### 重现步骤

输入框绑定数据长度超出了输入框的长度，且输入框被禁用时，由于输入框有超出省略样式，显示了省略号无法查看全部内容，但输入框可以左右拖动。
<img width="482" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/8012098/8636243d-7db0-47fc-ba1b-eed8698156de">

### 期望结果

可查看全部内容

### 实际结果

无法查看全部内容且可以拖动

### 框架版本

2.6.14

### 浏览器版本

chrome 125

**Comment by uyarn** [comment]
fixed 1.9.8
