### ISSUE TITLE
[Tree 树] 错误的过滤掉了 value = 0的节点

### ISSUE THREAD

**Issue by dhwebs** [Tencent/tdesign-vue#3227]
### tdesign-vue 版本

1.9.5

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-vue-next-demo-whjy9w?file=%2Fsrc%2Fdemo.vue

### 重现步骤

随便挑一个节点，设置value=0，然后这一节点就会被过滤

### 期望结果

value = 0的不被过滤

### 实际结果

value = 0 的被过滤了

### 框架版本

2.7.0

### 浏览器版本

Chrome(104.0.5112.81)

### 系统版本

window10

### Node版本

16.18.0

### 补充说明

看了源码，是 在23年6月28改的，直接!取反，0也进判断了
![image](https://github.com/Tencent/tdesign-vue/assets/53416746/4d06cbb3-3b15-4b2b-9937-05b2fa49646f)

**Comment by uyarn** [comment]
fixed 1.9.8
