### ISSUE TITLE
[Cascader 级联选择器]  多选删除t-tag，会触发两次Cascader的change事件

### ISSUE THREAD

**Issue by dhwebs** [Tencent/tdesign-vue#3243]
### tdesign-vue 版本

1.9.8

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.vue

### 重现步骤

t-cascader组件多选模式， 在t-cascader绑定change事件，删除tag的时候change事件会执行两次。

看了源码，在tag的删除方法handleRemoveTagEffect里，调用了两次setValue
![image](https://github.com/user-attachments/assets/522287ce-185d-46d2-bc3f-425f86c14e3b)

### 期望结果

删除tag 只触发一次change事件

### 实际结果

删除tag 会触发两次change事件

### 框架版本

2.7.0

### 浏览器版本

Chrome(104.0.5112.81)

### 系统版本

window10

### Node版本

16.18.0

**Comment by uyarn** [comment]
fixed 1.9.9
