### ISSUE TITLE
[Form] 表单校验不通过时，不滚动到指定位置且报错。

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3247]
### tdesign-vue 版本

1.9.8

### 重现链接

https://stackblitz.com/edit/mymvow?file=src%2Fdemo.vue

### 重现步骤

scrollToFirstError设置为true时，且表单内包含数组类数据时，提交校验时报错。

### 期望结果

能正常滚动到错误位置

### 实际结果

<img width="435" alt="image" src="https://github.com/user-attachments/assets/a2958edf-87e9-4bbc-a54d-db4e5ce8e1a8">

### 框架版本

2.6.14

### 补充说明

修改querySelector方法为getElementsByClassName就可以

**Comment by morningbao** [comment]
认领

**Comment by uyarn** [comment]
fixed 1.9.9

**Comment by Loinver** [comment]
<img width="531" alt="image" src="https://github.com/user-attachments/assets/b1e2e4a3-c5b2-4998-9884-95eb07895e7b">
使用.的方式还是会出现找不到dom节点的问题。

**Comment by Loinver** [comment]
> fixed 1.9.9

<img width="531" alt="image" src="https://github.com/user-attachments/assets/69dbc5bc-7b86-4070-b650-956c144df31c">
使用.的方式还是会出现找不到dom节点的问题。

**Comment by morningbao** [comment]
> > fixed 1.9.9
> 
> <img alt="image" width="531" src="https://private-user-images.githubusercontent.com/8012098/375597190-69dbc5bc-7b86-4070-b650-956c144df31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQ1MTUsIm5iZiI6MTczMDE2NDIxNSwicGF0aCI6Ii84MDEyMDk4LzM3NTU5NzE5MC02OWRiYzViYy03Yjg2LTQwNzAtYjY1MC05NTZjMTQ0ZGYzMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMDExMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDViOWQ3MTg4YWI5NGYwNWRlM2QyMWVkMzFkOGQyNWYzM2QzYThiMDlhOTMwNzYyOGZkZDU2ZWFkN2NiYjBhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kA8o2De2Y304ovC58WgCPWoSZhDWDwVhippHIt5qOEQ"> 使用.的方式还是会出现找不到dom节点的问题。

不是用 . 哦，是下划线_。你可以f12检查一下dom元素的class，是t-form-item__students_0_name这样的

**Comment by Loinver** [comment]
> > > fixed 1.9.9
> > 
> > 
> > <img alt="image" width="531" src="https://private-user-images.githubusercontent.com/8012098/375597190-69dbc5bc-7b86-4070-b650-956c144df31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQ1MTUsIm5iZiI6MTczMDE2NDIxNSwicGF0aCI6Ii84MDEyMDk4LzM3NTU5NzE5MC02OWRiYzViYy03Yjg2LTQwNzAtYjY1MC05NTZjMTQ0ZGYzMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMDExMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDViOWQ3MTg4YWI5NGYwNWRlM2QyMWVkMzFkOGQyNWYzM2QzYThiMDlhOTMwNzYyOGZkZDU2ZWFkN2NiYjBhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kA8o2De2Y304ovC58WgCPWoSZhDWDwVhippHIt5qOEQ"> 使用.的方式还是会出现找不到dom节点的问题。
> 
> 不是用 . 哦，是下划线_。你可以f12检查一下dom元素的class，是t-form-item__students_0_name这样的

const formItemName = `${this.tableDataName}[${rowIndex}].${__.prop}`;使用这种方式可以正常滚动了
