### ISSUE TITLE
[DatePocker] 鼠标滚动一格，时间跳动一下，但是没有调整值

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-vue#3248]
### tdesign-vue 版本

1.3.0，1.9.8

### 重现链接

https://tdesign.tencent.com/vue/components/date-picker

### 重现步骤

官网直接测试

https://github.com/user-attachments/assets/c6439e85-0315-4fdc-b344-69c694a1aabd

### 期望结果

鼠标滚动一格精准调整一格值

### 实际结果

见测试视频

**Comment by uyarn** [comment]
已在企业微信群内沟通 此问题暂时不会处理
