### ISSUE TITLE
【table】width用String赋值，fixed失效，数据左移

### ISSUE THREAD

**Issue by Yizhizhenhties** [Tencent/tdesign-vue#325]
如题
【用的示例中`固定列的表格`的例子，第一列fixed，最后三列fixed结果如下】
![image](https://user-images.githubusercontent.com/73346429/150671101-bb48b7dd-d930-41bb-ae36-607c670881a1.png)
![image](https://user-images.githubusercontent.com/73346429/150671165-bc1d484f-98de-4c71-a999-d49bd72accfa.png)
【最后三列→最后俩列fixed，正常】
![image](https://user-images.githubusercontent.com/73346429/150671216-01588802-1ac5-41b3-b4c1-a2f96b29cac4.png)
【width用number赋值是正常的】

**Comment by chaishi** [comment]
没太看明白，可以在细化一下描述么

**Comment by Yizhizhenhties** [comment]
就是width这一项如果用String去赋值的话会产生失效的问题【我把例子中的第一列，最后三列设成了fixed】
![image](https://user-images.githubusercontent.com/73346429/150671388-b4340797-2590-4f48-8491-3ffe90898ca4.png)

**Comment by realyuyanan** [comment]
> 就是width这一项如果用String去赋值的话会产生失效的问题【我把例子中的第一列，最后三列设成了fixed】 ![image](https://user-images.githubusercontent.com/73346429/150671388-b4340797-2590-4f48-8491-3ffe90898ca4.png)

有没有沙箱链接呢？我这边看起来没什么问题。

**Comment by Yizhizhenhties** [comment]
> > 就是width这一项如果用String去赋值的话会产生失效的问题【我把例子中的第一列，最后三列设成了fixed】 ![image](https://user-images.githubusercontent.com/73346429/150671388-b4340797-2590-4f48-8491-3ffe90898ca4.png)
> 
> 有没有沙箱链接呢？我这边看起来没什么问题。

https://codesandbox.io/s/tdesign-vue-demo-forked-zuym7?file=/src/demo.vue
![image](https://user-images.githubusercontent.com/73346429/150916852-ed4563bc-6a61-4dfe-8b05-f6e8201caf40.png)

**Comment by realyuyanan** [comment]
> > > 就是width这一项如果用String去赋值的话会产生失效的问题【我把例子中的第一列，最后三列设成了fixed】 ![image](https://user-images.githubusercontent.com/73346429/150671388-b4340797-2590-4f48-8491-3ffe90898ca4.png)
> > 
> > 
> > 有没有沙箱链接呢？我这边看起来没什么问题。
> 
> https://codesandbox.io/s/tdesign-vue-demo-forked-zuym7?file=/src/demo.vue ![image](https://user-images.githubusercontent.com/73346429/150916852-ed4563bc-6a61-4dfe-8b05-f6e8201caf40.png)

好的，我看下。

**Comment by xiaosansiji** [comment]
已在 0.35.0 版本中修复
