### ISSUE TITLE
table组件 固定表头/固定行的表格示例   chrome80版本表头不固定

### ISSUE THREAD

**Issue by suidagang** [Tencent/tdesign-vue#3250]
### tdesign-vue 版本

1.7.1

### 期望结果

高版本chrome浏览器正常，chrome80版本表头没固定，期望chrome80版本表头能固定

### 框架版本

Vue(2.6.11)

### 浏览器版本

Chrome(80.0.3987.149)

### 系统版本

windows

**Comment by uyarn** [comment]
兼容性问题见 https://github.com/Tencent/tdesign/wiki/Browser-Compatibility chrome 80对sticky属性不支持 我们不会兼容到80的版本
