### ISSUE TITLE
[DatePicker] 周选择器时跨年周场景下获得的时间格式异常

### ISSUE THREAD

**Issue by zdz4510** [Tencent/tdesign-vue#3261]
### tdesign-vue 版本

1.9.4

### 重现链接

[https://tdesign.tencent.com/vue/components/date-picker?tab=demo#%E5%91%A8%E9%80%89%E6%8B%A9%E5%99%A8](https://tdesign.tencent.com/vue/components/date-picker?tab=demo#%E5%91%A8%E9%80%89%E6%8B%A9%E5%99%A8)

### 重现步骤

使用周[范围]选择器时，当选择某年的【第一周】时，若鼠标点中的是【上一年末的日期】，则会导致显示年份计算错误（如：选择2014-1周时，若鼠标悬停至2013年12月31日，控件显示的时间会变成错误的2013-1周）

### 期望结果

正常应该是2014-1周

### 实际结果

https://github.com/user-attachments/assets/39edd90b-8c91-4b88-96a4-1b9b1d249a33

### 框架版本

vue 2.6.10

### Node版本

v14.15.4

**Comment by zdz4510** [comment]
![8f5124a74307b43fdc2a265c62622830](https://github.com/user-attachments/assets/d1951ee1-7f6c-43bf-89c6-949c9462c61d)

**Comment by activeroc** [comment]
我这也有相同的问题，很头痛，临时把周选择器换成其它的了

**Comment by uyarn** [comment]
fixed 1.10.1
