### ISSUE TITLE
[Form] required和whitespace同时使用，则whitespace不生效

### ISSUE THREAD

**Issue by mdxiaohu** [Tencent/tdesign-vue#3262]
### tdesign-vue 版本

1.9.8

### 重现链接

https://tdesign.tencent.com/vue/components/form?tab=api

### 重现步骤

rules: {
	name: [{
	required: true,
	whitespace: true
	}],
}
创建一个表单，并写入一个input，使用rules来验证，输入空格即可重现

### 期望结果

required和whitespace一起使用均可以生效

### 实际结果

required独立使用生效
whitespace独立使用生效
required和whitespace一起使用，则required生效，whitespace不生效

### 框架版本

2.6.14

### Node版本

16

**Comment by uyarn** [comment]
published 1.10.0
