### ISSUE TITLE
[ColorPicker] selectInputProps 属性传入值后无效

### ISSUE THREAD

**Issue by 673019334** [Tencent/tdesign-vue#3271]
### tdesign-vue 版本

1.9.0-naruto

### 期望结果

传入属性后可修改成功

### 实际结果

传入属性后无效

### 框架版本

Vue(2.7)

### 浏览器版本

chrome(121.0.6167.139)

### 系统版本

maxos(13.2)

### Node版本

14.3.0

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-08-23 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by taninsist** [comment]
@673019334 你能在 https://jsfiddle.net/ 平台复现下吗？

**Comment by uyarn** [comment]
published 1.10.0
