### ISSUE TITLE
[Select 选择器] 键盘聚焦没有展开下拉列表，方向键选取下拉项面板内容没跟随滚动

### ISSUE THREAD

**Issue by dhwebs** [Tencent/tdesign-vue#3272]
### tdesign-vue 版本

1.9.8

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.vue

### 重现步骤

先聚焦第一个，然后用键盘tab键切换表单，切换到第二个时，表单已经是激活选中状态，但是没有展开下拉框，输入关键字搜索也不会触发下拉框展开。然后还有个问题，展开下拉框后，用键盘的方向键向下选取，当选项数量多超出下拉面板有滚动条时，继续用方向键向下，下拉面板内容不会跟着滚动

### 期望结果

键盘tab切换表单到select组件时，默认展开下拉列表。选项太多超出面板时，方向键选取超出的选项，下拉面板内容能跟随激活项滚动

### 实际结果

键盘tab切换表单到select组件时，没有展开下拉列表，搜索也没触发下拉展开。选项太多超出面板时，方向键选取超出的选项，下拉面板内容没有跟随滚动，导致看不到键盘选取的光标

### 框架版本

2.7.0

### 浏览器版本

Chrome(104.0.5112.81)

### 系统版本

window10

### Node版本

16.18.0

```[tasklist]
### Tasks
```

**Comment by uyarn** [comment]
published 1.10.0
