### ISSUE TITLE
[Select] 希望能全选分组过滤后的结果

### ISSUE THREAD

**Issue by claydichen** [Tencent/tdesign-vue#3276]
### 这个功能解决了什么问题

<img width="574" alt="企业微信截图_8e9874fa-29ae-4134-a300-6b89e8fca607" src="https://github.com/user-attachments/assets/362eb74b-db9f-4e3a-b577-088924115c79">
<img width="536" alt="企业微信截图_fa5b2243-1be4-4bbf-a5e6-b735bb6b3991" src="https://github.com/user-attachments/assets/e2383cc6-ed9d-4fe4-a1cd-451b2fa4150c">
select输入内容和全选的选择框不见了，如果通过修改filter强行展示的话点击选中后也不是得到想要的结果，反而是把options中所有内容选中了

### 你建议的方案是什么

希望能支持全选框常驻，在输入过滤值后可以选中过滤后的所有结果
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-08-27 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
supported 1.10.1
