### ISSUE TITLE
【tree-select】自定义valueDisplay不生效

### ISSUE THREAD

**Issue by kucorei** [Tencent/tdesign-vue#330]
不管是绑定Function还是slot都没有生效，单纯的select就可以生效，
![image](https://user-images.githubusercontent.com/54382769/150709297-31b87020-1dee-4367-abf8-7a29c7781606.png)

codesandbox:
https://codesandbox.io/s/tdesign-vue-demo-forked-k72v8?file=/src/demo.vue

**Comment by chaishi** [comment]
已实现，并发布至 `v0.33.2`

**Comment by kucorei** [comment]
> 

![image](https://user-images.githubusercontent.com/54382769/150736631-6f4e4f2d-77ee-4c82-98e6-301e6f6da423.png)
这个还是没有生效啊，select就可以，麻烦看看什么哦，能不能给的demo看看
