### ISSUE TITLE
[Dialog] 非模态对话框可识别性差

### ISSUE THREAD

**Issue by ghostzhang** [Tencent/tdesign-vue#3314]
### tdesign-vue 版本

1.10

### 重现链接

https://tdesign.tencent.com/vue/components/dialog

### 重现步骤

非模态对话框

### 期望结果

非模态下增加投影

### 实际结果

![image](https://github.com/user-attachments/assets/de98fd02-88ea-4553-9cf1-dda6125d3381)

**Comment by uyarn** [comment]
assign to @RSS1102

**Comment by uyarn** [comment]
optimised 1.10.1
