### ISSUE TITLE
[组件名称] 请将less变量替换为var 变量

### ISSUE THREAD

**Issue by lelouch-xue** [Tencent/tdesign-vue#3347]
### 这个功能解决了什么问题

请将less变量替换为var 变量

### 你建议的方案是什么

请将less变量替换为var 变量
1. 可以用多种预处理插件
2. 全局（局部）修改样式时更为方便

**Comment by lelouch-xue** [comment]
![image](https://github.com/user-attachments/assets/81daa56d-80f9-449f-85c6-dc1e0b4cf94a)
以途中的button为例，将@btn-height-s 等 变为--btn-height-s 作为一个var是不是更好一些呢，我看现在主流的框架都变成var了, 浏览器兼容除了ie都支持的很好了

**Comment by uyarn** [comment]
了解了，但是1.0的版本暂时不会做这种变动了，因为有一些使用方已经基于less来覆盖样式，这种改动影响比较大；
现在其实也可以基于全局变量也是可以支持组件级别的覆盖的，利用就近原则进行单个组件的二次覆盖；
```css
.t-button {
--td-brand-color: xx 
}
```
