### ISSUE TITLE
[TimePicker] timeRangePicker自动排序默认行为无法修改?

### ISSUE THREAD

**Issue by furylee** [Tencent/tdesign-vue#3355]
### tdesign-vue 版本

1.10.3

### 重现步骤

feat https://github.com/Tencent/tdesign-vue/pull/3327
新的行为直接为默认无法切换开关,原本可以设置跨天的时间段需要在事件中重新调整,即前大后小,是否应该改为开关控制?

```[tasklist]
### Tasks
```

**Comment by uyarn** [comment]
好吧看来还是有这种需求 我们还是增加开关来满足下

**Comment by uyarn** [comment]
support `autoSwap` 1.10.4
