### ISSUE TITLE
Upload 上传组件， 增加图片预览功能 add preview image

### ISSUE THREAD

**Issue by cybrobin** [Tencent/tdesign-vue#336]
图片上传成功后可以回写 上传组件的预览，但保存后就无法预览了，需要增加这控制参数

**Comment by chaishi** [comment]
应该支持这个特性的，辛苦给一个 codesandbox 可以复现问题的链接

**Comment by cybrobin** [comment]
> 应该支持这个特性的，辛苦给一个 codesandbox 可以复现问题的链接

目前是不支持的，需要官方支持。
