### ISSUE TITLE
[dialog] 开关dialog时背景抖动

### ISSUE THREAD

**Issue by Erimus-Koo** [Tencent/tdesign-vue#3360]
### tdesign-vue 版本

1.10.2

### 重现步骤

1. [Dialog 对话框 | TDesign](https://tdesign.tencent.com/vue-next/components/dialog#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8-dialog-%E4%B8%AD%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E6%A0%B7%E5%BC%8F%E7%A9%BF%E9%80%8F%EF%BC%9F) 在这个官方示例页面，开启和关闭dialog。
2. 观察背景的变化。由于body滚动的取消，导致滚动条消失，导致body宽度变化，导致抖动。

### 期望结果

不要抖动

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-common/pull/1968

**Comment by uyarn** [comment]
fixed 1.10.4
