### ISSUE TITLE
DatePicker 日期选择器 中 value 设置 数组报错问题

### ISSUE THREAD

**Issue by Corgis** [Tencent/tdesign-vue#3361]
### tdesign-vue 版本

1.10.3

### 重现链接

https://stackblitz.com/edit/gpujss?file=src%2Fdemo.vue,package.json

### 重现步骤

打开控制台可看到如下报错，而按照api中 对于 value 类型的描述 是可以支持String / Number / Array / Date 的，不应该会有如下错误！！
![image](https://github.com/user-attachments/assets/61b26bb7-01e0-4fdd-88be-35e696a7a6b4)

### 期望结果

能正常显示绑定的数组类型的多个日期

### 实际结果

报错如下
![image](https://github.com/user-attachments/assets/8773607a-9c33-442f-a10a-1e6904117318)

### 框架版本

vue 2.6.14

### 浏览器版本

Chrome ( 129.0.6668.90 ) 64位版

### Node版本

v18.20.1

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-10-20 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
这个是文档上删除遗漏了，最开始的版本date-range-picker没有单独成一个子组件 而是通过<t-date-picker range /> 的方式使用的 所以才会有数组，谢谢反馈问题，也欢迎提PR改正文档 🌹
