### ISSUE TITLE
[Form] 表单校验不通过时，不滚动到指定位置且报错

### ISSUE THREAD

**Issue by Loinver** [Tencent/tdesign-vue#3364]
### tdesign-vue 版本

1.10.3

### 重现链接

https://stackblitz.com/edit/mymvow?file=package.json,src%2Fdemo.vue

### 重现步骤

scrollToFirstError设置为true时，且表单内包含数组类数据时，提交校验时报错。

### 期望结果

能正常滚动到错误位置

### 实际结果

![image](https://github.com/user-attachments/assets/7e93e78d-3b2f-42ec-9acc-b1989899fa4f)

### 框架版本

2.6.14

**Comment by liweijie0812** [comment]
<img width="794" alt="image" src="https://github.com/user-attachments/assets/f6a8cd9d-6fba-490f-85a9-85deb7e0a8f5">
提供的是示例，跳转正常没报错

**Comment by Loinver** [comment]
审查元素看到示例的节点class是_连接
<img width="1514" alt="image" src="https://github.com/user-attachments/assets/77536ffc-c8d7-4e52-b829-c937b2bf6e6e">
我本地是用.连接
<img width="415" alt="image" src="https://github.com/user-attachments/assets/28042f73-a371-40cb-95a5-969327b35ab3">

**Comment by Loinver** [comment]
噢噢，知道了，我使用的是
<img width="456" alt="image" src="https://github.com/user-attachments/assets/1a62b9e0-5fb4-470f-9897-64feff8633ed">
zhe zh这种去定义form-item的name
