### ISSUE TITLE
Table 表格 的示例代码 'width' 的值 一会 '数字' 一会 '字符串'

### ISSUE THREAD

**Issue by ccccpj** [Tencent/tdesign-vue#339]
![image](https://user-images.githubusercontent.com/39974142/150746529-612c607e-192b-4573-9be6-d296339c72b8.png)
Table 表格 的示例代码 'width' 的值 一会 '数字' 一会 '字符串' 感觉不太规范

**Comment by chaishi** [comment]
这不是规范与否的问题，是为了告诉大家，字符串和数字都可以，业务侧不用担心哪一个不可以
