### ISSUE TITLE
[dateRangePicker] 日期范围选择问题

### ISSUE THREAD

**Issue by Elinya** [Tencent/tdesign-vue#3419]
### 这个功能解决了什么问题

onChange事件选择一个日期之后就马上触发了，想要重新选择两个日期后再触发事件

### 你建议的方案是什么

可否设置一个选项给用户选择？

**Comment by uyarn** [comment]
可以参考这个方式 https://stackblitz.com/edit/nyytqabp-zkhb2r7o?file=src%2Fdemo.vue
