### ISSUE TITLE
[Cascader] valueType为full时点击重复点击已选中的项会继续触发change事件

### ISSUE THREAD

**Issue by iceyxx6** [Tencent/tdesign-vue#3430]
### tdesign-vue 版本

1.10.7

### 重现步骤

![image](https://github.com/user-attachments/assets/adac8c55-b88d-431e-83b1-b02b9390b61b)
设置valueType为full
重复点击已选中的项会重复触发change事件

### 期望结果

值不变时不触发change事件

### 实际结果

值不变时依旧触发change事件

### 框架版本

vue2.6.14

**Comment by uyarn** [comment]
fixed 1.10.8
