### ISSUE TITLE
[Dialog] 自1.10.6之后对话框的closeOnOverlayClick属性默认值不生效

### ISSUE THREAD

**Issue by iceyxx6** [Tencent/tdesign-vue#3432]
### tdesign-vue 版本

1.10.7

### 期望结果

closeOnOverlayClick默认值为true，与文档中一致，现在需要主动将closeOnOverlayClick设置为true才生效

### 框架版本

vue2.6.14

**Comment by uyarn** [comment]
1.10.6有个默认值变化引起，谢谢反馈 这周会重新发个版本修复

**Comment by uyarn** [comment]
fixed 1.10.8
