### ISSUE TITLE
[Cascader 级联选择器] valueType=full&showAllLevels=false导致单选勾选不上

### ISSUE THREAD

**Issue by dhwebs** [Tencent/tdesign-vue#3436]
### tdesign-vue 版本

1.10.7

### 重现链接

https://stackblitz.com/edit/rtux8dsj?file=src%2Fdemo.vue

### 重现步骤

传参
    :showAllLevels="false"
    valueType="full"
   勾选时会清空选中值

### 期望结果

正常勾选展示

### 实际结果

   勾选时会清空选中值

### 框架版本

2.7.0

### 浏览器版本

Chrome(104.0.5112.81)

### 系统版本

window10

### Node版本

16.18.0

**Comment by uyarn** [comment]
fixed 1.10.8
