### ISSUE TITLE
steps(bug): 

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue#36]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

官网

**streps 组件 extra demo**

未出现 extra 内容
![image](https://user-images.githubusercontent.com/35833812/146882187-df6d6e0d-6864-4af4-b322-b4cfedfb8139.png)

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
