### ISSUE TITLE
【table 组件】多级表头的表格 改变children的宽度无效

### ISSUE THREAD

**Issue by QJBChou** [Tencent/tdesign-vue#367]
https://codesandbox.io/s/tdesign-vue-demo-forked-xp45w?file=/src/demo.vue
![image](https://user-images.githubusercontent.com/38748326/151301277-1ab085b1-0364-4687-9342-a86000f9913d.png)

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365

可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验
