### ISSUE TITLE
progress 的 circle 主题下不支持 trackColor 属性

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#368]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 97.0.4692.71（正式版本） (x86_64)

**Describe the bug**
progress 的 circle 主题下不支持 trackColor 属性

**Additional context**
theme="circle"

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/410

**Comment by xiaosansiji** [comment]
已在 0.35.0 版本中修复
