### ISSUE TITLE
table 组件使用 PrimaryTable 控制台报错 t-primary-table 未注册

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#373]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 97.0.4692.71（正式版本） (x86_64)

**Describe the bug**
table 组件使用 PrimaryTable 控制台报错 t-primary-table 未注册
demo: [https://codesandbox.io/s/tdesign-vue-demo-forked-lq6fl?file=/src/demo.vue](https://codesandbox.io/s/tdesign-vue-demo-forked-lq6fl?file=/src/demo.vue)

**Additional context**
使用PrimaryTable组件

**Comment by xiaosansiji** [comment]
其实直接用 `t-table` 标签就是在使用 `PrimaryTable` 了，默认 export 的就是它：
https://github.com/Tencent/tdesign-vue/blob/develop/src/table/index.ts#L36

**Comment by wwervin72** [comment]
> 

确实 t-table 和 PrimaryTable 实际上使用的是一个组件，不过既然文档里面给出了 PrimaryTable 的这种用法，如果能处理下保证正常使用是不是会更好呢，然后现在实际使用起来却报错，容易给人造成误解。

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验
