### ISSUE TITLE
【drawer】 组件按下 esc 事件不触发，导致 closeOnEscKeydown onEscKeydown 等都不生效

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#380]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Describe the bug**
drawer 组件 esc 等操作不触发，导致 closeOnEscKeydown onEscKeydown 等都不生效，需要设置 tabindex，
[https://stackoverflow.com/questions/43503964/onkeydown-event-not-working-on-divs-in-react](https://stackoverflow.com/questions/43503964/onkeydown-event-not-working-on-divs-in-react)

demo: [https://codesandbox.io/s/tdesign-vue-demo-forked-6li7s?file=/src/demo.vue](https://codesandbox.io/s/tdesign-vue-demo-forked-6li7s?file=/src/demo.vue)

**Comment by xiaosansiji** [comment]
已在 0.35.0 版本中修复
