### ISSUE TITLE
【steps】readonly 和 onChange 一起使用不生效

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#382]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Describe the bug**
readonly 和 onChange 一起使用，并且在处理 onChange 事件的方法里面去设置 current step的值，会导致 steps仍然可用
demo: [https://codesandbox.io/s/tdesign-vue-demo-forked-34ndd?file=/src/demo.vue:137-145](https://codesandbox.io/s/tdesign-vue-demo-forked-34ndd?file=/src/demo.vue:137-145)

**Additional context**
1. readonly 和 onChange 一起使用
2. 在处理 onChange 事件的方法里面去设置 current step的值

**Comment by cong-min** [comment]
遇到同样的问题，@chaishi 帮忙看看。这是设计如此还是BUG？
