### ISSUE TITLE
设置最大高度和固定列之后，滚动横行滚动条，操作列右侧会出现文字

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#383]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**
设置最大高度和固定列之后，滚动横行滚动条，操作列右侧会出现文字

<img width="715" alt="image" src="https://user-images.githubusercontent.com/20809990/153140896-475765f5-14ea-4b2c-aa57-5ec4582dec68.png">

[codesandbox地址](https://codesandbox.io/s/tdesign-vue-demo-forked-oj0qu)

**Additional context**

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365, Ring

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
