### ISSUE TITLE
table组件设置height后，加载数据和空数据生成的dom不一致。

### ISSUE THREAD

**Issue by HULANG-BTB** [Tencent/tdesign-vue#384]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome： 版本 97.0.4692.99（正式版本） （64 位）

tdesign-vue： 0.33.2

**Describe the bug**

设置table的height属性，在空数据时：

![before](https://user-images.githubusercontent.com/30247854/151097586-9ba5b1d1-7a14-4b64-9420-07f2d320370a.PNG)

异步加载数据后：

![after](https://user-images.githubusercontent.com/30247854/151097639-c813e6c9-dc6f-4c0d-b1f1-f71fa95565ce.PNG)

即便是展示暂无数据的时候，也应该保留原有的t-table__header,t-table__body等dom结构，而不是直接省略其中的部分内容。

并且异步加载数据后表头的boder-bottom失效了。

**Comment by chaishi** [comment]
这个 issue 没有看明白，难以处理

**Comment by chaishi** [comment]
BaseTable 已经重构，see https://github.com/Tencent/tdesign-vue/pull/365，且看后续结构是否符合你的预期
