### ISSUE TITLE
使用栅格布局的gutterAPI设置行间距，在70版本chrome上无效

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#386]
**Describe Framework**

tdesign-vue

**Describe Environment**

70版本的chrome

**Describe the bug**
使用栅格布局的gutterAPI设置行间距，在70版本chrome上无效，上下两行贴在一起了
![image](https://user-images.githubusercontent.com/20809990/153197034-e34cc492-20ba-4b81-a319-9fbca583195c.png)

**Additional context**

**Comment by HQ-Lin** [comment]
纵向间距使用了 `row-gap` 来实现，该属性在 Chrome 84 以上才支持
https://caniuse.com/?search=row-gap

**Comment by xiecz123** [comment]
> 

是这样的，但是tDesign需要兼容69以上版本的chrome。https://tdesign.tencent.com/vue/getting-started#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by HQ-Lin** [comment]
当时撰写兼容性版本的时候看成了 grid layout 的 `row-gap` 😂 ，想问下能否升级下chrome 版本，70版本已经是 2018 年发布的内核了

**Comment by HQ-Lin** [comment]
> > 纵向间距使用了 flex layout 的`row-gap` 来实现，该属性在 Chrome 84 以上才支持 https://caniuse.com/?search=row-gap
> 
> 但是tDesign明确写着兼容69以上版本的chrome。https://tdesign.tencent.com/vue/getting-started#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

当时撰写兼容性版本的时候看成了 grid layout 的 row-gap 😂 ，想问下能否升级下chrome 版本，70版本已经是 2018 年发布的内核了

**Comment by xiecz123** [comment]
> > > 纵向间距使用了 flex layout 的`row-gap` 来实现，该属性在 Chrome 84 以上才支持 https://caniuse.com/?search=row-gap
> > 
> > 
> > 但是tDesign明确写着兼容69以上版本的chrome。https://tdesign.tencent.com/vue/getting-started#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7
> 
> 当时撰写兼容性版本的时候看成了 grid layout 的 row-gap 😂 ，想问下能否升级下chrome 版本，70版本已经是 2018 年发布的内核了

因为这是你们承诺支持的版本,并且客户的浏览器不可能始终是最新版本。
