### ISSUE TITLE
Textarea在设置maxcharacter属性时，若不绑定value值，初始长度显示为9

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#387]
**Describe Framework**

tdesign-vue

**Describe Environment**

Add browser version here

**Describe the bug**
![image](https://user-images.githubusercontent.com/16223845/153328931-cb244ca8-7c07-4ebb-a60f-3ea8e95cb757.png)

**demo**

```
<t-textarea :maxcharacter="20"></t-textarea>
```

**Comment by xiaosansiji** [comment]
已在 0.35.0 版本中修复
