### ISSUE TITLE
【select】可创建新条目的选择框，选择创建的新条目后，出现了一个空白的项目可选择，选择这个空白条目后，又会出现一个空白的项目可选择

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#388]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Describe the bug**
【select】可创建新条目的选择框，选择创建的新条目后，出现了一个空白的项目可选择，选择这个空白条目后，又会出现一个空白的项目可选择

**Additional context**
可创建条目和filterable一起使用

**Comment by geff1991** [comment]
请问有预览链接或者代码么

**Comment by geff1991** [comment]
> 请问有预览链接或者代码么

https://codesandbox.io/s/zml1cc?file=/src/demo.vue
![企业微信截图_16462747443301](https://user-images.githubusercontent.com/6264677/156519700-372a9b35-521c-45a1-acca-2446dd43e2d5.png)

**Comment by xiaosansiji** [comment]
已在 0.36.0 版本中修复

**Comment by geff1991** [comment]
这个可以close了吧
