### ISSUE TITLE
【Table 表格】默认的分页显示在表格底部，是否可以增加现在在表格顶部

### ISSUE THREAD

**Issue by ggbdpq** [Tencent/tdesign-vue#389]
如题，鉴于实际项目开发中业务需求的数量庞大，分页显示在底部难以被客户发现，是否可增加一个属性来把握分页的显示位置，比如控制显示在表格顶部，谢谢~

**Comment by chaishi** [comment]
已收到信息，会联系交互设计师跟进

**Comment by chaishi** [comment]
如果是顶部，业务侧可以完全自己定义一个单独的 pagination 组件哈，不在 Table 里面内置了
