### ISSUE TITLE
Textarea、Input的autofocus属性很多时候没有聚焦成功

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#390]
**Describe Framework**

tdesign-vue

**Describe Environment**

版本：0.34.0

**Describe the bug**

**Additional context**

**Comment by mokywu** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-ozq0y?file=/src/demo.vue

https://ozq0y.csb.app/

从demo里面看好像没啥问题，能不能提供一下 demo 之类的？

**Comment by huangpiqiao** [comment]
1、例如源码在本地跑dev的时候
```
<t-input autofocus />
<t-textarea
      v-model="value"
      placeholder="请输入描述文案"
      name="description"
      autofocus
      @change="onChange"
    />
```
![image](https://user-images.githubusercontent.com/16223845/153383926-67d6ba98-78a4-4807-a05d-82af9ece06c6.png)
![image](https://user-images.githubusercontent.com/16223845/153384786-0c20f856-52fd-48bb-9752-1071a69535dc.png)

2、textarea在项目里面，手动刷新浏览器页面可以聚焦，vue路由跳转就没有聚焦

**Comment by huangpiqiao** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-7dxyi?file=/src/demo.vue
