### ISSUE TITLE
Table组件BaseTableCol配置项fixed和ellipsis(true)属性共存导致fix阴影无法显示

### ISSUE THREAD

**Issue by dreamsqin** [Tencent/tdesign-vue#392]
**Describe Framework**

tdesign-vue 0.34.0

**Describe Environment**

Chrome 97.0.4692.71（正式版本） (x86_64)

**Describe the bug**
codesandbox复现：https://codesandbox.io/s/tdesign-vue-demo-forked-0plte?file=/src/demo.vue
- ellipsis为false阴影正常显示
![image](https://user-images.githubusercontent.com/15522703/153378207-b4d255c9-6b03-4c25-80f5-fa33916d631c.png)
- ellipsis为true阴影无法显示
![image](https://user-images.githubusercontent.com/15522703/153378351-344b8163-8a45-4856-b922-c0746e9cd613.png)

**Additional context**
因为fixed底层实现阴影为伪元素after，ellipsis为true时overflow:hidden导致after显示失败
![image](https://user-images.githubusercontent.com/15522703/153378900-89aa5710-a5af-4369-8dfe-132f197e47b8.png)
![image](https://user-images.githubusercontent.com/15522703/153378975-50e17efd-e7d2-43aa-9c61-4818eb61c56b.png)

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365

**Comment by chaishi** [comment]
resolved in `v0.39.1`
