### ISSUE TITLE
【date-picker】allowinput 为true时，当输入内容长度为1时，不能删除成功

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#393]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Describe the bug**
allowinput 为true时，当输入内容长度为1时，不能删除成功
demo: [https://codesandbox.io/s/tdesign-vue-demo-forked-g2x0w?file=/src/demo.vue](https://codesandbox.io/s/tdesign-vue-demo-forked-g2x0w?file=/src/demo.vue)

**Additional context**
allowinput=true

**Comment by xiaosansiji** [comment]
datepicker 新交互稿已经确定了，正在出设计，里面会包括 datepicker 可输入相关的交互，到时会重构 allowinput 的实现。争取3月初搞定
