### ISSUE TITLE
【Form】错误提示的字体好像变小了

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#395]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome  97.0.4692.99

**Describe the bug**

之前的版本：
![image](https://user-images.githubusercontent.com/15682051/153546654-01426a9c-cf7c-4cbc-b632-248040b0a828.png)

"tdesign-vue": "^0.34.0"：
![image](https://user-images.githubusercontent.com/15682051/153546666-f8ebbe92-d683-4eb5-8466-fe6d7faf444b.png)

**Additional context**

**Comment by uyarn** [comment]
符合预期的
