### ISSUE TITLE
Loading组件当使用attach时，设置loading prop为false，无法关闭笼罩层

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#398]
**Describe Framework**

tdesign-vue

**Describe the bug**
https://codesandbox.io/s/tdesign-vue-demo-forked-zdqpp

**Additional context**
<img width="880" alt="image" src="https://user-images.githubusercontent.com/11243798/153555045-8248bf16-c6a2-4c88-9991-b4d34e56da5f.png">

**Comment by chaishi** [comment]
resovled in https://github.com/Tencent/tdesign-vue/pull/409
