### ISSUE TITLE
【slider】双滑块模式，拖动一个点越过另一个点时，另一个点也跟着一起移动了

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#399]
**Describe Framework**

tdesign-vue

**Describe Environment**

chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Describe the bug**
双滑块模式，拖动一个点越过另一个点时，另一个点也跟着一起移动了，期望另一个点不会动，如果拖动右边的点跑到左边去了，那拖动的这个点就应该作为起点，拖动左边点跑到最右边去了 那应该变成终点。

**Additional context**
双滑块模式

**Comment by chaishi** [comment]
交互可能需要再讨论一下
