### ISSUE TITLE
Progress进度条在circle模式下进度低于5%时会显示两个进度条，且为0%时会显示两个圆点

### ISSUE THREAD

**Issue by Liunian7032** [Tencent/tdesign-vue#412]
**Describe Framework**

tdesign-vue

**Describe Environment**

Chrome  98.0.4758.80

**Describe the bug**
Progress进度条在circle模式下进度低于5%时会显示两个进度条，且为0%时会显示两个圆点

**Additional context**
```
<t-progress theme="circle" :percentage="0" ></t-progress>
```

**Comment by huanyue2019** [comment]
认领
