### ISSUE TITLE
【Table 表格】有关滚动条的尺寸大小的建议

### ISSUE THREAD

**Issue by ggbdpq** [Tencent/tdesign-vue#414]
在大量表格执行滚动效果的时候，现在默认滚动条太细，操作及其不方便，可以新增一个属性专用设置滚动条的尺寸大小吗？

**Comment by xiaosansiji** [comment]
滚动条样式是组件库中统一的风格，单独给表格开 API 设置滚动条样式感觉不太好，需要修改表格滚动条样式的话可以覆盖下这里的样式 https://github.com/Tencent/tdesign-common/blob/develop/style/web/mixins/_scrollbar.less#L9

**Comment by uyarn** [comment]
默认样式不会修改 暂时也没看出专门新增这种属性的必要 但是完全可以自己做样式覆盖

**Comment by ggbdpq** [comment]
好的，谢谢你~
