### ISSUE TITLE
Cascader 条目数多会卡死问题

### ISSUE THREAD

**Issue by mrhoric** [Tencent/tdesign-vue#422]
版本： `0.24.0`
数据条目数： `5000左右`

现象：
点击展开内容需要等大约20s才能展开第一级，点击第二级，需要再等很久才能展开二级

**Comment by delenzhang** [comment]
> 我用的是vue2 不是react

https://github.com/Tencent/tdesign-vue/pull/491 该pr已修复问题，更新最新的td-vue
