### ISSUE TITLE
【table】bug1：children表头无法设置宽度 bug2：固定带有children的表头，或者设置了rowspanAndColspan的表头，内容位移 bug3：表格有设置children或者rowspanAndColspan时，fixed多个表头时，内容位移

### ISSUE THREAD

**Issue by QJBChou** [Tencent/tdesign-vue#432]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-b3ntir?file=/src/demo.vue

### 重现步骤
bug1：children表头无法设置宽度
bug2：固定带有children的表头，或者设置了rowspanAndColspan的表头，内容位移
bug3：表格有设置children或者rowspanAndColspan时，fixed多个表头时，内容位移

### 实际结果

| Environment | Info |
|---|---|
| 相关版本 | 0.34.0 |
| 框架版本 / 基础库版本 | vue2 |
| 系统、浏览器 | edge |
| Node版本 |  |

**Comment by QJBChou** [comment]
![image](https://user-images.githubusercontent.com/38748326/154454007-139a3d81-514f-4ce1-b887-b0b43f35c860.png)

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365

**Comment by chaishi** [comment]
可在先行版本 `npm install tdesign-vue@0.36.0-alpha.1` 中体验
