### ISSUE TITLE
[datepicker] 点击年份或月份后，弹窗会消失

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue#443]
### 重现链接
https://codesandbox.io/s/6ss0e4?file=/src/demo.vue

https://user-images.githubusercontent.com/26377630/154937983-432a88c8-4329-4905-99f3-658eff23f71d.mp4

### 重现步骤
打开日期选择器的“日期选择器” Demo，弹窗出现后 点击左上角的年份 即可复现

### 期望结果
点击年份或月份后，弹窗不会消失

### 实际结果
点击年份或月份后，弹窗会消失

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | vue2.x |
| 系统、浏览器 | 无关 |
| Node版本 | 无关 |

**Comment by xiaosansiji** [comment]
已在 0.36.0 版本中修复
