### ISSUE TITLE
[Select]大数据量下选中某一项卡顿

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-vue#446]
### 重现链接
https://stackblitz.com/edit/angular-pzfq6c?file=src%2Fdemo.vue

### 重现步骤
选项中大改有 700 条数据；

### 期望结果
选中某项时不出现卡顿

### 实际结果
展开滚动无卡顿感觉；
选中某一项时有明显卡顿

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | Mac(15.x) |
| Node版本 | v16.13.1 |

**Comment by rengelyes** [comment]
选项5000个时，点击下拉框就卡死，有时浏览器还会crash
