### ISSUE TITLE
请问下，date-pick 点击清空按钮没有清空上一次的选中，如果把value=‘’ 也没有清空上一次的选中，是特性，还是bug？

### ISSUE THREAD

**Issue by delenzhang** [Tencent/tdesign-vue#448]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-z2p7cw?file=/src/demo.vue

### 重现步骤
点击清除，但是依然保留上一次的选择

### 期望结果
清空上一次的选择

### 实际结果
未清空上一次的选择

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | Vue2 |
| 系统、浏览器 | * |
| Node版本 |  |

**Comment by xiaosansiji** [comment]
是清空后，再次打开面板的时候数据又展示出来是吧？应该是 bug，我来看看

**Comment by xiaosansiji** [comment]
已在 0.36.0 版本中修复
