### ISSUE TITLE
固定表头为什么不采用和固定列的一样的做法使用css实现呢？

### ISSUE THREAD

**Issue by yangyanggege** [Tencent/tdesign-vue#452]
### 这个功能解决了什么问题
。

### 你建议的方案是什么？
。

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/365

这个 PR 里面，已经采用了一样的做法实现固定表头，只是一直没有合并（因为三个框架需要同步修改），预计最近两周内全部完整。
