### ISSUE TITLE
[form]带框的表单组件在表单校验失败时不变红

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#454]
### 重现链接
https://codesandbox.io/s/wai-kuang-bian-hong-yi-chang-wen-ti-y0fyrq

### 重现步骤
点击“提交”按钮即可复现

### 期望结果
select、input-number、date-picker、radio-group等带的外框的表单组件在表单校验失败时变红

### 实际结果
select、input-number、date-picker、radio-group等带的表单组件外框在表单校验失败时不变红

| Environment | Info |
|---|---|
| 相关版本 | 0.34.0 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | Mac(10.14.6) Chrome(98.0.4758.80) |
| Node版本 |  |

**Comment by YikaJ** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/8725110/156985021-162d6d86-1a57-4675-9f38-0d2693b8ecb0.png">

对标其他产品，确实有不少的边框状态没有显示的情况。
包含 (InputNumber, DatePicker, Select, TimePicker, TreeSelect, RadioButton, Textarea）

**Comment by YikaJ** [comment]
@uyarn 可以 closed 了
