### ISSUE TITLE
[menu] 子菜单多加会有滚动条。

### ISSUE THREAD

**Issue by lanniuniu** [Tencent/tdesign-vue#459]
### 重现链接
https://codesandbox.io/s/c5c06?file=/src/demo.vue

### 重现步骤
1、添加足够多的子菜单
2、折叠菜单
3、复现图片
<img width="1782" alt="wecom-temp-acc72d461b14ba3fbe6138fff941c3dd" src="https://user-images.githubusercontent.com/20572977/155489333-8146e5f7-c2ba-4599-b0a8-70e60a4ff4ff.png">

### 期望结果
popup框设置最大高度

### 实际结果
popup无限高度导致滚动条

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | lastest vue |
| 系统、浏览器 | lastest MAC OS chrome |
| Node版本 |  |

**Comment by LeeJim** [comment]
后面 menu 的 popup 全部都要使用 t-popup 来实现，改动略大，需要点时间
