### ISSUE TITLE
[t-select]下拉框默认选项未选中

### ISSUE THREAD

**Issue by colaiven** [Tencent/tdesign-vue#462]
### 重现链接
https://stackblitz.com/edit/angular-ahqop9?file=src%2Fdemo.vue

### 重现步骤
见图片
![image](https://user-images.githubusercontent.com/46585176/155674346-edfe840b-adcb-4459-b55c-44e5a5477323.png)

### 期望结果
下拉框默认选中

### 实际结果
下拉框未选中

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | Vue2.6 |
| 系统、浏览器 | Win10 chrome |
| Node版本 |  |

**Comment by uyarn** [comment]
thanks for ur report : ) 
系0.34升至0.35.0的Bug 已在0.35.1中修复 升级至0.35.1即可
