### ISSUE TITLE
多级表头添加固定列之后多级表头显示不完整，并且固定列不起作用

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#465]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-veglo0?file=/src/demo.vue

### 重现步骤
见codesandbox

### 期望结果
多级表头正常显示，固定列能正常工作。

### 实际结果
多级表头添加固定列之后多级表头显示不完整，并且固定列不起作用

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | Vue2.X |
| 系统、浏览器 | Chrome97 |
| Node版本 |  |

**Comment by chaishi** [comment]
可在先行版本 npm install tdesign-vue@0.36.0-alpha.1 中体验

**Comment by chaishi** [comment]
tdesign-vue@0.36.0-alpha.2 临时预览地址：https://preview-pr365-tdesign-vue.surge.sh/vue/components/table

**Comment by chaishi** [comment]
resolved in `v0.39.1`
