### ISSUE TITLE
[t-cascader]级联选择器动态改options为空数组不生效

### ISSUE THREAD

**Issue by imzhaojian** [Tencent/tdesign-vue#467]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-xylgl2?file=/src/demo.vue

### 重现步骤
点击test按钮，重置options为空数组，组件中的选择项还在

### 期望结果
选择项也为空

### 实际结果
组件中的选择项还在

| Environment | Info |
|---|---|
| 相关版本 | 0.31.0 |
| 框架版本 / 基础库版本 | Vue（2.6.11） |
| 系统、浏览器 | MacOS，Chrome |
| Node版本 |  |

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
