### ISSUE TITLE
大数据量下级联选择器卡顿（选择全国省市区）

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#477]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-bg16qy?file=/src/demo.vue:247-780

### 重现步骤
请查看sandbox链接

### 期望结果
在级联选择器上选择全国省市区，操作流畅。

### 实际结果
在级联选择器上选择全国省市区，操作卡顿。

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | Vue2.X |
| 系统、浏览器 | Chrome97 |
| Node版本 |  |

**Comment by chaishi** [comment]
resolved in 0.37.0
