### ISSUE TITLE
tree组件在大数据量下，收起展开卡顿

### ISSUE THREAD

**Issue by xiecz123** [Tencent/tdesign-vue#478]
### 这个功能解决了什么问题
tree组件在大数据量下，收起展开卡顿。[codesandbox 复现地址](https://codesandbox.io/s/da-shu-ju-shu-tdesign-i4k9cf?file=/src/demo.vue)

### 你建议的方案是什么？
添加虚拟列表属性，在大量数据时获得高性能表现。

**Comment by delenzhang** [comment]
非虚拟dom下，element使用嵌套结构略卡，但是可用，demo：https://codepen.io/ddcouples/pen/vYWvzLZ，tdesign的非虚拟dom，卡死不可用 ：https://codesandbox.io/s/da-shu-ju-shu-tdesign-i4k9cf?file=/src/demo.vue

**Comment by TabSpace** [comment]
我先调研下有没有平铺结构的优化方案，如果一时找不到，就考虑非虚拟滚动时使用嵌套结构。
