### ISSUE TITLE
[Select]选择框可创建新条目后，下拉框永远有一个空白选项

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#482]
### 重现链接
https://codesandbox.io/s/zml1cc?file=/src/demo.vue

### 重现步骤
在提供的官方demo实例中，点击select并输入123，点击123选项，然后再点击select

### 期望结果
在select内输入123，点击123选项，然后再点击select，不出现常驻的空白选项

### 实际结果
在select内输入123，点击123选项，然后再点击select，即可看到常驻的空白选项

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | * |
| 系统、浏览器 | * |
| Node版本 |  |

**Comment by xiaosansiji** [comment]
已在 0.36.0 版本中修复
