### ISSUE TITLE
【Table】表格列宽可由用户拖动定义

### ISSUE THREAD

**Issue by sinbadmaster** [Tencent/tdesign-vue#489]
### 这个功能解决了什么问题
用户使用过程中期望其可以自己像使用Excel一样拖动调整某一列的列宽

### 你建议的方案是什么？
开启可拖动定义列宽后，用户鼠标靠近列分界边框线时出现可拖动标识，拖动可自定义列宽

**Comment by cong-min** [comment]
+1

**Comment by chaishi** [comment]
CR 中

**Comment by xiaosansiji** [comment]
已在 0.41.1 版本中实现
