### ISSUE TITLE
[select]下拉框组件：自定义下拉数据渲染，数组改变时<t-option>未动态更新

### ISSUE THREAD

**Issue by hy212** [Tencent/tdesign-vue#490]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-9gkswx?file=/src/demo.vue

### 重现步骤
数组渲染<t-option>，创建下拉数据，下拉列表数据不对

### 期望结果
下拉数据动态更新

### 实际结果
下拉列表数据不对

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | Chrome(98.0.4758.109) |
| Node版本 |  |

**Comment by YikaJ** [comment]
https://github.com/Tencent/tdesign-vue/issues/495

**Comment by chaishi** [comment]
resolved in new version
