### ISSUE TITLE
[tabs] 可滑动的选项卡后面选项的下划线没有对齐

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#496]
### 重现链接
https://codesandbox.io/s/y33cz1?file=/src/demo.vue
<img width="169" alt="image" src="https://user-images.githubusercontent.com/16223845/156865105-969dfe86-35a0-4d8b-967d-d26d0f5ab20d.png">

### 重现步骤
直接在官网查看可滑动的选项卡

### 期望结果
下划线和文本内容能居中对齐

### 实际结果
下划线和文本内容没有居中对齐

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | vue2.x |
| 系统、浏览器 | Chrome(99.0.4844.51) |
| Node版本 |  |

**Comment by start940315** [comment]
![截屏2022-03-07 下午2 31 50](https://user-images.githubusercontent.com/4272575/156980077-775845db-dda5-4d58-acf6-f0612ab9df34.png)
你好，我这里没有复现，请问你是在什么情况下出现这个问题的？

**Comment by huangpiqiao** [comment]
可查看官网地址：https://tdesign.tencent.com/vue/components/tabs
