### ISSUE TITLE
[datepicker]点击面板顶部年份、月份按钮导致面板隐藏

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#500]
### 重现链接
https://codesandbox.io/s/bh5g26?file=/src/demo.vue

### 重现步骤
点击date-picker组件，弹出面板，点击面板顶部月份或者年份按钮

### 期望结果
点击date-picker组件，弹出面板，点击面板顶部月份或者年份按钮，面板不隐藏

### 实际结果
点击date-picker组件，弹出面板，点击面板顶部月份或者年份按钮，面板被隐藏

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | * |
| 系统、浏览器 | * |
| Node版本 |  |

**Comment by uyarn** [comment]
Duplicate of https://github.com/Tencent/tdesign-vue/issues/443
