### ISSUE TITLE
[Drawer]destroyOnClose属性设为true，抽屉呼出时console报错"TypeError: Cannot read properties of undefined (reading 'focus')"

### ISSUE THREAD

**Issue by dreamsqin** [Tencent/tdesign-vue#504]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-jw55ky?file=/src/demo.vue

### 重现步骤
destroyOnClose属性设为true，打开抽屉

### 期望结果
console不报错

### 实际结果
console报错"TypeError: Cannot read properties of undefined (reading 'focus')"

### 补充说明
visible的watcher中应做判断后调用focus：应修改为(this.$refs.drawerContainer as HTMLDivElement)?.focus?.();
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/15522703/156918666-3fb908cc-421d-418c-ac0b-8e4f8b060059.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | Vue（2.6.14） |
| 系统、浏览器 | MacOS（10.15.7）、Chrome（98.0.4758.80） |
| Node版本 | 12.22.2 |

**Comment by uyarn** [comment]
I see

**Comment by xiaosansiji** [comment]
已在 0.36.0 版本中修复
