### ISSUE TITLE
table组件自定义表头

### ISSUE THREAD

**Issue by kavizzz** [Tencent/tdesign-vue#516]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-w4kq78?file=/src/demo.vue

### 重现步骤
我的表头是手动添加的，我希望每次添加之后，表头中只能是一个文本，不能自定义模板

### 期望结果
我希望表头能根据我的数据渲染模板，现有的文档方法中没找到相关说明，无论是插槽还是title函数，还是render函数，都不能实现，如果有方法，希望指教一下，谢谢

### 实际结果
可看demo

| Environment | Info |
|---|---|
| 相关版本 | 0.36.0 |
| 框架版本 / 基础库版本 | Vue2.0 |
| 系统、浏览器 | MacOS 12.2.1 |
| Node版本 | 12.18.3 |

**Comment by chaishi** [comment]
示例代码：https://codesandbox.io/s/tdesign-vue-demo-forked-eqz31c?file=/src/demo.vue
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/11605702/157029710-2dd8b91f-361f-44aa-8489-c76bcf90567d.png">
