### ISSUE TITLE
在抽屉组件中使用上传组件，点击上传成功的图片预览时，图片相对抽屉居中并非相对页面居中

### ISSUE THREAD

**Issue by Mumuxiz** [Tencent/tdesign-vue#518]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-rcnffp?file=/src/demo.vue

### 重现步骤
在抽屉组件中使用上传组件，点击上传成功的图片预览时，图片相对抽屉居中并非相对页面居中

### 期望结果
上传图片预览相对页面居中,能改成可配置更好

### 实际结果
上传图片预览相对抽屉组件居中

| Environment | Info |
|---|---|
| 相关版本 | 0.36.0 |
| 框架版本 / 基础库版本 | Vue(2.6.11) |
| 系统、浏览器 | Chrome 96.0.4664.45 |
| Node版本 |  |

**Comment by uyarn** [comment]
没有相对页面居中吧？你把size改成200px之类的试试？

**Comment by chaishi** [comment]
Drawer 场景，点击图片预览是否为全屏预览，需求无非 绝对一致

我们后期处理，支持一下 Dialog 在某一个元素内部弹出，就可以满足 全屏或者半屏的需求，关注 issue： https://github.com/Tencent/tdesign-vue/issues/633
