### ISSUE TITLE
[Table] 虚拟滚动出现列错位

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#524]
### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-p9el5n?file=/src/demo.vue

### 重现步骤
见重现链接

### 期望结果
滚动时不出现列错位情况

### 实际结果
滚动时出现列错位情况

| Environment | Info |
|---|---|
| 相关版本 | 0.37.0-alhpa.2 |
| 框架版本 / 基础库版本 | Vue2 |
| 系统、浏览器 | Macos\Chrome96.0.4664.110 |
| Node版本 |  |

**Comment by chaishi** [comment]
已处理，试试 0.37.0-alhpa.3

**Comment by chaishi** [comment]
0.37.0-alhpa.3 需要去除一下 右侧边框，以保证绝对对齐

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/11605702/157233225-f66f98d4-51a2-4d98-8bf3-ba12488a254c.png">

**Comment by chaishi** [comment]
resolved in `v0.39.1`
