### ISSUE TITLE
[Form\Select]选择器组件错误状态下没标红框

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#525]
### 重现链接
https://codesandbox.io/s/wai-kuang-bian-hong-yi-chang-wen-ti-forked-c5if84?file=/src/demo.vue

### 重现步骤
Select等校验未通过时应出现红框

### 期望结果
Select等校验未通过时应出现红框

### 实际结果
Select等校验未通过时未出现红框

| Environment | Info |
|---|---|
| 相关版本 | 0.37.0-alhpa.2 |
| 框架版本 / 基础库版本 | Vue2 |
| 系统、浏览器 | MacOs/Chrome97 |
| Node版本 |  |

**Comment by scope9Ri** [comment]
补充：常规状态下的边框也不见了。

**Comment by uyarn** [comment]
已在0.37.2中修复
