### ISSUE TITLE
Error: IE dom.animate doesn’t support property or method animate

### ISSUE THREAD

**Issue by brianzhang** [Tencent/tdesign-vue#535]
![image](https://user-images.githubusercontent.com/766999/158011443-0c3f4237-58d5-4165-93e4-93671d17920f.png)

https://github.com/Tencent/tdesign-vue/blob/cd370a7bddc3ff5a01591e4218de7509545a82e6/src/message/animation.ts#L16

**Comment by xiaosansiji** [comment]
已在 0.37.0 版本中修复
