### ISSUE TITLE
[TreeSelect] treeSelect异步加载的时候，选中后，input框显示的是value的值不是label的值

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#537]
### tdesign-vue 版本

0.36.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-52hx8q?file=/src/demo.vue

### 重现步骤

在示例中，
1.  选择 一.1.1。 
2. 选中后， input框中显示的是1.1.1

### 期望结果

应该显示label值: 一.1.1

### 实际结果

实际显示了value值

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.2.2

### 补充说明

比较了一下版本。0.34.0版本是对的。0.35.0之后的版本就变成value了

**Comment by xiaosansiji** [comment]
已在 0.37.2 版本中修复
