### ISSUE TITLE
[table] 右侧固定的列超过一列后，缩放屏幕，固定列的right 坐标错误，导致覆盖其他列，出现了空白列

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#540]
### tdesign-vue 版本

0.37.0-alpha.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-2h4ts7?file=/src/demo.vue

### 重现步骤

右侧固定两列，缩放页面宽度

### 期望结果

固定列位置正常

### 实际结果

固定列定位坐标错误

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by wwervin72** [comment]
![image](https://user-images.githubusercontent.com/17847729/158023197-11727c0c-b4bb-44d6-be09-570676ff50f4.png)

**Comment by chaishi** [comment]
问题定位：窗口变动，为更新固定状态

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/365/commits/796d6ae5e9c725d52cd5c3d0ab4f96edea381790

to be published

**Comment by chaishi** [comment]
resolved in `v0.39.1`
