### ISSUE TITLE
[message] 需要一个onClose 事件

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#544]
### 这个功能解决了什么问题

需要有一个 onClose 事件，用来处理信息窗体在关闭的时候应该做的一些事情， duration-end 在手动关闭或者是代码里面执行 close, closeAll 方法时，不会执行

### 你建议的方案是什么

在关闭的时候emit一个 close 事件

**Comment by chaishi** [comment]
**看代码，是有抛出关闭事件的。看不明白 issue 想要表达的含义**

<img width="672" alt="image" src="https://user-images.githubusercontent.com/11605702/164374850-908bc6ab-3e83-4e47-ae2e-dc0ce70b49bc.png">
