### ISSUE TITLE
[table] ellipsis 属性无效

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#546]
### tdesign-vue 版本

0.37.0-alpha.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-0si54r?file=/src/demo.vue

### 期望结果

能够正常的超出隐藏出现省略号

### 实际结果

基础表格和多级表头表格的 ellipsis 属性都无效，超出宽度后换行了。

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by chaishi** [comment]
#### Demo 里面没有复现
<img width="842" alt="image" src="https://user-images.githubusercontent.com/11605702/158184721-564a6380-7fb0-457b-8471-e584a20a9e25.png">

**Comment by chaishi** [comment]
resolved in `v0.39.1`
