### ISSUE TITLE
[table] 期望无数据时 empty 内容不应滚动，仅滚动表头即可

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#547]
### 这个功能解决了什么问题

当表格很宽的时候，出现了水平滚动条，空数据empty提示部分在水平方向居中，然后超出了可以范围了，需要滚动才能看到。所以期望空数据提示部分不会移动

### 你建议的方案是什么

期望空数据提示部分不能滚动，仅仅能滚动表头部分

**Comment by chaishi** [comment]
resolved in `v0.39.1`
