### ISSUE TITLE
【BUG】【table】当列固定的时候，标题看起来为啥呈现灰色了？

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#55]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

![image](https://user-images.githubusercontent.com/15682051/147071733-ba8ca0a0-9e34-4509-b3eb-dfd7b201f257.png)

**Comment by pattybaby110** [comment]
标题现在都是灰色，看起来截图有点有效拦截有点模糊 是这个问题吗？

**Comment by sampsonliu** [comment]
是的，为啥固定列就变模糊了，看着很难受

**Comment by chaishi** [comment]
是不是因为我们没有加粗的原因？

**Comment by LeeJim** [comment]
刚确认了下，在 MacOS 是正常的，估计是 windows 下才会复现。
我再持续跟进处理下。

**Comment by Wen1kang** [comment]
请问下使用的显示器是4k的，但是这里表格文字却是模糊么？刚在Windows复现不了问题

**Comment by Wen1kang** [comment]
@sampsonliu 请问下是因为表头的文字较灰，导致视觉效果模糊的问题么？从设计的统一来考虑，因为表头使用的是第三级批示文字颜色，如果使用的二级文字颜色的话，会造成基础表格表头与内容色阶无法拉开的问题。麻烦看看修改为2级文字颜色是否可以接受，如果可以的话建议业务侧针对表格颜色快速修改单独引用下token:text-color-secondary。
![image](https://user-images.githubusercontent.com/89069385/148741179-5b0e3fb4-a576-470d-a571-cd73af870831.png)

我们也会持续跟进这个问题，因为涉及到全局的颜色层级问题，我们下个组件设计优化版本进行确认下

**Comment by Wen1kang** [comment]
@sampsonliu 嗯呢，4K转到2K肯定会模糊的，并且Windows的系统字体是比较扁，字重较轻，但如果使用600的font weight又会太粗，希望微软快点把中文系统字体改了~
那我把这里的issue关闭了哦
