### ISSUE TITLE
[TreeSelect, Tree] filter 内容为空时导致Tree无法折叠收起

### ISSUE THREAD

**Issue by brianzhang** [Tencent/tdesign-vue#550]
### tdesign-vue 版本

0.37

### 重现链接

https://codesandbox.io/s/2cc4mc?file=/src/demo.vue

### 重现步骤

https://user-images.githubusercontent.com/766999/158167974-4594ab54-ad28-409e-a55b-f6b4c48b96cc.mov

### 实际结果

内容为空或未设置filter，树icon点击无反应

**Comment by xiaosansiji** [comment]
已在 0.39.1 版本中修复
