### ISSUE TITLE
[Table] 0.37.0-alpha7版本 lastFullRow 属性失效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#555]
### tdesign-vue 版本

0.37.0-alpha7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-x9q8nc?file=/src/demo.vue

### 重现步骤

在0.37.0-alpha7版本中 lastFullRow 属性失效

### 期望结果

和0.36.0版本

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.2.2

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
