### ISSUE TITLE
 下拉框dom结构能否放在组件内方便写样式，而非全局？

### ISSUE THREAD

**Issue by ericjiajia** [Tencent/tdesign-vue#557]
### tdesign-vue 版本

0.36.0

### 重现链接

https://codesandbox.io/s/teiwzx?file=/src/demo.vue

### 重现步骤

1. CodeSandbox可直接复现，下拉箭头的图标并未生效
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/26456192/158333610-eb643741-68f3-4d3b-84f9-1ed7db06e282.png">

2.是否方便将t-popup组件放在组件内，而非全局dom中，导致样式需要在全局中处理很不方便
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/26456192/158334045-16ec12fd-dedf-4947-bac3-e737815adbd8.png">

**Comment by uyarn** [comment]
问题1 输入框0.37+ 的版本已经修复了。
问题2 @ikeq 看看~

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-tjfe35

**Comment by ikeq** [comment]
vue2 由于只能渲染 1 个根节点，为了去掉额外包裹元素，弹层注定是渲染在额外的 node tree，目前的行为和有相同特性的其他开源组件库完全一致。

vue3 版本的 tdesign-vue-next 后面可以做到。

**Comment by chaishi** [comment]
**Popup 有一个 API，叫 `attach`，可以自由调整浮层挂载的元素，指定 Popup 浮层挂载到任意元素**

<img width="902" alt="image" src="https://user-images.githubusercontent.com/11605702/164374358-6005bb53-9ae2-4e21-80e1-95743851d1d4.png">
