### ISSUE TITLE
[TreeSelect] 无法满足仅允许选中叶子节点

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#558]
### 这个功能解决了什么问题

在某些场景下TreeSelect仅允许选中子节点，当前API控制粒度无法满足该场景。

### 你建议的方案是什么

允许开发者控制各节点是否选中。当节点不允许选中时，点击该节点也不应收起pupup

**Comment by chaishi** [comment]
使用 `Tree.valueMode`，即 `treeProps={ valueMode }` 控制选中项的值

如果无法控制，请提供复现问题的 Demo

**Comment by scope9Ri** [comment]
tree属性透传无法实现该需求，https://codesandbox.io/s/tdesign-vue-demo-forked-o9wklr
实际期望是控制当仅允许子节点选中时的交互

**Comment by Inori-Lover** [comment]
> 具体什么交互，需求描述详细些，不太明白

目前treeSelect多选情况下仍然点击一次后就收起；官网example可复现

**Comment by scope9Ri** [comment]
> 

业务方使用时存在一种特殊情况：仅允许叶子结点被点击选中，而非叶子结点不允许选中。当前不论是叶子结点还是非叶子节点选中时popup都会被收起。我们期望在这种情况下，点击非叶子结点时，不触发change事件，popup不收起。

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
