### ISSUE TITLE
[input-number] 输入的小数位数超过2位时，组件会把值给改了

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#559]
### tdesign-vue 版本

0.37.0-alpha.8

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-gifiun?file=/src/demo.vue

### 重现步骤

输入超过2位小数的小数值，然后让input-number 失去焦点

### 期望结果

值是正常的

### 实际结果

值发生了变化

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by xiaosansiji** [comment]
已在 0.37.2 版本中修复
