### ISSUE TITLE
[Dropdown] 点击后下方的popup菜单消失

### ISSUE THREAD

**Issue by ericjiajia** [Tencent/tdesign-vue#565]
### tdesign-vue 版本

0.36.0

### 重现链接

https://codesandbox.io/s/w4wjn6?file=/src/demo.vue

### 重现步骤

1. 直接点击按钮，下方的popup菜单消失
2. popup菜单目前修改样式必须在全局修改，无法在组件内修改，看是否考虑把对应组件的popup挪到组件内去，而不是插入全局dom中

### 期望结果

在触发状态为hover时，期待点击按钮不消失

**Comment by uyarn** [comment]
cc @ikeq

**Comment by xiaosansiji** [comment]
已在 0.37.2 版本中修复
