### ISSUE TITLE
[Progress 进度条] 值为10文字描述缺失

### ISSUE THREAD

**Issue by zhangningself** [Tencent/tdesign-vue#569]
### tdesign-vue 版本

0.37.0

### 重现步骤

![f124bd0bb756ea3db2786945202238b](https://user-images.githubusercontent.com/26316530/158502322-5115cdb5-7811-424b-9cbc-a350be1e0dfd.png)
![dbc975902dd8a70bc3fbb11dc588e5b](https://user-images.githubusercontent.com/26316530/158502329-6a0610b5-50f6-4078-bffa-6891486b5c59.png)

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
