### ISSUE TITLE
[Table] 虚拟滚动表格在异步获取数据时报错

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#570]
### tdesign-vue 版本

0.37.0-alpha.9

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-o2r67q?file=/src/demo.vue

### 重现步骤

开启虚拟滚动，延迟加载数据，控制台报错

### 期望结果

虚拟滚动正确渲染数据，不报错

### 实际结果

组件内部报错，无法渲染

### 框架版本

Vue2

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
