### ISSUE TITLE
[Tree] `@click` 会执行两次

### ISSUE THREAD

**Issue by ikeq** [Tencent/tdesign-vue#571]
### tdesign-vue 版本

0.37.0

### 重现链接

https://tdesign.tencent.com/vue/components/tree

### 重现步骤

<img width="884" alt="image" src="https://user-images.githubusercontent.com/9206414/158518445-b887054a-2744-473e-9b31-d513c5421e55.png">

**Comment by chaishi** [comment]
resolved in new version
