### ISSUE TITLE
[Table] Table右侧固定两列， 倒数第二列依旧滚动

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#574]
### tdesign-vue 版本

0.37.0-alpha9

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-9x34oc?file=/src/demo.vue

### 重现步骤

table配置中配置最后两列fixed: 'right'.
横行滚动时，倒数第二列没有固定住，依旧滚动

### 期望结果

期望和0.36.0版本展示效果一样。
后两列都能固定住

### 实际结果

横行滚动时，倒数第二列没有固定住，依旧滚动

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
