### ISSUE TITLE
[Select] focus触发机制有问题

### ISSUE THREAD

**Issue by scope9Ri** [Tencent/tdesign-vue#577]
### tdesign-vue 版本

0.37.0-alpha.9

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-5uqdxn

### 重现步骤

无选中项时点击Select 没有触发focus事件

### 框架版本

Vue2

**Comment by YikaJ** [comment]
![image](https://user-images.githubusercontent.com/8725110/158729079-499ca8ee-93bf-46bf-8adf-0c0df67253aa.png)

readonly 导致 focus 事件被提前 return

**Comment by YikaJ** [comment]
#580 与这个其实是同一个问题

**Comment by YikaJ** [comment]
Select 下时机不正确，会先触发内部的 input focus，但是 select 的 visible 仍然为 false。导致最后 focus

**Comment by uyarn** [comment]
已在0.37.2中修复。
