### ISSUE TITLE
[Input] Input readonly 下不再触发 focus 事件

### ISSUE THREAD

**Issue by YikaJ** [Tencent/tdesign-vue#580]
### tdesign-vue 版本

0.38.0-alpha.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-g4e9d0?file=/src/demo.vue

### 重现步骤

点击 TInput 无事件返回，点击原生 input 有事件返回。

0.37 版本是正常的。

### 期望结果

t-input 即使是 readonly 下，依然需要返回 focus 事件，与原生 input 规则保持一致。

### 实际结果

无 focus 事件

### 框架版本

Vue2

**Comment by xiaosansiji** [comment]
已在 0.37.2 版本中修复
