### ISSUE TITLE
[Table] 固定列时，未设置 column witdh 该列会不显示

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-vue#582]
### tdesign-vue 版本

0.37.0

### 重现链接

https://stackblitz.com/edit/angular-vb8tzx?file=src%2Fdemo.vue

### 重现步骤

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7600149/158734820-73c82b93-25b7-41d1-aba2-2ad41bbc2f23.png">
某非固定列未设置 width 属性

### 期望结果

改列能够正常显示

### 实际结果

改列未下你

**Comment by chaishi** [comment]
这不是组件的特别表现，或者组件加了什么特别的属性，是原生 HTML 标签 <table> 的表现：`table-layout: fixed` 模式，当设置过列宽的宽度加起来超过 table 元素时，没有设置宽度的元素就会变成 0。

在考虑在宽度超出的时机加上默认宽度 `100`，而且只能在设置宽度超出 table 元素时添加默认宽度 `100`，但是这种方式属于 Hack 代码，要多出一堆的判断，不能因为这一种使用不当的场景给所有场景都加上默认宽度 `100`，默认宽度 `100` 会失去内容宽度自适应的特性。

暂时不计划针对这种使用不当的情况在组件内部做特殊处理。

**解决方案**
方案一：`table-layout: fixed` 模式，如果设置过宽度的列宽加起来，超过了 table 元素宽度，请给每一列都加上列宽。就一行代码，很简单，并不会增加开发成本。

方案二：如果希望宽度随内容自适应（列宽加起来超过 table 元素宽度，永远不可能宽度随内容自适应），请设置模式为 `table-layout: auto`，并设置 `tableContentWidth` 来加宽 table 元素宽度。

**只有当每一列设置的列宽总和小于 table 元素的宽度，才可能实现某些列宽随内容自适应**

<img width="936" alt="image" src="https://user-images.githubusercontent.com/11605702/159159137-3270ef7e-8d2d-4145-b492-44fb987130d1.png">
