### ISSUE TITLE
[Slider] `label` 类型为函数时，新增参数 value 和 position: 'start' | 'end'

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#585]
### 这个功能解决了什么问题

自定义滑块提示

### 你建议的方案是什么

1. `label` 类型为函数时，新增参数 `value` 和 `position: 'start' | 'end'`
2. 同名插槽 `label` 也需要新增参数 `value` 和 `position`

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中实现
