### ISSUE TITLE
[Menu] 0.38.0-alpha.1版本 windows下出现横行滚动条

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#586]
### tdesign-vue 版本

0.38.0-alpha1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-c0oq43?file=/src/demo.vue

### 重现步骤

查看codesandbox链接即可查看效果

mac下显示正常，没有滚动条
windows下edge和firefox显示异常，出现横行滚动条

### 期望结果

期望和mac下一致

### 实际结果

windows下edge和firefox显示异常，出现横行滚动条

### 框架版本

Vue(2.6.0)

### 浏览器版本

Edge(99.0.1150.39)

### 系统版本

windows

### Node版本

12.22.0

### 补充说明

mac下：
chrome
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13745660/158777846-fb9c8e40-b1f0-4316-a2ca-56cd07f629ed.png">
windows下：
edge:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/13745660/158778072-6f0b1061-9a9b-4f8b-846d-ca71516cc2ad.png">
firefox:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/13745660/158778274-9aee73e1-86f3-4c40-8c7a-6522aee36ad8.png">

**Comment by LeeJim** [comment]
已修复，关联 PR：https://github.com/Tencent/tdesign-common/pull/312/files
