### ISSUE TITLE
[Menu] 多层收纳导航和收缩的侧边栏导航无法弹出浮框

### ISSUE THREAD

**Issue by winfcloud** [Tencent/tdesign-vue#604]
### tdesign-vue 版本

0.37.2

### 重现链接

https://codesandbox.io/s/ezpzzf?file=/src/demo.vue

### 重现步骤

提供的是官网的demo，在官网就能发现问题
顶部收纳菜单和侧边栏收起菜单，鼠标移入无法显示

### 期望结果

收缩菜单可以正常展示

### 实际结果

收缩菜单被overflow隐藏了

### 框架版本

Vue(^2.6.11)

### 浏览器版本

Chrome(99.0.4844.74)

### 补充说明

调试看了一下
因为 .t-menu{ overflow: auto hidden } 被隐藏掉了
去看了下 [tdesign-vue-starter](https://github.com/Tencent/tdesign-vue-starter)
在使用的版本是"tdesign-vue": "~0.35.1" ，没有此问题
出问题的版本是0.37.2，不确定开发者是因为什么功能修改把这个css属性加进来的

**Comment by metowolf** [comment]
https://github.com/Tencent/tdesign-common/commit/8564e147b45b1853a6978bbdf610d934479dd596

**Comment by uyarn** [comment]
已在0.38.0修复。
