### ISSUE TITLE
[table] 树形结构的表格无法自定义首列

### ISSUE THREAD

**Issue by LShuai87** [Tencent/tdesign-vue#605]
### tdesign-vue 版本

0.37.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-o9bbu4

### 重现步骤

tree table无法通过插槽自定义首列单元格

### 期望结果

tree table的首列单元格可以通过插槽自定义

### 实际结果

tree table的首列单元格无法通过插槽自定义

### 框架版本

Vue2

**Comment by chaishi** [comment]
收到，尽快处理

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/365

to be published, 请耐心等待新版本

**Comment by chaishi** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/11605702/159205327-8ba5085a-c0ae-43a9-8ea8-e30373259207.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/11605702/159205282-2421e7af-5b95-4af8-aed9-f50a55c72d0d.png">

**Comment by chaishi** [comment]
resolved in 0.39.1
