### ISSUE TITLE
[table] row-db-click 事件不触发

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#606]
### tdesign-vue 版本

0.38.0-alpha.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-sir0yb?file=/src/demo.vue

### 重现步骤

双击表格行

### 期望结果

双击表格行，正常触发事件绑定函数

### 实际结果

不触发事件绑定函数

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by chaishi** [comment]
请更为使用 `@row-dblclick` 或者 `:onRowDblclick`

`row-db-click` 已废弃
