### ISSUE TITLE
[table] 有固定列的表格，loading 的遮罩层不能全部覆盖 table

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#609]
### tdesign-vue 版本

0.38.0-alpha.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-xrgv7u?file=/src/demo.vue

### 期望结果

loading 的遮罩层能全部覆盖表格区域

### 实际结果

loading 的遮罩层不能全部覆盖 table

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by chaishi** [comment]
已修复，待发布

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
