### ISSUE TITLE
[Upload] FileFlow事件回调异常

### ISSUE THREAD

**Issue by brianzhang** [Tencent/tdesign-vue#610]
### tdesign-vue 版本

0.37.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-dfd4rw?file=/src/demo.vue

### 重现步骤

```vue
<t-upload
      v-model="files"
      action="https://service-bv448zsw-1257786608.gz.apigw.tencentcs.com/api/upload-demo"
      placeholder="支持批量上传文件，文件格式不限，最多只能上传 10 份文件"
      theme="file-flow"
      multiple
      :auto-upload="false"
      :max="10"
      @remove="removeHanle"
      @selectChange="selectChangeHanle"
      @change="changeHanle"
    ></t-upload>
```

> t-upload 组件设置`file-flow` 添加remove， selectChange, change 事件回调绑定

-------
官方文档回调方法说明：
<img width="874" alt="image" src="https://user-images.githubusercontent.com/766999/159214521-ac7030bf-dd87-4d2f-80a7-6b936b9da3d3.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/766999/159214544-8c66f84e-b567-4db3-9881-6b2e5097bb64.png">

### 实际结果

remove 回调未执行，selectChange未执行， change回调执行时机不对（点击上传才执行）

### 框架版本

vue 2.0

### 浏览器版本

 99.0.4844.74（正式版本） (x86_64)

### 系统版本

macos

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中修复
