### ISSUE TITLE
[Dialog、Drawer] visible默认为true时body没有添加t-dialog--lock、t-drawer--lock类

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-vue#612]
### tdesign-vue 版本

0.37.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-m5gpgg

### 重现步骤

dialog示例，drawer同理
```
<template>
  <dialog :visible="visible">
  </dialog>
</template>

<script>
export default {
  data() {
    return {
      visible: true
    };
  },
};
</script>
```

### 期望结果

body中能够出现对应的lock类（t-dialog--lock、t-drawer--lock）

### 实际结果

body没有出现对应的lock类（t-dialog--lock、t-drawer--lock）

**Comment by chaishi** [comment]
@luisma 处理中

**Comment by xiaosansiji** [comment]
已在 0.41.1 版本中修复
