### ISSUE TITLE
[table] table在tab-panel包裹情况下，固定列被遮盖

### ISSUE THREAD

**Issue by Zwow** [Tencent/tdesign-vue#613]
### tdesign-vue 版本

0.38.0-alpha.1

### 重现链接

https://codesandbox.io/s/tabjie-he-tabledao-zhi-gu-ding-lie-ding-wei-bu-dui-tgz6gv?file=/src/demo.vue

### 重现步骤

点击"缺陷例子"的tab切换，可见“是否必传”一列定位错误而被遮盖

### 期望结果

点击"缺陷例子"的tab切换，“是否必传”一列不被遮盖

### 实际结果

点击"缺陷例子"的tab切换，可见“是否必传”一列定位错误而被遮盖

### 补充说明

排查时发现是在tab-panel设置destroyOnHide为false时，才出现table固定列被遮盖的情况

**Comment by chaishi** [comment]
resolved in 0.38.0-alpha.2
