### ISSUE TITLE
[Table] 带边框，分页功能的表格设置高度后border样式异常

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#614]
### tdesign-vue 版本

0.38.0-alpha1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-qw1y5r?file=/src/demo.vue

### 重现步骤

打开CodeSandbox链接，
当设置了border, pagination, height值设置多于内容时， border样式异常，bottom少了border

### 期望结果

最后一个数据的bottom有border

### 实际结果

最后一个数据的bottom少了border

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
示例代码使用不当。

如果想要表格高度自适应，请使用 `max-height` 设置高度，而非固定的 `height`。
