### ISSUE TITLE
[date-picker] 0.38.0-alpha1版本clearable不生效

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#616]
### tdesign-vue 版本

0.38.0-alpha1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-j304zw?file=/src/main.js/src/demo.vue

### 重现步骤

codesandbox链接， 设置了clearable， 选中时间后，没有清除icon

### 期望结果

0.37.2版本中效果

### 实际结果

没有显示清除icon

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
