### ISSUE TITLE
[tree-select] tree-select选择节点后，第二次点击选择同一个节点清空了已选

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#617]
### tdesign-vue 版本

0.38.0-alpha1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-vug69u?file=/src/demo.vue

### 重现步骤

tree-select选择节点后，第二次点击选择同一个节点清空了已选：
1. 选中广东省
2. 目前select框中显示广东省
3. 选择广东省
4. select框中清空了已选

### 期望结果

期望在第二次点击选择同一个节点，不会清空了已选

### 实际结果

第二次点击选择同一个节点清空了已选

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by YikaJ** [comment]
该 Issue 提到的就是， TreeSelect 组件与我们常见的 Select 组件的交互行为不符

**Comment by xiaosansiji** [comment]
已在 0.39.1 版本中修复
