### ISSUE TITLE
[upload] cancel-upload 事件不触发

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#618]
### tdesign-vue 版本

0.38.0-alpha.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-uc3irz?file=/src/demo.vue

### 重现步骤

点击取消上传按钮

### 期望结果

触发 cancel-upload 事件，弹出 123 的弹出框

### 实际结果

点击按钮，没有反应

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by uyarn** [comment]
0.40.0已修复
