### ISSUE TITLE
[t-cascader]级联选择器中的value为number类型时无法回显

### ISSUE THREAD

**Issue by Mumuxiz** [Tencent/tdesign-vue#619]
### tdesign-vue 版本

0.37.2

### 重现链接

https://tdesign.tencent.com/vue/components/cascader?tab=demo

### 重现步骤

将options中的value值改为number类型时无法回显

### 期望结果

能回显number类型

### 框架版本

Vue2.6.11

### 浏览器版本

Chrome96

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
