### ISSUE TITLE
[t-input-number] input框默认宽度过短

### ISSUE THREAD

**Issue by lanniuniu** [Tencent/tdesign-vue#623]
### tdesign-vue 版本

0.37.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-zx7snm

### 重现步骤

当t-input-number 值为undefined时，placeholder显示不全。
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/20572977/159662672-835e4336-70ce-4f89-be58-827db0a35529.png">

### 期望结果

调整默认宽度，至少能容下3个字。

**Comment by xiaosansiji** [comment]
默认宽度 120 确实短了一点，可以考虑下个迭代里调整下，你可以先用下 `autoWidth` 属性，官网最后的例子，自适应内容宽度
`<t-input-number v-model="value" :min="0" :autoWidth="true"></t-input-number>`
<img width="251" alt="image" src="https://user-images.githubusercontent.com/7600149/159830858-53a3f81f-ebe9-4f20-8ecf-9ffb0ace158c.png">

**Comment by xiaosansiji** [comment]
已在 0.38.0 版本中修复
