### ISSUE TITLE
[Bug?] [Table] table-header 并不存在 columnsProp，但是传了值

### ISSUE THREAD

**Issue by backrunner** [Tencent/tdesign-vue#63]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Latest Chrome stable, mac os

复现地址：https://tdesign.tencent.com/vue/components/table?tab=demo

**Describe the bug**

偶然注意到一个问题，table 组件的 thead 标签里有找不到对应 prop 的绑定。
![image](https://user-images.githubusercontent.com/12205593/147233669-b1d93ebe-542b-4cb3-8228-70cf47dd95f0.png)

翻查代码发现 `src/table/base-table/index.tsx` 中有给 `TableHeader` 绑定相关值，
![image](https://user-images.githubusercontent.com/12205593/147233717-04f4be58-2026-4848-a773-a867e25a98b7.png)

但是 `table-header` 里实际上并没有这个prop（路径： `src/table/base-table/table-header.tsx`）。

![image](https://user-images.githubusercontent.com/12205593/147233792-dd784e6d-fb83-4474-a435-4f42d34e3a43.png)

这里是编码失误，还是 `columnsProp` 在 `table-header` 中是有用途的？

**Comment by chaishi** [comment]
处理 PR：https://github.com/Tencent/tdesign-vue/pull/80

**Comment by chaishi** [comment]
PR 已合并，待发布

**Comment by chaishi** [comment]
published in v0.32.0

**Comment by uyarn** [comment]
fixed in 0.33
