### ISSUE TITLE
[Select] 多选的时候，行数和光标位置不太美观

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-vue#630]
### tdesign-vue 版本

0.37.0

### 重现链接

https://tdesign.woa.com/vue/components/select#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

![image](https://user-images.githubusercontent.com/5036903/159888322-e07892b6-7e29-4a84-a6dc-94565e5b125b.png)

### 期望结果

![image](https://user-images.githubusercontent.com/5036903/159888371-697c7e20-feb6-4fb8-9046-b39ff5c9d44b.png)

**Comment by uyarn** [comment]
fixed
