### ISSUE TITLE
[TreeSelect] 数据展示异常

### ISSUE THREAD

**Issue by tanshamao** [Tencent/tdesign-vue#635]
### tdesign-vue 版本

0.37.2

### 重现链接

https://0_37_2-tdesign-vue.surge.sh/vue/components/tree-select?tab=demo

### 重现步骤

当输入一个搜索条件，点击其他区域。再点击树形组件，组件还是保留之前的搜索结果。

### 期望结果

点击其他区域再点击树形组件时，不需要保留上次搜索结果。如果想保留结果的话，也把上次的搜索条件恢复到输入框中

### 框架版本

@vue/cli 4.5.15

### 浏览器版本

98.0.4758.102（正式版本） （64 位）

### 系统版本

Windows 10 专业版(20H2)

### Node版本

v16.13.2

**Comment by xiaosansiji** [comment]
已在 0.41.0 版本中修复
