### ISSUE TITLE
[Table] 第一列设置的width较小，align设置center时，多选按钮或文字没有居中，多选按钮被遮挡

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#644]
### tdesign-vue 版本

0.38.0-alpha3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-k8fs7k?file=/src/demo.vue

### 重现步骤

codesandbox可见，当第一列设置的width较小，align设置为center时，
当第一列是多选按钮被遮挡，同时没有居中显示。
当第一列是文字时，也没有居中显示。

### 期望结果

期望第一列的多选按钮/文字能够居中显示

### 实际结果

目前多选按钮/文字没有居中， 多选按钮被部分遮挡

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by delenzhang** [comment]
table 列表 列宽度过小，而每一列又有不一样的padding-left 和 padding-right导致，和td设计ui风格冲突，需要td这边出方案是限制每一列最小宽度，还是修改tdesign-common 修改样式， 此外，t-checkbox 使用 display:inline-flex;导致宽度变成32px，为何不使用 .t-checkbox {
    display: inline-block;
    width: 16px;
  } 限制一下宽度，保持固定？
业务可暂时使用hack css方式处理如下
`.t-table td.t-align-center:first-child {
    padding-left: 0;
    padding-right: 0;
   .t-checkbox {
    display: inline-block;
    width: 16px;
  }`

**Comment by chaishi** [comment]
<img width="1056" alt="wecom-temp-94484943b89f2fc83eae646e36af8b49" src="https://user-images.githubusercontent.com/11605702/160762307-e51a85a8-183e-4532-98d0-affa20b293af.png">

如果强制 设置宽度为 35，业务侧自行处理，组件库不做任何修改（也没有找到上文说的 margin 什么的在哪里）
