### ISSUE TITLE
[Upload 上传] 文件超出限制数时能否做个提示？或者其他方式可以设置提示 可以限制

### ISSUE THREAD

**Issue by wxl199286** [Tencent/tdesign-vue#646]
### tdesign-vue 版本

0.36.0

### 重现链接

https://tdesign.tencent.com/vue/components/upload?tab=api

### 期望结果
还有就是当文件超出限制数时能否做个提示？或者其他方式可以设置提示
可以限制

### 实际结果

限制了2个文件但是可以传无数个

**Comment by uyarn** [comment]
怎么配置的呢？可以提供个codesandbox复现下吗 https://codesandbox.io/s/tdesign-vue-demo-forked-oslszb?file=/src/demo.vue

**Comment by wxl199286** [comment]
发现0.39.1已经修护

**Comment by uyarn** [comment]
`还有就是当文件超出限制数时能否做个提示？或者其他方式可以设置提示`
会完善select-change的API 可以在这个回调自己用Message或Alert自己提示

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中实现
