### ISSUE TITLE
[table] 表格配置项按钮可否自定义位置

### ISSUE THREAD

**Issue by qingmang** [Tencent/tdesign-vue#652]
### 这个功能解决了什么问题
目前的配置项 和 topContent 无关联，开启:columnController 无法控制配置项按钮的位置，可否支持slot 属性之类的调用

### 你建议的方案是什么？
目前的配置项 和 topContent 无关联，开启:columnController 无法控制配置项按钮的位置，可否支持slot 属性之类的调用

**Comment by chaishi** [comment]
🉑️

**Comment by chaishi** [comment]
feat(Table): topContent 和自定义列配置同时存在时，自定义列配置后渲染，保持在下方靠近表格的位置

如果这样，是否可以满足需求

**Comment by qingmang** [comment]
> feat(Table): topContent 和自定义列配置同时存在时，自定义列配置后渲染，保持在下方靠近表格的位置
> 
> 如果这样，是否可以满足需求

单独一行感觉留大白太厉害了，因为表格的topContent可以放很多按钮，自定义列应该归属 到其中比较好

**Comment by chaishi** [comment]
自定义列现在本来就是在 topContent 里面，如果你还有查询条件，也可以放进 topContent

后续我们考虑新增 列配置按钮的位置

**Comment by chaishi** [comment]
`v0.40.2` 已支持自定义位置
