### ISSUE TITLE
[Table] 虚拟滚动表格，当数据增加超过threshold时， 滚动产生空白并且报错TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#661]
### tdesign-vue 版本

0.39.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-l77fyj?file=/src/demo.vue:411-420

### 重现步骤

打开codesandbox链接，目前表格数据数量是19项，滚动没有异常。
1. 点击增加按钮，增加数据数量超过threshold
2. 此时滚动表格
3. 控制台报错：Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')"
4. 滚动到最下面出现大量的空白，同时点击增加按钮已不起效

### 期望结果

正常滚动，不会出现大量空白

### 实际结果

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13745660/160523022-b70b1cc4-4aec-48a3-a996-429987b625b6.png">

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/660

**Comment by xiaosansiji** [comment]
已在 0.39.1 版本中修复
