### ISSUE TITLE
[tree] 父子节点选中状态关联异常

### ISSUE THREAD

**Issue by Fly-Feel** [Tencent/tdesign-vue#662]
### tdesign-vue 版本

0.37.0

### 重现步骤

tree在t-dialog对话框里的form表单内，异步tree数据，checkStrictly属性为true，即父子节点选中状态关联
我点修改按钮弹窗，第一次点击弹窗tree父子节点选中状态异常，第二次点修改按钮弹窗后，tree父子节点选中状态正常
第一次的时候：
子节点全选中或不全选中，父节点没有选中或半选中状态
但我点击修改tree任意节点选中状态时，父子节点选中状态关联恢复正常，
![image](https://user-images.githubusercontent.com/53337386/160522744-6c482bb7-21bb-452a-9af4-a24e0c2867e8.png)
![image](https://user-images.githubusercontent.com/53337386/160522848-6b765a39-1793-45a1-9079-e900a3027f9b.png)

### 期望结果

父子节点选中状态关联正常

### 实际结果

异步数据，子节点全选中或不全选中，父节点没有选中或半选中状态

### 框架版本

Vue(2.6.11)

**Comment by qianlongdoit** [comment]
遇到了同样的问题

**Comment by TabSpace** [comment]
我测试了一下，没能复现你所说的的问题，要么就是我理解有误。
https://codesandbox.io/s/tdesign-vue-demo-forked-9nxf6r
这是一个示例代码，麻烦验证下是否存在你是说的问题，如果需要代码修改后才能复现，麻烦 fork 一个示例给我看下。

**Comment by Fly-Feel** [comment]
描述的不是很清楚，录制了动图@[TabSpace](https://github.com/TabSpace)
![treebug](https://user-images.githubusercontent.com/53337386/163914893-b42be879-787f-43d2-b216-ee2129f73523.gif)

**Comment by TabSpace** [comment]
我新建了一个示例，还是没能重现你所碰到的问题。
https://codesandbox.io/s/tdesign-vue-demo-tree-check-strictly-i7c6bg?file=/src/demo.vue
检查下 checkStrictly 属性，传递后是否有发生变更？

**Comment by Fly-Feel** [comment]
我这个是表单异步数据回显，上面有仁兄也说遇到了这个问题，而且我检查过，没有变更checkStrictly 属性，我研究下怎么复现一下这个问题
