### ISSUE TITLE
[Message] 希望增加message的全局配置

### ISSUE THREAD

**Issue by Leotw** [Tencent/tdesign-vue#663]
### 这个功能解决了什么问题

Message组件新增全局配置，方便局部调用满足需求，如attach等功能，无需在局部进行再次设置

### 你建议的方案是什么

[Message] 希望增加message的全局配置

**Comment by sommouns** [comment]
认领该任务，预计5-10日期前提交

**Comment by xiaosansiji** [comment]
已在 0.41.1 版本修复
