### ISSUE TITLE
tree 组件bug

### ISSUE THREAD

**Issue by EdenStrive** [Tencent/tdesign-vue#67]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
![wecom-temp-58de644b1bbde908ca768cf672330c9c](https://user-images.githubusercontent.com/43888558/147237558-6a378ab3-f011-4668-aa5b-e167c0be744c.png)

Add browser version here
![wecom-temp-2b653cb08548131a4d3c4064ebf29319](https://user-images.githubusercontent.com/43888558/147237570-6c7e48c2-8097-4571-8a8d-a11a35891283.png)

**Describe the bug**
请问 为什么我的子节点已经禁用了，但是点击父节点还可以影响到子节点的选中呢～

**Comment by chaishi** [comment]
收到，我们尽快处理

**Comment by chaishi** [comment]
@barnettyang 处理中

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-common/pull/72

**Comment by chaishi** [comment]
已修复并发布至 0.33.0
