### ISSUE TITLE
[Table] 合并单元格边框样式问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#671]
### tdesign-vue 版本

0.39.0

### 重现链接

https://stackblitz.com/edit/angular-awfw9u?file=src/demo.vue 

### 重现步骤

<img width="587" alt="wecom-temp-8b13785634afbfe5b4b43dd17f14877f" src="https://user-images.githubusercontent.com/11605702/160619135-73f64a23-dc0e-4a28-a900-02a8d422b8a9.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/345 and  https://github.com/Tencent/tdesign-vue/pull/672

**Comment by xiaosansiji** [comment]
已在 0.40.0 版本中修复
