### ISSUE TITLE
[tree-select] 点击空白区域（popup）被关闭了

### ISSUE THREAD

**Issue by luchuanqi** [Tencent/tdesign-vue#680]
### tdesign-vue 版本

0.39.1

### 期望结果

点击空白区域（popup）不被关闭了

### 实际结果

点击空白区域（popup）会关闭

### 框架版本

Vue(2.x)

**Comment by YikaJ** [comment]
@luchuanqi  这个应该是个需求吧，是为了允许控制 popup 的展示关闭逻辑？

**Comment by chaishi** [comment]
看不懂这个 issue 要表达的意思，Popup 组件支持自由控制 visible
TreeSelect 透传全部 Popup 组件属性
