### ISSUE TITLE
[EnhancedTable] 写错rowKey的value 时会出现页面卡死。

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#682]
### tdesign-vue 版本

"tdesign-vue": "^0.39.1"

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-1ldsej?file=/src/demo.vue

### 重现步骤

点击展开子数据图标会导致页面卡死，需要删除掉rowKey属性（只是作为测试而已）或者修改为data数据中有的属性。

### 期望结果

正常展开子数据，当rowKey的value绑定错误时，应在控制台进行提示。

### 实际结果

页面卡死

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/693

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中修复
