### ISSUE TITLE
[Table] Safari浏览器下固定表头且固定列时，横向高速滚动时表头会抖动

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#684]
### tdesign-vue 版本

0.40.1

### 重现链接

https://0_39_1-tdesign-vue.surge.sh/vue/components/table#固定表头和列的表格

### 重现步骤

https://user-images.githubusercontent.com/11243798/162116056-eca60a63-56dd-4ad9-873d-7fd8e7fcea7b.mp4

”序号“、 ”操作“ 列抖动严重

### 框架版本

Vue2

### 浏览器版本

Safari 15.3

**Comment by cong-min** [comment]
safari浏览器下，表格还有其他的样式问题：
例如这个也怪怪的
<img width="700" alt="image" src="https://user-images.githubusercontent.com/11243798/160966491-a20eece0-c474-4b83-bb21-4cc64bb7e758.png">

**Comment by chaishi** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns

AntDesign 在 Safari 浏览器中，高速横向滚动，也会有同样的问题

**Comment by chaishi** [comment]
只有 Safari + Mac + 触发板滚动会触发这类 Scrolling Debouncing

**Comment by cong-min** [comment]
`0.38.1` 的表现相对更稳定一点：

https://0_38_1-tdesign-vue.surge.sh/vue/components/table#固定表头和列的表格

https://user-images.githubusercontent.com/11243798/162117174-34370ba9-3039-41ea-b7a9-acea361a7d7d.mp4


---

`0.40.1` 的表现，也更新了视频在1楼可以对比。

**Comment by chaishi** [comment]
这个属于 safari 特性，debouncing scroll，等浏览器解决这个问题吧

**Comment by chaishi** [comment]
后面可以使用 Affix 特性解决这个问题，表头吸顶或吸底

**Comment by chaishi** [comment]
此类问题暂不处理，以后有时间再 reopen

**Comment by chaishi** [comment]
今天测试了看看，发现，竟然不抖动了

https://user-images.githubusercontent.com/11605702/174421436-2cdd3ea0-db02-4a6e-b0a3-6d4828816c9d.mov
