### ISSUE TITLE
[upload] 上传中点击取消上传后，就一直是上传中的状态了，另外在选择一个文件 按钮还是上传中不可用

### ISSUE THREAD

**Issue by wwervin72** [Tencent/tdesign-vue#691]
### tdesign-vue 版本

0.40.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-0v7zm4?file=/src/demo.vue:206-207

### 重现步骤

上传过程中点击取消上传按钮

### 期望结果

上传的接口取消，再次选择文件能正常上传，取消文件的状态和上传按钮的状态正常

### 实际结果

上传的接口取消了，但是再次选择文件不能上传，取消文件的状态和上传按钮的状态一直是上传中

### 框架版本

2.6.14

### 浏览器版本

chrome(版本 98.0.4758.109（正式版本） (x86_64))

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中修复
