### ISSUE TITLE
用 composition-api 开发的组件按需引入都报错

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#696]
### tdesign-vue 版本

0.40.1

### 重现链接

Table: https://codesandbox.io/s/tdesign-vue-demo-forked-udg497?file=/src/demo.vue

Menu: https://codesandbox.io/s/tdesign-vue-demo-forked-j9bypt?file=/src/demo.vue

### 重现步骤

不通过 `Vue.use` 直接按需引入组件：
```js
import { Table as TTable } from 'tdesign-vue';
export default {
  component: { TTable }
};
```

#### 报错
<img width="584" alt="wecom-temp-f3c3744ad3b3b5ac77bcccdf75b901d3" src="https://user-images.githubusercontent.com/11243798/161212094-cd3c6308-6d54-4c36-a466-5397570b6273.png">

#### 原因初步分析

业务没有安装`@vue/composition-api` 且没有执行 use 未触发 td 的自动安装，导致 setup 未执行，报错

### 框架版本

Vue2

### 浏览器版本

*

### 系统版本

*

**Comment by uyarn** [comment]
升级到0.40+ 一下 已经fix了

**Comment by cong-min** [comment]
@uyarn 不管用，看了逻辑0.40.1只解决了Vue.use(Table)的场景，没有调use依然不生效。
另外例子的依赖也升级到了0.40.1，同样的报错

**Comment by cong-min** [comment]
初步分析是所有使用了 composition-api 开发的组件的共性问题，直接 import 按需引入会出问题，例如 Menu  
https://codesandbox.io/s/tdesign-vue-demo-forked-j9bypt?file=/src/demo.vue

**Comment by LeeJim** [comment]
我看看

**Comment by xiaosansiji** [comment]
已在 0.40.3 版本中修复 cong 试一下

**Comment by Hsomething** [comment]
这个问题解决了吗，0.47.0版本的也会出现这个问题
