### ISSUE TITLE
[table] 属性selectedRowKeys有值的情况下，表格行未添加样式  t-table__row--selected

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#700]
### tdesign-vue 版本

0.40.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-5i9wmp?file=/src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/15682051/161233294-5e0c1846-fabc-4c13-a9bb-53acd15d17c5.png)

### 期望结果

选中的行应该要添加样式  t-table__row--selected

### 实际结果

实际没有样式  t-table__row--selected

### 框架版本

Vue(2.6.11)

### 浏览器版本

98.0.4758.82

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/693

**Comment by xiaosansiji** [comment]
已在 0.40.2 版本中修复
