### ISSUE TITLE
[Section] 标题

### ISSUE THREAD

**Issue by wxl199286** [Tencent/tdesign-vue#701]
### 这个功能解决了什么问题

![888](https://user-images.githubusercontent.com/55227919/161244627-001f5af3-aad1-48dd-8318-b4df6e22067d.png)
希望在PC端可以加一个“标题”类似这样的组件。可以显示竖条，设置颜色以及大小宽度等。
在详情页面等页面，对信息区域的分区或者啥的经常用到。发现各大vue都没有这个功能。麻烦考虑下。

### 你建议的方案是什么

竖条可控，颜色大小可控。

**Comment by chaishi** [comment]
这个可以考虑列入排版组件的 title
