### ISSUE TITLE
[Table] 关于列支持配置 min-width 最小宽度的讨论

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#708]
### 这个功能解决了什么问题

需求：

<img width="536" alt="image" src="https://user-images.githubusercontent.com/11243798/161375108-1b5e83c6-678f-4d8c-b7f4-9b6dd47550b4.png">

当前 `t-table` 的表格无法支持通过配置 min-width 实现上述效果，目前只有 width 不符合预期：

https://codesandbox.io/s/tdesign-vue-demo-forked-j42crj?file=/src/demo.vue

而 element 支持 min-width 满足需求：

[elelment table min-width 的效果](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCI+XG4gICAgPGVsLXRhYmxlIDpkYXRhPVwiZGF0YTFcIiB0YWJsZS1sYXlvdXQ9XCJmaXhlZFwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiB2LWZvcj1cIml0ZW0gaW4gY29sdW1uc1wiIHYtYmluZD1cIml0ZW1cIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gICAgPGJyPjxwIGFsaWduPVwiY2VudGVyXCI+5paw5aKe5LiA5YiXIEU6PC9wPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cImRhdGEyXCIgdGFibGUtbGF5b3V0PVwiZml4ZWRcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gdi1mb3I9XCJpdGVtIGluIGNvbHVtbnMyXCIgdi1iaW5kPVwiaXRlbVwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB0YWJsZUxheW91dCA9IHJlZignZml4ZWQnKVxuXG5jb25zdCBjb2x1bW5zID0gW3tcbiAgbGFiZWw6IFwiQSB3aWR0aD0xMDBcIixcbiAgd2lkdGg6IDEwMCxcbiAgcHJvcDogXCJhXCIsXG4gIGtleTogXCJhXCJcbn0sXG57XG5cdGxhYmVsOiBcIkIgbWluLXdpZHRoPTEwMFwiLFxuXHRtaW5XaWR0aDogMTAwLFxuXHRwcm9wOiBcImJcIixcblx0a2V5OiBcImJcIlxufSxcbntcblx0bGFiZWw6IFwiQyB3aWR0aD0xMDBcIixcblx0d2lkdGg6IDEwMCxcblx0cHJvcDogXCJjXCIsXG5cdGtleTogXCJjXCJcbn0sXG57XG5cdGxhYmVsOiBcIkQgd2lkdGg9MTAwXCIsXG5cdHdpZHRoOiAxMDAsXG5cdGtleTogXCJkXCIsXG5cdHByb3A6IFwiZFwiXG59XTtcbiAgXG5jb25zdCBkYXRhMSA9IFtcbiAge1xuICAgIGE6IFwi6aKE5pyfPeWunumZhSB3aWR0aD0xMDBcIixcbiAgICBiOiBcIumihOacnz3lrp7pmYUgd2lkdGg9MjUwXCIsXG4gICAgYzogXCLpooTmnJ895a6e6ZmFIHdpZHRoPTEwMFwiLFxuICAgIGQ6IFwi6aKE5pyfPeWunumZhSB3aWR0aD0xMDBcIlxuICB9XG5dO1xuICBcbmNvbnN0IGNvbHVtbnMyID0gY29sdW1ucy5jb25jYXQoW1xuICB7XG4gICAgbGFiZWw6IFwiRSB3aWR0aD01MDBcIixcbiAgICB3aWR0aDogNTAwLFxuICAgIGtleTogXCJlXCIsXG4gICAgcHJvcDogXCJlXCJcbiAgfVxuXSk7XG5cbmNvbnN0IGRhdGEyID0gW1xuICB7XG4gICAgYTogXCLpooTmnJ895a6e6ZmFIHdpZHRoPTEwMFwiLFxuICAgIGI6IFwi6aKE5pyfPeWunumZhSB3aWR0aD0xMDBcIixcbiAgICBjOiBcIumihOacnz3lrp7pmYUgd2lkdGg9MTAwXCIsXG4gICAgZDogXCLpooTmnJ895a6e6ZmFIHdpZHRoPTEwMFwiLFxuICAgIGU6IFwi6aKE5pyfPeWunumZhSB3aWR0aD01MDBcIlxuICB9XG5dO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLmJveCB7XG4gICAgd2lkdGg6IDU1MHB4O1xuICAgIG92ZXJmbG93OiBhdXRvO1xuICAgIGJvcmRlcjogM3B4IGRhc2hlZDtcbiAgICBvdmVyZmxvdzogYXV0bztcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### 你建议的方案是什么

参考 element

**Comment by chaishi** [comment]
想要的 minWidth 表格效果，应该都可以通过 `width` 实现的，只要合理调整 `table` 元素的宽度

**Comment by chaishi** [comment]
原生标签特性，不支持 minWdith；
AntD 也不支持 minWidth;

本就是一个很不需要的特性

**Comment by chaishi** [comment]
你想要的 Element 效果，一定可以通过 td.width 和 table.width 去达到你的预期的

**Comment by cong-min** [comment]
可以后续讨论下这个的必要性。这是 AntD 的讨论： https://github.com/ant-design/ant-design/issues/20885

**Comment by cong-min** [comment]
> 你想要的 Element 效果，一定可以通过 td.width 和 table.width 去达到你的预期的

是的，能够实现。
当产品需求是表格列的数量是动态不确定时，根据产品要求某些列需设有最小宽度，又某些列不限制宽度时，
这时需要业务自行去计算并设置和分配 col 与 table 的 width 再传入才能实现

**Comment by chaishi** [comment]
设置 `table` 元素本身的宽度，就可以达到 minWidth 效果。
否则原生 table 就支持 minWidth 了。

**Comment by btnkr** [comment]
这个需求会很有用

多个列同时设置`min-width`的时候，如果`table`宽度大于`min-width`总和，多余宽度按比例分配给各列，如果`table`可视宽度小于`min-width`总和，出现横向滚动条

在实际应用中，经常会出现需要在不同的可视宽度内需要表格列宽度合理的情况，比如有一列表头为状态，需要100px可以完全展示出来，如果固定`width`的话，在可视宽度很大的时候这一列会显得非常拥挤，如果不固定`width`这一列在可视宽度很小的时候甚至会换行。这个情况下如果指定`min-width`，在窄的时候不会让状态展示换行，在宽的时候按比例分配剩余宽度也不会显得很拥挤。

还有一种情况，表头的文字可能会比内容多，如果有`min-width`就可以自然地不让表头换行。

**Comment by chaishi** [comment]
> 还有一种情况，表头的文字可能会比内容多，如果有min-width就可以自然地不让表头换行。

宽度自适应，控制好 width 设置，同样可以做到 `min-width` 效果，同样可以自然地不换行。

此处和 antd 、原生浏览器行为保持一致，不支持。

**Comment by cong-min** [comment]
最新版 Chrome 浏览器采用了 [TablesNG 渲染架构](https://docs.google.com/document/d/16PFD1GtMI9Zgwu0jtPaKZJ75Q2wyZ9EZnVbBacOfiNA/preview)， `<col>` 标签已支持 `min-width` 等属性设置，例子：https://jsfiddle.net/dgrogan/8x4j21ms/  （Safari尚未支持）

**期望 TDesign 也能支持为 col 透传设置样式属性 `min-width` 等**

---

- TablesNG 渲染架构介绍：https://docs.google.com/document/d/16PFD1GtMI9Zgwu0jtPaKZJ75Q2wyZ9EZnVbBacOfiNA/preview
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11243798/180727852-a29c3080-554e-48b1-aafa-6e748acbad0a.png">

- 判断浏览器是否为 TablesNG： https://tablesng.com/

--- 

其他信息来源：

https://bugs.chromium.org/p/chromium/issues/detail?id=120886 

- 标题：min-width does not work on col
- 2012年3月30日发布
- 2020年6月9日回复：TablesNG will support column min-width.
- 2021年4月2日状态改为“已修复”

**Comment by chaishi** [comment]
如果原生浏览器开始支持，可以透传

**Comment by chaishi** [comment]
resolved in 0.45.1, published
