### ISSUE TITLE
[MessagePlugin] 函数式调用全局提示动画效果丢失问题

### ISSUE THREAD

**Issue by brankcar** [Tencent/tdesign-vue#712]
### tdesign-vue 版本

0.34.0

### 重现步骤

使用 tdesign-vue 解决方案构建新项目，在 src/utils/request.ts 文件中新增全局错误信息提示功能，在弹出提示时动画效果丢失
https://tdesign.tencent.com/starter/docs/vue/get-started

`import { MessagePlugin } from 'tdesign-vue';`
`MessagePlugin.error(data.msg, CODE.COUNT_DOWN)`

### 期望结果

正常显示动画

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(99.0.4844.84)

### 系统版本

Windows10

### Node版本

14.17.3

**Comment by uyarn** [comment]
升级版本上来就正常了。
