### ISSUE TITLE
关于Dialog 对话框组件及使用文档疑问

### ISSUE THREAD

**Issue by gzg1023** [Tencent/tdesign-vue#72]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Additional context**

关于Dialog 对话框组件的疑问，拖拽只有非模态对话框时候才可以拖动，api中是存在该参数的，但是文档似乎漏掉了DEMO。
https://github.com/Tencent/tdesign-vue/blob/develop/src/dialog/dialog.tsx#L52
这一行添加了一个dragend事件是什么时候会有这种情况呢，mouseUpHandler这个事件逻辑好像有点问题，创建移除会重复移除多次，可以通过弹出-关闭，弹出-关闭 来进行测试。 我看dragend只写了添加了event没有移除event事件，是否需要修复呢？

 感谢回复，如果需要添加修复，我可以提供pr

**Comment by chaishi** [comment]
> 我看dragend只写了添加了event没有移除event事件，是否需要修复呢？

需要修复，欢迎提供 PR

**Comment by chaishi** [comment]
> 拖拽只有非模态对话框时候才可以拖动，api中是存在该参数的，但是文档似乎漏掉了DEMO。

目前的设计是：只有非模态对话框才能拖动，模态对话框就是阻断的不允许操，API 设计如此。

**Comment by chaishi** [comment]
> 这一行添加了一个dragend事件是什么时候会有这种情况呢

期望是：拖拽结束的时候，就应该触发 `dragend` 事件

**Comment by chaishi** [comment]
> mouseUpHandler这个事件逻辑好像有点问题，创建移除会重复移除多次，可以通过弹出-关闭，弹出-关闭 来进行测试

欢迎提供 PR

**Comment by chaishi** [comment]
方便留个联系方式么？issue 沟通太慢

**Comment by gzg1023** [comment]
好的，这个bug我来修复。占坑
