### ISSUE TITLE
[treeSelect] 根节点显示异常

### ISSUE THREAD

**Issue by Fly-Feel** [Tencent/tdesign-vue#722]
### tdesign-vue 版本

0.40.1

### 重现链接

https://codesandbox.io/s/tdesgin-demo-1pgjq3?file=/src/demo.vue

### 重现步骤

异常
38行：this.form.parentId = 0;
45行：const menu = { menuId: 0, menuName: "主类目", children: [] };
![image](https://user-images.githubusercontent.com/53337386/162355650-d1e966ef-9666-4d42-b7ae-939b5d8dd659.png)

正常
38行：this.form.parentId = '0';
45行：const menu = { menuId: '0', menuName: "主类目", children: [] };
![image](https://user-images.githubusercontent.com/53337386/162355676-b6622221-fe89-4aa3-bfda-6b1d935f77b6.png)

38行：this.form.parentId = 1;

### 期望结果

根节点为数字0时也正常显示

### 框架版本

Vue(2.6.11)

### 浏览器版本

Microsoft Edge 100.0.1185.29 (正式版本) (64 位)

### 系统版本

win10

**Comment by Fly-Feel** [comment]
@[chaishi](https://github.com/chaishi)

**Comment by chaishi** [comment]
收到，我找同学看下

**Comment by xiaosansiji** [comment]
已在 0.41.0 版本中修复
