### ISSUE TITLE
[t-select] 可过滤的选择器提前换行问题

### ISSUE THREAD

**Issue by 1092622894** [Tencent/tdesign-vue#726]
### tdesign-vue 版本

0.40.2

### 重现链接

https://tdesign.woa.com/vue/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

![wecom-temp-352ca5cc392b5b239d9b725b7ef66f3f](https://user-images.githubusercontent.com/52640753/162680420-3c7b4243-af5a-4db3-8223-f51f878481f6.png)
连续选中值

### 期望结果

应该选够四个才换行才对

### 实际结果

实际选了三个就换行，后面其实还放得下一个

### 框架版本

0.40.2

### 系统版本

8.5.5

### Node版本

v16.14.0

**Comment by xiaosansiji** [comment]
已在 0.40.3 版本中修复
