### ISSUE TITLE
Textarea多行文本框

### ISSUE THREAD

**Issue by Dazzling-one** [Tencent/tdesign-vue#727]
### tdesign-vue 版本

0.40.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-0iiiff?file=/src/demo.vue

### 重现步骤

Textarea多行文本框输入number类型的0时，样式错乱

### 期望结果

输入number类型的0时，显示的0应该展示到textarea里面，不是外面
![image](https://user-images.githubusercontent.com/67211308/162740405-1e4c4fa9-424a-4500-b72d-bbdfd9a9f7a1.png)

### 实际结果

输入number类型的0时,展示到textarea外面
![image](https://user-images.githubusercontent.com/67211308/162740556-6667ee23-a8a5-44d6-9bd8-d91de2e1e2cf.png)

### 浏览器版本

Chrome(00.0.4896.75)

### 系统版本

MacOS(12.1)

**Comment by xiaosansiji** [comment]
已在 0.40.3 版本中修复
