### ISSUE TITLE
[Tree] 树形菜单设置可以整行选中

### ISSUE THREAD

**Issue by samchenws** [Tencent/tdesign-vue#728]
### 这个功能解决了什么问题

树形菜单设置可以整行选中 无法 连图标一起选中是否能支持类似功能？
![image](https://user-images.githubusercontent.com/37535153/162752280-3af11eb6-2b35-4653-9b9c-774e019ab39d.png)

### 你建议的方案是什么

希望能整行选中

**Comment by chaishi** [comment]
没看明白需求

**Comment by samchenws** [comment]
> 
就是设置可以整行选中的时候，图标没法选中
![image](https://user-images.githubusercontent.com/37535153/162753958-97e81230-7e4c-458b-9c2b-0aad98411e5a.png)

**Comment by samchenws** [comment]
@chaishi 还有就是
1.选中子节点的时候能整行选中
![image](https://user-images.githubusercontent.com/37535153/162754808-70af5644-fc78-471d-894b-83882af8e158.png)
![image](https://user-images.githubusercontent.com/37535153/162754849-1a8a9237-d88a-4590-abde-a53e82d13312.png)
2.设置自定义图标的时候折叠的图标也能存在
![image](https://user-images.githubusercontent.com/37535153/162755092-bcc43cb2-267b-4382-8188-7f3f0b1460fc.png)

**Comment by samchenws** [comment]
我利用label的solt和设置全局的样式已完美解决问题了，谢谢
