### ISSUE TITLE
[tree] 关于增加一个valueMode控制属性的讨论

### ISSUE THREAD

**Issue by Fly-Feel** [Tencent/tdesign-vue#729]
### 这个功能解决了什么问题

属性值为all时，
需求：菜单权限管理，子菜单部分选中，半选中的父节点也要在选中值中提交，不然提交表单后该父节点值没提交，导致整个菜单不可见
父子联动是checkStrictly属性来控制
![image](https://user-images.githubusercontent.com/53337386/162872339-4e4540bf-ea3c-4af9-ae54-f873086cc9ea.png)

![image](https://user-images.githubusercontent.com/53337386/162873354-f090aec8-cc39-4643-9c84-07716b944171.png)

### 你建议的方案是什么

1.增加获取半选中节点的方法
2.valueMode增加个控制属性

**Comment by TabSpace** [comment]
这里如果修改了节点选中规则，可能会影响到已经在使用这个组件的人，形成 breaking change。
考虑到当前的实现方式与判断规则，也存在其合理性，所以应该不会修改 valueMode 为 all 模式下的选中规则。
valueMode 增加控制属性，目前看不是很必要，因为你的需求结合节点的 api 是很容易实现的。
选中的节点，可以用 getParents 方法获取所有父节点，联动模式下，所有选中节点，其父节点要么是选中的，要么就是半选的。
所以甚至都不需要判断父节点半选与否就可以获取你所需要的值。
如果确实有半选判断需求，节点属性 indeterminate 标记了是否为半选状态。
