### ISSUE TITLE
[Editor] 后续是否有富文本编辑器、图片裁剪的组件开发计划呢？

### ISSUE THREAD

**Issue by brankcar** [Tencent/tdesign-vue#736]
### 这个功能解决了什么问题

很多管理端系统当中都有富文本编辑器需求，在该需求的同时如果也内置了图片裁剪功能能提升不少的效率，现在市面上的很多富文本编辑器各有各的优点和缺陷，比如`quill`是需要`项目内置导入css文件`才能使用完整的所见即所得富文本配置功能，其它类型的插件自定义开发方案又不够，跨端能力也不强。TDesign是集合了跨端开发能力，并且也内置小程序端开发解决方案，在同一个UI框架当中集成富文本`编辑`与`解析`能力也减少很多额外的插件开发或查找适合的技术方案所耗费的时间。麻烦TDesign团队多多考虑一下，在一众偏业务方向的后端UI框架当中是需要交互体验更出色的UI框架来作为`鲶鱼`，激发整体后端系统的UI体验意识，天下苦‘秦’矣~

在此祝愿TDesign团队越来越好！

### 你建议的方案是什么

希望TDesign能集成高度可自定义开发并能跨端解析的富文本编辑器与图片裁切功能。

**Comment by xiaosansiji** [comment]
感谢关注，TDesign 组件库中暂时不会考虑新增富文本编辑器，主要基于以下两个原因：
- 富文本编辑器可能还不够“通用”，TDesign 并不仅专注于内容平台/服务端管理系统，富文本编辑器是比较重的一类组件，贸然引入会极大增加业务项目构建产物大小，可能还要依赖用户按需引入或手动排除编辑器组件的方式来减小包大小
- 目前业界情况比较复杂，有倾向于直接使用 CKEditor 等功能比较完善的产品，也有倾向于基于 slate、draft 等自行封装修改，要看业务项目具体需求以及技术栈

总之，富文本编辑器开发是业界比较专门的一类产品，相关实现跟通用 UI 组件库技术差别也较大，TDesign 团队暂时不会投入到编辑器开发中，如果你感兴趣可以为正在使用的编辑器产品如 quill 等开发一套 TDesign 风格皮肤，我们会放在官网社区推荐组件中展示 😘

**Comment by xiaosansiji** [comment]
我们正在考虑新增一个图片展示及预览功能的组件，大概下个月上线，或许你可以搭配 [Cropper.js](https://github.com/fengyuanchen/cropperjs) 等类似的第三方库来实现业务需求

**Comment by brankcar** [comment]
> 我们正在考虑新增一个图片展示及预览功能的组件，大概下个月上线，或许你可以搭配 [Cropper.js](https://github.com/fengyuanchen/cropperjs) 等类似的第三方库来实现业务需求

好的，感谢答复，只能继续搞业务插件了，图片预览目前我都暂时用的 avatar 组件替代的
