### ISSUE TITLE
迁移至td后的一点小思考

### ISSUE THREAD

**Issue by os7blue** [Tencent/tdesign-vue#738]
首先，感谢各位的付出与努力。
目前把老版本的后台页面以及个人做的一些服务迁移至td中，虽有小磕碰，到也无伤大雅，好评。
在使用诸多组件之后，产生了一些想法，主要是两方面：

1. ”可扩展“
2. ”意向中业务的样子“

避免篇幅冗余，下面叙述以1和2代指。

1没有什么好说的，主要是2，并且1也受2的影响。
做一个通用的中后台解决方案，私以为最难的一点也在这里，上述1和2之间的平衡。

其实这边写了有一千多字叙述这个事情，但是觉的以一两个组件来叙述容易产生偏差，遂删之。

通用是前提，所以在这个前提下，尽量不要受太多的2的影响，目前感觉有些组件的设计有受到这方面的影响，2意味着赋予组件更多的能力，但同时很容易对1造成影响，私以为，组件只用注重本身的功能就好，结合现代js框架的各种特性（比如vue的双向绑定，监听，计算，插槽等），能产生多种可能，就足够了，至于无法满足的那些东西，大多都超脱出‘通用’这个范畴了。在往上一点，群里甚至听到过各种直接定位到业务本身的建议，这种就更不必理会了，解决方案是解决大方向上的重复工作的，不是帮人做业务的。

封装是必须的，但是封装也意味着更多的考量和妥协，时间长了会在开发中产生纠结以及疲惫感，对于长期的发展来说，不是好事。

文笔不足，一点拙见，希望有所帮助，再次感谢。

**Comment by uyarn** [comment]
"其实这边写了有一千多字叙述这个事情" 可以的话可以把这一千多字发给我们 ~

**Comment by os7blue** [comment]
> 👋 @os7blue，感谢给 TDesign 提出了 issue。 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

昨天太晚全在GitHub这个编辑器写的，一时也不太好复述，等全部迁移完了看能不能详细写一点吧。

**Comment by xiaosansiji** [comment]
组件的通用性和易用性（功能多）确实很多时候是比较难同时满足，也在通过跟公司的很多一线业务团队合作来解决这个问题：

通用组件解决通用性问题，功能性需求由某个领域的业务组件库解决（地图、政务、医疗行业等等），后面可能会以物料市场的方式对外曝光这些业务组件库。不过现在也遇到了业务组件库在这个领域中不够通用的问题，参与的业务团队会更倾向于以自己的业务形态为第一优先级考虑，还在尝试解决。。

通用组件库里新增组件功能或者组件类型基本上还是会按比较谨慎的方式来进行：需要所有 PMC 同学参与讨论；能不加 API 的就考虑通过扩展或者几个 API 组合的方式来实现，API 多了也会增加用户使用心智负担，反而变得“不好用”。

记得好像有同学提过想要定制 pagination 里一些元素的显示位置，这个感觉就不太适合去支持，也不符合 TDesign 的设计风格

**Comment by os7blue** [comment]
> 组件的通用性和易用性（功能多）确实很多时候是比较难同时满足，也在通过跟公司的很多一线业务团队合作来解决这个问题：
> 
> 通用组件解决通用性问题，功能性需求由某个领域的业务组件库解决（地图、政务、医疗行业等等），后面可能会以物料市场的方式对外曝光这些业务组件库。不过现在也遇到了业务组件库在这个领域中不够通用的问题，参与的业务团队会更倾向于以自己的业务形态为第一优先级考虑，还在尝试解决。。
> 
> 通用组件库里新增组件功能或者组件类型基本上还是会按比较谨慎的方式来进行：需要所有 PMC 同学参与讨论；能不加 API 的就考虑通过扩展或者几个 API 组合的方式来实现，API 多了也会增加用户使用心智负担，反而变得“不好用”。
> 
> 记得好像有同学提过想要定制 pagination 里一些元素的显示位置，这个感觉就不太适合去支持，也不符合 TDesign 的设计风格

赞，物料市场是个很好的想法
