### ISSUE TITLE
[Table] SSR ReferenceError window is not defined

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#741]
### tdesign-vue 版本

"tdesign-vue": "^0.40.2",

### 实际结果

![image](https://user-images.githubusercontent.com/49895922/163352574-476f2b54-0e7f-4033-b2a3-6589b1ddfea8.png)

**Comment by uyarn** [comment]
@codenotkey 认领修复 ~

**Comment by chaishi** [comment]
我这边搬代码的时候，也顺带处理过

**Comment by xiaosansiji** [comment]
已在 0.41.0 版本中修复
