### ISSUE TITLE
tdesign-vue 可以封装一些比较常用的图表库吗如echart hightchart

### ISSUE THREAD

**Issue by alexjlw** [Tencent/tdesign-vue#743]
tdesign-vue 可以封装一些比较常用的图表库吗如echart hightchart

**Comment by alexjlw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by uyarn** [comment]
tdesign不会做图表相关的组件 图表相关的会以tvision来运作 目前还未开源
