### ISSUE TITLE
新增贡献指南，子项目未拉取可以运行 `git submodule update --init`

### ISSUE THREAD

**Issue by turkyden** [Tencent/tdesign-vue#75]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaishi** [comment]
我记得之前有，我们补回来

**Comment by chaishi** [comment]
贡献指南里面，有关于更新子仓库的描述

https://github.com/Tencent/tdesign-vue/blob/develop/CONTRIBUTING.md

![image](https://user-images.githubusercontent.com/11605702/147311634-0c560487-dbdb-45a3-80d4-99f5bf143828.png)

**Comment by cong-min** [comment]
另外可执行 `git clone --recursive git@github.com:Tencent/tdesign-vue.git` 一次性拉取所有模块

可免去对子模块额外的 `git submodule` `init` / `update` 的操作

**Comment by turkyden** [comment]
OK 是我没仔细看，哈哈 先 Closed 了哈！

**Comment by cong-min** [comment]
> 另外可执行 `git clone --recursive git@github.com:Tencent/tdesign-vue.git` 一次性拉取所有模块
> 
> 可免去对子模块额外的 `git submodule` `init` / `update` 的操作

#87
