### ISSUE TITLE
[t-upload] Props onSelectChange 无法触发

### ISSUE THREAD

**Issue by samchenws** [Tencent/tdesign-vue#752]
### tdesign-vue 版本

Vue for Web 0.40.3

### 重现链接

[_预览地址_](https://codesandbox.io/s/tdesign-vue-demo-forked-x5rpqz?file=/src/demo.vue)
https://codesandbox.io/s/tdesign-vue-demo-forked-x5rpqz?file=/src/demo.vue
### 重现步骤

 
![image](https://user-images.githubusercontent.com/37535153/163679422-2741f35f-f00a-4f6d-891b-6e8d7408f415.png)

![image](https://user-images.githubusercontent.com/37535153/163679377-4bebbbaf-1204-4e31-a9af-10341e3369ea.png)

### 期望结果

上传文件时能触发

### 实际结果

上传文件时无法触发

**Comment by samchenws** [comment]
select-change事件也是一样的效果

**Comment by uyarn** [comment]
@select-change 可以正常触发 有什么问题吗？

**Comment by samchenws** [comment]
> @select-change 可以正常触发 有什么问题吗？

奇怪了，你看我的复现链接，触发不了

**Comment by samchenws** [comment]
> @select-change 可以正常触发 有什么问题吗？

![image](https://user-images.githubusercontent.com/37535153/164237797-7ecbfe2c-1b89-4c21-a17e-28769d344982.png)
  alert("1");
 选择文件确定后不会触发
 
![image](https://user-images.githubusercontent.com/37535153/164238136-f02253a8-9460-463b-8a40-3dfc063417fe.png)

**Comment by samchenws** [comment]
希望能增强这个吧，或者完善下文档吧，谢谢
