### ISSUE TITLE
[Transfer] 穿梭框可否支持不展示箭头操作按钮操作

### ISSUE THREAD

**Issue by qingmang** [Tencent/tdesign-vue#760]
### 这个功能解决了什么问题

选中即穿梭

![image](https://user-images.githubusercontent.com/67047984/163790496-a19ea56b-ba20-4353-ab98-ea9dcdfe02b7.png)

### 你建议的方案是什么

穿梭框支持必须点击按钮穿梭比较麻烦 是否考虑点击即穿梭 不展示箭头操作按钮操作

**Comment by xiaosansiji** [comment]
![image](https://user-images.githubusercontent.com/7600149/163804993-a9b39c0c-6763-4951-b3cb-4f466eef29ee.png)
目前 operation 并不支持传入 `[]` 强制不展示操作按钮区域，可能你得自己写个样式先覆盖下 `t-transfer__operations` 的样式为不展示：
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/7600149/163805281-351392bb-d188-40d4-94fb-c4f68242240c.png">
勾选即穿梭至右侧可以结合 handleCheckedChange 和 targetValue 来实现，参考这个例子：
https://stackblitz.com/edit/angular-6jwz7j?file=src%2Fdemo.vue
