### ISSUE TITLE
[Tree] node节点的状态为什么获取的不对

### ISSUE THREAD

**Issue by qingmang** [Tencent/tdesign-vue#762]
### tdesign-vue 版本

0.40.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-nzh4zo?file=/src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/67047984/163969487-5416cd75-bca0-4b38-9e63-f60973a991e2.png)
选中的cheked为false.未选中为true ，是我使用的方式不对吗

### 期望结果

选中checked:true

### 实际结果

选中checked:false

**Comment by TabSpace** [comment]
关联提案  #768
