### ISSUE TITLE
上传组件

### ISSUE THREAD

**Issue by yoder** [Tencent/tdesign-vue#765]
### 这个功能解决了什么问题
上传组件在复杂表单中如何通过提交表单一同上传图片(文件),而不是先上传了图片(文件)之后返回了文件地址再提交表单

### 你建议的方案是什么？
上传组件增加手动执行上传的事件，可通过构造FormData触发上传完整表单

**Comment by chaishi** [comment]
可以设置 Upload 组件的 `autoUpload` 为 `false`，然后在外部自由控制组件的文件上传时机。

组件本身不考虑这类情况
