### ISSUE TITLE
[select] select选中和下拉项中增加title属性是否显示的控制

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#769]
### 这个功能解决了什么问题

目前select选中项和select的下拉项中均有title属性，当鼠标停留一段时间后会出现提示显示label的内容。

业务上，一方面希望当文本不长的时候，不展示title。另一方面是当需要提示时，可以自定义提示的样式。

<img width="288" alt="image" src="https://user-images.githubusercontent.com/13745660/164150190-f4f86d90-bd99-40bb-a296-d8bbecafbe87.png">

<img width="254" alt="image" src="https://user-images.githubusercontent.com/13745660/164150237-c34c59d4-780c-42b3-bbc9-e8a23fffc6e1.png">

### 你建议的方案是什么

建议可以增加title是否展示的api，或者使用popup实现title提示的功能。

**Comment by LoopZhou** [comment]
目前尝试valueDisplay自定义内容的方法。但是单选情况获取不到value值。https://codesandbox.io/s/tdesign-vue-demo-forked-ltdxt6?file=/src/demo.vue

**Comment by chaishi** [comment]
直接去掉 `title` 属性

**Comment by geff1991** [comment]
ok

**Comment by xiaosansiji** [comment]
已在 0.41.0 版本中实现
