### ISSUE TITLE
Table组件渲染DOM结构存在不明attr

### ISSUE THREAD

**Issue by wanchun** [Tencent/tdesign-vue#77]
**Describe Framework**

**Describe Environment**

chrome 90

**Describe the bug**
![企业微信截图_8299c463-713d-4d8e-8b99-099fff4a3216](https://user-images.githubusercontent.com/4636302/147309297-d12b654b-2148-4ee5-ad17-a1a3ff1dffb2.png)
查看官网 table 渲染出来的 DOM 结构，不应该出现这个

**Comment by chaishi** [comment]
issue 已存在，处理中

**Comment by chaishi** [comment]
see here: https://github.com/Tencent/tdesign-vue/issues/63

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
