### ISSUE TITLE
[Table] 表格多选模式 表头checkoutbox不居中

### ISSUE THREAD

**Issue by PhotoByLucas** [Tencent/tdesign-vue#771]
### tdesign-vue 版本

0.40.3

### 重现链接

https://tdesign.tencent.com/vue/components/table?tab=demo#%E5%8F%AF%E9%80%89%E4%B8%AD%E8%A1%8C%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

官方文档 Table-可选中行的表格-多选中的demo

![image](https://user-images.githubusercontent.com/44331351/164172818-14d74a8f-08a1-4ae6-9430-8001f8632482.png)

将表头第一列背景色设置为红色后可以明显看到
第一个checkbox有明显的不居中（上边距更小下边距更大），但是在codedesign中打开的时候并没有能够复现
![image](https://user-images.githubusercontent.com/44331351/164173135-34c28dc3-321d-4165-9bc5-1e9b9bdfb641.png)

### 期望结果

两边同步

**Comment by chaishi** [comment]
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/11605702/164372491-c2dc1628-a259-4964-87a1-84a8d4740e21.png">

**Comment by chaishi** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/11605702/164382510-5b9b5ff6-5cbf-4edb-a8ca-1380a3b366ca.png">

@realyuyanan  已接受处理

**Comment by uyarn** [comment]
fixed in 0.41
