### ISSUE TITLE
[table] 表格sorter:true 且 ellipsis: true 时 样式出现冲突

### ISSUE THREAD

**Issue by PhotoByLucas** [Tencent/tdesign-vue#778]
### tdesign-vue 版本

0.40.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-mkq9jn?file=/src/demo.vue:724-733

### 重现步骤

![image](https://user-images.githubusercontent.com/44331351/164363182-c5652996-f8f0-444d-adc5-c1fc5e9c2bee.png)
sorter排序被隐藏 且ellipsis样式不生效

### 期望结果

![image](https://user-images.githubusercontent.com/44331351/164363297-5d822a8c-298c-47f1-902a-ce6b7da25dbb.png)

sorter不被隐藏且ellipsis样式生效
向底层的div文字片段透传入t-ellipsis样式
![image](https://user-images.githubusercontent.com/44331351/164363609-07ea1e89-2276-426f-8342-f29329bf599a.png)

**Comment by chaishi** [comment]
收到，我们处理下

**Comment by chaishi** [comment]
- 其他解决方案一：使用 CSS 给文本添加行省略
- 其他解决方案二：使用 `title` 自定义表头，可以自定义为任何想要的效果

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/832

<img width="884" alt="image" src="https://user-images.githubusercontent.com/11605702/166629866-102c393f-6de9-4fb4-b92b-04863dd0539c.png">

**Comment by xiaosansiji** [comment]
已在 0.41.2 版本修复
