### ISSUE TITLE
t-input

### ISSUE THREAD

**Issue by lavender-juan** [Tencent/tdesign-vue#779]
### tdesign-vue 版本

0.39.1

### 重现步骤

1.给input输入框添加enter事件触发搜索。
2.input框内在中文输入法给搜索框添加文案。
3.按enter键，获取不到输入的值。
原因：键盘事件对于中文输入法 无法立即获取。

### 期望结果

期待中文输入法情况下 也可按住enter获取输入绑定的值。

**Comment by chaishi** [comment]
@mokywu

**Comment by chaishi** [comment]
按理说，中文确认输入之后，是可以有 enter 事件的

**Comment by lavender-juan** [comment]
有enter事情，但是第一次按enter的时候获取不到绑定的值

**Comment by lavender-juan** [comment]
有enter事件，但是enter事件获取不到绑定的值
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/55191916/164373498-1cf4392d-71f2-45ff-85e3-8a77dd0a53f7.png">
按第二次的时候：才有z值
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/55191916/164373577-e84438ef-2ac2-45d2-a041-d7556b3f7bb3.png">

**Comment by lavender-juan** [comment]
中文输入法状态下输入的 test

**Comment by mokywu** [comment]
这个没办法直接在官网的demo里面复现。。能不能给一下 测试代码，我这里再看看。。
