### ISSUE TITLE
Upload的基础上传在点击空白处也会触发

### ISSUE THREAD

**Issue by codenotkey** [Tencent/tdesign-vue#78]
**Describe Framework**
- [x] tdesign-vue

![image](https://user-images.githubusercontent.com/49895922/147309776-9c2b1ed7-524e-4441-9cb0-4e630f1881e0.png)

**Describe Environment**
官网示例

**Describe the bug**
![upload](https://user-images.githubusercontent.com/49895922/147310242-0a5c6b6e-ae12-4895-9418-fe07db64202a.gif)

**Comment by codenotkey** [comment]
建议修改 class t-upload__trigger display:block

**Comment by chaishi** [comment]
收到，我们改一下

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-common/pull/50

**Comment by codenotkey** [comment]
自定义上传也存在相同问题
![自定义上传upload](https://user-images.githubusercontent.com/49895922/147442733-3af44b48-4de7-4c9e-886b-340b27f4526c.gif)

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
