### ISSUE TITLE
关于 Dialog 对话框过渡效果优化建议。

### ISSUE THREAD

**Issue by dufu1991** [Tencent/tdesign-vue#79]
我还没使用，只是在文档里面试了一下 Dialog 对话框，对话框开启与关闭的时候感觉有点闪，哪里不对？看了下是因为对话框是有透明度与缩放动画过渡的，但是半透明的遮罩是没有的，这样一起的话就会感觉很奇怪。我觉得给遮罩加个过渡应该会好点（算是我吹毛求疵吧🐶）。

**Comment by chaishi** [comment]
收到，我们改进一下

**Comment by pattybaby110** [comment]
非常欢迎继续“吹毛求疵”～ 这里体验是需要改进 ～非常感谢。

**Comment by dufu1991** [comment]
刚刚又试了下其他的组件比如抽屉，好像很多遮罩都没有过渡，或者是过渡时间与遮罩上面的内容的过渡时间不一致，用起来总感觉哪里不对。

**Comment by pattybaby110** [comment]
是的  接下来是组件动效的持续优化
