### ISSUE TITLE
为什么组件的demo使用<t-button /> 和 <Button />

### ISSUE THREAD

**Issue by kajweb** [Tencent/tdesign-vue#807]
### 这个功能解决了什么问题
这两种有什么区别呢？
更推荐哪种？

### 你建议的方案是什么？
🈚️

**Comment by xiaosansiji** [comment]
Vue template 用户更习惯于 <t-button /> ，React Jsx 用户习惯于 <Button />，你如果是按需引入的用法没有区别。

全局全量引入在 template 里用的用 <t-button />

**Comment by kajweb** [comment]
> Vue template 用户更习惯于 ，React Jsx 用户习惯于

这里没说全吗？😂
