### ISSUE TITLE
[table] table组件 固定表头不固定

### ISSUE THREAD

**Issue by PhotoByLucas** [Tencent/tdesign-vue#812]
### tdesign-vue 版本

0.41

### 重现链接

https://tdesign.tencent.com/vue/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4%E5%92%8C%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

![image](https://user-images.githubusercontent.com/44331351/165666008-c6b57222-616c-41e6-97d6-8b69dfe1b12c.png)

### 期望结果

![image](https://user-images.githubusercontent.com/44331351/165666171-35414af7-08f0-4d1a-8b90-34a6c58ef37b.png)
像多级表头展示方式相同吸附在顶部

**Comment by chaishi** [comment]
提供的地址，无法复现问题， issue 关闭

可以再次提供必现问题的示例代码，然后 reopen

**Comment by PhotoByLucas** [comment]
![image](https://user-images.githubusercontent.com/44331351/167535292-a568eddd-e212-4a56-b962-db7d4254fd08.png)

理解中的 固定表头功能 应该是和[element固定表格](https://element.eleme.cn/#/zh-CN/component/table#gu-ding-biao-tou)这种滚动时候**表头保持吸顶，只滚动表格项**的？

but在tdesign版本的固定表头示例中滚动表格 **表头也会滚动**
![image](https://user-images.githubusercontent.com/44331351/167535050-e53d5eda-a4a8-4df5-abe1-16163fd62b65.png)

想问下这是tdesign的特殊设计嘛 @chaishi
