### ISSUE TITLE
[table] 希望新增表格右键快捷菜单的功能

### ISSUE THREAD

**Issue by luger1990** [Tencent/tdesign-vue#824]
### 这个功能解决了什么问题

方便操作，比如一条数据项操作非常多，如果放到一个单元格那么很挤。可以右键点击，通过 更改状态-> 上线|下线 来修改状态

### 你建议的方案是什么

增加右键快捷菜单，可以操作本条记录。

**Comment by chaishi** [comment]
需求较为特殊，待评估

**Comment by chaishi** [comment]
其实，我没太看明白这个需求

**Comment by uyarn** [comment]
看着不是通用的场景..

**Comment by chaishi** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/11605702/168280373-1d336f76-a873-480c-8ba4-4d227e10fc6f.png">

是指这种鼠标右键吗？

**Comment by luger1990** [comment]
> #### 是指这种鼠标右键吗？
> <img alt="image" width="611" src="https://user-images.githubusercontent.com/11605702/168280373-1d336f76-a873-480c-8ba4-4d227e10fc6f.png">

是的 就是这样的效果，可以自定义右键菜单和每一项的方法

**Comment by chaishi** [comment]
可以支持，只是暂时优先级不高。需耐心等待

**Comment by chaishi** [comment]
右键功能，不仅仅是 Table，需同步考虑其他组件。比如：输出一个单独的组件，「右键快捷菜单」

**Comment by luger1990** [comment]
> 可以支持，只是暂时优先级不高。需耐心等待

请问大概什么版本可以支持？因为数据的操作button可能很多，如果放到action列的话可能很拥挤，不如点击右键操作这一列的数据

**Comment by yangJinRui325** [comment]
> > 可以支持，只是暂时优先级不高。需耐心等待
> 
> 请问大概什么版本可以支持？因为数据的操作button可能很多，如果放到action列的话可能很拥挤，不如点击右键操作这一列的数据

是否可以通过插槽的方式+<t-dropdown>组件来实现呢，比如像下面这样
![1657626549082](https://user-images.githubusercontent.com/27172821/178483231-9537a616-7eb6-4991-a9ff-a1337552171c.png)

**Comment by xiaosansiji** [comment]
这样其实更好，用户不一定能快速理解到这里“右键”操作，直接用下拉菜单更直观一些

> 是否可以通过插槽的方式 + dropdown组件来实现呢，比如像下面这样 ![1657626549082](https://user-images.githubusercontent.com/27172821/178483231-9537a616-7eb6-4991-a9ff-a1337552171c.png)
