### ISSUE TITLE
[颜色选择器ColorPicker] 可不可以增添个颜色选择器呢？

### ISSUE THREAD

**Issue by shalom-lab** [Tencent/tdesign-vue#825]
### 这个功能解决了什么问题

颜色选择器

### 你建议的方案是什么

选择颜色

**Comment by uyarn** [comment]
开发中了 预计五月上旬发布

**Comment by shalom-lab** [comment]
Nice,坐等发布

**Comment by chaishi** [comment]
Vue3 很早就开发完了，我以为 Vue2 也有了，才发现还没有

**Comment by shalom-lab** [comment]
原来如此，我说怎么少了这个重要的组件，好多项目用的还是vue2

**Comment by uyarn** [comment]
PR: https://github.com/Tencent/tdesign-vue/pull/867

**Comment by uyarn** [comment]
fixed in 0.34.3
