### ISSUE TITLE
Upload 组件 `list-style` 样式未重置

### ISSUE THREAD

**Issue by cong-min** [Tencent/tdesign-vue#84]
**Describe Framework**
- tdesign-vue

**Describe the bug**
Upload 组件 `list-style` 样式未重置，在官网上看起来正常，是因为官网 reset css 对其进行了设置

异常效果可看 https://codesandbox.io/s/hd5jg?file=/src/demo.vue

<img width="663" alt="image" src="https://user-images.githubusercontent.com/11243798/147330546-22980fa8-7bc1-4091-9903-adf4db7fc3f5.png">

**Comment by chaishi** [comment]
@uyarn 跟进

**Comment by chaishi** [comment]
published in v0.32.0
