### ISSUE TITLE
[Dropdown] 通过插槽方式时 max-height 不生效

### ISSUE THREAD

**Issue by Wykay-z** [Tencent/tdesign-vue#840]
### tdesign-vue 版本

是

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-c813hc?file=/src/demo.vue

### 重现步骤

通过插槽方式使用下拉菜单组件，设置 max-height 值不生效，菜单项内容较多时会直接溢出无滚动条。
<img width="1053" alt="wecom-temp-849acd83338c2494edcff44d0cdb77ff" src="https://user-images.githubusercontent.com/5928372/167097848-92d21cb8-0389-4852-8880-32529606d76d.png">

### 期望结果

使用 slot 时 max-height 也应该生效。

### 实际结果

菜单项溢出。

### 补充说明

同时希望 minColumnWidth 不要有默认值，不设置时可以根据菜单项内容自适应宽度。

**Comment by xiaosansiji** [comment]
已在 0.41.3 版本修复
