### ISSUE TITLE
[Table] fixed固定列的阴影效果样式异常

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#858]
### tdesign-vue 版本

0.41.1

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-zliizf?file=/src/demo.vue

### 重现步骤

打开重新链接，左右滚动表格即可复现。

### 期望结果

期望和0.41.0效果一致。

滚动条在最左边时，左边固定列没有阴影，右边有。
滚动条在中间时，左右都有阴影。
滚动条在最右边时，左边固定列有阴影，右边没有。

![image](https://user-images.githubusercontent.com/13745660/167567867-f632d2c7-08ae-40f1-a1b7-6b5b5ed40a1e.png)

### 实际结果

目前无论怎么滚动，左边固定列没有阴影效果；而右边一直有阴影效果

![image](https://user-images.githubusercontent.com/13745660/167567256-0c34212f-98ad-4ceb-9cf5-b7bebcd483c6.png)

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/860

**Comment by xiaosansiji** [comment]
已在 0.41.3 版本修复
