### ISSUE TITLE
[Table] 列拖动功能：当把列宽拖动到最小后，不能再选中调整该列了

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#859]
### tdesign-vue 版本

0.41.2

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-gg6uc3?file=/src/demo.vue

### 重现步骤

拖动列到最小
<img width="671" alt="image" src="https://user-images.githubusercontent.com/13745660/167574897-21cef63f-a945-405b-b43b-0495fc4599ca.png">

该列不能选中调整了
<img width="746" alt="image" src="https://user-images.githubusercontent.com/13745660/167574211-9d4aea45-2628-42d2-8ab4-b49b8ba48396.png">

### 期望结果

拖动到最小后，列依旧可以再调整列宽

### 实际结果

拖动列宽到最小后，不能再选中该列这个边线了

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
拖动列宽到最小，是多小

最小的临界值是多少？

**Comment by LoopZhou** [comment]
临界值是30， 当列宽拖动到最小的30时，不能拖动该列了。
应该是这里的判断有一点问题。同时当列比较窄时，边缘的target可能是文本了，导致拖动没有效果。
https://github.com/Tencent/tdesign-vue/blob/develop/src/table/hooks/useColumnResize.tsx#L29

**Comment by LoopZhou** [comment]
另外还有一个问题，如示例程序，列拖动后，再选中某一行，列拖动后到距离被重置了

**Comment by xiaosansiji** [comment]
已在 0.41.3 版本修复
