### ISSUE TITLE
表格的源码好像有报错：index.tsx:162 Uncaught TypeError: Cannot read properties of undefined (reading 'scrollLeft')

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#86]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

# 文件位置：/node_modules/tdesign-vue/src/table/base-table/index.tsx

![image](https://user-images.githubusercontent.com/15682051/147332739-4470624c-379e-4019-a36a-6b06ac3e31b3.png)

![image](https://user-images.githubusercontent.com/15682051/147332467-bf02d63a-7a0b-4410-b980-0d8699db5519.png)

**Comment by chaishi** [comment]
收到，我们处理一下判空

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/94

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
