### ISSUE TITLE
[t-tabs]选项卡新增和删除在normal风格下无效

### ISSUE THREAD

**Issue by colaiven** [Tencent/tdesign-vue#865]
### tdesign-vue 版本

0.41.2

### 重现步骤

1：更改t-tabs的theme="normal"
2：设置t-tabs的addable=true，设置t-tab-panel的removable=true

![image](https://user-images.githubusercontent.com/46585176/167799535-d72cf527-b1fe-4448-b663-a5e7a603db93.png)

增加和删除的按钮无显示

### 框架版本

"vue": "^2.6.14"

**Comment by xiaosansiji** [comment]
已在 0.41.6 版本中修复
