### ISSUE TITLE
[select]文档示例中 Select 选择器选择多选功能后，所选择的个别项不显示

### ISSUE THREAD

**Issue by 445697790** [Tencent/tdesign-vue#876]
### tdesign-vue 版本

当前最新文档

### 重现链接

https://tdesign.tencent.com/vue/components/select?tab=demo

### 重现步骤

select 选择器文档示例中，当我在右边配置栏选择multiple，然后选择所有项，其中 Orange 未显示，这里多选显示的每一条内容都要将名称赋值给 label 属性吗
![1652496261(1)](https://user-images.githubusercontent.com/69765617/168408056-f2f1ac2e-a1dd-4ac2-8806-c25ba6ba3196.png)

**Comment by geff1991** [comment]
@445697790 是的哈，这里t-option的value和label属性都是需要的。

**Comment by uyarn** [comment]
已修复
