### ISSUE TITLE
[TreeSelect ] 过滤之后，没法选中，根本选不了

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#887]
### tdesign-vue 版本

0.41.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-7if55d?file=/package.json:244-250

### 重现步骤

![a](https://user-images.githubusercontent.com/15682051/168708252-3dc2ec1b-8712-4935-9c99-8a74c3ce93f9.gif)

### 期望结果

过滤之后，应该是可以选中的

### 实际结果

无法选中

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(100.0.4896.127)

### 系统版本

win 10

**Comment by sampsonliu** [comment]
这个严重bug没人看一下么

**Comment by uyarn** [comment]
fixed in 0.42.2
