### ISSUE TITLE
[Table] 希望可以在table内添加列信息

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue#892]
### 这个功能解决了什么问题

列的数量信息是一个数组循环出来，而不是固定的columns

### 你建议的方案是什么

![QQ截图20220519101319](https://user-images.githubusercontent.com/35481087/169189227-22f03670-efca-4a28-bc31-dae6795102a9.png)

**Comment by squallliu** [comment]
> 暂时不计划支持 `<t-table-column />` 组件，当前的 table 组件`columns` 已经可以满足所有场景的需要。
> 
> 如果想要使用插槽，直接使用 colKey 作为插槽名称
> 
> ```
> <t-table :columns="[{ colKey: 'nameCol' }]">
>    <template #nameCol>
>      <span>列内容</span>
>    </template>
> </t-table>
> ```

使用插槽也要定义 columns，把模板的内容写到代码里太难看了
