### ISSUE TITLE
[Progress] theme 由 circle 切换至 plump 后样式错乱

### ISSUE THREAD

**Issue by HQ-Lin** [Tencent/tdesign-vue#895]
### tdesign-vue 版本

0.41.3

### 重现步骤

https://user-images.githubusercontent.com/24469546/169436545-06b648b5-a57f-47dd-b584-bdfa61e756c8.mov

**Comment by uyarn** [comment]
@Isabella327 可以提个PR上来

**Comment by xiaosansiji** [comment]
已在 0.41.7 版本中修复
