### ISSUE TITLE
input输入框移除内容后没有聚焦

### ISSUE THREAD

**Issue by clark-cui** [Tencent/tdesign-vue#90]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe the bug**
带移除图标的输入框，在点击移除按钮后，输入框变成了blur状态，应该是聚焦状态。
目前状态如图：

https://user-images.githubusercontent.com/46164858/147359099-1e2ce928-2e43-4077-9a7a-3357f609b203.mov

参考别的组件库，如图：

https://user-images.githubusercontent.com/46164858/147359162-a500a7d4-fe75-4f81-9786-490592c776bf.mov

**Comment by chaishi** [comment]
fixed by https://github.com/Tencent/tdesign-vue/pull/91

**Comment by chaishi** [comment]
待发布

**Comment by xiaosansiji** [comment]
已在 0.33.0 版本中修复
