### ISSUE TITLE
minCollapsedNum在多级树的情况下，功能显示异常，折叠不了子节点数据

### ISSUE THREAD

**Issue by kucorei** [Tencent/tdesign-vue#911]
复现:
https://codesandbox.io/s/tdesign-vue-demo-forked-kdy01h?file=/src/demo.vue
截图:
![企业微信截图_16533884079500](https://user-images.githubusercontent.com/54382769/170012151-24d6876a-cf6b-4dd4-bc89-e67ebf354196.png)
![企业微信截图_16533884189728](https://user-images.githubusercontent.com/54382769/170012237-515fa89f-aa74-48e7-a7ce-7baec1c5d246.png)
树的层级超过3层，切子节点的数量过多的情况下,

**Comment by Godlike-meteor** [comment]
该问题是因为 minCollapsedNum 和 valuedisplay 混用导致，既然使用插槽控制展示内容，建议直接自定义控制
