### ISSUE TITLE
[Table] 表头多选框无法居中和居右

### ISSUE THREAD

**Issue by WULIbinbin** [Tencent/tdesign-vue#912]
### tdesign-vue 版本

0.41.5

### 重现链接

https://codesandbox.io/s/sleepy-brahmagupta-x0qq7?file=/src/App.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/24265957/170171067-5b4b22d1-3127-405a-8f99-eb3ece1c1fbc.png)

宽度足够的情况下，设置居中和居右都没有变化。

### 期望结果

设置居中和居右后多选框处于相应位置。

### 实际结果

宽度足够的情况下，设置居中和居右都没有变化。

### 框架版本

vue(2.6.11)

**Comment by chaishi** [comment]
收到，我们尽快处理，关注周五新版本

**Comment by chaishi** [comment]
可以先设置：`.t-table__th-row-select .t-table__th-cell-inner { display: inline-flext }` 解决问题

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/485

**Comment by xiaosansiji** [comment]
已在 0.41.7 版本中修复
