### ISSUE TITLE
[t-input-number] theme属性为column时align="center"居中不生效

### ISSUE THREAD

**Issue by Fly-Feel** [Tencent/tdesign-vue#913]
### tdesign-vue 版本

0.41.5

### 期望结果

theme="column"时align="center"居中

![image](https://user-images.githubusercontent.com/53337386/170455995-bfb74aaf-8014-43a0-a5d7-411a87b040b1.png)
![image](https://user-images.githubusercontent.com/53337386/170456029-b1889a5c-ebe9-4278-89b3-f8c07c72ff52.png)

### 框架版本

Vue(2.6.11)

**Comment by jchalex** [comment]
follow

**Comment by xiaosansiji** [comment]
已在 0.41.7 版本中修复
