### ISSUE TITLE
[Menu] 如果是动态渲染，子菜单没渲染出来，并且主菜单没有选中

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#916]
### tdesign-vue 版本

0.41.3

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-8lx3zh?file=/src/demo.vue

### 重现步骤

直接看链接即可

### 期望结果

![image](https://user-images.githubusercontent.com/15682051/170446850-a1229ae3-9867-467f-ba67-3045afa3750b.png)

### 实际结果

![image](https://user-images.githubusercontent.com/15682051/170446534-2ccbeb29-34c2-4faf-85fe-c97ce45cd2b3.png)

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(100.0.4896.127)

### 系统版本

win 10

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-77nqlu?file=/src/demo.vue
