### ISSUE TITLE
[table] 拖动调整宽度，需设置最小宽度，宽度过小，文本显示不正常的情况

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-vue#929]
### tdesign-vue 版本

0.4.15

### 重现步骤

官网固定表头和列的表格示例即可复现。拖动序号列和操作列到最小。

https://user-images.githubusercontent.com/13745660/170819164-e071557d-c812-41b0-83a3-ca9276981129.mp4

### 期望结果

fixed列有正常的文字遮挡效果。

### 框架版本

Vue(2.6.0)

### 浏览器版本

Chrome(99.0.4844.51)

### 系统版本

MacOS(10.15.7)

### Node版本

12.22.0

**Comment by chaishi** [comment]
这也算问题吗？那可能整个组件的问题都太多了，处理不了

**Comment by chaishi** [comment]
看视频，很明显是操作者故意往非常小了拖

不知道要怎么做，才能符合大家的所有期望了

**Comment by LoopZhou** [comment]
我觉得是默认拖动的最小30px太小了。
table每个单元格两边的padding就是24px了。 30px的默认限制能否增加到至少能够显示完整一个中文文字。

或者能不能在columns中增加一个拖动配置参数， 支持自定义该列拖动的最小宽度等。

**Comment by chaishi** [comment]
哦，最小宽度的话，可以内部加下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/952

**Comment by xiaosansiji** [comment]
已在 0.42.0 版本修复
