### ISSUE TITLE
[Select] inputProps透传失效

### ISSUE THREAD

**Issue by LuoCharlie** [Tencent/tdesign-vue#939]
### 重现链接
https://codesandbox.io/s/ylyfwx?file=/src/App.vue

### 重现步骤
传入了inputProps对象{ label: 'asdas', maxcharacter: 2 }，选择器的输入框没有生效。同样传入popupProps对象{ placement: 'top' }，选择器的下拉框位置到顶部了

### 期望结果
传入inputProps能够定义选择器的输入框

### 实际结果
传入inputProps没有任何效果

### 补充说明
在选择器文档的props里有inputProps，
![image](https://user-images.githubusercontent.com/60652443/171404752-68234af4-43af-4fac-915f-9a42e5abbf0d.png)

在其详细类型定义里没有，类型定义链接如下：https://github.com/Tencent/tdesign-vue/blob/develop/src/select/type.ts

| Environment | Info |
|---|---|
| 相关版本 | 0.41.6 |
| 框架版本 / 基础库版本 | Vue(2.6.14) |
| 系统、浏览器 | MacOs(10.15.7 )、Chrome(100.0.4896.75) |
| Node版本 |  |

**Comment by geff1991** [comment]
你好，inputProps目前还没支持，（可能文档先定义了，select 正在进行selectInput的改造，完成后可以投传inputProps）
popupProps是支持的

**Comment by xiaosansiji** [comment]
已在 0.42.0 版本修复
