### ISSUE TITLE
[TagInput] 中文输入法输入后按enter键，出现undefined标签

### ISSUE THREAD

**Issue by LittlehorseXie** [Tencent/tdesign-vue#943]
### tdesign-vue 版本

0.41.6

### 重现链接

https://tdesign.tencent.com/vue/components/tag-input

### 重现步骤

1. 刷新重现链接的地址
2. 切换到中文输入法
3. 输入halo
4. 出现一个undefined Tag 且 inputValue 为 halo

### 期望结果

不出现 undefined Tag

### 实际结果

出现一个undefined Tag 且 inputValue 为 halo

**Comment by uyarn** [comment]
published in 0.43.0
