### ISSUE TITLE
[TagInput] 中文输入按下 Enter 时不触发新标签，直接迁移 React 功能

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue#945]
### tdesign-vue 版本

0.41.6

**抄代码**： https://github.com/Tencent/tdesign-react/pull/835

React 已实现，需同步迁移特性到 Vue3。https://github.com/Tencent/tdesign-vue-next/issues/929

**Comment by chiyu1996** [comment]
认领
