### ISSUE TITLE
[Table] 对table进行二次封装动态列问题

### ISSUE THREAD

**Issue by samchenws** [Tencent/tdesign-vue#948]
### tdesign-vue 版本

Vue for Web 0.40.3

### 重现链接
https://codesandbox.io/s/tdesign-vue-demo-forked-x5rpqz?file=/src/demo.vue
_No response_

### 重现步骤

![image](https://user-images.githubusercontent.com/37535153/171581177-ff7f0d09-db37-4bd5-aaf8-e356e0fb2b3a.png)
下面这样可以生效（但是我怎么拿到值了？）
![image](https://user-images.githubusercontent.com/37535153/171581322-ca5b80e3-2abf-47aa-8e68-e61288de0628.png)
下面这样无法生效
![image](https://user-images.githubusercontent.com/37535153/171581555-75963e9a-9aa3-4f7c-a645-b45ad9ecba37.png)

**Comment by chaishi** [comment]
实在看不懂问题是什么

**Comment by samchenws** [comment]
> 实在看不懂问题是什么

[就是外部](https://codesandbox.io/s/tdesign-vue-demo-forked-x5rpqz?file=/src/demo.vue)

**Comment by samchenws** [comment]
> 实在看不懂问题是什么

这个是刚写的Demo，https://codesandbox.io/s/tdesign-vue-demo-forked-x5rpqz?file=/src/demo.vue

**Comment by chaishi** [comment]
题外话，不用每一列都写个 `cell`，`colKey` 的值会被默认作为插槽的名称。一般情况，有 colKey 就够了

**Comment by chaishi** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/11605702/171985507-3b65d990-cc06-4ad9-b978-71b6f624f48d.png">

**Comment by samchenws** [comment]
好的谢谢
