### ISSUE TITLE
[Table] 表头无法固定，在某些条件下失效了

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#956]
### tdesign-vue 版本

0.39.1

### 重现步骤

sticky 失效，在腾讯会议里的 webview ，表头没有固定住。
![image](https://user-images.githubusercontent.com/8199240/172040515-133fbb55-ea04-4e63-9635-fb7248434135.png)

### 框架版本

2.6.11

### 浏览器版本

5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 QBCore/77.0.406.400 QQBrowser/10.0.0.999  app/tencent_wemeet os_name/Windows os_version/Windows_11_Desktop app_version/3.7.9.426 c_district/0 app_sdk_id/0300000000 app_lang/zh-cn app_instance_id/1

### 系统版本

windows11

**Comment by chaishi** [comment]
`headerAffixedTop` 表头吸顶。使用此向功能，需要非常注意表格是相对于哪一个父元素进行滚动，默认为整个窗口。如果表格滚动的父元素不是整个窗口，请通过 `headerAffixProps.container` 调整固钉的吸顶范围

尝试调整滚动的父元素。只有截图看不出来是在哪个元素里面滚动

**Comment by Wonder233** [comment]
已使用 headerAffixedTop 功能解决~
