### ISSUE TITLE
[select] slot valueDisplay 当组件单选时，无法自定义选中项的呈现方式

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#959]
### tdesign-vue 版本

0.41.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-c1nz34

### 重现步骤

当 select 单选时，valueDisplay 不起作用

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(100.0.4896.127)

**Comment by xiaosansiji** [comment]
已在 0.42.0 版本修复
