### ISSUE TITLE
[table]table组件动态添加数据合并单元格异常

### ISSUE THREAD

**Issue by a-l-o-n-g** [Tencent/tdesign-vue#960]
### tdesign-vue 版本

0.41.7

### 重现链接

https://stackblitz.com/edit/angular-hhyqtm-eaubnn?file=src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/25051361/172309864-ca1f3dd1-98f3-4a0a-9f9a-7fce63214c61.png)
点击按钮添加data数据，动态添加表格行数据，如果有合并单元格操作，则最后一行的单元格显示异常，并未被合并；

### 框架版本

3.6.11

### 浏览器版本

Chrome   101.0.4951.67（正式版本） （64 位）

**Comment by uyarn** [comment]
fixed in 0.42.0
