### ISSUE TITLE
[form表单校验]form中嵌套table后进行校验失效，有在线例子

### ISSUE THREAD

**Issue by windyboyy** [Tencent/tdesign-vue#961]
https://codesandbox.io/s/tdesign-vue-demo-forked-epu5k5?file=/src/demo.vue

无论是否填入数据，都会校验为空数据

**Comment by uyarn** [comment]
已排查 是用户使用问题

**Comment by cat-uncles** [comment]
如果我只是想判断table有没有数据，保证一行是完整填入数据的，怎么去校验
