### ISSUE TITLE
[Tree] onClick、onExpand 功能一致，没有区别

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-vue#965]
### tdesign-vue 版本

0.41.7

### 重现链接

https://stackblitz.com/edit/angular-qljnuh-pbpvyj?file=src%2Fdemo.vue

### 重现步骤

点击折叠按钮，onClick、onExpand 事件同时被触发

### 期望结果

点击折叠按钮时，只出发 onExpand 事件

**Comment by ontheroad1992** [comment]
> 但这个操作也是点击操作啊。。

如果这样的话， onExpand 就没必要存在了；

场景：父子选项都可以点击并修改路由，并跳转不同的内容，如果我只是想折叠一下，并不想跳转

**Comment by xiaosansiji** [comment]
可以加个 `expandOnClickNode = false`，不在点击整个节点时做展开收起，只有点击节点前面 icon 时才响应展开，你业务需要的 onClick 可以绑定到节点上，不与 onExpand 冲突

**Comment by ontheroad1992** [comment]
> 

这样的做法，个人感觉并不优雅，增加了业务的复杂度

**Comment by ontheroad1992** [comment]
存在 onActive 事件，这是个错误的 issus

**Comment by ontheroad1992** [comment]
> 存在 onActive 事件，这是个错误的 issus

onActive 需要配合 activable 使用，功能只是相似

**Comment by chaishi** [comment]
onClick 只是个简单的点击事件而已

`onExpand` 有更多的参数（当前展开了哪些节点），和 `expanded` 共同构成 Vue 的语法糖 `.sync`，以及相关的非受控属性 `defaultExpanded`。

差多了，不要混淆。

**Comment by ontheroad1992** [comment]
> onClick 只是个简单的点击事件而已
> 
> `onExpand` 有更多的参数（当前展开了哪些节点），和 `expanded` 共同构成 Vue 的语法糖 `.sync`，以及相关的非受控属性 `defaultExpanded`。
> 
> 差多了，不要混淆。

我现在就一个简单需求，点击按钮的时候，能不触发 onClick 事件，或者单独有 onSelect 的事实，参照 antd 的
