### ISSUE TITLE
[DatePicker] 时间区间选择 跨月时样式优化

### ISSUE THREAD

**Issue by tansentcn** [Tencent/tdesign-vue#966]
### 这个功能解决了什么问题

跨月多出来的高亮样式容易误导（会吸引注意力）

### 你建议的方案是什么

建议取消框出来两处的高亮样式
![image](https://user-images.githubusercontent.com/38307150/172656708-7d839595-c705-4d24-a140-010cf8606fd1.png)

非高亮样式效果可以参考antd
![image](https://user-images.githubusercontent.com/38307150/172657204-25987705-3f4a-4389-a74f-04349cd7cb54.png)

**Comment by uyarn** [comment]
fixed in 0.43.0
