### ISSUE TITLE
[DatePicker] 年份区间选择样式错误

### ISSUE THREAD

**Issue by tansentcn** [Tencent/tdesign-vue#967]
### tdesign-vue 版本

0.41.7

### 重现链接

https://codesandbox.io/s/fervent-minsky-sokivr?file=/src/App.vue

### 重现步骤

    <t-date-picker
      mode="year"
      format="YYYY"
      range
      :placeholder="['开始时间', '结束时间']"
    />

配置
mode="year"
format="YYYY"
range

选择时间区间后，最后一个节点样式错误
![image](https://user-images.githubusercontent.com/38307150/172748810-0b9dc25f-d23d-45a5-9af5-b29c477581f5.png)

是因为设置了 format="YYYY" 才会出现问题

### 期望结果

![image](https://user-images.githubusercontent.com/38307150/172748941-a5dcd54b-c971-4f87-870b-dd5e32b2e72e.png)

### 实际结果

![image](https://user-images.githubusercontent.com/38307150/172748810-0b9dc25f-d23d-45a5-9af5-b29c477581f5.png)

### 框架版本

Vue2.x

### 系统版本

win10

**Comment by uyarn** [comment]
datepicker正在实现全新的UI 预计本周五发布新版本

**Comment by uyarn** [comment]
published in 0.43.0
