### ISSUE TITLE
[Popup/Dropdown] 功能加强建议

### ISSUE THREAD

**Issue by zhangtianxiao** [Tencent/tdesign-vue#968]
### 这个功能解决了什么问题

一切皆可作为下拉元素

### 你建议的方案是什么

Dropdown应成为抽象控件, 不仅仅是一个类select组件, 能够嵌套任意元素, 
```html
<dropdown trigger="click">
   <t-input/>
  <t-table ></table>
</dropdown>
```
用户在触发table的点击 选中事件时, 能够手动对input进行赋值, 调用dropdown.hide().
我细看了一下, dropdown和datepicker都是基于popup实现的,
但Popup的trigger只有四种事件支持, 没有方法支持.
假设触发元素是个disabled/readonly 的input, 在点击时, popup就不该响应事件

**Comment by xiaosansiji** [comment]
https://stackblitz.com/edit/angular-ipcaju?file=src%2Fdemo.vue 触发元素 disabled 时我看也没触发 dropdown 下拉展示啊

**Comment by zhangtianxiao** [comment]
> https://stackblitz.com/edit/angular-ipcaju?file=src%2Fdemo.vue 触发元素 disabled 时我看也没触发 dropdown 下拉展示啊

主要是想要一个方法 能够手动显示/隐藏dropdown
