### ISSUE TITLE
input组件样式看起来有问题

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#97]
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

![image](https://user-images.githubusercontent.com/15682051/147382518-65b661f9-2fa3-4b83-840e-08411fcecd22.png)

**Comment by chaishi** [comment]
没有看明白是什么样式问题

**Comment by sampsonliu** [comment]
placeholder前面好像有点灰色

**Comment by sampsonliu** [comment]
看错了，是这个：https://github.com/Tencent/tdesign-vue/issues/101
