### ISSUE TITLE
[table] 表格合并貌似不支持动态数据，展示乱套了

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue#973]
### tdesign-vue 版本

0.41.7

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-1v28uy?file=/src/demo.vue

### 重现步骤

点击按钮加一个数据
![image](https://user-images.githubusercontent.com/15682051/172819917-2a5833f0-c09a-44fc-b3f2-62178a71d1d8.png)

### 框架版本

Vue(2.6.14)

### 浏览器版本

Chrome(100.0.4896.127)

### 系统版本

win 10

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/975

已修复，待发布

https://user-images.githubusercontent.com/11605702/172981315-e3b96d91-f289-4c40-b60f-ae6364dbcfc5.mov

**Comment by sampsonliu** [comment]
非常感谢

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/969

**Comment by chaishi** [comment]
React resolved in https://github.com/Tencent/tdesign-react/pull/866

**Comment by a-l-o-n-g** [comment]
为什么这个问题我提了几天了都没回复。。 @chaishi
