### ISSUE TITLE
[ InputAdornment 输入装饰器] 比例不合适

### ISSUE THREAD

**Issue by pattybaby110** [Tencent/tdesign-vue#988]
### tdesign-vue 版本

官网可以复现

### 重现链接

https://tdesign.woa.com/vue/components/input-adornment

### 重现步骤

<img width="789" alt="image" src="https://user-images.githubusercontent.com/88708072/173268365-a777375e-289a-430d-a7d8-78d98c5adf4f.png">

### 期望结果

需要重新设计比例

**Comment by xiaosansiji** [comment]
需要修改到下拉框宽度与触发元素相同
