### ISSUE TITLE
[select] 当前数据大概一千条，非常卡顿

### ISSUE THREAD

**Issue by waviness** [Tencent/tdesign-vue#997]
### tdesign-vue 版本

0.41.0

### 重现步骤

使用t-select组件，数据条数目前是在1000条，非常卡顿，无法正常使用，没有试过具体超过多少条时会出现当前问题

### 期望结果

希望下拉选择功能能正常操作

### 实际结果

下拉选择非常卡顿，无法正常使用

### 框架版本

vue2

### 系统版本

windows

**Comment by skytt** [comment]
升级0.42.0版本以后开启虚拟滚动试试  https://tdesign.tencent.com/vue/components/select#%E5%BC%80%E5%90%AF%E8%99%9A%E6%8B%9F%E6%BB%9A%E5%8A%A8%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by waviness** [comment]
没明白，问题很简单 面熟的挺清楚的呀，是不处理了吗？
